#pragma once
#ifndef __GSTATES_H__
#define __GSTATES_H__

// Last Saved,#2001-07-30 17:03:04#,"Jonty Barnes"

//*****************************************************************************
// ENUM Values: VILLAGER_STATES
//*****************************************************************************
enum     VILLAGER_STATES
{
    VILLAGER_STATE_INVALID_STATE                                                         =  0 ,
    VILLAGER_STATE_MOVE_TO_POS                                                           =  1 ,
    VILLAGER_STATE_MOVE_TO_OBJECT                                                        =  2 ,
    VILLAGER_STATE_MOVE_ON_STRUCTURE                                                     =  3 ,
    VILLAGER_STATE_IN_SCRIPT                                                             =  4 ,
    VILLAGER_STATE_IN_DANCE                                                              =  5 ,
    VILLAGER_STATE_FLEEING_FROM_OBJECT_REACTION                                          =  6 ,
    VILLAGER_STATE_LOOKING_AT_OBJECT_REACTION                                            =  7 ,
    VILLAGER_STATE_FOLLOWING_OBJECT_REACTION                                             =  8 ,
    VILLAGER_STATE_INSPECT_OBJECT_REACTION                                               =  9 ,
    VILLAGER_STATE_FLYING                                                                =  10 ,
    VILLAGER_STATE_LANDED                                                                =  11 ,
    VILLAGER_STATE_LOOK_AT_FLYING_OBJECT_REACTION                                        =  12 ,
    VILLAGER_STATE_SET_DYING                                                             =  13 ,
    VILLAGER_STATE_DYING                                                                 =  14 ,
    VILLAGER_STATE_DEAD                                                                  =  15 ,
    VILLAGER_STATE_DROWNING                                                              =  16 ,
    VILLAGER_STATE_DOWNED                                                                =  17 ,
    VILLAGER_STATE_BEING_EATEN                                                           =  18 ,
    VILLAGER_STATE_GOTO_FOOD_REACTION                                                    =  19 ,
    VILLAGER_STATE_ARRIVES_AT_FOOD_REACTION                                              =  20 ,
    VILLAGER_STATE_GOTO_WOOD_REACTION                                                    =  21 ,
    VILLAGER_STATE_ARRIVES_AT_WOOD_REACTION                                              =  22 ,
    VILLAGER_STATE_WAIT_FOR_ANIMATION                                                    =  23 ,
    VILLAGER_STATE_IN_HAND                                                               =  24 ,
    VILLAGER_STATE_GOTO_PICKUP_BALL_REACTION                                             =  25 ,
    VILLAGER_STATE_ARRIVES_AT_PICKUP_BALL_REACTION                                       =  26 ,
    VILLAGER_STATE_MOVE_IN_FLOCK                                                         =  27 ,
    VILLAGER_STATE_MOVE_ALONG_PATH                                                       =  28 ,
    VILLAGER_STATE_MOVE_ON_PATH                                                          =  29 ,
    VILLAGER_STATE_FLEEING_AND_LOOKING_AT_OBJECT_REACTION                                =  30 ,
    VILLAGER_STATE_GOTO_STORAGE_PIT_FOR_DROP_OFF                                         =  31 ,
    VILLAGER_STATE_ARRIVES_AT_STORAGE_PIT_FOR_DROP_OFF                                   =  32 ,
    VILLAGER_STATE_GOTO_STORAGE_PIT_FOR_FOOD                                             =  33 ,
    VILLAGER_STATE_ARRIVES_AT_STORAGE_PIT_FOR_FOOD                                       =  34 ,
    VILLAGER_STATE_ARRIVES_AT_HOME_WITH_FOOD                                             =  35 ,
    VILLAGER_STATE_GO_HOME                                                               =  36 ,
    VILLAGER_STATE_ARRIVES_HOME                                                          =  37 ,
    VILLAGER_STATE_AT_HOME                                                               =  38 ,
    VILLAGER_STATE_ARRIVES_AT_STORAGE_PIT_FOR_BUILDING_MATERIALS                         =  39 ,
    VILLAGER_STATE_ARRIVES_AT_BUILDING_SITE                                              =  40 ,
    VILLAGER_STATE_BUILDING                                                              =  41 ,
    VILLAGER_STATE_GOTO_STORAGE_PIT_FOR_WORSHIP_SUPPLIES                                 =  42 ,
    VILLAGER_STATE_ARRIVES_AT_STORAGE_PIT_FOR_WORSHIP_SUPPLIES                           =  43 ,
    VILLAGER_STATE_GOTO_WORSHIP_SITE_WITH_SUPPLIES                                       =  44 ,
    VILLAGER_STATE_MOVE_TO_WORSHIP_SITE_WITH_SUPPLIES                                    =  45 ,
    VILLAGER_STATE_ARRIVES_AT_WORSHIP_SITE_WITH_SUPPLIES                                 =  46 ,
    VILLAGER_STATE_FORESTER_MOVE_TO_FOREST                                               =  47 ,
    VILLAGER_STATE_FORESTER_GOTO_FOREST                                                  =  48 ,
    VILLAGER_STATE_FORESTER_ARRIVES_AT_FOREST                                            =  49 ,
    VILLAGER_STATE_FORESTER_CHOPS_TREE                                                   =  50 ,
    VILLAGER_STATE_FORESTER_CHOPS_TREE_FOR_BUILDING                                      =  51 ,
    VILLAGER_STATE_FORESTER_FINISHED_FORESTERING                                         =  52 ,
    VILLAGER_STATE_ARRIVES_AT_BIG_FOREST                                                 =  53 ,
    VILLAGER_STATE_ARRIVES_AT_BIG_FOREST_FOR_BUILDING                                    =  54 ,
    VILLAGER_STATE_FISHERMAN_ARRIVES_AT_FISHING                                          =  55 ,
    VILLAGER_STATE_FISHING                                                               =  56 ,
    VILLAGER_STATE_WAIT_FOR_COUNTER                                                      =  57 ,
    VILLAGER_STATE_GOTO_WORSHIP_SITE_FOR_WORSHIP                                         =  58 ,
    VILLAGER_STATE_ARRIVES_AT_WORSHIP_SITE_FOR_WORSHIP                                   =  59 ,
    VILLAGER_STATE_WORSHIPPING_AT_WORSHIP_SITE                                           =  60 ,
    VILLAGER_STATE_GOTO_ALTAR_FOR_REST                                                   =  61 ,
    VILLAGER_STATE_ARRIVES_AT_ALTAR_FOR_REST                                             =  62 ,
    VILLAGER_STATE_AT_ALTAR_REST                                                         =  63 ,
    VILLAGER_STATE_AT_ALTAR_FINISHED_REST                                                =  64 ,
    VILLAGER_STATE_RESTART_WORSHIPPING_AT_WORSHIP_SITE                                   =  65 ,
    VILLAGER_STATE_RESTART_WORSHIPPING_CREATURE                                          =  66 ,
    VILLAGER_STATE_FARMER_ARRIVES_AT_FARM                                                =  67 ,
    VILLAGER_STATE_FARMER_PLANTS_CROP                                                    =  68 ,
    VILLAGER_STATE_FARMER_DIGS_UP_CROP                                                   =  69 ,
    VILLAGER_STATE_MOVE_TO_FOOTBALL_PITCH_CONSTRUCTION                                   =  70 ,
    VILLAGER_STATE_FOOTBALL_WALK_TO_POSITION                                             =  71 ,
    VILLAGER_STATE_FOOTBALL_WAIT_FOR_KICK_OFF                                            =  72 ,
    VILLAGER_STATE_FOOTBALL_ATTACKER                                                     =  73 ,
    VILLAGER_STATE_FOOTBALL_GOALIE                                                       =  74 ,
    VILLAGER_STATE_FOOTBALL_DEFENDER                                                     =  75 ,
    VILLAGER_STATE_FOOTBALL_WON_GOAL                                                     =  76 ,
    VILLAGER_STATE_FOOTBALL_LOST_GOAL                                                    =  77 ,
    VILLAGER_STATE_START_MOVE_TO_PICK_UP_BALL_FOR_DEAD_BALL                              =  78 ,
    VILLAGER_STATE_ARRIVED_AT_PICK_UP_BALL_FOR_DEAD_BALL                                 =  79 ,
    VILLAGER_STATE_ARRIVED_AT_PUT_DOWN_BALL_FOR_DEAD_BALL_START                          =  80 ,
    VILLAGER_STATE_ARRIVED_AT_PUT_DOWN_BALL_FOR_DEAD_BALL_END                            =  81 ,
    VILLAGER_STATE_FOOTBALL_MATCH_PAUSED                                                 =  82 ,
    VILLAGER_STATE_FOOTBALL_WATCH_MATCH                                                  =  83 ,
    VILLAGER_STATE_FOOTBALL_MEXICAN_WAVE                                                 =  84 ,
    VILLAGER_STATE_CREATED                                                               =  85 ,
    VILLAGER_STATE_ARRIVES_IN_ABODE_TO_TRADE                                             =  86 ,
    VILLAGER_STATE_ARRIVES_IN_ABODE_TO_PICK_UP_EXCESS                                    =  87 ,
    VILLAGER_STATE_MAKE_SCARED_STIFF                                                     =  88 ,
    VILLAGER_STATE_SCARED_STIFF                                                          =  89 ,
    VILLAGER_STATE_WORSHIPPING_CREATURE                                                  =  90 ,
    VILLAGER_STATE_SHEPHERD_LOOK_FOR_FLOCK                                               =  91 ,
    VILLAGER_STATE_SHEPHERD_MOVE_FLOCK_TO_WATER                                          =  92 ,
    VILLAGER_STATE_SHEPHERD_MOVE_FLOCK_TO_FOOD                                           =  93 ,
    VILLAGER_STATE_SHEPHERD_MOVE_FLOCK_BACK                                              =  94 ,
    VILLAGER_STATE_SHEPHERD_DECIDE_WHAT_TO_DO_WITH_FLOCK                                 =  95 ,
    VILLAGER_STATE_SHEPHERD_WAIT_FOR_FLOCK                                               =  96 ,
    VILLAGER_STATE_SHEPHERD_SLAUGHTER_ANIMAL                                             =  97 ,
    VILLAGER_STATE_SHEPHERD_FETCH_STRAY                                                  =  98 ,
    VILLAGER_STATE_SHEPHERD_GOTO_FLOCK                                                   =  99 ,
    VILLAGER_STATE_HOUSEWIFE_AT_HOME                                                     =  100 ,
    VILLAGER_STATE_HOUSEWIFE_GOTO_STORAGE_PIT                                            =  101 ,
    VILLAGER_STATE_HOUSEWIFE_ARRIVES_AT_STORAGE_PIT                                      =  102 ,
    VILLAGER_STATE_HOUSEWIFE_PICKUP_FROM_STORAGE_PIT                                     =  103 ,
    VILLAGER_STATE_HOUSEWIFE_RETURN_HOME_WITH_FOOD                                       =  104 ,
    VILLAGER_STATE_HOUSEWIFE_MAKE_DINNER                                                 =  105 ,
    VILLAGER_STATE_HOUSEWIFE_SERVES_DINNER                                               =  106 ,
    VILLAGER_STATE_HOUSEWIFE_CLEARS_AWAY_DINNER                                          =  107 ,
    VILLAGER_STATE_HOUSEWIFE_DOES_HOUSEWORK                                              =  108 ,
    VILLAGER_STATE_HOUSEWIFE_GOSSIPS_AROUND_STORAGE_PIT                                  =  109 ,
    VILLAGER_STATE_HOUSEWIFE_STARTS_GIVING_BIRTH                                         =  110 ,
    VILLAGER_STATE_HOUSEWIFE_GIVING_BIRTH                                                =  111 ,
    VILLAGER_STATE_HOUSEWIFE_GIVEN_BIRTH                                                 =  112 ,
    VILLAGER_STATE_CHILD_AT_CRECHE                                                       =  113 ,
    VILLAGER_STATE_CHILD_FOLLOWS_MOTHER                                                  =  114 ,
    VILLAGER_STATE_CHILD_BECOMES_ADULT                                                   =  115 ,
    VILLAGER_STATE_SITS_DOWN_TO_DINNER                                                   =  116 ,
    VILLAGER_STATE_EAT_FOOD                                                              =  117 ,
    VILLAGER_STATE_EAT_FOOD_AT_HOME                                                      =  118 ,
    VILLAGER_STATE_GOTO_BED_AT_HOME                                                      =  119 ,
    VILLAGER_STATE_SLEEPING_AT_HOME                                                      =  120 ,
    VILLAGER_STATE_WAKE_UP_AT_HOME                                                       =  121 ,
    VILLAGER_STATE_START_HAVING_SEX                                                      =  122 ,
    VILLAGER_STATE_HAVING_SEX                                                            =  123 ,
    VILLAGER_STATE_STOP_HAVING_SEX                                                       =  124 ,
    VILLAGER_STATE_START_HAVING_SEX_AT_HOME                                              =  125 ,
    VILLAGER_STATE_HAVING_SEX_AT_HOME                                                    =  126 ,
    VILLAGER_STATE_STOP_HAVING_SEX_AT_HOME                                               =  127 ,
    VILLAGER_STATE_WAIT_FOR_DINNER                                                       =  128 ,
    VILLAGER_STATE_HOMELESS_START                                                        =  129 ,
    VILLAGER_STATE_VAGRANT_START                                                         =  130 ,
    VILLAGER_STATE_MORN_DEATH                                                            =  131 ,
    VILLAGER_STATE_PERFORM_INSPECTION_REACTION                                           =  132 ,
    VILLAGER_STATE_APPROACH_OBJECT_REACTION                                              =  133 ,
    VILLAGER_STATE_INITIALISE_TELL_OTHERS_ABOUT_OBJECT                                   =  134 ,
    VILLAGER_STATE_TELL_OTHERS_ABOUT_INTERESTING_OBJECT                                  =  135 ,
    VILLAGER_STATE_APPROACH_VILLAGER_TO_TALK_TO                                          =  136 ,
    VILLAGER_STATE_TELL_PARTICULAR_VILLAGER_ABOUT_OBJECT                                 =  137 ,
    VILLAGER_STATE_INITIALISE_LOOK_AROUND_FOR_VILLAGER_TO_TELL                           =  138 ,
    VILLAGER_STATE_LOOK_AROUND_FOR_VILLAGER_TO_TELL                                      =  139 ,
    VILLAGER_STATE_MOVE_TOWARDS_OBJECT_TO_LOOK_AT                                        =  140 ,
    VILLAGER_STATE_INITIALISE_IMPRESSED_REACTION                                         =  141 ,
    VILLAGER_STATE_PERFORM_IMPRESSED_REACTION                                            =  142 ,
    VILLAGER_STATE_INITIALISE_FIGHT_REACTION                                             =  143 ,
    VILLAGER_STATE_PERFORM_FIGHT_REACTION                                                =  144 ,
    VILLAGER_STATE_HOMELESS_EAT_DINNER                                                   =  145 ,
    VILLAGER_STATE_INSPECT_CREATURE_REACTION                                             =  146 ,
    VILLAGER_STATE_PERFORM_INSPECT_CREATURE_REACTION                                     =  147 ,
    VILLAGER_STATE_APPROACH_CREATURE_REACTION                                            =  148 ,
    VILLAGER_STATE_INITIALISE_BEWILDERED_BY_MAGIC_TREE_REACTION                          =  149 ,
    VILLAGER_STATE_PERFORM_BEWILDERED_BY_MAGIC_TREE_REACTION                             =  150 ,
    VILLAGER_STATE_TURN_TO_FACE_MAGIC_TREE                                               =  151 ,
    VILLAGER_STATE_LOOK_AT_MAGIC_TREE                                                    =  152 ,
    VILLAGER_STATE_DANCE_FOR_EDITING_PURPOSES                                            =  153 ,
    VILLAGER_STATE_MOVE_TO_DANCE_POS                                                     =  154 ,
    VILLAGER_STATE_INITIALISE_RESPECT_CREATURE_REACTION                                  =  155 ,
    VILLAGER_STATE_PERFORM_RESPECT_CREATURE_REACTION                                     =  156 ,
    VILLAGER_STATE_FINISH_RESPECT_CREATURE_REACTION                                      =  157 ,
    VILLAGER_STATE_APPROACH_HAND_REACTION                                                =  158 ,
    VILLAGER_STATE_FLEEING_FROM_CREATURE_REACTION                                        =  159 ,
    VILLAGER_STATE_TURN_TO_FACE_CREATURE_REACTION                                        =  160 ,
    VILLAGER_STATE_WATCH_FLYING_OBJECT_REACTION                                          =  161 ,
    VILLAGER_STATE_POINT_AT_FLYING_OBJECT_REACTION                                       =  162 ,
    VILLAGER_STATE_DECIDE_WHAT_TO_DO                                                     =  163 ,
    VILLAGER_STATE_INTERACT_DECIDE_WHAT_TO_DO                                            =  164 ,
    VILLAGER_STATE_EAT_OUTSIDE                                                           =  165 ,
    VILLAGER_STATE_RUN_AWAY_FROM_OBJECT_REACTION                                         =  166 ,
    VILLAGER_STATE_MOVE_TOWARDS_CREATURE_REACTION                                        =  167 ,
    VILLAGER_STATE_AMAZED_BY_MAGIC_SHIELD_REACTION                                       =  168 ,
    VILLAGER_STATE_VILLAGER_GOSSIPS                                                      =  169 ,
    VILLAGER_STATE_CHECK_INTERACT_WITH_ANIMAL                                            =  170 ,
    VILLAGER_STATE_CHECK_INTERACT_WITH_WORSHIP_SITE                                      =  171 ,
    VILLAGER_STATE_CHECK_INTERACT_WITH_ABODE                                             =  172 ,
    VILLAGER_STATE_CHECK_INTERACT_WITH_FIELD                                             =  173 ,
    VILLAGER_STATE_CHECK_INTERACT_WITH_FISH_FARM                                         =  174 ,
    VILLAGER_STATE_CHECK_INTERACT_WITH_TREE                                              =  175 ,
    VILLAGER_STATE_CHECK_INTERACT_WITH_BALL                                              =  176 ,
    VILLAGER_STATE_CHECK_INTERACT_WITH_POT                                               =  177 ,
    VILLAGER_STATE_CHECK_INTERACT_WITH_FOOTBALL                                          =  178 ,
    VILLAGER_STATE_CHECK_INTERACT_WITH_VILLAGER                                          =  179 ,
    VILLAGER_STATE_CHECK_INTERACT_WITH_MAGIC_LIVING                                      =  180 ,
    VILLAGER_STATE_CHECK_INTERACT_WITH_ROCK                                              =  181 ,
    VILLAGER_STATE_ARRIVES_AT_ROCK_FOR_WOOD                                              =  182 ,
    VILLAGER_STATE_GOT_WOOD_FROM_ROCK                                                    =  183 ,
    VILLAGER_STATE_REENTER_BUILDING_STATE                                                =  184 ,
    VILLAGER_STATE_ARRIVE_AT_PUSH_OBJECT                                                 =  185 ,
    VILLAGER_STATE_TAKE_WOOD_FROM_TREE                                                   =  186 ,
    VILLAGER_STATE_TAKE_WOOD_FROM_POT                                                    =  187 ,
    VILLAGER_STATE_TAKE_WOOD_FROM_TREE_FOR_BUILDING                                      =  188 ,
    VILLAGER_STATE_TAKE_WOOD_FROM_POT_FOR_BUILDING                                       =  189 ,
    VILLAGER_STATE_SHEPHERD_TAKE_ANIMAL_FOR_SLAUGHTER                                    =  190 ,
    VILLAGER_STATE_SHEPHERD_TAKES_CONTROL_OF_FLOCK                                       =  191 ,
    VILLAGER_STATE_SHEPHERD_RELEASES_CONTROL_OF_FLOCK                                    =  192 ,
    VILLAGER_STATE_DANCE_BUT_NOT_WORSHIP                                                 =  193 ,
    VILLAGER_STATE_FAINTING_REACTION                                                     =  194 ,
    VILLAGER_STATE_START_CONFUSED_REACTION                                               =  195 ,
    VILLAGER_STATE_CONFUSED_REACTION                                                     =  196 ,
    VILLAGER_STATE_AFTER_TAP_ON_ABODE                                                    =  197 ,
    VILLAGER_STATE_WEAK_ON_GROUND                                                        =  198 ,
    VILLAGER_STATE_SCRIPT_WANDER_AROUND_POSITION                                         =  199 ,
    VILLAGER_STATE_SCRIPT_PLAY_ANIM                                                      =  200 ,
    VILLAGER_STATE_GO_TOWARDS_TELEPORT_REACTION                                          =  201 ,
    VILLAGER_STATE_TELEPORT_REACTION                                                     =  202 ,
    VILLAGER_STATE_DANCE_WHILE_REACTING                                                  =  203 ,
    VILLAGER_STATE_CONTROLLED_BY_CREATURE                                                =  204 ,
    VILLAGER_STATE_POINT_AT_DEAD_PERSON                                                  =  205 ,
    VILLAGER_STATE_GO_TOWARDS_DEAD_PERSON                                                =  206 ,
    VILLAGER_STATE_LOOK_AT_DEAD_PERSON                                                   =  207 ,
    VILLAGER_STATE_MOURN_DEAD_PERSON                                                     =  208 ,
    VILLAGER_STATE_NOTHING_TO_DO                                                         =  209 ,
    VILLAGER_STATE_ARRIVES_AT_WORKSHOP_FOR_DROP_OFF                                      =  210 ,
    VILLAGER_STATE_ARRIVES_AT_STORAGE_PIT_FOR_WORKSHOP_MATERIALS                         =  211 ,
    VILLAGER_STATE_SHOW_POISONED                                                         =  212 ,
    VILLAGER_STATE_HIDING_AT_WORSHIP_SITE                                                =  213 ,
    VILLAGER_STATE_CROWD_REACTION                                                        =  214 ,
    VILLAGER_STATE_REACT_TO_FIRE                                                         =  215 ,
    VILLAGER_STATE_PUT_OUT_FIRE_BY_BEATING                                               =  216 ,
    VILLAGER_STATE_PUT_OUT_FIRE_WITH_WATER                                               =  217 ,
    VILLAGER_STATE_GET_WATER_TO_PUT_OUT_FIRE                                             =  218 ,
    VILLAGER_STATE_ON_FIRE                                                               =  219 ,
    VILLAGER_STATE_MOVE_AROUND_FIRE                                                      =  220 ,
    VILLAGER_STATE_DISCIPLE_NOTHING_TO_DO                                                =  221 ,
    VILLAGER_STATE_FOOTBALL_MOVE_TO_BALL                                                 =  222 ,
    VILLAGER_STATE_ARRIVES_AT_STORAGE_PIT_FOR_TRADER_PICK_UP                             =  223 ,
    VILLAGER_STATE_ARRIVES_AT_STORAGE_PIT_FOR_TRADER_DROP_OFF                            =  224 ,
    VILLAGER_STATE_BREEDER_DISCIPLE                                                      =  225 ,
    VILLAGER_STATE_MISSIONARY_DISCIPLE                                                   =  226 ,
    VILLAGER_STATE_REACT_TO_BREEDER                                                      =  227 ,
    VILLAGER_STATE_SHEPHERD_CHECK_ANIMAL_FOR_SLAUGHTER                                   =  228 ,
    VILLAGER_STATE_INTERACT_DECIDE_WHAT_TO_DO_FOR_OTHER_VILLAGER                         =  229 ,
    VILLAGER_STATE_ARTIFACT_DANCE                                                        =  230 ,
    VILLAGER_STATE_FLEEING_FROM_PREDATOR_REACTION                                        =  231 ,
    VILLAGER_STATE_WAIT_FOR_WOOD                                                         =  232 ,
    VILLAGER_STATE_INSPECT_OBJECT                                                        =  233 ,
    VILLAGER_STATE_GO_HOME_AND_CHANGE                                                    =  234 ,
    VILLAGER_STATE_WAIT_FOR_MATE                                                         =  235 ,
    VILLAGER_STATE_GO_AND_HIDE_IN_NEARBY_BUILDING                                        =  236 ,
    VILLAGER_STATE_LOOK_TO_SEE_IF_IT_IS_SAFE                                             =  237 ,
    VILLAGER_STATE_SLEEP_IN_TENT                                                         =  238 ,
    VILLAGER_STATE_PAUSE_FOR_A_SECOND                                                    =  239 ,
    VILLAGER_STATE_PANIC_REACTION                                                        =  240 ,
    VILLAGER_STATE_GET_FOOD_AT_WORSHIP_SITE                                              =  241 ,
    VILLAGER_STATE_GOTO_CONGREGATE_IN_TOWN_AFTER_EMERGENCY                               =  242 ,
    VILLAGER_STATE_CONGREGATE_IN_TOWN_AFTER_EMERGENCY                                    =  243 ,
    VILLAGER_STATE_SCRIPT_IN_CROWD                                                       =  244 ,
    VILLAGER_STATE_GO_AND_CHILLOUT_OUTSIDE_HOME                                          =  245 ,
    VILLAGER_STATE_SIT_AND_CHILLOUT                                                      =  246 ,
    VILLAGER_STATE_SCRIPT_GO_AND_MOVE_ALONG_PATH                                         =  247 ,
    VILLAGER_STATE_GO_HOME_FROM_WORSHIP                                                  =  248 ,
    VILLAGER_STATE_ARRIVES_HOME_FROM_WORSHIP                                             =  249 ,
    VILLAGER_STATE_SLEEP_IN_TENT_FROM_WORSHIP                                            =  250 ,
    VILLAGER_STATE_GO_TOWARDS_TELEPORT_REACTION_QUICKLY                                  =  251 ,
    VILLAGER_STATE_GO_AND_CHILLOUT_IN_TOWN                                               =  252 ,
    VILLAGER_STATE_WAIT_FOR_ARTIFACT_DANCE                                               =  253 ,
    VILLAGER_STATE_BREEDER_JUST_LANDED                                                   =  254 ,
    VILLAGER_STATE_LAST_STATE                                                            =  255 ,
};

static const char* VILLAGER_STATE_strs[VILLAGER_STATE_LAST_STATE] = {
  "VILLAGER_STATE_INVALID_STATE",
  "VILLAGER_STATE_MOVE_TO_POS",
  "VILLAGER_STATE_MOVE_TO_OBJECT",
  "VILLAGER_STATE_MOVE_ON_STRUCTURE",
  "VILLAGER_STATE_IN_SCRIPT",
  "VILLAGER_STATE_IN_DANCE",
  "VILLAGER_STATE_FLEEING_FROM_OBJECT_REACTION",
  "VILLAGER_STATE_LOOKING_AT_OBJECT_REACTION",
  "VILLAGER_STATE_FOLLOWING_OBJECT_REACTION",
  "VILLAGER_STATE_INSPECT_OBJECT_REACTION",
  "VILLAGER_STATE_FLYING",
  "VILLAGER_STATE_LANDED",
  "VILLAGER_STATE_LOOK_AT_FLYING_OBJECT_REACTION",
  "VILLAGER_STATE_SET_DYING",
  "VILLAGER_STATE_DYING",
  "VILLAGER_STATE_DEAD",
  "VILLAGER_STATE_DROWNING",
  "VILLAGER_STATE_DOWNED",
  "VILLAGER_STATE_BEING_EATEN",
  "VILLAGER_STATE_GOTO_FOOD_REACTION",
  "VILLAGER_STATE_ARRIVES_AT_FOOD_REACTION",
  "VILLAGER_STATE_GOTO_WOOD_REACTION",
  "VILLAGER_STATE_ARRIVES_AT_WOOD_REACTION",
  "VILLAGER_STATE_WAIT_FOR_ANIMATION",
  "VILLAGER_STATE_IN_HAND",
  "VILLAGER_STATE_GOTO_PICKUP_BALL_REACTION",
  "VILLAGER_STATE_ARRIVES_AT_PICKUP_BALL_REACTION",
  "VILLAGER_STATE_MOVE_IN_FLOCK",
  "VILLAGER_STATE_MOVE_ALONG_PATH",
  "VILLAGER_STATE_MOVE_ON_PATH",
  "VILLAGER_STATE_FLEEING_AND_LOOKING_AT_OBJECT_REACTION",
  "VILLAGER_STATE_GOTO_STORAGE_PIT_FOR_DROP_OFF",
  "VILLAGER_STATE_ARRIVES_AT_STORAGE_PIT_FOR_DROP_OFF",
  "VILLAGER_STATE_GOTO_STORAGE_PIT_FOR_FOOD",
  "VILLAGER_STATE_ARRIVES_AT_STORAGE_PIT_FOR_FOOD",
  "VILLAGER_STATE_ARRIVES_AT_HOME_WITH_FOOD",
  "VILLAGER_STATE_GO_HOME",
  "VILLAGER_STATE_ARRIVES_HOME",
  "VILLAGER_STATE_AT_HOME",
  "VILLAGER_STATE_ARRIVES_AT_STORAGE_PIT_FOR_BUILDING_MATERIALS",
  "VILLAGER_STATE_ARRIVES_AT_BUILDING_SITE",
  "VILLAGER_STATE_BUILDING",
  "VILLAGER_STATE_GOTO_STORAGE_PIT_FOR_WORSHIP_SUPPLIES",
  "VILLAGER_STATE_ARRIVES_AT_STORAGE_PIT_FOR_WORSHIP_SUPPLIES",
  "VILLAGER_STATE_GOTO_WORSHIP_SITE_WITH_SUPPLIES",
  "VILLAGER_STATE_MOVE_TO_WORSHIP_SITE_WITH_SUPPLIES",
  "VILLAGER_STATE_ARRIVES_AT_WORSHIP_SITE_WITH_SUPPLIES",
  "VILLAGER_STATE_FORESTER_MOVE_TO_FOREST",
  "VILLAGER_STATE_FORESTER_GOTO_FOREST",
  "VILLAGER_STATE_FORESTER_ARRIVES_AT_FOREST",
  "VILLAGER_STATE_FORESTER_CHOPS_TREE",
  "VILLAGER_STATE_FORESTER_CHOPS_TREE_FOR_BUILDING",
  "VILLAGER_STATE_FORESTER_FINISHED_FORESTERING",
  "VILLAGER_STATE_ARRIVES_AT_BIG_FOREST",
  "VILLAGER_STATE_ARRIVES_AT_BIG_FOREST_FOR_BUILDING",
  "VILLAGER_STATE_FISHERMAN_ARRIVES_AT_FISHING",
  "VILLAGER_STATE_FISHING",
  "VILLAGER_STATE_WAIT_FOR_COUNTER",
  "VILLAGER_STATE_GOTO_WORSHIP_SITE_FOR_WORSHIP",
  "VILLAGER_STATE_ARRIVES_AT_WORSHIP_SITE_FOR_WORSHIP",
  "VILLAGER_STATE_WORSHIPPING_AT_WORSHIP_SITE",
  "VILLAGER_STATE_GOTO_ALTAR_FOR_REST",
  "VILLAGER_STATE_ARRIVES_AT_ALTAR_FOR_REST",
  "VILLAGER_STATE_AT_ALTAR_REST",
  "VILLAGER_STATE_AT_ALTAR_FINISHED_REST",
  "VILLAGER_STATE_RESTART_WORSHIPPING_AT_WORSHIP_SITE",
  "VILLAGER_STATE_RESTART_WORSHIPPING_CREATURE",
  "VILLAGER_STATE_FARMER_ARRIVES_AT_FARM",
  "VILLAGER_STATE_FARMER_PLANTS_CROP",
  "VILLAGER_STATE_FARMER_DIGS_UP_CROP",
  "VILLAGER_STATE_MOVE_TO_FOOTBALL_PITCH_CONSTRUCTION",
  "VILLAGER_STATE_FOOTBALL_WALK_TO_POSITION",
  "VILLAGER_STATE_FOOTBALL_WAIT_FOR_KICK_OFF",
  "VILLAGER_STATE_FOOTBALL_ATTACKER",
  "VILLAGER_STATE_FOOTBALL_GOALIE",
  "VILLAGER_STATE_FOOTBALL_DEFENDER",
  "VILLAGER_STATE_FOOTBALL_WON_GOAL",
  "VILLAGER_STATE_FOOTBALL_LOST_GOAL",
  "VILLAGER_STATE_START_MOVE_TO_PICK_UP_BALL_FOR_DEAD_BALL",
  "VILLAGER_STATE_ARRIVED_AT_PICK_UP_BALL_FOR_DEAD_BALL",
  "VILLAGER_STATE_ARRIVED_AT_PUT_DOWN_BALL_FOR_DEAD_BALL_START",
  "VILLAGER_STATE_ARRIVED_AT_PUT_DOWN_BALL_FOR_DEAD_BALL_END",
  "VILLAGER_STATE_FOOTBALL_MATCH_PAUSED",
  "VILLAGER_STATE_FOOTBALL_WATCH_MATCH",
  "VILLAGER_STATE_FOOTBALL_MEXICAN_WAVE",
  "VILLAGER_STATE_CREATED",
  "VILLAGER_STATE_ARRIVES_IN_ABODE_TO_TRADE",
  "VILLAGER_STATE_ARRIVES_IN_ABODE_TO_PICK_UP_EXCESS",
  "VILLAGER_STATE_MAKE_SCARED_STIFF",
  "VILLAGER_STATE_SCARED_STIFF",
  "VILLAGER_STATE_WORSHIPPING_CREATURE",
  "VILLAGER_STATE_SHEPHERD_LOOK_FOR_FLOCK",
  "VILLAGER_STATE_SHEPHERD_MOVE_FLOCK_TO_WATER",
  "VILLAGER_STATE_SHEPHERD_MOVE_FLOCK_TO_FOOD",
  "VILLAGER_STATE_SHEPHERD_MOVE_FLOCK_BACK",
  "VILLAGER_STATE_SHEPHERD_DECIDE_WHAT_TO_DO_WITH_FLOCK",
  "VILLAGER_STATE_SHEPHERD_WAIT_FOR_FLOCK",
  "VILLAGER_STATE_SHEPHERD_SLAUGHTER_ANIMAL",
  "VILLAGER_STATE_SHEPHERD_FETCH_STRAY",
  "VILLAGER_STATE_SHEPHERD_GOTO_FLOCK",
  "VILLAGER_STATE_HOUSEWIFE_AT_HOME",
  "VILLAGER_STATE_HOUSEWIFE_GOTO_STORAGE_PIT",
  "VILLAGER_STATE_HOUSEWIFE_ARRIVES_AT_STORAGE_PIT",
  "VILLAGER_STATE_HOUSEWIFE_PICKUP_FROM_STORAGE_PIT",
  "VILLAGER_STATE_HOUSEWIFE_RETURN_HOME_WITH_FOOD",
  "VILLAGER_STATE_HOUSEWIFE_MAKE_DINNER",
  "VILLAGER_STATE_HOUSEWIFE_SERVES_DINNER",
  "VILLAGER_STATE_HOUSEWIFE_CLEARS_AWAY_DINNER",
  "VILLAGER_STATE_HOUSEWIFE_DOES_HOUSEWORK",
  "VILLAGER_STATE_HOUSEWIFE_GOSSIPS_AROUND_STORAGE_PIT",
  "VILLAGER_STATE_HOUSEWIFE_STARTS_GIVING_BIRTH",
  "VILLAGER_STATE_HOUSEWIFE_GIVING_BIRTH",
  "VILLAGER_STATE_HOUSEWIFE_GIVEN_BIRTH",
  "VILLAGER_STATE_CHILD_AT_CRECHE",
  "VILLAGER_STATE_CHILD_FOLLOWS_MOTHER",
  "VILLAGER_STATE_CHILD_BECOMES_ADULT",
  "VILLAGER_STATE_SITS_DOWN_TO_DINNER",
  "VILLAGER_STATE_EAT_FOOD",
  "VILLAGER_STATE_EAT_FOOD_AT_HOME",
  "VILLAGER_STATE_GOTO_BED_AT_HOME",
  "VILLAGER_STATE_SLEEPING_AT_HOME",
  "VILLAGER_STATE_WAKE_UP_AT_HOME",
  "VILLAGER_STATE_START_HAVING_SEX",
  "VILLAGER_STATE_HAVING_SEX",
  "VILLAGER_STATE_STOP_HAVING_SEX",
  "VILLAGER_STATE_START_HAVING_SEX_AT_HOME",
  "VILLAGER_STATE_HAVING_SEX_AT_HOME",
  "VILLAGER_STATE_STOP_HAVING_SEX_AT_HOME",
  "VILLAGER_STATE_WAIT_FOR_DINNER",
  "VILLAGER_STATE_HOMELESS_START",
  "VILLAGER_STATE_VAGRANT_START",
  "VILLAGER_STATE_MORN_DEATH",
  "VILLAGER_STATE_PERFORM_INSPECTION_REACTION",
  "VILLAGER_STATE_APPROACH_OBJECT_REACTION",
  "VILLAGER_STATE_INITIALISE_TELL_OTHERS_ABOUT_OBJECT",
  "VILLAGER_STATE_TELL_OTHERS_ABOUT_INTERESTING_OBJECT",
  "VILLAGER_STATE_APPROACH_VILLAGER_TO_TALK_TO",
  "VILLAGER_STATE_TELL_PARTICULAR_VILLAGER_ABOUT_OBJECT",
  "VILLAGER_STATE_INITIALISE_LOOK_AROUND_FOR_VILLAGER_TO_TELL",
  "VILLAGER_STATE_LOOK_AROUND_FOR_VILLAGER_TO_TELL",
  "VILLAGER_STATE_MOVE_TOWARDS_OBJECT_TO_LOOK_AT",
  "VILLAGER_STATE_INITIALISE_IMPRESSED_REACTION",
  "VILLAGER_STATE_PERFORM_IMPRESSED_REACTION",
  "VILLAGER_STATE_INITIALISE_FIGHT_REACTION",
  "VILLAGER_STATE_PERFORM_FIGHT_REACTION",
  "VILLAGER_STATE_HOMELESS_EAT_DINNER",
  "VILLAGER_STATE_INSPECT_CREATURE_REACTION",
  "VILLAGER_STATE_PERFORM_INSPECT_CREATURE_REACTION",
  "VILLAGER_STATE_APPROACH_CREATURE_REACTION",
  "VILLAGER_STATE_INITIALISE_BEWILDERED_BY_MAGIC_TREE_REACTION",
  "VILLAGER_STATE_PERFORM_BEWILDERED_BY_MAGIC_TREE_REACTION",
  "VILLAGER_STATE_TURN_TO_FACE_MAGIC_TREE",
  "VILLAGER_STATE_LOOK_AT_MAGIC_TREE",
  "VILLAGER_STATE_DANCE_FOR_EDITING_PURPOSES",
  "VILLAGER_STATE_MOVE_TO_DANCE_POS",
  "VILLAGER_STATE_INITIALISE_RESPECT_CREATURE_REACTION",
  "VILLAGER_STATE_PERFORM_RESPECT_CREATURE_REACTION",
  "VILLAGER_STATE_FINISH_RESPECT_CREATURE_REACTION",
  "VILLAGER_STATE_APPROACH_HAND_REACTION",
  "VILLAGER_STATE_FLEEING_FROM_CREATURE_REACTION",
  "VILLAGER_STATE_TURN_TO_FACE_CREATURE_REACTION",
  "VILLAGER_STATE_WATCH_FLYING_OBJECT_REACTION",
  "VILLAGER_STATE_POINT_AT_FLYING_OBJECT_REACTION",
  "VILLAGER_STATE_DECIDE_WHAT_TO_DO",
  "VILLAGER_STATE_INTERACT_DECIDE_WHAT_TO_DO",
  "VILLAGER_STATE_EAT_OUTSIDE",
  "VILLAGER_STATE_RUN_AWAY_FROM_OBJECT_REACTION",
  "VILLAGER_STATE_MOVE_TOWARDS_CREATURE_REACTION",
  "VILLAGER_STATE_AMAZED_BY_MAGIC_SHIELD_REACTION",
  "VILLAGER_STATE_VILLAGER_GOSSIPS",
  "VILLAGER_STATE_CHECK_INTERACT_WITH_ANIMAL",
  "VILLAGER_STATE_CHECK_INTERACT_WITH_WORSHIP_SITE",
  "VILLAGER_STATE_CHECK_INTERACT_WITH_ABODE",
  "VILLAGER_STATE_CHECK_INTERACT_WITH_FIELD",
  "VILLAGER_STATE_CHECK_INTERACT_WITH_FISH_FARM",
  "VILLAGER_STATE_CHECK_INTERACT_WITH_TREE",
  "VILLAGER_STATE_CHECK_INTERACT_WITH_BALL",
  "VILLAGER_STATE_CHECK_INTERACT_WITH_POT",
  "VILLAGER_STATE_CHECK_INTERACT_WITH_FOOTBALL",
  "VILLAGER_STATE_CHECK_INTERACT_WITH_VILLAGER",
  "VILLAGER_STATE_CHECK_INTERACT_WITH_MAGIC_LIVING",
  "VILLAGER_STATE_CHECK_INTERACT_WITH_ROCK",
  "VILLAGER_STATE_ARRIVES_AT_ROCK_FOR_WOOD",
  "VILLAGER_STATE_GOT_WOOD_FROM_ROCK",
  "VILLAGER_STATE_REENTER_BUILDING_STATE",
  "VILLAGER_STATE_ARRIVE_AT_PUSH_OBJECT",
  "VILLAGER_STATE_TAKE_WOOD_FROM_TREE",
  "VILLAGER_STATE_TAKE_WOOD_FROM_POT",
  "VILLAGER_STATE_TAKE_WOOD_FROM_TREE_FOR_BUILDING",
  "VILLAGER_STATE_TAKE_WOOD_FROM_POT_FOR_BUILDING",
  "VILLAGER_STATE_SHEPHERD_TAKE_ANIMAL_FOR_SLAUGHTER",
  "VILLAGER_STATE_SHEPHERD_TAKES_CONTROL_OF_FLOCK",
  "VILLAGER_STATE_SHEPHERD_RELEASES_CONTROL_OF_FLOCK",
  "VILLAGER_STATE_DANCE_BUT_NOT_WORSHIP",
  "VILLAGER_STATE_FAINTING_REACTION",
  "VILLAGER_STATE_START_CONFUSED_REACTION",
  "VILLAGER_STATE_CONFUSED_REACTION",
  "VILLAGER_STATE_AFTER_TAP_ON_ABODE",
  "VILLAGER_STATE_WEAK_ON_GROUND",
  "VILLAGER_STATE_SCRIPT_WANDER_AROUND_POSITION",
  "VILLAGER_STATE_SCRIPT_PLAY_ANIM",
  "VILLAGER_STATE_GO_TOWARDS_TELEPORT_REACTION",
  "VILLAGER_STATE_TELEPORT_REACTION",
  "VILLAGER_STATE_DANCE_WHILE_REACTING",
  "VILLAGER_STATE_CONTROLLED_BY_CREATURE",
  "VILLAGER_STATE_POINT_AT_DEAD_PERSON",
  "VILLAGER_STATE_GO_TOWARDS_DEAD_PERSON",
  "VILLAGER_STATE_LOOK_AT_DEAD_PERSON",
  "VILLAGER_STATE_MOURN_DEAD_PERSON",
  "VILLAGER_STATE_NOTHING_TO_DO",
  "VILLAGER_STATE_ARRIVES_AT_WORKSHOP_FOR_DROP_OFF",
  "VILLAGER_STATE_ARRIVES_AT_STORAGE_PIT_FOR_WORKSHOP_MATERIALS",
  "VILLAGER_STATE_SHOW_POISONED",
  "VILLAGER_STATE_HIDING_AT_WORSHIP_SITE",
  "VILLAGER_STATE_CROWD_REACTION",
  "VILLAGER_STATE_REACT_TO_FIRE",
  "VILLAGER_STATE_PUT_OUT_FIRE_BY_BEATING",
  "VILLAGER_STATE_PUT_OUT_FIRE_WITH_WATER",
  "VILLAGER_STATE_GET_WATER_TO_PUT_OUT_FIRE",
  "VILLAGER_STATE_ON_FIRE",
  "VILLAGER_STATE_MOVE_AROUND_FIRE",
  "VILLAGER_STATE_DISCIPLE_NOTHING_TO_DO",
  "VILLAGER_STATE_FOOTBALL_MOVE_TO_BALL",
  "VILLAGER_STATE_ARRIVES_AT_STORAGE_PIT_FOR_TRADER_PICK_UP",
  "VILLAGER_STATE_ARRIVES_AT_STORAGE_PIT_FOR_TRADER_DROP_OFF",
  "VILLAGER_STATE_BREEDER_DISCIPLE",
  "VILLAGER_STATE_MISSIONARY_DISCIPLE",
  "VILLAGER_STATE_REACT_TO_BREEDER",
  "VILLAGER_STATE_SHEPHERD_CHECK_ANIMAL_FOR_SLAUGHTER",
  "VILLAGER_STATE_INTERACT_DECIDE_WHAT_TO_DO_FOR_OTHER_VILLAGER",
  "VILLAGER_STATE_ARTIFACT_DANCE",
  "VILLAGER_STATE_FLEEING_FROM_PREDATOR_REACTION",
  "VILLAGER_STATE_WAIT_FOR_WOOD",
  "VILLAGER_STATE_INSPECT_OBJECT",
  "VILLAGER_STATE_GO_HOME_AND_CHANGE",
  "VILLAGER_STATE_WAIT_FOR_MATE",
  "VILLAGER_STATE_GO_AND_HIDE_IN_NEARBY_BUILDING",
  "VILLAGER_STATE_LOOK_TO_SEE_IF_IT_IS_SAFE",
  "VILLAGER_STATE_SLEEP_IN_TENT",
  "VILLAGER_STATE_PAUSE_FOR_A_SECOND",
  "VILLAGER_STATE_PANIC_REACTION",
  "VILLAGER_STATE_GET_FOOD_AT_WORSHIP_SITE",
  "VILLAGER_STATE_GOTO_CONGREGATE_IN_TOWN_AFTER_EMERGENCY",
  "VILLAGER_STATE_CONGREGATE_IN_TOWN_AFTER_EMERGENCY",
  "VILLAGER_STATE_SCRIPT_IN_CROWD",
  "VILLAGER_STATE_GO_AND_CHILLOUT_OUTSIDE_HOME",
  "VILLAGER_STATE_SIT_AND_CHILLOUT",
  "VILLAGER_STATE_SCRIPT_GO_AND_MOVE_ALONG_PATH",
  "VILLAGER_STATE_GO_HOME_FROM_WORSHIP",
  "VILLAGER_STATE_ARRIVES_HOME_FROM_WORSHIP",
  "VILLAGER_STATE_SLEEP_IN_TENT_FROM_WORSHIP",
  "VILLAGER_STATE_GO_TOWARDS_TELEPORT_REACTION_QUICKLY",
  "VILLAGER_STATE_GO_AND_CHILLOUT_IN_TOWN",
  "VILLAGER_STATE_WAIT_FOR_ARTIFACT_DANCE",
  "VILLAGER_STATE_BREEDER_JUST_LANDED",
};

//*****************************************************************************
// ENUM Values: ANIMAL_STATES
//*****************************************************************************
enum     ANIMAL_STATES
{
    ANIMAL_STATE_INVALID_STATE                                                           =  0 ,
    ANIMAL_STATE_MOVE_TO_POS                                                             =  1 ,
    ANIMAL_STATE_MOVE_TO_OBJECT                                                          =  2 ,
    ANIMAL_STATE_MOVE_ON_STRUCTURE                                                       =  3 ,
    ANIMAL_STATE_IN_SCRIPT                                                               =  4 ,
    ANIMAL_STATE_IN_DANCE                                                                =  5 ,
    ANIMAL_STATE_FLEEING_FROM_OBJECT_REACTION                                            =  6 ,
    ANIMAL_STATE_LOOKING_AT_OBJECT_REACTION                                              =  7 ,
    ANIMAL_STATE_FOLLOWING_OBJECT_REACTION                                               =  8 ,
    ANIMAL_STATE_INSPECT_OBJECT_REACTION                                                 =  9 ,
    ANIMAL_STATE_FLYING                                                                  =  10 ,
    ANIMAL_STATE_LANDED                                                                  =  11 ,
    ANIMAL_STATE_LOOK_AT_FLYING_OBJECT_REACTION                                          =  12 ,
    ANIMAL_STATE_SET_DYING                                                               =  13 ,
    ANIMAL_STATE_DYING                                                                   =  14 ,
    ANIMAL_STATE_DEAD                                                                    =  15 ,
    ANIMAL_STATE_DROWNING                                                                =  16 ,
    ANIMAL_STATE_DOWNED                                                                  =  17 ,
    ANIMAL_STATE_BEING_EATEN                                                             =  18 ,
    ANIMAL_STATE_GOTO_FOOD_REACTION                                                      =  19 ,
    ANIMAL_STATE_ARRIVES_AT_FOOD_REACTION                                                =  20 ,
    ANIMAL_STATE_GOTO_WOOD_REACTION                                                      =  21 ,
    ANIMAL_STATE_ARRIVES_AT_WOOD_REACTION                                                =  22 ,
    ANIMAL_STATE_WAIT_FOR_ANIMATION                                                      =  23 ,
    ANIMAL_STATE_IN_HAND                                                                 =  24 ,
    ANIMAL_STATE_GOTO_PICKUP_BALL_REACTION                                               =  25 ,
    ANIMAL_STATE_ARRIVES_AT_PICKUP_BALL_REACTION                                         =  26 ,
    ANIMAL_STATE_MOVE_IN_FLOCK                                                           =  27 ,
    ANIMAL_STATE_MOVE_ALONG_PATH                                                         =  28 ,
    ANIMAL_STATE_MOVE_ON_PATH                                                            =  29 ,
    ANIMAL_STATE_FLEEING_AND_LOOKING_AT_OBJECT_REACTION                                  =  30 ,
    ANIMAL_STATE_START_WANDER                                                            =  31 ,
    ANIMAL_STATE_WANDER                                                                  =  32 ,
    ANIMAL_STATE_EAT                                                                     =  33 ,
    ANIMAL_STATE_SEEK_SLEEP                                                              =  34 ,
    ANIMAL_STATE_SLEEPS                                                                  =  35 ,
    ANIMAL_STATE_SEEK_ENVIRONMENT                                                        =  36 ,
    ANIMAL_STATE_STANDARD_ACTION                                                         =  37 ,
    ANIMAL_STATE_START_TO_EAT                                                            =  38 ,
    ANIMAL_STATE_FINISH_EATING                                                           =  39 ,
    ANIMAL_STATE_TARGET_POUNCE                                                           =  40 ,
    ANIMAL_STATE_HUNTING_MOVE_TO_POS                                                     =  41 ,
    ANIMAL_STATE_MOVE_TO_POS_AND_LOOK_AROUND                                             =  42 ,
    ANIMAL_STATE_DECIDE_WHAT_TO_DO                                                       =  43 ,
    ANIMAL_STATE_SPECIAL_MOVE_TO_POS                                                     =  44 ,
    ANIMAL_STATE_FOLLOW_FLOCK                                                            =  45 ,
    ANIMAL_STATE_LAND_ON_OBJECT                                                          =  46 ,
    ANIMAL_STATE_LAND_AT_POS                                                             =  47 ,
    ANIMAL_STATE_INTERACT_DECIDE_WHAT_TO_DO                                              =  48 ,
    ANIMAL_STATE_FLEEING_FROM_PREDATOR_REACTION                                          =  49 ,
    ANIMAL_STATE_GIVES_BIRTH                                                             =  50 ,
    ANIMAL_STATE_HIDE_IN_LAIR                                                            =  51 ,
    ANIMAL_STATE_SEEK_FOOD                                                               =  52 ,
    ANIMAL_STATE_LAST_STATE                                                              =  53 ,
    // ANIMAL_STATE_SCRIPT_PLAY_ANIM                                                        =  53 ,
    // ANIMAL_STATE_LAST_STATE                                                              =  54 ,
};

#endif
