#ifndef BW1_DECOMP_LH_NET_ERRORS_INCLUDED_H
#define BW1_DECOMP_LH_NET_ERRORS_INCLUDED_H

#include <Lionhead/LHLog/ver4.0/LHLogger.h>

enum LH_NET_LOG_ERROR_LIST
{
	LH_NET_LOG_ERROR_NO_VALID_HOSTNAME = 0,
	LH_NET_LOG_ERROR_ADDRESS_NOT_RESOLVED = 1,
	LH_NET_LOG_ERROR_CREATING_SOCKET = 2,
	LH_NET_LOG_ERROR_CONNECT_TIMED_OUT = 3,
	LH_NET_LOG_ERROR_PLAYER_ALREADY_ON_CHANNEL = 4,
	LH_NET_LOG_ERROR_UNSUPPORTED_APPLICATION = 5,
	LH_NET_LOG_ERROR_UNSUPPORTED_PROTOCOL = 6,
	LH_NET_LOG_ERROR_WRONG_SERVER_TYPE = 7,
	LH_NET_LOG_ERROR_ALREADY_CONNECTED = 8,
	LH_NET_LOG_ERROR_SERVER_TIMED_OUT = 9,
	LH_NET_LOG_ERROR_GAME_NOT_RUNNING = 10,
	LH_NET_LOG_ERROR_CHANNEL_NOT_FOUND = 11,
	LH_NET_LOG_ERROR_MGJ_NOT_IN_PROGRESS = 12,
	LH_NET_LOG_ERROR_GAME_NOT_OPEN_FOR_MGJ = 13,
	LH_NET_LOG_ERROR_GAME_CALLBACK_FAILED = 14,
	LH_NET_LOG_ERROR_MGJ_PREVENTED = 15,
	LH_NET_LOG_ERROR_PLAYER_IN_RUNNING_GAME = 16,
	LH_NET_LOG_ERROR_USER_ID_NOT_IN_STRING = 17,
	LH_NET_LOG_ERROR_USER_NOT_REGISTERED = 18,
	LH_NET_LOG_ERROR_INVALID_LOGIN = 19,
	LH_NET_LOG_ERROR_PASSWORD_REQUIRED = 20,
	LH_NET_LOG_ERROR_USER_BUSY = 21,
	LH_NET_LOG_ERROR_INVALID_CHANNEL = 22,
	LH_NET_LOG_ERROR_LOGIN_SERVER_PROBLEM = 23,
	LH_NET_LOG_ERROR_ACCOUNT_NOT_ACTIVATED = 24,
	LH_NET_LOG_ERROR_REMOTE_SOCKET_CLOSED = 25,
	LH_NET_LOG_ERROR_COMPRESSION = 26,
	LH_NET_LOG_ERROR_COMPRESSED_DATA_CORRUPTED = 27,
	LH_NET_LOG_ERROR_SERVER_FULL = 28,
	LH_NET_LOG_ERROR_WINSOCK2_REQUIRED = 29,
	LH_NET_LOG_ERROR_INVALID_CD_KEY = 30,
	LH_NET_LOG_ERROR_HOST_AUTHENTICATION_FAILED = 31,
};

// BW1W120 10061d78 BW1M119 null
extern LHErrorCode LH_NET_Errors[];

static char*        LHLogLibraryName = "MultiplayerLib";
static LHErrorCode* LHLogErrorCodes = LH_NET_Errors;

#endif /* BW1_DECOMP_LH_NET_ERRORS_INCLUDED_H */
