#!/usr/bin/env python3

###
# Generates build files for the project.
# This file also includes the project configuration,
# such as compiler flags and the object matching status.
#
# Usage:
#   python3 configure.py
#   ninja
#
# Append --help to see available options.
###

import argparse
import sys
from pathlib import Path
from typing import Any, Dict, List

from tools.project import (
    Object,
    ProgressCategory,
    ProjectConfig,
    calculate_progress,
    generate_build,
    is_windows,
)

# Game versions
DEFAULT_VERSION = 2
VERSIONS = [
    "BW1W100",  # 0   PE/COFF, Windows v1.0
    "BW1W110",  # 1   PE/COFF, Windows v1.1
    "BW1W120",  # 2   PE/COFF, Windows v1.2
]

parser = argparse.ArgumentParser()
parser.add_argument(
    "mode",
    choices=["configure", "progress"],
    default="configure",
    help="script mode (default: configure)",
    nargs="?",
)
parser.add_argument(
    "-v",
    "--version",
    choices=VERSIONS,
    type=str.upper,
    default=VERSIONS[DEFAULT_VERSION],
    help="version to build",
)
parser.add_argument(
    "--build-dir",
    metavar="DIR",
    type=Path,
    default=Path("build"),
    help="base build directory (default: build)",
)
parser.add_argument(
    "--compilers",
    metavar="DIR",
    type=Path,
    help="path to compilers directory (optional)",
)
parser.add_argument(
    "--static-libs-dir",
    metavar="DIR",
    type=Path,
    dest="static_libs_dir",
    help="directory of prebuilt static libs (<lib_id>.lib); used verbatim "
    "instead of downloading the SP5 disc (optional)",
)
parser.add_argument(
    "--lld-link",
    metavar="BINARY",
    type=Path,
    dest="lld_link",
    help="path to lld-link binary (optional, defaults to lld-link in PATH)",
)
parser.add_argument(
    "--map",
    action="store_true",
    help="generate map file(s)",
)
parser.add_argument(
    "--debug",
    action="store_true",
    help="build with debug info (non-matching)",
)
if not is_windows():
    parser.add_argument(
        "--wrapper",
        metavar="BINARY",
        type=Path,
        help="path to wibo or wine (optional)",
    )
parser.add_argument(
    "--dtk",
    metavar="BINARY | DIR",
    type=Path,
    help="path to decomp-toolkit binary or source (optional)",
)
parser.add_argument(
    "--objdiff",
    metavar="BINARY | DIR",
    type=Path,
    help="path to objdiff-cli binary or source (optional)",
)
parser.add_argument(
    "--sjiswrap",
    metavar="EXE",
    type=Path,
    help="path to sjiswrap.exe (optional)",
)
parser.add_argument(
    "--ninja",
    metavar="BINARY",
    type=Path,
    help="path to ninja binary (optional)",
)
parser.add_argument(
    "--verbose",
    action="store_true",
    help="print verbose output",
)
parser.add_argument(
    "--non-matching",
    dest="non_matching",
    action="store_true",
    help="builds equivalent (but non-matching) or modded objects",
)
parser.add_argument(
    "--warn",
    dest="warn",
    type=str,
    choices=["all", "off", "error"],
    help="how to handle warnings",
)
parser.add_argument(
    "--no-progress",
    dest="progress",
    action="store_false",
    help="disable progress calculation",
)
args = parser.parse_args()

config = ProjectConfig()
config.version = str(args.version)
version_num = VERSIONS.index(config.version)

config.platform = "pe"

# Apply arguments
config.build_dir = args.build_dir
config.dtk_path = args.dtk
config.objdiff_path = args.objdiff
config.compilers_path = args.compilers
config.static_libs_path = args.static_libs_dir
config.lld_link_path = args.lld_link
config.generate_map = args.map
config.non_matching = args.non_matching
config.sjiswrap_path = args.sjiswrap
config.ninja_path = args.ninja
config.progress = args.progress
if not is_windows():
    config.wrapper = args.wrapper
# Don't build asm unless we're --non-matching
if not config.non_matching:
    config.asm_dir = None

# Tool versions
config.binutils_tag = "2.42-2"
config.dtk_tag = "v0.0.19"
config.objdiff_tag = "v3.7.2"
config.sjiswrap_tag = "v1.2.2"
config.wibo_tag = "1.1.0"
config.compilers_tag = "6.5"  # MSVC 6.0 SP5
config.lld_link_tag = "bw1-decomp-017"
# Static libraries to pull verbatim CRT objects from (see LibObject). All ship
# in the "msvc6.5" package: Visual Studio 6.0 (1998) SP5. When --static-libs-dir
# is given they are read from <dir>/msvc6.5/<lib>.lib; otherwise each is
# extracted at build time from the genuine SP5 install CD on the Internet Archive
# (item X08-02111) — the disc is downloaded and the file pulled out of its
# ISO9660 filesystem, so nothing is committed (see tools/download_tool.py).
# `static_lib_packages` maps each package to its archive.org item id; each id
# must have a matching download_tool URL entry.
config.static_lib_packages = {
    "msvc6.5": "X08-02111",  # MSVC 6.0 SP5 install CD
}
config.static_libs = {
    "libcmt": "msvc6.5",   # multithreaded C runtime (CRT)
    "libcpmt": "msvc6.5",  # multithreaded C++ standard library (iostreams, RTTI)
}

# Project
config.config_path = Path("config") / config.version / "config.yml"
config.check_sha_path = Path("config") / config.version / "build.sha1"
config.asflags = None
config.ldflags = []
config.reconfig_deps = []

# Post-link patch: applies version-specific binary fixups after linking,
# producing the final exe that is checked against build.sha1.
_linked = f"build/{config.version}/runblack-decrypted-linked.exe"
_patched = f"build/{config.version}/runblack-decrypted.exe"
_modules = ["LHAudio", "LHLog", "LHMultiplayer", "LHDialog"]
_module_linked = [f"build/{config.version}/{m}-linked.dll" for m in _modules]
_module_patched = [f"build/{config.version}/{m}.dll" for m in _modules]
config.custom_build_rules = [
    {
        "name": "postpatch",
        "command": f"$python tools/post_link_patch.py --version {config.version} $in $out",
        "description": "PATCH $out",
    },
]
config.custom_build_steps = {
    "post-link": [
        {
            "outputs": _patched,
            "rule": "postpatch",
            "inputs": _linked,
            "implicit": ["tools/post_link_patch.py", *_module_linked],
            "implicit_outputs": _module_patched,
        },
    ],
}
config.linker_version = "MSVC/6.5"
cflags_base = [
    "/nologo",
    "/W3",
    "/O2",
    "/Og",
    "/Ob1",
    "/Zd",
    "/MT",
    "/GR",
    "/I", "include",
    "/I", "src",
    f"/I", f"build/{config.version}/include",
    f"/I", f"build/compilers/{config.linker_version}/include",
    f"/DBUILD_VERSION={version_num}",
    f"/DVERSION_{config.version}",
]
if args.debug:
    cflags_base.extend(["/Zi", "/DDEBUG=1"])
else:
    cflags_base.append("/DNDEBUG=1")

# Optional numeric ID for decomp.me preset
config.scratch_preset_id = 208


Matching = True                   # Object matches and should be linked
NonMatching = False               # Object does not match and should not be linked
Equivalent = config.non_matching  # Object should be linked when configured with --non-matching


# Object is only matching for specific versions
def MatchingFor(*versions):
    return config.version in versions


# An object linked verbatim from a downloaded static library (e.g. LIBCMT.LIB).
# `archive` is the library id (see config.libcmt_tag); `member` is the path of
# the object inside the archive. The unit name is derived as lib/<archive>/<obj>.
def LibObject(completed, archive, member, **options):
    name = "lib/" + archive + "/" + member.replace("\\", "/").rsplit("/", 1)[-1]
    return Object(completed, name, lib_archive=archive, lib_member=member, **options)


config.warn_missing_config = True
config.warn_missing_source = False
config.libs = [
    {
        "lib": "runblack",
        "compiler_version": config.linker_version,
        "cflags": cflags_base,
        "progress_category": "game",
        "objects": [
            Object(NonMatching, "Black/Abode.cpp"),
            Object(NonMatching, "Black/AbodeInfo.cpp"),
            Object(NonMatching, "Black/alexmfc.cpp"),
            Object(NonMatching, "Black/Alignment.cpp"),
            Object(NonMatching, "Black/AlignmentInfo.cpp"),
            Object(NonMatching, "Black/Animal.cpp"),
            Object(NonMatching, "Black/AnimalAnimation.cpp"),
            Object(NonMatching, "Black/AnimalBat.cpp"),
            Object(NonMatching, "Black/AnimalCow.cpp"),
            Object(NonMatching, "Black/AnimalCrow.cpp"),
            Object(NonMatching, "Black/AnimalDove.cpp"),
            Object(NonMatching, "Black/AnimalGoat.cpp"),
            Object(NonMatching, "Black/AnimalHorse.cpp"),
            Object(NonMatching, "Black/AnimalInfo.cpp"),
            Object(NonMatching, "Black/AnimalLeopard.cpp"),
            Object(NonMatching, "Black/AnimalLion.cpp"),
            Object(NonMatching, "Black/AnimalPig.cpp"),
            Object(NonMatching, "Black/AnimalPigeon.cpp"),
            Object(NonMatching, "Black/AnimalReaction.cpp"),
            Object(NonMatching, "Black/AnimalSeagull.cpp"),
            Object(NonMatching, "Black/AnimalSheep.cpp"),
            Object(NonMatching, "Black/AnimalSpellWolf.cpp"),
            Object(NonMatching, "Black/AnimalStateTableInfo.cpp"),
            Object(NonMatching, "Black/AnimalSwallow.cpp"),
            Object(NonMatching, "Black/AnimalTiger.cpp"),
            Object(NonMatching, "Black/AnimalTortoise.cpp"),
            Object(NonMatching, "Black/AnimalVulture.cpp"),
            Object(NonMatching, "Black/AnimalWolf.cpp"),
            Object(NonMatching, "Black/AnimalZebra.cpp"),
            Object(NonMatching, "Black/AnimatedStatic.cpp"),
            Object(NonMatching, "Black/AnimatedStaticInfo.cpp"),
            Object(NonMatching, "Black/Animations.cpp"),
            Object(NonMatching, "Black/Arena.cpp"),
            Object(NonMatching, "Black/Arrow.cpp"),
            Object(NonMatching, "Black/ArrowInfo.cpp"),
            Object(NonMatching, "Black/Artifact.cpp"),
            Object(NonMatching, "Black/Audio.cpp"),
            Object(NonMatching, "Black/AudioMusicThing.cpp"),
            Object(NonMatching, "Black/audiotag.cpp"),
            Object(NonMatching, "Black/Balance.cpp"),
            Object(NonMatching, "Black/Ball.cpp"),
            Object(NonMatching, "Black/BallInfo.cpp"),
            Object(NonMatching, "Black/Base.cpp"),
            Object(NonMatching, "Black/BaseInfo.cpp"),
            Object(NonMatching, "Black/Belief.cpp"),
            Object(NonMatching, "Black/BeliefInfo.cpp"),
            Object(NonMatching, "Black/BigForest.cpp"),
            Object(NonMatching, "Black/BigForestInfo.cpp"),
            Object(NonMatching, "Black/BindableAction.cpp"),
            Object(NonMatching, "Black/Bonfire.cpp"),
            Object(NonMatching, "Black/Bookmark.cpp"),
            Object(NonMatching, "Black/Bubble.cpp"),
            Object(NonMatching, "Black/BuildingSite.cpp"),
            Object(NonMatching, "Black/BWGameSpy.cpp"),
            Object(NonMatching, "Black/BWLan.cpp"),
            Object(NonMatching, "Black/Camera.cpp"),
            Object(NonMatching, "Black/CameraEditor.cpp"),
            Object(NonMatching, "Black/CameraExclusion.cpp"),
            Object(NonMatching, "Black/CameraHelp.cpp"),
            Object(NonMatching, "Black/CameraMode.cpp"),
            Object(NonMatching, "Black/CameraModeCitadel.cpp"),
            Object(NonMatching, "Black/CameraModeCtrInteract.cpp"),
            Object(NonMatching, "Black/CameraModeDance.cpp"),
            Object(NonMatching, "Black/CameraModeFlyAndClick.cpp"),
            Object(NonMatching, "Black/CameraModeFollow.cpp"),
            Object(NonMatching, "Black/CameraModeFollowHeading.cpp"),
            Object(NonMatching, "Black/CameraModeFree.cpp"),
            Object(NonMatching, "Black/CameraModeNew.cpp"),
            Object(NonMatching, "Black/CameraModeNew1.cpp"),
            Object(NonMatching, "Black/CameraModeNew2.cpp"),
            Object(NonMatching, "Black/CameraModeNew3.cpp"),
            Object(NonMatching, "Black/CameraModePath.cpp"),
            Object(NonMatching, "Black/CameraModeScript.cpp"),
            Object(NonMatching, "Black/CameraModeTwoObjects.cpp"),
            Object(NonMatching, "Black/CarriedObject.cpp"),
            Object(NonMatching, "Black/CDBox.cpp"),
            Object(NonMatching, "Black/Chain.cpp"),
            Object(NonMatching, "Black/ChallengeRoom.cpp"),
            Object(NonMatching, "Black/ChallengeRoomCamera.cpp"),
            Object(NonMatching, "Black/ChannelBox.cpp"),
            Object(NonMatching, "Black/Citadel.cpp"),
            Object(NonMatching, "Black/CitadelBuildingSite.cpp"),
            Object(NonMatching, "Black/CitadelEntrance.cpp"),
            Object(NonMatching, "Black/CitadelHeart.cpp"),
            Object(NonMatching, "Black/CitadelHeartInfo.cpp"),
            Object(NonMatching, "Black/CitadelInfo.cpp"),
            Object(NonMatching, "Black/CitadelPart.cpp"),
            Object(NonMatching, "Black/CitadelPartInfo.cpp"),
            Object(NonMatching, "Black/citadelpeople.cpp"),
            Object(NonMatching, "Black/Climate.cpp"),
            Object(NonMatching, "Black/ClimateInfo.cpp"),
            Object(NonMatching, "Black/ClimateRainInfo.cpp"),
            Object(NonMatching, "Black/Collide.cpp"),
            Object(NonMatching, "Black/Config.cpp"),
            Object(NonMatching, "Black/Container.cpp"),
            Object(NonMatching, "Black/ContainerInfo.cpp"),
            Object(NonMatching, "Black/ControlHand.cpp"),
            Object(NonMatching, "Black/ControlMap.cpp"),
            Object(NonMatching, "Black/Cow.cpp"),
            Object(NonMatching, "Black/CPUCheck.cpp"),
            Object(NonMatching, "Black/Creature.cpp"),
            Object(NonMatching, "Black/Creature3D.cpp"),
            Object(NonMatching, "Black/CreatureAction.cpp"),
            Object(NonMatching, "Black/CreatureActionInfo.cpp"),
            Object(NonMatching, "Black/CreatureActionsKnownAbout.cpp"),
            Object(NonMatching, "Black/CreatureAgenda.cpp"),
            Object(NonMatching, "Black/CreatureAttitudeToCreature.cpp"),
            Object(NonMatching, "Black/CreatureAttitudeToPlayer.cpp"),
            Object(NonMatching, "Black/CreatureCommandState.cpp"),
            Object(NonMatching, "Black/CreatureContext.cpp"),
            Object(NonMatching, "Black/CreatureDatabase.cpp"),
            Object(NonMatching, "Black/CreatureDevelopment.cpp"),
            Object(NonMatching, "Black/CreatureDirectControl.cpp"),
            Object(NonMatching, "Black/CreatureExplorationMap.cpp"),
            Object(NonMatching, "Black/CreatureFace.cpp"),
            Object(NonMatching, "Black/CreatureHelp.cpp"),
            Object(NonMatching, "Black/CreatureInfo.cpp"),
            Object(NonMatching, "Black/CreatureInitialDesireInfo.cpp"),
            Object(NonMatching, "Black/CreatureInitialLesson.cpp"),
            Object(NonMatching, "Black/CreatureInitialSourceInfo.cpp"),
            Object(NonMatching, "Black/CreatureLearning.cpp"),
            Object(NonMatching, "Black/CreatureLessonChooser.cpp"),
            Object(NonMatching, "Black/CreatureLook.cpp"),
            Object(NonMatching, "Black/CreatureMental.cpp"),
            Object(NonMatching, "Black/CreatureMentalAttributeTest.cpp"),
            Object(NonMatching, "Black/CreatureMentalBelief.cpp"),
            Object(NonMatching, "Black/CreatureMentalBeliefs.cpp"),
            Object(NonMatching, "Black/CreatureMentalDebug.cpp"),
            Object(NonMatching, "Black/CreatureMentalDesire.cpp"),
            Object(NonMatching, "Black/CreatureMentalDesireSource.cpp"),
            Object(NonMatching, "Black/CreatureMentalExploration.cpp"),
            Object(NonMatching, "Black/CreatureMentalLearn.cpp"),
            Object(NonMatching, "Black/CreatureMentalLearnAction.cpp"),
            Object(NonMatching, "Black/CreatureMentalMisc.cpp"),
            Object(NonMatching, "Black/CreatureMentalSaveAndLoad.cpp"),
            Object(NonMatching, "Black/CreatureMimic.cpp"),
            Object(NonMatching, "Black/CreatureMimicInfo.cpp"),
            Object(NonMatching, "Black/CreatureMorph.cpp"),
            Object(NonMatching, "Black/CreatureObjectsInspected.cpp"),
            Object(NonMatching, "Black/CreaturePen.cpp"),
            Object(NonMatching, "Black/CreaturePenInfo.cpp"),
            Object(NonMatching, "Black/CreaturePhysical.cpp"),
            Object(NonMatching, "Black/CreaturePlan.cpp"),
            Object(NonMatching, "Black/CreaturePreviousLesson.cpp"),
            Object(NonMatching, "Black/CreatureReaction.cpp"),
            Object(NonMatching, "Black/CreatureReceiveSpell.cpp"),
            Object(NonMatching, "Black/CreatureRoom.cpp"),
            Object(NonMatching, "Black/CreatureRoomCamera.cpp"),
            Object(NonMatching, "Black/CreatureScript.cpp"),
            Object(NonMatching, "Black/CreatureSelect.cpp"),
            Object(NonMatching, "Black/CreatureSourceBoundsInfo.cpp"),
            Object(NonMatching, "Black/CreatureSubAction.cpp"),
            Object(NonMatching, "Black/CreatureSubActions.cpp"),
            Object(NonMatching, "Black/CreatureVisionState.cpp"),
            Object(NonMatching, "Black/CreatureWhatToDoNext.cpp"),
            Object(NonMatching, "Black/Creche.cpp"),
            Object(NonMatching, "Black/CreditsRoom.cpp"),
            Object(NonMatching, "Black/Creed.cpp"),
            Object(NonMatching, "Black/Dance.cpp"),
            Object(NonMatching, "Black/DanceGroup.cpp"),
            Object(NonMatching, "Black/DanceInfo.cpp"),
            Object(NonMatching, "Black/DanceKey.cpp"),
            Object(NonMatching, "Black/DanceLight.cpp"),
            Object(NonMatching, "Black/DancePathInfo.cpp"),
            Object(NonMatching, "Black/DanceShape.cpp"),
            Object(NonMatching, "Black/Data.cpp"),
            Object(NonMatching, "Black/DeadTree.cpp"),
            Object(NonMatching, "Black/Debug.cpp"),
            Object(NonMatching, "Black/DefensiveSphere.cpp"),
            Object(NonMatching, "Black/DialogBoxBase.cpp"),
            Object(NonMatching, "Black/DialogBoxImmersion.cpp"),
            Object(NonMatching, "Black/DialogBoxKeyBinding.cpp"),
            Object(NonMatching, "Black/DialogBoxMain.cpp"),
            Object(NonMatching, "Black/DialogBoxOptions.cpp"),
            Object(NonMatching, "Black/DialogBoxSaveMessage.cpp"),
            Object(NonMatching, "Black/DifferentCreatureInfo.cpp"),
            Object(NonMatching, "Black/DrawingObject.cpp"),
            Object(NonMatching, "Black/EarthQuake.cpp"),
            Object(NonMatching, "Black/EditingDebugBox.cpp"),
            Object(NonMatching, "Black/EditorAnim.cpp"),
            Object(NonMatching, "Black/EditorHug.cpp"),
            Object(NonMatching, "Black/EditorIcon.cpp"),
            Object(NonMatching, "Black/EditorIconBase.cpp"),
            Object(NonMatching, "Black/EditorIconGraph.cpp"),
            Object(NonMatching, "Black/EditorIconPDM.cpp"),
            Object(NonMatching, "Black/EditorIconPlace.cpp"),
            Object(NonMatching, "Black/EditorIconStrip.cpp"),
            Object(NonMatching, "Black/EditorPhysics.cpp"),
            Object(NonMatching, "Black/Effect.cpp"),
            Object(NonMatching, "Black/EffectInfo.cpp"),
            Object(NonMatching, "Black/EffectValues.cpp"),
            Object(NonMatching, "Black/EndGameBox.cpp"),
            Object(NonMatching, "Black/ExtraFeatures.cpp"),
            Object(NonMatching, "Black/fallingspell.cpp"),
            Object(NonMatching, "Black/Feature.cpp"),
            Object(NonMatching, "Black/FeatureInfo.cpp"),
            Object(NonMatching, "Black/FelledTree.cpp"),
            Object(NonMatching, "Black/Field.cpp"),
            Object(NonMatching, "Black/FieldInfo.cpp"),
            Object(NonMatching, "Black/FieldTypeInfo.cpp"),
            Object(NonMatching, "Black/FireEffect.cpp"),
            Object(NonMatching, "Black/FireFly.cpp"),
            Object(NonMatching, "Black/FireGraphic.cpp"),
            Object(NonMatching, "Black/FishFarm.cpp"),
            Object(NonMatching, "Black/FishFarmInfo.cpp"),
            Object(NonMatching, "Black/Fixed.cpp"),
            Object(NonMatching, "Black/Flock.cpp"),
            Object(NonMatching, "Black/Flower.cpp"),
            Object(NonMatching, "Black/FlowersInfo.cpp"),
            Object(NonMatching, "Black/FootBall.cpp"),
            Object(NonMatching, "Black/FootballInfo.cpp"),
            Object(NonMatching, "Black/FootballPositionInfo.cpp"),
            Object(NonMatching, "Black/Footpath.cpp"),
            Object(NonMatching, "Black/FootpathFinder.cpp"),
            Object(NonMatching, "Black/FootpathLink.cpp"),
            Object(NonMatching, "Black/FootpathLinkSave.cpp"),
            Object(NonMatching, "Black/FootpathNode.cpp"),
            Object(NonMatching, "Black/Forest.cpp"),
            Object(NonMatching, "Black/ForestInfo.cpp"),
            Object(NonMatching, "Black/Fragment.cpp"),
            Object(NonMatching, "Black/frontend.cpp"),
            Object(NonMatching, "Black/FrontEndSetupGame.cpp"),
            Object(NonMatching, "Black/FrontEndSetupMultiplayer.cpp"),
            Object(NonMatching, "Black/FuncT.cpp"),
            Object(NonMatching, "Black/Furniture.cpp"),
            Object(NonMatching, "Black/FurnitureInfo.cpp"),
            Object(NonMatching, "Black/Game.cpp"),
            Object(NonMatching, "Black/Game3DObject.cpp"),
            Object(NonMatching, "Black/GameArea.cpp"),
            Object(NonMatching, "Black/GameInfo.cpp"),
            Object(NonMatching, "Black/GameOptionsRoom.cpp"),
            Object(NonMatching, "Black/GameOSFile.cpp"),
            Object(NonMatching, "Black/GameStats.cpp"),
            Object(NonMatching, "Black/GameStatsFrontEnd.cpp"),
            Object(NonMatching, "Black/GameStatsList.cpp"),
            Object(NonMatching, "Black/GameThing.cpp"),
            Object(NonMatching, "Black/GameThingWithPos.cpp"),
            Object(NonMatching, "Black/GatheringBox.cpp"),
            Object(NonMatching, "Black/GatheringInterface.cpp"),
            Object(NonMatching, "Black/GenerateCreatureHTML.cpp"),
            Object(NonMatching, "Black/GestureSystem.cpp"),
            Object(NonMatching, "Black/GestureSystemData.cpp"),
            Object(NonMatching, "Black/GestureSystemDataList.cpp"),
            Object(NonMatching, "Black/GestureSystemResult.cpp"),
            Object(NonMatching, "Black/GJPersistent.cpp"),
            Object(NonMatching, "Black/GJProperty.cpp"),
            Object(NonMatching, "Black/GJUtils.cpp"),
            Object(NonMatching, "Black/GJVnoise.cpp"),
            Object(NonMatching, "Black/Global.cpp"),
            Object(NonMatching, "Black/GlobalGameList.cpp"),
            Object(NonMatching, "Black/GlobalGameLists.cpp"),
            Object(NonMatching, "Black/GraveYard.cpp"),
            Object(NonMatching, "Black/GroupBehaviour.cpp"),
            Object(NonMatching, "Black/GSLobbybox.cpp"),
            Object(NonMatching, "Black/Guidance.cpp"),
            Object(NonMatching, "Black/HairGroup.cpp"),
            Object(NonMatching, "Black/HandState.cpp"),
            Object(NonMatching, "Black/HandStateCamera.cpp"),
            Object(NonMatching, "Black/HandStateCitadel.cpp"),
            Object(NonMatching, "Black/HandStateCreature.cpp"),
            Object(NonMatching, "Black/HandStateGrain.cpp"),
            Object(NonMatching, "Black/HandStateHolding.cpp"),
            Object(NonMatching, "Black/HandStateInvisible.cpp"),
            Object(NonMatching, "Black/HandStateMultiPickUp.cpp"),
            Object(NonMatching, "Black/HandStateNormal.cpp"),
            Object(NonMatching, "Black/HandStatePlayAnim.cpp"),
            Object(NonMatching, "Black/HandStateTotem.cpp"),
            Object(NonMatching, "Black/HandStateTug.cpp"),
            Object(NonMatching, "Black/HanoiBlock.cpp"),
            Object(NonMatching, "Black/helpdude.cpp"),
            Object(NonMatching, "Black/HelpDudeControl.cpp"),
            Object(NonMatching, "Black/HelpDudeLipSync.cpp"),
            Object(NonMatching, "Black/HelpEditor.cpp"),
            Object(NonMatching, "Black/HelpProfile.cpp"),
            Object(NonMatching, "Black/HelpSpirit.cpp"),
            Object(NonMatching, "Black/HelpSpiritInfo.cpp"),
            Object(NonMatching, "Black/HelpSpritesGuidance.cpp"),
            Object(NonMatching, "Black/HelpSystem.cpp"),
            Object(NonMatching, "Black/HelpSystemBubble.cpp"),
            Object(NonMatching, "Black/HelpSystemInfo.cpp"),
            Object(NonMatching, "Black/HelpSystemToolTips.cpp"),
            Object(NonMatching, "Black/HelpText.cpp"),
            Object(NonMatching, "Black/HistoryBox.cpp"),
            Object(NonMatching, "Black/Influence.cpp"),
            Object(NonMatching, "Black/InfluenceInfo.cpp"),
            Object(NonMatching, "Black/InnerCamera.cpp"),
            Object(NonMatching, "Black/Interface.cpp"),
            Object(NonMatching, "Black/InterfaceAction.cpp"),
            Object(NonMatching, "Black/InterfaceCollide.cpp"),
            Object(NonMatching, "Black/InterfaceFlags.cpp"),
            Object(NonMatching, "Black/InterfaceHandState.cpp"),
            Object(NonMatching, "Black/InterfaceImmersion.cpp"),
            Object(NonMatching, "Black/InterfaceMessage.cpp"),
            Object(NonMatching, "Black/InterfaceMessageBuffer.cpp"),
            Object(NonMatching, "Black/InterfaceStatus.cpp"),
            Object(NonMatching, "Black/IpSpecialDialog.cpp"),
            Object(NonMatching, "Black/JCGameBlock.cpp"),
            Object(NonMatching, "Black/JCMisc.cpp"),
            Object(NonMatching, "Black/Job.cpp"),
            Object(NonMatching, "Black/JobInfo.cpp"),
            Object(NonMatching, "Black/KeyBuffer.cpp"),
            Object(NonMatching, "Black/LandAlignement.cpp"),
            Object(NonMatching, "Black/LandBalance.cpp"),
            Object(NonMatching, "Black/LandFeature.cpp"),
            Object(NonMatching, "Black/Landscape.cpp"),
            Object(NonMatching, "Black/Language.cpp"),
            Object(NonMatching, "Black/LayerCommunication.cpp"),
            Object(NonMatching, "Black/Leash.cpp"),
            Object(NonMatching, "Black/LeashSelectorInfo.cpp"),
            Object(NonMatching, "Black/LeashStatus.cpp"),
            Object(NonMatching, "Black/LevelOfDetail.cpp"),
            Object(NonMatching, "Black/LHInetWeather.cpp"),
            Object(NonMatching, "Black/LHNetBase.cpp"),
            Object(NonMatching, "Black/LightSheet.cpp"),
            Object(NonMatching, "Black/LiquidParticle.cpp"),
            Object(NonMatching, "Black/Living.cpp"),
            Object(NonMatching, "Black/LivingAction.cpp"),
            Object(NonMatching, "Black/LivingInfo.cpp"),
            Object(NonMatching, "Black/LivingProjectile.cpp"),
            Object(NonMatching, "Black/LivingReaction.cpp"),
            Object(NonMatching, "Black/LoaderAnon.cpp"),
            Object(NonMatching, "Black/LoadingBox.cpp"),
            Object(NonMatching, "Black/LoadingScreen.cpp"),
            Object(NonMatching, "Black/Lobbybox.cpp"),
            Object(NonMatching, "Black/LocalBase.cpp"),
            Object(NonMatching, "Black/LoginBox.cpp"),
            Object(NonMatching, "Black/logo.cpp"),
            Object(NonMatching, "Black/MagicCreatureSpellInfo.cpp"),
            Object(NonMatching, "Black/MagicEffectInfo.cpp"),
            Object(NonMatching, "Black/MagicFireBallInfo.cpp"),
            Object(NonMatching, "Black/MagicFlockFlyingInfo.cpp"),
            Object(NonMatching, "Black/MagicFlockGroundInfo.cpp"),
            Object(NonMatching, "Black/MagicFood.cpp"),
            Object(NonMatching, "Black/MagicFoodInfo.cpp"),
            Object(NonMatching, "Black/MagicForestInfo.cpp"),
            Object(NonMatching, "Black/MagicHand.cpp"),
            Object(NonMatching, "Black/MagicHealInfo.cpp"),
            Object(NonMatching, "Black/MagicInfo.cpp"),
            Object(NonMatching, "Black/MagicLivingInfo.cpp"),
            Object(NonMatching, "Black/MagicObjectInfo.cpp"),
            Object(NonMatching, "Black/MagicRadiusSpellInfo.cpp"),
            Object(NonMatching, "Black/MagicResourceInfo.cpp"),
            Object(NonMatching, "Black/MagicShield.cpp"),
            Object(NonMatching, "Black/MagicShieldInfo.cpp"),
            Object(NonMatching, "Black/MagicStormAndTornadoInfo.cpp"),
            Object(NonMatching, "Black/MagicTeleport.cpp"),
            Object(NonMatching, "Black/MagicTeleportInfo.cpp"),
            Object(NonMatching, "Black/MagicTree.cpp"),
            Object(NonMatching, "Black/MagicVortex.cpp"),
            Object(NonMatching, "Black/MagicWaterInfo.cpp"),
            Object(NonMatching, "Black/MagicWood.cpp"),
            Object(NonMatching, "Black/MainMenu.cpp"),
            Object(NonMatching, "Black/Map.cpp"),
            Object(NonMatching, "Black/MapCoords.cpp"),
            Object(NonMatching, "Black/MapShield.cpp"),
            Object(NonMatching, "Black/MapShieldInfo.cpp"),
            Object(NonMatching, "Black/Meeting.cpp"),
            Object(NonMatching, "Black/MiniDialogBoxOptions.cpp"),
            Object(NonMatching, "Black/Mist.cpp"),
            Object(NonMatching, "Black/Mobile.cpp"),
            Object(NonMatching, "Black/MobileInfo.cpp"),
            Object(NonMatching, "Black/MobileObject.cpp"),
            Object(NonMatching, "Black/MobileObjectInfo.cpp"),
            Object(NonMatching, "Black/MobileStatic.cpp"),
            Object(NonMatching, "Black/MobileStaticInfo.cpp"),
            Object(NonMatching, "Black/MobileWallHug.cpp", extra_cflags=["/GX"]),
            Object(NonMatching, "Black/MobileWallHugInfo.cpp"),
            Object(NonMatching, "Black/MorphableObject.cpp"),
            Object(NonMatching, "Black/MPFEAlexDialog.cpp"),
            Object(NonMatching, "Black/MPFEAskJoinMessage.cpp"),
            Object(NonMatching, "Black/MPFECancelStartMessage.cpp"),
            Object(NonMatching, "Black/MPFEChangeClanRequest.cpp"),
            Object(NonMatching, "Black/MPFEChangedMapMessage.cpp"),
            Object(NonMatching, "Black/MPFEChangedTeamRequestMessage.cpp"),
            Object(NonMatching, "Black/MPFEChannelData.cpp"),
            Object(NonMatching, "Black/MPFEChannelMessages.cpp"),
            Object(NonMatching, "Black/MPFEChannelSelector.cpp"),
            Object(NonMatching, "Black/MPFEChooseConnection.cpp"),
            Object(NonMatching, "Black/MPFEClanDetails.cpp"),
            Object(NonMatching, "Black/MPFEClanList.cpp"),
            Object(NonMatching, "Black/MPFEConditionMessages.cpp"),
            Object(NonMatching, "Black/MPFECondtionUpdateMessage.cpp"),
            Object(Matching, "Black/MPFEConnectionStatus.cpp"),
            Object(NonMatching, "Black/MPFECreateGame.cpp"),
            Object(NonMatching, "Black/MPFEDatabase.cpp"),
            Object(NonMatching, "Black/MPFEDatabaseID.cpp"),
            Object(NonMatching, "Black/MPFEDisconnectNowMessage.cpp"),
            Object(NonMatching, "Black/MPFEDownloads.cpp"),
            Object(NonMatching, "Black/MPFEFileTransfer.cpp"),
            Object(NonMatching, "Black/MPFEFileTransferMessage.cpp"),
            Object(NonMatching, "Black/MPFEFindGame.cpp"),
            Object(NonMatching, "Black/MPFEGameStartMessages.cpp"),
            Object(NonMatching, "Black/MPFEHasCreature.cpp"),
            Object(NonMatching, "Black/MPFEInviteToTeamMessage.cpp"),
            Object(NonMatching, "Black/MPFEKickMessage.cpp"),
            Object(NonMatching, "Black/MPFEKickMessageRequest.cpp"),
            Object(NonMatching, "Black/MPFELogin.cpp"),
            Object(NonMatching, "Black/MPFEMapErrorMessage.cpp"),
            Object(NonMatching, "Black/MPFEMapMessages.cpp"),
            Object(NonMatching, "Black/MPFEMessageObject.cpp"),
            Object(NonMatching, "Black/MPFEPlayerDetails.cpp"),
            Object(NonMatching, "Black/MPFEPrivateChatMessage.cpp"),
            Object(NonMatching, "Black/MPFEPublicChatMessage.cpp"),
            Object(NonMatching, "Black/MPFEReadyMessage.cpp"),
            Object(NonMatching, "Black/MPFEReplyToInviteMessage.cpp"),
            Object(NonMatching, "Black/MPFEReplyToJoinMessage.cpp"),
            Object(NonMatching, "Black/MPFEStartGameNowMessage.cpp"),
            Object(NonMatching, "Black/MPFEStartGameOkayToStartMessage.cpp"),
            Object(NonMatching, "Black/MPFEStartGameReadyMessage.cpp"),
            Object(NonMatching, "Black/MPFEStartGameTransferFilesMessage.cpp"),
            Object(NonMatching, "Black/MPFETeamsReadyList.cpp"),
            Object(NonMatching, "Black/MPFEUserTeamList.cpp"),
            Object(NonMatching, "Black/MultiMapFixed.cpp"),
            Object(NonMatching, "Black/MultiMapFixedInfo.cpp"),
            Object(NonMatching, "Black/MultiplayerConditionBox.cpp"),
            Object(NonMatching, "Black/MultiplayerDatabase.cpp"),
            Object(NonMatching, "Black/MusicMood.cpp"),
            Object(NonMatching, "Black/Name.cpp"),
            Object(NonMatching, "Black/Network.cpp"),
            Object(NonMatching, "Black/NewProfileBox.cpp"),
            Object(NonMatching, "Black/Object.cpp"),
            Object(NonMatching, "Black/ObjectInfo.cpp"),
            Object(NonMatching, "Black/OneOffSpellSeed.cpp"),
            Object(NonMatching, "Black/OOSDebug.cpp"),
            Object(NonMatching, "Black/Packet.cpp"),
            Object(NonMatching, "Black/Particle3DAnim.cpp"),
            Object(NonMatching, "Black/Particle3DAnimWithCamera.cpp"),
            Object(NonMatching, "Black/Particle3DObj.cpp"),
            Object(NonMatching, "Black/Particle3DObjAnimTextured.cpp"),
            Object(NonMatching, "Black/Particle3DPnt.cpp"),
            Object(NonMatching, "Black/Particle3DSprite.cpp"),
            Object(NonMatching, "Black/ParticleBaseMeshCreator.cpp"),
            Object(NonMatching, "Black/ParticleChainJoint.cpp"),
            Object(NonMatching, "Black/ParticleContainer.cpp"),
            Object(NonMatching, "Black/ParticleCreator.cpp"),
            Object(NonMatching, "Black/ParticleLightMap.cpp"),
            Object(NonMatching, "Black/ParticlePlayerSymbol.cpp"),
            Object(NonMatching, "Black/PathCreator.cpp"),
            Object(NonMatching, "Black/PBall.cpp"),
            Object(NonMatching, "Black/PCInput.cpp"),
            Object(NonMatching, "Black/PCMain.cpp"),
            Object(NonMatching, "Black/Persistent.cpp"),
            Object(NonMatching, "Black/PFootball.cpp"),
            Object(NonMatching, "Black/PhysicalShield.cpp"),
            Object(NonMatching, "Black/PhysicsObject.cpp"),
            Object(NonMatching, "Black/PhysicsSaveInfo.cpp"),
            Object(NonMatching, "Black/PictureRoom.cpp"),
            Object(NonMatching, "Black/PileResource.cpp"),
            Object(NonMatching, "Black/PileWood.cpp"),
            Object(NonMatching, "Black/PlaceSupport.cpp"),
            Object(NonMatching, "Black/PlannedAbode.cpp"),
            Object(NonMatching, "Black/PlannedCitadelHeart.cpp"),
            Object(NonMatching, "Black/PlannedCitadelPart.cpp"),
            Object(NonMatching, "Black/PlannedCreaturePen.cpp"),
            Object(NonMatching, "Black/PlannedFeature.cpp"),
            Object(NonMatching, "Black/PlannedMultiMapFixed.cpp"),
            Object(NonMatching, "Black/PlannedTownCentre.cpp"),
            Object(NonMatching, "Black/PlannedTownCitadelHeart.cpp"),
            Object(NonMatching, "Black/PlannedWorshipSite.cpp"),
            Object(NonMatching, "Black/PlannedWorshipSiteUpgrade.cpp"),
            Object(NonMatching, "Black/Plasma.cpp"),
            Object(NonMatching, "Black/Player.cpp"),
            Object(NonMatching, "Black/PlayerAction.cpp"),
            Object(NonMatching, "Black/PlayerActions.cpp"),
            Object(NonMatching, "Black/PlayerComputer.cpp"),
            Object(NonMatching, "Black/PlayerComputerCreature.cpp"),
            Object(NonMatching, "Black/PlayerComputerInterface.cpp"),
            Object(NonMatching, "Black/PlayerComputerReact.cpp"),
            Object(NonMatching, "Black/PlayerComputerSpell.cpp"),
            Object(NonMatching, "Black/PlayerComputerTown.cpp"),
            Object(NonMatching, "Black/PlayerInfo.cpp"),
            Object(NonMatching, "Black/PlayerMessage.cpp"),
            Object(NonMatching, "Black/PlayerProfile.cpp"),
            Object(NonMatching, "Black/Playtime.cpp"),
            Object(NonMatching, "Black/PlaytimeDance.cpp"),
            Object(NonMatching, "Black/Poo.cpp"),
            Object(NonMatching, "Black/Pot.cpp"),
            Object(NonMatching, "Black/PotInfo.cpp"),
            Object(NonMatching, "Black/PotStructure.cpp"),
            Object(NonMatching, "Black/PowerSpin.cpp"),
            Object(NonMatching, "Black/Prayer.cpp"),
            Object(NonMatching, "Black/PrayerIconInfo.cpp"),
            Object(NonMatching, "Black/PrayerSite.cpp"),
            Object(NonMatching, "Black/PrayerSiteInfo.cpp"),
            Object(NonMatching, "Black/ProfileEditor.cpp"),
            Object(NonMatching, "Black/Property.cpp"),
            Object(NonMatching, "Black/PSys3d.cpp"),
            Object(NonMatching, "Black/PSysAtomCore.cpp"),
            Object(NonMatching, "Black/PSysBase.cpp"),
            Object(NonMatching, "Black/PSysBaseModifiers.cpp"),
            Object(NonMatching, "Black/PSysBeam.cpp"),
            Object(NonMatching, "Black/PSysCreature.cpp"),
            Object(NonMatching, "Black/PSysDraw.cpp"),
            Object(NonMatching, "Black/PSysEditor.cpp"),
            Object(NonMatching, "Black/PSysEvents.cpp"),
            Object(NonMatching, "Black/PSysExplosion.cpp"),
            Object(NonMatching, "Black/PSysFireball.cpp"),
            Object(NonMatching, "Black/PSysFlock.cpp"),
            Object(NonMatching, "Black/PSysGeom.cpp"),
            Object(NonMatching, "Black/PSysGesture.cpp"),
            Object(NonMatching, "Black/PSysHandFX.cpp"),
            Object(NonMatching, "Black/PSysInterface.cpp"),
            Object(NonMatching, "Black/PSysLightning.cpp"),
            Object(NonMatching, "Black/PSysLoad.cpp"),
            Object(NonMatching, "Black/PSysLocal.cpp"),
            Object(NonMatching, "Black/PSysMagicSystem.cpp"),
            Object(NonMatching, "Black/PSysModifiers.cpp"),
            Object(NonMatching, "Black/PSysPCreator.cpp"),
            Object(NonMatching, "Black/PSysProcessInfo.cpp"),
            Object(NonMatching, "Black/PSysProperties.cpp"),
            Object(NonMatching, "Black/PSysRenderParticle.cpp"),
            Object(NonMatching, "Black/PSysSave.cpp"),
            Object(NonMatching, "Black/PSysShield.cpp"),
            Object(NonMatching, "Black/PSysSound.cpp"),
            Object(NonMatching, "Black/PSysTornado.cpp"),
            Object(NonMatching, "Black/puzzlegame.cpp"),
            Object(NonMatching, "Black/Rand.cpp"),
            Object(NonMatching, "Black/RandomBuildingPlacement.cpp"),
            Object(NonMatching, "Black/RandomBuildingPlacementDefence.cpp"),
            Object(NonMatching, "Black/Rank.cpp"),
            Object(NonMatching, "Black/RankInfo.cpp"),
            Object(NonMatching, "Black/Reaction.cpp"),
            Object(NonMatching, "Black/ReactionInfo.cpp"),
            Object(NonMatching, "Black/RegisterBox.cpp"),
            Object(NonMatching, "Black/Reward.cpp"),
            Object(NonMatching, "Black/RewardInfo.cpp"),
            Object(NonMatching, "Black/Rock.cpp"),
            Object(NonMatching, "Black/RoutePlan.cpp"),
            Object(NonMatching, "Black/SaveGameRoom.cpp"),
            Object(NonMatching, "Black/SaveLoadPtr.cpp"),
            Object(NonMatching, "Black/Scaffold.cpp"),
            Object(NonMatching, "Black/ScaffoldInfo.cpp"),
            Object(NonMatching, "Black/Script.cpp"),
            Object(NonMatching, "Black/ScriptCamera.cpp"),
            Object(NonMatching, "Black/ScriptContainer.cpp"),
            Object(NonMatching, "Black/ScriptCreateOrCall.cpp"),
            Object(NonMatching, "Black/ScriptCreatureCurse.cpp"),
            Object(NonMatching, "Black/ScriptDLL.cpp"),
            Object(NonMatching, "Black/ScriptedCamera.cpp"),
            Object(NonMatching, "Black/ScriptFunctions.cpp"),
            Object(NonMatching, "Black/ScriptGFX.cpp"),
            Object(NonMatching, "Black/ScriptHighlight.cpp"),
            Object(NonMatching, "Black/ScriptHighlightInfo.cpp"),
            Object(NonMatching, "Black/ScriptManage.cpp"),
            Object(NonMatching, "Black/ScriptMarker.cpp"),
            Object(NonMatching, "Black/ScriptTimer.cpp"),
            Object(NonMatching, "Black/SecretCreature.cpp"),
            Object(NonMatching, "Black/Serialise.cpp"),
            Object(NonMatching, "Black/ServerLandscapeMap.cpp"),
            Object(NonMatching, "Black/Settings.cpp"),
            Object(NonMatching, "Black/Setup.cpp"),
            Object(NonMatching, "Black/SetupBigButton.cpp"),
            Object(NonMatching, "Black/SetupBox.cpp"),
            Object(NonMatching, "Black/SetupButton.cpp"),
            Object(NonMatching, "Black/SetupCheckBox.cpp"),
            Object(NonMatching, "Black/SetupColourPicker.cpp"),
            Object(NonMatching, "Black/SetupControl.cpp"),
            Object(NonMatching, "Black/SetupEdit.cpp"),
            Object(NonMatching, "Black/SetupHLineGraph.cpp"),
            Object(NonMatching, "Black/SetupHSBarGraph.cpp"),
            Object(NonMatching, "Black/SetupList.cpp"),
            Object(NonMatching, "Black/SetupMP3Button.cpp"),
            Object(NonMatching, "Black/SetupMultiList.cpp"),
            Object(NonMatching, "Black/SetupMultiplayerMain.cpp"),
            Object(NonMatching, "Black/SetupOnlineLandscapes.cpp"),
            Object(NonMatching, "Black/SetupPicture.cpp"),
            Object(NonMatching, "Black/SetupRect.cpp"),
            Object(NonMatching, "Black/SetupSlider.cpp"),
            Object(NonMatching, "Black/SetupStaticText.cpp"),
            Object(NonMatching, "Black/SetupStaticTextNoHit.cpp"),
            Object(NonMatching, "Black/SetupTabButton.cpp"),
            Object(NonMatching, "Black/SetupThing.cpp"),
            Object(NonMatching, "Black/SetupVBarGraph.cpp"),
            Object(NonMatching, "Black/ShowNeeds.cpp"),
            Object(NonMatching, "Black/ShowNeedsInfo.cpp"),
            Object(NonMatching, "Black/ShowNeedsVisuals.cpp"),
            Object(NonMatching, "Black/SingleMapFixedInfo.cpp"),
            Object(NonMatching, "Black/SkipBox.cpp"),
            Object(NonMatching, "Black/SkirmishGameBox.cpp"),
            Object(NonMatching, "Black/SLLTemplate.cpp"),
            Object(NonMatching, "Black/SLobbyBox.cpp"),
            Object(NonMatching, "Black/SoundConfirmation.cpp"),
            Object(NonMatching, "Black/SoundGuidance.cpp"),
            Object(NonMatching, "Black/SoundInfo.cpp"),
            Object(NonMatching, "Black/SoundMap.cpp"),
            Object(NonMatching, "Black/SoundTag.cpp"),
            Object(NonMatching, "Black/SpecialVillager.cpp"),
            Object(NonMatching, "Black/SpecialVillagerInfo.cpp"),
            Object(NonMatching, "Black/Spell.cpp"),
            Object(NonMatching, "Black/SpellCreature"),
            Object(NonMatching, "Black/SpellCreature.cpp"),
            Object(NonMatching, "Black/SpellDispenser.cpp"),
            Object(NonMatching, "Black/SpellFlock.cpp"),
            Object(NonMatching, "Black/SpellFlockFlying"),
            Object(NonMatching, "Black/SpellFlockGround"),
            Object(NonMatching, "Black/SpellFood.cpp"),
            Object(NonMatching, "Black/SpellForest.cpp"),
            Object(NonMatching, "Black/SpellHeal"),
            Object(NonMatching, "Black/SpellIcon.cpp"),
            Object(NonMatching, "Black/SpellIconInfo.cpp"),
            Object(NonMatching, "Black/SpellPointInf"),
            Object(NonMatching, "Black/SpellResource"),
            Object(NonMatching, "Black/SpellSeed.cpp"),
            Object(NonMatching, "Black/SpellSeedGraphic.cpp"),
            Object(NonMatching, "Black/SpellSeedInfo.cpp"),
            Object(NonMatching, "Black/SpellSetupBox"),
            Object(NonMatching, "Black/SpellShield.cpp"),
            Object(NonMatching, "Black/SpellStormAndTornado"),
            Object(NonMatching, "Black/SpellSystemInfo.cpp"),
            Object(NonMatching, "Black/SpellTeleport"),
            Object(NonMatching, "Black/SpellWater.cpp"),
            Object(NonMatching, "Black/SpellWithObjects.cpp"),
            Object(NonMatching, "Black/SpookyVoiceInfo.cpp"),
            Object(NonMatching, "Black/SpookyVoices.cpp"),
            Object(NonMatching, "Black/SpookyVoicesInfo.cpp"),
            Object(NonMatching, "Black/SpotVisualInfo.cpp"),
            Object(NonMatching, "Black/SpreadEffect.cpp"),
            Object(NonMatching, "Black/SquadInfo.cpp"),
            Object(NonMatching, "Black/StandardBuildingSite.cpp"),
            Object(NonMatching, "Black/StartGameBox.cpp"),
            Object(NonMatching, "Black/StatsBox.cpp"),
            Object(NonMatching, "Black/StatsDatabase.cpp"),
            Object(NonMatching, "Black/StoragePit.cpp"),
            Object(NonMatching, "Black/Stream.cpp"),
            Object(NonMatching, "Black/StreetLantern.cpp"),
            Object(NonMatching, "Black/StreetLight.cpp"),
            Object(NonMatching, "Black/SubArgument.cpp"),
            Object(NonMatching, "Black/SubOptionEntry.cpp"),
            Object(NonMatching, "Black/TattooEditor.cpp"),
            Object(NonMatching, "Black/Temple.cpp"),
            Object(NonMatching, "Black/TempleEngine.cpp"),
            Object(NonMatching, "Black/TempleRoom.cpp"),
            Object(NonMatching, "Black/TempleRoomAddText.cpp"),
            Object(NonMatching, "Black/Terrain.cpp"),
            Object(NonMatching, "Black/TerrainMap.cpp"),
            Object(NonMatching, "Black/TerrainMapInfo.cpp"),
            Object(NonMatching, "Black/TerrainMapTypeInfo.cpp"),
            Object(NonMatching, "Black/TerrainMaterialInfo.cpp"),
            Object(NonMatching, "Black/ThingMusicInfo.cpp"),
            Object(NonMatching, "Black/TOMnavigator.cpp"),
            Object(NonMatching, "Black/ToolTipsInfo.cpp"),
            Object(NonMatching, "Black/Totem.cpp"),
            Object(NonMatching, "Black/TotemStatue.cpp"),
            Object(NonMatching, "Black/TotemStatueInfo.cpp"),
            Object(NonMatching, "Black/Town.cpp"),
            Object(NonMatching, "Black/TownAttitudeToCreature.cpp"),
            Object(NonMatching, "Black/TownCentre.cpp"),
            Object(NonMatching, "Black/TownCreatureInfo.cpp"),
            Object(NonMatching, "Black/TownDesire.cpp"),
            Object(NonMatching, "Black/TownDesireFlags.cpp"),
            Object(NonMatching, "Black/TownDesireInfo.cpp"),
            Object(NonMatching, "Black/TownInfo.cpp"),
            Object(NonMatching, "Black/TownSpellIcon.cpp"),
            Object(NonMatching, "Black/TownStats.cpp"),
            Object(NonMatching, "Black/Tree.cpp"),
            Object(NonMatching, "Black/TreeInfo.cpp"),
            Object(NonMatching, "Black/Tribe.cpp"),
            Object(NonMatching, "Black/TribeInfo.cpp"),
            Object(NonMatching, "Black/Utils.cpp"),
            Object(NonMatching, "Black/ValueSpinner.cpp"),
            Object(NonMatching, "Black/Villager.cpp"),
            Object(NonMatching, "Black/VillagerCheck.cpp"),
            Object(NonMatching, "Black/VillagerChild.cpp"),
            Object(NonMatching, "Black/VillagerCivic.cpp"),
            Object(NonMatching, "Black/VillagerDance.cpp"),
            Object(NonMatching, "Black/VillagerFarmer.cpp"),
            Object(NonMatching, "Black/VillagerFireman.cpp"),
            Object(NonMatching, "Black/VillagerFisherman.cpp"),
            Object(NonMatching, "Black/VillagerFood.cpp"),
            Object(NonMatching, "Black/VillagerFootball.cpp"),
            Object(NonMatching, "Black/VillagerForester.cpp"),
            Object(NonMatching, "Black/VillagerHome.cpp"),
            Object(NonMatching, "Black/VillagerHousewife.cpp"),
            Object(NonMatching, "Black/VillagerInfo.cpp"),
            Object(NonMatching, "Black/VillagerLeader.cpp"),
            Object(NonMatching, "Black/villagernames.cpp"),
            Object(NonMatching, "Black/VillagerPlaytime.cpp"),
            Object(NonMatching, "Black/VillagerReaction.cpp"),
            Object(NonMatching, "Black/VillagerReactionToCreature.cpp"),
            Object(NonMatching, "Black/VillagerScript.cpp"),
            Object(NonMatching, "Black/VillagerShepherd.cpp"),
            Object(NonMatching, "Black/VillagerStates.cpp"),
            Object(NonMatching, "Black/VillagerStateTableInfo.cpp"),
            Object(NonMatching, "Black/VillagerTrader.cpp"),
            Object(NonMatching, "Black/VillagerWorshipper.cpp"),
            Object(NonMatching, "Black/VirtualInfluence.cpp"),
            Object(NonMatching, "Black/ViscousLiquid.cpp"),
            Object(NonMatching, "Black/VortexInfo.cpp"),
            Object(NonMatching, "Black/VortexObjectInfo.cpp"),
            Object(NonMatching, "Black/VortexSave.cpp"),
            Object(NonMatching, "Black/Wallhug.cpp"),
            Object(NonMatching, "Black/Waterfall.cpp"),
            Object(NonMatching, "Black/WayPoint.cpp"),
            Object(NonMatching, "Black/Weather.cpp"),
            Object(NonMatching, "Black/WeatherInfo.cpp"),
            Object(NonMatching, "Black/WeatherRain.cpp"),
            Object(NonMatching, "Black/WeatherThing.cpp"),
            Object(NonMatching, "Black/Whale.cpp"),
            Object(NonMatching, "Black/Windmill.cpp"),
            Object(NonMatching, "Black/Wonder.cpp"),
            Object(NonMatching, "Black/Workshop.cpp"),
            Object(NonMatching, "Black/WorkshopBuildingSite.cpp"),
            Object(NonMatching, "Black/WorldRoom.cpp"),
            Object(NonMatching, "Black/Worship.cpp"),
            Object(NonMatching, "Black/WorshipSite.cpp"),
            Object(NonMatching, "Black/WorshipSiteInfo.cpp"),
            Object(NonMatching, "Black/WorshipSiteUpgrade.cpp"),
            Object(NonMatching, "Black/WorshipSiteUpgradeInfo.cpp"),
            Object(NonMatching, "Black/WorshipSpell.cpp"),
            Object(NonMatching, "Black/WorshipSpellIcon.cpp"),
            Object(NonMatching, "Black/WorshipTotem.cpp"),

            Object(NonMatching, "Lionhead/LHDLL/ver1.0/LHDLL.cpp"),

            Object(NonMatching, "Lionhead/LHFile/ver3.0/LHFile.cpp"),
            Object(NonMatching, "Lionhead/LHFile/ver3.0/LHOSFile.cpp", extra_cflags=["/GX"]),

            Object(NonMatching, "zlib/compress.c"),

            Object(NonMatching, "Lionhead/LHFile/ver3.0/LHParseFile.cpp"),

            Object(Matching, "zlib/deflate.c"),
            Object(Matching, "zlib/inflate.c"),
            # TODO: 1.1 seems to bump .bss address space
            Object(MatchingFor("BW1W120"), "zlib/zutil.c"),
            Object(Matching, "zlib/adler32.c"),
            Object(Matching, "zlib/trees.c"),
            Object(Matching, "zlib/infblock.c"),
            Object(Matching, "zlib/infcodes.c"),
            Object(Matching, "zlib/inftrees.c"),
            Object(Matching, "zlib/infutil.c"),
            Object(Matching, "zlib/inffast.c"),

            LibObject(NonMatching, "libcpmt", "build\\intel\\mt_obj\\delop.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcpmt", "build\\intel\\mt_obj\\xlock.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcpmt", "build\\intel\\mt_obj\\ios.obj", progress_category="sdk"),

            LibObject(Matching, "libcmt", "..\\build\\intel\\mt_obj\\fpinit.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\typinfo.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\onexit.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\sprintf.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\rtti.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\toupper.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\wcscat.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\xtow.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\purevirt.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\memmove.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\wcsncpy.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\wcslen.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\swprintf.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\new.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\atox.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\malloc.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\free.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\_ctype.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\sscanf.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\_wctype.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\rename.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\unlink.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\getenv.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\stricmp.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\fprintf.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\fopen.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\fclose.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\chkstk.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\wcscmp.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "..\\build\\intel\\mt_obj\\ieeemisc.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "..\\build\\intel\\mt_obj\\asin.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\fread.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\fwrite.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "..\\build\\intel\\mt_obj\\acos.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\asctime.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\localtim.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\time.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "..\\build\\intel\\mt_obj\\pow.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\lldiv.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\fscanf.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\fgetc.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\vsprintf.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\qsort.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "..\\build\\intel\\mt_obj\\87fmod.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "..\\build\\intel\\mt_obj\\ceil.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\bsearch.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\wcsstr.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\trnsctrl.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\exsup.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\fgets.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\splitpat.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\wtox.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\rand.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\fseek.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\ftell.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\fputs.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "..\\build\\intel\\mt_obj\\floor.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\stdexcpt.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\throw.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\strcspn.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\memchr.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\lconv.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\strtol.obj", progress_category="sdk"),
            LibObject(MatchingFor("BW1W120"), "libcmt", "build\\intel\\mt_obj\\dosmap.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\strncpy.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\strncmp.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\strchr.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\calloc.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\printf.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\strtok.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\atof.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\swscanf.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\strstr.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\tolower.obj", progress_category="sdk"),
            LibObject(MatchingFor("BW1W110", "BW1W120"), "libcmt", "build\\intel\\mt_obj\\wcsncmp.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\towlower.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\abort.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\chmod.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\realloc.obj", progress_category="sdk"),
            LibObject(MatchingFor("BW1W120"), "libcmt", "build\\intel\\mt_obj\\slbeep.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\strrchr.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "..\\build\\intel\\mt_obj\\ieee87.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\ulldiv.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\llmul.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\crt0dat.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\crt0init.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\llshr.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\llshl.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\llrem.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\mkdir.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\fputc.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\ungetc.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\fgetpos.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\fsetpos.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\setvbuf.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\fflush.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\wcsncat.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\wincrt0.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\strlen.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\ehprolog.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\memcpy.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\memcmp.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\setlocal.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\memset.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\_file.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\fputwc.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\ungetwc.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\fgetwc.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\mlock.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\nlsdata2.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\a_map.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\isctype.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\strtod.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\ctype.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\nlsdata1.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\strftime.obj", progress_category="sdk"), # mismatch for the __Strftime function

            Object(NonMatching, "Lionhead/LH3DLib/development/LH3DCameraChecker.cpp"),

            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\cmiscdat.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\a_cmp.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\fp8.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "..\\build\\intel\\mt_obj\\testfdiv.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "..\\build\\intel\\mt_obj\\cvt.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\strcmp.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\msize.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\_flsbuf.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\output.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\exsup3.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\xtoa.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\woutput.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\_newmode.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\handler.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\heapinit.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\sbheap.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\input.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\iswctype.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\mbsnbico.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\wtombenv.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\_sftbuf.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\_open.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\stream.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\close.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\_freebuf.obj", progress_category="sdk"),
            LibObject(MatchingFor("BW1W110", "BW1W120"), "libcmt", "..\\build\\intel\\mt_obj\\ldexp.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "..\\build\\intel\\mt_obj\\util.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "..\\build\\intel\\mt_obj\\fpexcept.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "..\\build\\intel\\mt_obj\\fpctrl.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "..\\build\\intel\\mt_obj\\87disp.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "..\\build\\intel\\mt_obj\\genexcep.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "..\\build\\intel\\mt_obj\\common.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\_filbuf.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\read.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\write.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\timeset.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\tidtable.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\tzset.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\gmtime.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\dtoxtime.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "..\\build\\intel\\mt_obj\\87tran.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "..\\build\\intel\\mt_obj\\powhlp.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "..\\build\\intel\\mt_obj\\87cdisp.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "..\\build\\intel\\mt_obj\\adj_fdiv.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "..\\build\\intel\\mt_obj\\frnd.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\frame.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\lowhelpr.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\hooks.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\mbctype.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\mbsnbcpy.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\lseek.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\ioinit.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\strcat.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\unhandld.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "..\\build\\intel\\mt_obj\\cfin.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\winput.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\w_map.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\winsig.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\crt0msg.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\_getbuf.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\ftelli64.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\fseeki64.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\commit.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\winxfltr.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\wincmdln.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\stdenvp.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\stdargv.obj", progress_category="sdk"),
            LibObject(MatchingFor("BW1W120"), "libcmt", "build\\intel\\mt_obj\\a_env.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\inittime.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\initnum.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\initmon.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\initctyp.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\initcoll.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\strpbrk.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\nlsdata3.obj", progress_category="sdk"),
            # TODO(#178): Looks like a different libcmt might be used for 1.1 and below because TestDefaultCountry in
            #   getqloc.obj differs by one byte. A compare + jump moved from JC (0x72) in 1.1 to JL (0x7c) in 1.42,
            #   indicating a shift from signed address compare in 1.1 and an unsigned compare in 1.42.
            LibObject(MatchingFor("BW1W142"), "libcmt", "build\\intel\\mt_obj\\getqloc.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\closeall.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\_flswbuf.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\wctomb.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\_filwbuf.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\mbtowc.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\a_str.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "..\\build\\intel\\mt_obj\\huge.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "..\\build\\intel\\mt_obj\\intrncvt.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\_fptostr.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "..\\build\\intel\\mt_obj\\cfout.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\crt0fp.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\isatty.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\ullrem.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\w_str.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\setenv.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\open.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\osfinfo.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "..\\build\\intel\\mt_obj\\matherr.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "..\\build\\intel\\mt_obj\\87except.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\validate.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "..\\build\\intel\\mt_obj\\strgtold.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\wcstombs.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\ncommode.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\crtmbox.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\lseeki64.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\ismbbyte.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\inithelp.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\days.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\strnicmp.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "..\\build\\intel\\mt_obj\\mantold.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "..\\build\\intel\\mt_obj\\x10fout.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\mbschr.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\strdup.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\chsize.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "..\\build\\intel\\mt_obj\\tenpow.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "..\\build\\intel\\mt_obj\\constpow.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\txtmode.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\w_loc.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\a_loc.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\setmode.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\wcsdup.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\wcsicmp.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\flength.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\fileno.obj", progress_category="sdk"),
            LibObject(Matching, "libcmt", "build\\intel\\mt_obj\\wcsnicmp.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\chdir.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\strlwr.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\getpid.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\ehvecdtr.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\strspn.obj", progress_category="sdk"),
            LibObject(MatchingFor("BW1W110", "BW1W120"), "libcmt", "build\\intel\\mt_obj\\wcschr.obj", progress_category="sdk"),
            LibObject(MatchingFor("BW1W110", "BW1W120"), "libcmt", "build\\intel\\mt_obj\\wcsrchr.obj", progress_category="sdk"),
            LibObject(MatchingFor("BW1W110", "BW1W120"), "libcmt", "build\\intel\\mt_obj\\wcspbrk.obj", progress_category="sdk"),
            LibObject(MatchingFor("BW1W110", "BW1W120"), "libcmt", "build\\intel\\mt_obj\\wcsspn.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\ehvecctr.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\clock.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\longjmp.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\setjmp3.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\mbtoupr.obj", progress_category="sdk"),
            LibObject(NonMatching, "libcmt", "build\\intel\\mt_obj\\sehsupp.obj", progress_category="sdk"),

            Object(NonMatching, "Lionhead/LHLib/ver5.0/LHWin.cpp"),
            Object(Matching, "Lionhead/LHLib/ver5.0/LHMem.cpp"),
            Object(NonMatching, "Lionhead/LHLib/ver5.0/LHScreen.cpp"),
            Object(NonMatching, "Lionhead/LHLib/ver5.0/LHMemoryLeak.cpp"),
            Object(NonMatching, "Lionhead/LHLib/ver5.0/LHDraw.cpp"),
            Object(NonMatching, "Lionhead/LHLib/ver5.0/LHSurface.cpp"),
            Object(NonMatching, "Lionhead/LHLib/ver5.0/LHText.cpp"),
            Object(NonMatching, "Lionhead/LHLib/ver5.0/LHHeap2.cpp", extra_cflags=["/GX"]),
            Object(NonMatching, "Lionhead/LHLib/ver5.0/LHMouse.cpp"),
            Object(NonMatching, "Lionhead/LHLib/ver5.0/LHScript.cpp"),
            Object(NonMatching, "Lionhead/LHLib/ver5.0/LHSpriteList.cpp"),
            Object(NonMatching, "Lionhead/LHLib/ver5.0/LHConvert.cpp"),
            Object(NonMatching, "Lionhead/LHLib/ver5.0/LHSprite.cpp"),
            Object(NonMatching, "Lionhead/LH3DLib/development/LH3DSmoke.cpp"),
            Object(NonMatching, "Lionhead/LH3DLib/development/LH3DIsland.cpp"),
            Object(NonMatching, "Lionhead/LH3DLib/development/LH3DMesh.cpp"),
            Object(NonMatching, "Lionhead/LH3DLib/development/LH3DTech.cpp"),
            Object(NonMatching, "Lionhead/LHLib/ver5.0/LHCollide.cpp"),
            Object(NonMatching, "Lionhead/LH3DLib/development/LH3DRender.cpp"),
            Object(NonMatching, "Lionhead/LH3DLib/development/LH3DText.cpp"),
            Object(NonMatching, "Lionhead/LH3DLib/development/LH3DWay.cpp"),
            Object(NonMatching, "Lionhead/LH3DLib/development/LH3DHair.cpp"),
        ],
    },
    {
        "lib": "LHAudio",
        "compiler_version": config.linker_version,
        "cflags": cflags_base,
        "progress_category": "sdk",
        "objects": [
            Object(NonMatching, "Lionhead/LHAudio/ver7.0/LH_AudioBank.cpp"),
            Object(NonMatching, "Lionhead/LHAudio/ver7.0/LH_SamplePlayOptions.cpp"),
            Object(NonMatching, "Lionhead/LHAudio/ver7.0/LHAudioAtmos.cpp"),
            Object(NonMatching, "Lionhead/LHAudio/ver7.0/LHAudioBank.cpp"),
            Object(NonMatching, "Lionhead/LHAudio/ver7.0/LHAudioHeap.cpp"),
            Object(NonMatching, "Lionhead/LHAudio/ver7.0/LHAudioMidi.cpp"),
            Object(NonMatching, "Lionhead/LHAudio/ver7.0/LHAudioMusic.cpp"),
            Object(NonMatching, "Lionhead/LHAudio/ver7.0/LHAudioRedbook.cpp"),
            Object(NonMatching, "Lionhead/LHAudio/ver7.0/LHAudioSample.cpp"),
            Object(NonMatching, "Lionhead/LHAudio/ver7.0/LHAudioSystem.cpp"),
            Object(NonMatching, "Lionhead/LHAudio/ver7.0/LHAudioWave.cpp"),
        ],
    },
    {
        "lib": "LHLog",
        "compiler_version": config.linker_version,
        "cflags": cflags_base,
        "progress_category": "sdk",
        "objects": [
            Object(NonMatching, "Lionhead/LHLog/ver4.0/LHAssert.cpp"),
            Object(NonMatching, "Lionhead/LHLog/ver4.0/LHGenLog.cpp"),
            Object(NonMatching, "Lionhead/LHLog/ver4.0/LHLogProps.cpp"),
            Object(NonMatching, "Lionhead/LHLog/ver4.0/LHVersion.cpp"),
            Object(NonMatching, "Lionhead/LHLog/ver4.0/LogUtils.cpp"),
        ],
    },
    {
        "lib": "LHMultiplayer",
        "compiler_version": config.linker_version,
        "cflags": cflags_base,
        "progress_category": "sdk",
        "objects": [
            Object(NonMatching, "Lionhead/LHMultiplayer/ver4.0/LHConnection.cpp"),
            Object(NonMatching, "Lionhead/LHMultiplayer/ver4.0/LHConnectionServer.cpp"),
            Object(NonMatching, "Lionhead/LHMultiplayer/ver4.0/LHLobby.cpp"),
            Object(NonMatching, "Lionhead/LHMultiplayer/ver4.0/LHLobbyServer.cpp"),
            Object(NonMatching, "Lionhead/LHMultiplayer/ver4.0/LHMPServerStartInfo.cpp"),
            Object(NonMatching, "Lionhead/LHMultiplayer/ver4.0/LHNetEvent.cpp"),
            Object(NonMatching, "Lionhead/LHMultiplayer/ver4.0/LHNetUser.cpp"),
            Object(NonMatching, "Lionhead/LHMultiplayer/ver4.0/LHNetUtils.cpp"),
            Object(NonMatching, "Lionhead/LHMultiplayer/ver4.0/LHPacket.cpp"),
            Object(NonMatching, "Lionhead/LHMultiplayer/ver4.0/LHPacketisableObject.cpp"),
            Object(NonMatching, "Lionhead/LHMultiplayer/ver4.0/LHPlayer.cpp"),
            Object(NonMatching, "Lionhead/LHMultiplayer/ver4.0/LHSerial.cpp"),
            Object(NonMatching, "Lionhead/LHMultiplayer/ver4.0/LHServerPlayer.cpp"),
            Object(NonMatching, "Lionhead/LHMultiplayer/ver4.0/LHSession.cpp"),
            Object(NonMatching, "Lionhead/LHMultiplayer/ver4.0/LHSocket.cpp"),
            Object(NonMatching, "Lionhead/LHMultiplayer/ver4.0/LHSocketTCP.cpp"),
            Object(NonMatching, "Lionhead/LHMultiplayer/ver4.0/LHTransport.cpp"),
            Object(NonMatching, "Lionhead/LHMultiplayer/ver4.0/LHTransportInfo.cpp"),
        ],
    },
    {
        "lib": "LHDialog",
        "compiler_version": config.linker_version,
        "cflags": cflags_base,
        "progress_category": "sdk",
        "objects": [
            Object(NonMatching, "Lionhead/LHDialogLib/version 1.0/LHCameraParamsDialog.cpp"),
            Object(NonMatching, "Lionhead/LHDialogLib/version 1.0/LHDialogLib.cpp"),
            Object(NonMatching, "Lionhead/LHDialogLib/version 1.0/LHEditDialog.cpp"),
            Object(NonMatching, "Lionhead/LHDialogLib/version 1.0/LHEditDialogSizable.cpp"),
            Object(NonMatching, "Lionhead/LHDialogLib/version 1.0/LHProgressDialog.cpp"),
            Object(NonMatching, "Lionhead/LHDialogLib/version 1.0/LHSystemSpecDialog.cpp"),
            Object(NonMatching, "Lionhead/LHDialogLib/version 1.0/LHSystemSpecSummaryDialog.cpp"),
        ],
    },
]


# Optional callback to adjust link order. This can be used to add, remove, or reorder objects.
# This is called once per module, with the module ID and the current link order.
#
# For example, this adds "dummy.c" to the end of the DOL link order if configured with --non-matching.
# "dummy.c" *must* be configured as a Matching (or Equivalent) object in order to be linked.
def link_order_callback(module_id: int, objects: List[str]) -> List[str]:
    # Don't modify the link order for matching builds
    if not config.non_matching:
        return objects
    if module_id == 0:  # DOL
        return objects + ["dummy.c"]
    return objects


# Uncomment to enable the link order callback.
# config.link_order_callback = link_order_callback


# Optional extra categories for progress tracking
# Adjust as desired for your project
config.progress_categories = [
    ProgressCategory("game", "Game Code"),
    ProgressCategory("sdk", "SDK Code"),
]
config.progress_each_module = args.verbose
# Optional extra arguments to `objdiff-cli report generate`
config.progress_report_args = [
    # Marks relocations as mismatching if the target value is different
    # Default is "functionRelocDiffs=none", which is most lenient
    # "--config functionRelocDiffs=data_value",
]

if args.mode == "configure":
    # Write build.ninja and objdiff.json
    generate_build(config)
elif args.mode == "progress":
    # Print progress information
    calculate_progress(config)
else:
    sys.exit("Unknown mode: " + args.mode)
