object_base: orig/BW1W120
name: runblack
object: ../../build/BW1W120/runblack-preprocessed.exe
hash: e554d46de745e604c05d7e3607b2f4ec61e8c063
symbols: config/BW1W120/symbols.txt
splits: config/BW1W120/splits.txt

timestamp: "2002-06-18T06:13:22+00:00"
force_size: 0x00843000
linker_version: "6.0"
safe_disc_version: "2.60.52"
size_of_code: 0x4AE000
size_of_initialized_data: 0x71D000
size_of_image: 0xBC6000
entry_export_addr: 0x009c51e0
entry_export_size: 0x365
entry_import_addr: 0x009bf6e8
entry_import_size: 0x1B8
entry_resource_addr: 0x00fc2000
entry_resource_size: 0x38F8

modules:
- object: LHaudiodllR.dll
  hash: 35f149cb77e9f770751112c0c814331c5b92bb4d
  name: LHAudio
  symbols: config/BW1W120/LHAudio/symbols.txt
  splits: config/BW1W120/LHAudio/splits.txt

- object: LHLogR.dll
  hash: 3c42f20350da2c54eb1ba0a61829b94d9883669a
  name: LHLog
  linker_version: "7.0"
  symbols: config/BW1W120/LHLog/symbols.txt
  splits: config/BW1W120/LHLog/splits.txt

- object: LHMultiplayerR.dll
  hash: 4042119212fb6a5da6d736b059347f340eb4cd17
  name: LHMultiplayer
  symbols: config/BW1W120/LHMultiplayer/symbols.txt
  splits: config/BW1W120/LHMultiplayer/splits.txt

- object: LHDialogLib.dll
  hash: 64a22b88a51adc4bc119777642263e419ea8d09e
  name: LHDialog
  symbols: config/BW1W120/LHDialog/symbols.txt
  splits: config/BW1W120/LHDialog/splits.txt
