object_base: orig/BW1E110
object: runblack-decrypted.exe
hash: 44315eb19b6e2ab9023ea330b99bf5d471597402
symbols: config/BW1E110/symbols.txt
splits: config/BW1E110/splits.txt
# TODO: Unsure why we get 0x832000, probably because of decryptor
force_size: 0x00902a0b
linker_version: "6.0"
safe_disc_version: "2.30.33"
# TODO: Unsure why we get 0x49d000
size_of_code: 0x49d000
# TODO: Unsure why we get 0x71c000
size_of_initialized_data: 0x71c000
# TODO: Unsure why we get 0xbb493e
size_of_image: 0xbb493e
# TODO: Unsure why we get a wrong value
entry_export_addr: 0x009b4f30
# TODO: Unsure why we get a wrong value
entry_export_size: 0x39F
# TODO: Unsure why we get a wrong value
entry_import_addr: 0x009af438
# TODO: Unsure why we get a wrong value
entry_import_size: 0x1b8
# TODO: Unsure why we get a wrong value
entry_resource_size: 0x38f8

modules:
- object: LHaudiodllR.dll
  hash: 35f149cb77e9f770751112c0c814331c5b92bb4d
  name: LHAudio
  symbols: config/BW1E110/LHAudio/symbols.txt
  splits: config/BW1E110/LHAudio/splits.txt

- object: LHLogR.dll
  hash: 34419383df8eafc4c4a755cb84da38e64b598f80
  name: LHLog
  symbols: config/BW1E110/LHLog/symbols.txt
  splits: config/BW1E110/LHLog/splits.txt

- object: LHMultiplayerR.dll
  hash: 184601784d2eb1a2f999f79cd032128cf3196b38
  name: LHMultiplayer
  symbols: config/BW1E110/LHMultiplayer/symbols.txt
  splits: config/BW1E110/LHMultiplayer/splits.txt

- object: LHDialogLib.dll
  hash: 64a22b88a51adc4bc119777642263e419ea8d09e
  name: LHDialog
  symbols: config/BW1E110/LHDialog/symbols.txt
  splits: config/BW1E110/LHDialog/splits.txt
