name: 'Prep for Clang compilation'
description: 'Setup the correct version of clang to compile this recomp.'
inputs:
  llvm_tag:
    description: 'LLVM tag to download'
    default: 'bw1-decomp-012'
runs:
  using: "composite"
  steps:
    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - if: ${{ runner.os == 'Windows' }}
      shell: bash
      run: C:/msys64/usr/bin/pacman -Sy --noconfirm mingw-w64-clang-x86_64-headers-git

    - if: ${{ runner.os != 'Windows' }}
      shell: bash
      run: sudo apt install -y mingw-w64 libc6-dev-i386-cross

