# strings *.{exe,dll} Data/HelpSprite/markevil.hd Audio/SFX/Game/*.sad Audio/SFX/Creature/*.sad 'Plug Ins'/*.dll Profiles/Backup/*{.dll,.exe} | grep -i 'c:\\dev' | sort | uniq -i | less
import re
from pathlib import PureWindowsPath as BWPath
from collections import defaultdict

released_filepaths_from_strings = {
    BWPath(r"C:\Dev\libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DP3.cpp"),
    BWPath(r"C:\Dev\libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DP3.cpp"),
    BWPath(r"c:\dev\libs\lionhead\lh3dlib\development\mfcdebug\lh3damemory.obj"),
    # BWPath(r"C:\Dev\black language\Script Library\Debug\ScriptLibraryD.pdb"),
    BWPath(r"c:\dev\black language\script library\scriptmachine.cpp"),
    BWPath(r"c:\dev\black language\script library\scriptmachine.h"),
    # BWPath(r"C:\dev\Black Plug Ins\Language Library\Debug\LanguageD.pdb"),
    BWPath(r"C:\Dev\black\SoundAction.h"),
    BWPath(r"C:\Dev\black\SoundAlignment.h"),
    BWPath(r"C:\Dev\black\SoundObject.h"),
    BWPath(r"C:\Dev\black\SoundSize.h"),
    BWPath(r"C:\Dev\black\SoundSurface.h"),
    BWPath(r"C:\DEV\LIBS\LHALL\RELEASED\HEADERS\lhfile.h"),
    BWPath(r"c:\DEV\LIBS\LHALL\RELEASED\HEADERS\LHScreen.h"),
    BWPath(r"C:\DEV\LIBS\LHALL\RELEASED\HEADERS\LHTemplate.h"),
    BWPath(r"c:\DEV\LIBS\LHALL\RELEASED\HEADERS\LHTimer.h"),
    BWPath(r"C:\DEV\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DRender.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DTech.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DTech.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHMatrix.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHPoint.h"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioAtmos.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioBank.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioHeap.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioMidi.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioMusic.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioRedbook.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioSample.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioSystem.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioWave.cpp"),
    # BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\Release\LHaudiodllR.pdb"),
    # BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\Debug\LHDialogLib.pdb"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\LHCameraParamsDialog.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\LHDialogLib.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\LHEditDialog.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\LHEditDialogSizable.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\LHProgressDialog.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\LHSystemSpecDialog.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\LHSystemSpecSummaryDialog.cpp"),
    BWPath(r"C:\Dev\LIBS\Lionhead\LHDLL\VER1.0\LHDLL.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHFILE\VER3.0\LHFile.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHFILE\VER3.0\LHOSFile.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHFILE\VER3.0\LHParser.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHFlic.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHHeap2.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHMemoryLeak.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHMouse.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHScreen.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHScript.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHWin.cpp"),
    BWPath(r"C:\dev\libs\LIONHEAD\LHLog\VER4.0\LHAssert.cpp"),
    BWPath(r"C:\dev\libs\LIONHEAD\LHLog\VER4.0\LHGenLog.cpp"),
    BWPath(r"C:\dev\libs\LIONHEAD\LHLog\VER4.0\LHLogProps.cpp"),
    BWPath(r"C:\dev\libs\LIONHEAD\LHLog\VER4.0\LHVersion.cpp"),
    BWPath(r"C:\dev\libs\LIONHEAD\LHLog\VER4.0\LogUtils.cpp"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHConnectionServer.cpp"),
    # BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\Release\LHMultiplayerR.pdb"),
    BWPath(r"C:\dev\MP\Black\Abode.cpp"),
    BWPath(r"C:\dev\MP\Black\Abode.h"),
    BWPath(r"C:\dev\MP\Black\alexmfc.cpp"),
    BWPath(r"C:\dev\MP\Black\Alignment.cpp"),
    BWPath(r"C:\dev\MP\Black\Alignment.h"),
    BWPath(r"C:\dev\MP\Black\AnimalAnimation.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalCow.cpp"),
    BWPath(r"C:\dev\MP\Black\Animal.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalDove.cpp"),
    BWPath(r"C:\dev\MP\Black\Animal.h"),
    BWPath(r"C:\dev\MP\Black\AnimalLeopard.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalLion.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalReaction.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalSpellWolf.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalTiger.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalWolf.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimatedStatic.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimatedStatic.h"),
    BWPath(r"C:\dev\MP\Black\Animations.cpp"),
    BWPath(r"C:\dev\MP\Black\Arena.cpp"),
    BWPath(r"C:\dev\MP\Black\Arrow.cpp"),
    BWPath(r"C:\dev\MP\Black\Arrow.h"),
    BWPath(r"C:\dev\MP\Black\Artifact.cpp"),
    BWPath(r"C:\dev\MP\Black\Audio.cpp"),
    BWPath(r"C:\dev\MP\Black\AudioMusicThing.cpp"),
    BWPath(r"C:\dev\MP\Black\audiotag.cpp"),
    BWPath(r"C:\dev\MP\Black\Balance.cpp"),
    BWPath(r"C:\dev\MP\Black\Ball.cpp"),
    BWPath(r"C:\dev\MP\Black\Ball.h"),
    BWPath(r"C:\dev\MP\Black\Belief.cpp"),
    BWPath(r"C:\dev\MP\Black\Belief.h"),
    BWPath(r"C:\dev\MP\Black\BigForest.cpp"),
    BWPath(r"C:\dev\MP\Black\BigForest.h"),
    BWPath(r"C:\dev\MP\Black\Bonfire.cpp"),
    BWPath(r"C:\dev\MP\Black\Bookmark.cpp"),
    BWPath(r"C:\dev\MP\Black\BuildingSite.cpp"),
    BWPath(r"C:\dev\MP\Black\BWGameSpy.cpp"),
    BWPath(r"C:\dev\MP\Black\BWLan.cpp"),
    BWPath(r"C:\dev\MP\Black\Camera.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraEditor.cpp"),
    BWPath(r"C:\dev\MP\Black\camerahelp.cpp"),
    BWPath(r"C:\dev\MP\Black\camerahelp.h"),
    BWPath(r"C:\dev\MP\Black\CameraModeCitadel.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModeDance.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModeFlyAndClick.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModeFollow.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModeFollowHeading.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModeNew3.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModePath.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModeScript.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModeTwoObjects.cpp"),
    BWPath(r"C:\dev\MP\Black\ChallengeRoom.cpp"),
    BWPath(r"C:\dev\MP\Black\Citadel.cpp"),
    BWPath(r"C:\dev\MP\Black\Citadel.h"),
    BWPath(r"C:\dev\MP\Black\CitadelHeart.cpp"),
    BWPath(r"C:\dev\MP\Black\CitadelHeart.h"),
    BWPath(r"C:\dev\MP\Black\CitadelPart.h"),
    BWPath(r"C:\dev\MP\Black\citadelpeople.cpp"),
    BWPath(r"C:\dev\MP\Black\Collide.cpp"),
    BWPath(r"C:\dev\MP\Black\Config.cpp"),
    BWPath(r"C:\dev\MP\Black\Container.h"),
    BWPath(r"C:\dev\MP\Black\ControlHand.cpp"),
    BWPath(r"C:\dev\MP\Black\Creature3D.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureAction.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureAction.h"),
    BWPath(r"C:\dev\MP\Black\CreatureAttitudeToCreature.cpp"),
    BWPath(r"C:\dev\MP\Black\Creature.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureDevelopment.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureDirectControl.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureFace.cpp"),
    BWPath(r"C:\dev\MP\Black\Creature.h"),
    BWPath(r"C:\dev\MP\Black\CreatureHelp.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureInitialLesson.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureLessonChooser.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureLook.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalAttributeTest.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalBelief.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalBeliefs.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalDesire.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalDesire.h"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalDesireSource.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalDesireSource.h"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalExploration.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalLearnAction.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalLearnAction.h"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalLearn.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalMisc.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalSaveAndLoad.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMimic.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMimic.h"),
    BWPath(r"C:\dev\MP\Black\CreatureMorph.cpp"),
    BWPath(r"C:\dev\MP\Black\CreaturePen.cpp"),
    BWPath(r"C:\dev\MP\Black\CreaturePen.h"),
    BWPath(r"C:\dev\MP\Black\CreaturePhysical.cpp"),
    BWPath(r"C:\dev\MP\Black\CreaturePlan.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureReaction.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureReceiveSpell.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureRoom.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureScript.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureSelect.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureSubAction.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureSubActions.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureWhatToDoNext.cpp"),
    BWPath(r"C:\dev\MP\Black\Creche.cpp"),
    BWPath(r"C:\dev\MP\Black\Dance.cpp"),
    BWPath(r"C:\dev\MP\Black\Dance.h"),
    BWPath(r"C:\dev\MP\Black\DanceKey.cpp"),
    BWPath(r"C:\dev\MP\Black\DanceShape.cpp"),
    BWPath(r"C:\dev\MP\Black\DeadTree.cpp"),
    BWPath(r"C:\dev\MP\Black\DialogBoxKeyBinding.cpp"),
    BWPath(r"C:\dev\MP\Black\DialogBoxMain.cpp"),
    BWPath(r"C:\dev\MP\Black\DialogBoxOptions.cpp"),
    BWPath(r"C:\dev\MP\Black\DialogBoxSaveMessage.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorAnim.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorHug.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorIcon.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorIconBase.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorIconGraph.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorIconPDM.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorIconPDM.h"),
    BWPath(r"C:\dev\MP\Black\EditorIconPlace.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorIconStrip.cpp"),
    BWPath(r"C:\dev\MP\Black\Effect.h"),
    BWPath(r"C:\dev\MP\Black\ExtraFeatures.cpp"),
    BWPath(r"C:\dev\MP\Black\fallingspell.cpp"),
    BWPath(r"C:\dev\MP\Black\Feature.cpp"),
    BWPath(r"C:\dev\MP\Black\Feature.h"),
    BWPath(r"C:\dev\MP\Black\Field.cpp"),
    BWPath(r"C:\dev\MP\Black\Field.h"),
    BWPath(r"C:\dev\MP\Black\FireFly.cpp"),
    BWPath(r"C:\dev\MP\Black\FishFarm.cpp"),
    BWPath(r"C:\dev\MP\Black\FishFarm.h"),
    BWPath(r"C:\dev\MP\Black\Fixed.cpp"),
    BWPath(r"C:\dev\MP\Black\Fixed.h"),
    BWPath(r"C:\dev\MP\Black\Flock.cpp"),
    BWPath(r"C:\dev\MP\Black\FootBall.cpp"),
    BWPath(r"C:\dev\MP\Black\Football.h"),
    BWPath(r"C:\dev\MP\Black\Footpath.cpp"),
    BWPath(r"C:\dev\MP\Black\Forest.cpp"),
    BWPath(r"C:\dev\MP\Black\frontend.cpp"),
    BWPath(r"C:\dev\MP\Black\FrontEndSetupGame.cpp"),
    BWPath(r"C:\dev\MP\Black\FrontEndSetupMultiplayer.cpp"),
    BWPath(r"C:\dev\MP\Black\Furniture.cpp"),
    BWPath(r"C:\dev\MP\Black\Furniture.h"),
    BWPath(r"C:\dev\MP\Black\GameArea.h"),
    BWPath(r"C:\dev\MP\Black\Game.cpp"),
    BWPath(r"C:\dev\MP\Black\GameOSFile.cpp"),
    BWPath(r"C:\dev\MP\Black\GameOSFile.h"),
    BWPath(r"C:\dev\MP\Black\GameStats.cpp"),
    BWPath(r"C:\dev\MP\Black\GameStatsFrontEnd.cpp"),
    BWPath(r"C:\dev\MP\Black\GameStatsList.h"),
    BWPath(r"C:\dev\MP\Black\GatheringInterface.cpp"),
    BWPath(r"C:\dev\MP\Black\GatheringInterface.h"),
    BWPath(r"C:\dev\MP\Black\GenerateCreatureHTML.cpp"),
    BWPath(r"C:\dev\MP\Black\GJBaseUtils.inl"),
    BWPath(r"C:\dev\MP\Black\GJVnoise.cpp"),
    BWPath(r"C:\dev\MP\Black\GJPersistent.cpp"),
    BWPath(r"C:\dev\MP\Black\GJProperty.cpp"),
    BWPath(r"C:\dev\MP\Black\GJProperty.h"),
    BWPath(r"C:\dev\MP\Black\Global.cpp"),
    BWPath(r"C:\dev\MP\Black\GraveYard.cpp"),
    BWPath(r"C:\dev\MP\Black\GroupBehaviour.cpp"),
    BWPath(r"C:\dev\MP\Black\GSLobbybox.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpDudeControl.cpp"),
    BWPath(r"C:\dev\MP\Black\helpdude.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpDudeLipSync.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpEditor.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpProfile.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpSpirit.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpSpirit.h"),
    BWPath(r"C:\dev\MP\Black\HelpSystemBubble.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpSystem.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpSystem.h"),
    BWPath(r"C:\dev\MP\Black\HelpSystemToolTips.h"),
    BWPath(r"C:\dev\MP\Black\HelpText.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpText.h"),
    BWPath(r"C:\dev\MP\Black\Influence.cpp"),
    BWPath(r"C:\dev\MP\Black\Influence.h"),
    BWPath(r"C:\dev\MP\Black\Interface.cpp"),
    BWPath(r"C:\dev\MP\Black\InterfaceImmersion.cpp"),
    BWPath(r"C:\dev\MP\Black\InterfaceMessage.cpp"),
    BWPath(r"C:\dev\MP\Black\InterfaceStatus.cpp"),
    BWPath(r"C:\dev\MP\Black\IpSpecialDialog.cpp"),
    BWPath(r"C:\dev\MP\Black\JCGameBlock.cpp"),
    BWPath(r"C:\dev\MP\Black\JCMisc.cpp"),
    BWPath(r"C:\dev\MP\Black\Job.h"),
    BWPath(r"C:\dev\MP\Black\KeyBuffer.cpp"),
    BWPath(r"C:\dev\MP\Black\LandAlignement.cpp"),
    BWPath(r"C:\dev\MP\Black\LandFeature.cpp"),
    BWPath(r"C:\dev\MP\Black\Landscape.cpp"),
    BWPath(r"C:\dev\MP\Black\LevelOfDetail.cpp"),
    BWPath(r"C:\dev\MP\Black\LHInetWeather.cpp"),
    BWPath(r"C:\dev\MP\Black\LHNetBase.cpp"),
    BWPath(r"C:\dev\MP\Black\Living.cpp"),
    BWPath(r"C:\dev\MP\Black\Living.h"),
    BWPath(r"C:\dev\MP\Black\LivingProjectile.cpp"),
    BWPath(r"C:\dev\MP\Black\LivingReaction.cpp"),
    BWPath(r"C:\dev\MP\Black\LoaderAnon.cpp"),
    BWPath(r"C:\dev\MP\Black\LoadingScreen.cpp"),
    BWPath(r"C:\dev\MP\Black\Lobbybox.cpp"),
    BWPath(r"C:\dev\MP\Black\logo.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicCreatureSpellInfo.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicCreatureSpellInfo.h"),
    BWPath(r"C:\dev\MP\Black\MagicFood.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicFoodInfo.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicFoodInfo.h"),
    BWPath(r"C:\dev\MP\Black\MagicForestInfo.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicForestInfo.h"),
    BWPath(r"C:\dev\MP\Black\MagicInfo.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicInfo.h"),
    BWPath(r"C:\dev\MP\Black\MagicShieldInfo.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicShieldInfo.h"),
    BWPath(r"C:\dev\MP\Black\MagicTeleport.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicTeleport.h"),
    BWPath(r"C:\dev\MP\Black\MagicTree.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicVortex.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicVortex.h"),
    BWPath(r"C:\dev\MP\Black\MapCoords.cpp"),
    BWPath(r"C:\dev\MP\Black\Meeting.cpp"),
    BWPath(r"C:\dev\MP\Black\Mist.cpp"),
    BWPath(r"C:\dev\MP\Black\Mobile.h"),
    BWPath(r"C:\dev\MP\Black\MobileObject.cpp"),
    BWPath(r"C:\dev\MP\Black\MobileObject.h"),
    BWPath(r"C:\dev\MP\Black\MobileStatic.cpp"),
    BWPath(r"C:\dev\MP\Black\MobileStatic.h"),
    BWPath(r"C:\dev\MP\Black\MobileWallHug.cpp"),
    BWPath(r"C:\dev\MP\Black\MobileWallHug.h"),
    BWPath(r"C:\dev\MP\Black\MorphableObject.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEAlexDialog.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEAlexDialog.h"),
    BWPath(r"C:\dev\MP\Black\MPFEChannelData.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEChannelMessages.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEChannelSelector.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEChooseConnection.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEClanDetails.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEConditionMessages.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEFileTransfer.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEFindGame.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEGameStartMessages.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFELogin.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEMapMessages.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEPlayerDetails.cpp"),
    BWPath(r"C:\dev\MP\Black\MultiplayerDatabase.cpp"),
    BWPath(r"C:\dev\MP\Black\MusicMood.cpp"),
    BWPath(r"C:\dev\MP\Black\Network.cpp"),
    BWPath(r"C:\dev\MP\Black\Object.cpp"),
    BWPath(r"C:\dev\MP\Black\OOSDebug.cpp"),
    BWPath(r"C:\dev\MP\Black\Packet.cpp"),
    BWPath(r"C:\dev\MP\Black\ParticleContainer.cpp"),
    BWPath(r"C:\dev\MP\Black\PathCreator.cpp"),
    BWPath(r"C:\dev\MP\Black\PBall.cpp"),
    BWPath(r"C:\dev\MP\Black\PBall.h"),
    BWPath(r"C:\dev\MP\Black\PCInput.cpp"),
    BWPath(r"C:\dev\MP\Black\PCMain.cpp"),
    BWPath(r"C:\dev\MP\Black\PFootball.cpp"),
    BWPath(r"C:\dev\MP\Black\PFootball.h"),
    BWPath(r"C:\dev\MP\Black\PhysicsObject.cpp"),
    BWPath(r"C:\dev\MP\Black\PictureRoom.cpp"),
    BWPath(r"C:\dev\MP\Black\PlannedMultiMapFixed.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerAction.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerActions.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerComputer.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerComputerCreature.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerComputerInterface.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerComputerReact.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerComputerSpell.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerComputerTown.cpp"),
    BWPath(r"C:\dev\MP\Black\Player.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerMessage.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerProfile.h"),
    BWPath(r"C:\dev\MP\Black\PlaytimeDance.cpp"),
    BWPath(r"C:\dev\MP\Black\PlaytimeDance.h"),
    BWPath(r"C:\dev\MP\Black\Pot.cpp"),
    BWPath(r"C:\dev\MP\Black\Pot.h"),
    BWPath(r"C:\dev\MP\Black\PowerSpin.cpp"),
    BWPath(r"C:\dev\MP\Black\Prayer.h"),
    BWPath(r"C:\dev\MP\Black\PSys3d.cpp"),
    BWPath(r"C:\dev\MP\Black\PSys3d.h"),
    BWPath(r"C:\dev\MP\Black\PSysAtomCore.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysAtomCore.h"),
    BWPath(r"C:\dev\MP\Black\PSysCreature.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysExplosion.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysFireball.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysFireBall.h"),
    BWPath(r"C:\dev\MP\Black\PSysGeom.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysGesture.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysHandFX.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysHandFX.h"),
    BWPath(r"C:\dev\MP\Black\PSysInterface.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysLightning.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysMagicSystem.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysModifiers.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysPCreator.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysProperties.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysRenderParticle.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysShield.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysTornado.cpp"),
    BWPath(r"C:\dev\MP\Black\puzzlegame.cpp"),
    BWPath(r"C:\dev\MP\Black\RandomBuildingPlacement.cpp"),
    BWPath(r"C:\dev\MP\Black\RandomBuildingPlacementDefence.cpp"),
    BWPath(r"C:\dev\MP\Black\Rank.cpp"),
    BWPath(r"C:\dev\MP\Black\Reaction.cpp"),
    BWPath(r"C:\dev\MP\Black\Reaction.h"),
    BWPath(r"C:\dev\MP\Black\Reward.cpp"),
    BWPath(r"C:\dev\MP\Black\reward.h"),
    BWPath(r"C:\dev\MP\Black\Rock.cpp"),
    BWPath(r"C:\dev\MP\Black\RoutePlan.cpp"),
    BWPath(r"C:\dev\MP\Black\SaveGameRoom.cpp"),
    BWPath(r"C:\dev\MP\Black\Scaffold.cpp"),
    BWPath(r"C:\dev\MP\Black\Scaffold.h"),
    BWPath(r"C:\dev\MP\Black\ScriptCamera.cpp"),
    BWPath(r"C:\dev\MP\Black\ScriptContainer.cpp"),
    BWPath(r"C:\dev\MP\Black\Script.cpp"),
    BWPath(r"C:\dev\MP\Black\ScriptCreateOrCall.cpp"),
    BWPath(r"C:\dev\MP\Black\ScriptFunctions.cpp"),
    BWPath(r"C:\dev\MP\Black\ScriptGFX.cpp"),
    BWPath(r"C:\dev\MP\Black\Script.h"),
    BWPath(r"C:\dev\MP\Black\ScriptHighlight.cpp"),
    BWPath(r"C:\dev\MP\Black\ScriptHighlight.h"),
    BWPath(r"C:\dev\MP\Black\ScriptMarker.cpp"),
    BWPath(r"C:\dev\MP\Black\ScriptTimer.cpp"),
    BWPath(r"C:\dev\MP\Black\Serialise.cpp"),
    BWPath(r"C:\dev\MP\Black\Serialise.h"),
    BWPath(r"C:\dev\MP\Black\ServerLandscapeMap.cpp"),
    BWPath(r"C:\dev\MP\Black\ServerLandscapeMap.h"),
    BWPath(r"C:\dev\MP\Black\Setup.cpp"),
    BWPath(r"C:\dev\MP\Black\ShowNeeds.cpp"),
    BWPath(r"C:\dev\MP\Black\ShowNeeds.h"),
    BWPath(r"C:\dev\MP\Black\SLLTemplate.h"),
    BWPath(r"C:\dev\MP\Black\SoundConfirmation.cpp"),
    BWPath(r"C:\dev\MP\Black\SoundGuidance.cpp"),
    BWPath(r"C:\dev\MP\Black\SoundGuidance.h"),
    BWPath(r"C:\dev\MP\Black\SoundMap.h"),
    BWPath(r"C:\dev\MP\Black\SoundTag.cpp"),
    BWPath(r"C:\dev\MP\Black\SpecialVillager.cpp"),
    BWPath(r"C:\dev\MP\Black\SpecialVillager.h"),
    BWPath(r"C:\dev\MP\Black\SpellDispenser.cpp"),
    BWPath(r"C:\dev\MP\Black\SpellFlock.cpp"),
    BWPath(r"C:\dev\MP\Black\SpellFlock.h"),
    BWPath(r"C:\dev\MP\Black\SpellFood.cpp"),
    BWPath(r"C:\dev\MP\Black\SpellForest.cpp"),
    BWPath(r"C:\dev\MP\Black\SpellIcon.cpp"),
    BWPath(r"C:\dev\MP\Black\SpellIcon.h"),
    BWPath(r"C:\dev\MP\Black\SpellSeed.cpp"),
    BWPath(r"C:\dev\MP\Black\SpellSeedInfo.h"),
    BWPath(r"C:\dev\MP\Black\SpellShield.cpp"),
    BWPath(r"C:\dev\MP\Black\SpellShield.h"),
    BWPath(r"C:\dev\MP\Black\SpookyVoices.cpp"),
    BWPath(r"C:\dev\MP\Black\SpookyVoices.h"),
    BWPath(r"C:\dev\MP\Black\SpotVisualInfo.h"),
    BWPath(r"C:\dev\MP\Black\SpreadEffect.cpp"),
    BWPath(r"C:\dev\MP\Black\StoragePit.cpp"),
    BWPath(r"C:\dev\MP\Black\Stream.cpp"),
    BWPath(r"C:\dev\MP\Black\StreetLantern.cpp"),
    BWPath(r"C:\dev\MP\Black\StreetLight.cpp"),
    BWPath(r"C:\dev\MP\Black\Temple.cpp"),
    BWPath(r"C:\dev\MP\Black\TempleEngine.cpp"),
    BWPath(r"C:\dev\MP\Black\TempleRoomAddText.cpp"),
    BWPath(r"C:\dev\MP\Black\TempleRoom.cpp"),
    BWPath(r"C:\dev\MP\Black\Terrain.h"),
    BWPath(r"C:\dev\MP\Black\TOMnavigator.cpp"),
    BWPath(r"C:\dev\MP\Black\Totem.cpp"),
    BWPath(r"C:\dev\MP\Black\TotemStatue.cpp"),
    BWPath(r"C:\dev\MP\Black\TotemStatue.h"),
    BWPath(r"C:\dev\MP\Black\TownAttitudeToCreature.cpp"),
    BWPath(r"C:\dev\MP\Black\TownCentre.cpp"),
    BWPath(r"C:\dev\MP\Black\Town.cpp"),
    BWPath(r"C:\dev\MP\Black\TownDesire.cpp"),
    BWPath(r"C:\dev\MP\Black\TownDesire.h"),
    BWPath(r"C:\dev\MP\Black\Town.h"),
    BWPath(r"C:\dev\MP\Black\TownSpellIcon.cpp"),
    BWPath(r"C:\dev\MP\Black\Tree.cpp"),
    BWPath(r"C:\dev\MP\Black\Tree.h"),
    BWPath(r"C:\dev\MP\Black\Tribe.h"),
    BWPath(r"C:\dev\MP\Black\Utils.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerChild.cpp"),
    BWPath(r"C:\dev\MP\Black\Villager.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerFireman.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerFisherman.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerFootball.cpp"),
    BWPath(r"C:\dev\MP\Black\Villager.h"),
    BWPath(r"C:\dev\MP\Black\VillagerCivic.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerHome.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerHousewife.cpp"),
    BWPath(r"C:\dev\MP\Black\villagernames.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerReaction.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerReactionToCreature.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerScript.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerStates.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerStates.h"),
    BWPath(r"C:\dev\MP\Black\ViscousLiquid.cpp"),
    BWPath(r"C:\dev\MP\Black\VortexSave.cpp"),
    BWPath(r"C:\dev\MP\Black\Wallhug.cpp"),
    BWPath(r"C:\dev\MP\Black\WayPoint.cpp"),
    BWPath(r"C:\dev\MP\Black\Weather.cpp"),
    BWPath(r"C:\dev\MP\Black\Weather.h"),
    BWPath(r"C:\dev\MP\Black\WeatherRain.cpp"),
    BWPath(r"C:\dev\MP\Black\WeatherThing.cpp"),
    BWPath(r"C:\dev\MP\Black\Whale.cpp"),
    BWPath(r"C:\dev\MP\Black\Wonder.cpp"),
    BWPath(r"C:\dev\MP\Black\Workshop.cpp"),
    BWPath(r"C:\dev\MP\Black\WorldRoom.cpp"),
    BWPath(r"C:\dev\MP\Black\Worship.cpp"),
    BWPath(r"C:\dev\MP\Black\Worship.h"),
    BWPath(r"C:\dev\MP\Black\WorshipSiteUpgrade.cpp"),
    BWPath(r"C:\dev\MP\Black\WorshipSiteUpgrade.h"),
    BWPath(r"C:\dev\MP\Black\WorshipSpellIcon.cpp"),
    BWPath(r"C:\dev\MP\Black\WorshipTotem.cpp"),
    BWPath(r"C:\DEV\MP\LIBS\LHALL\RELEASED\HEADERS\LH3DDivers.h"),
    BWPath(r"C:\dev\MP\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHConnectionServer.cpp"),
    # BWPath(r"C:\dev\MP\Libs\LIONHEAD\LHMultiplayer\VER4.0\Release\LHMultiplayerR.pdb"),
    BWPath(r"C:\dev\setup\D3DInformation.cpp"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Mesh.l3d"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Blink_Left.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Blink_Right.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Displeased.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Head_Turn_LR.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Head_Turn_UD.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Hover.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Hover_Stable.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Point_Left_In.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Point_Left_UD.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Point_Right_In.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Point_Right_UD.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Sad.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Scared.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Smile.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Speak_AAA.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Speak_EEE.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Speak_OOO.anmW"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Stand.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Turn_Left.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Turn_Right.anm"),
    BWPath(r"C:\Dev\tools\CreatureUpload\CreatureUploadDlg.cpp"),
    BWPath(r"C:\dev\Tools\Setup\Final Setup\D3DInformation.cpp"),
}

guessed_filepaths = {
    BWPath(r"C:\Dev\black\Base.h"),
    BWPath(r"C:\Dev\black\BaseInfo.h"),
    BWPath(r"C:\Dev\black\LocalBase.h"),
    BWPath(r"C:\Dev\black\GameThing.h"),
    BWPath(r"C:\Dev\black\GameThingWithPos.h"),
}

dev_filepaths = released_filepaths_from_strings.union(guessed_filepaths)


def filter_paths(path: BWPath) -> BWPath:
    # Define parts to remove
    parts_to_remove = {'debug', 'release', 'mfcdebug', 'development', 'released', 'headers', 'mp'}
    # Convert to lower case and filter parts
    filtered_parts = [
        part.lower() for part in path.parts 
        if part.lower() not in parts_to_remove and not re.match(r'version \d+\.\d+', part.lower()) and not re.match(r'ver\d+\.\d+', part.lower())
    ]
    return BWPath(*filtered_parts)


def get_project_paths() -> set[BWPath]:

    relatives = map(lambda x: x.relative_to(BWPath(r"C:\dev")).parent, dev_filepaths)
    debug_release_stripped = map(filter_paths, relatives)
    
    return set(debug_release_stripped)



def map_projects_to_object_files() -> dict[BWPath, set[BWPath]]:
    projects = defaultdict(set)
    project_paths = get_project_paths()    
    for path in dev_filepaths:
        filtered_path = filter_paths(path.relative_to(BWPath(r"C:\dev")).parent)
        object_file = path.stem + ".obj"
        if filtered_path in project_paths:
            projects[filtered_path].add(object_file)
    return dict(projects)