# strings *.{exe,dll} Data/HelpSprite/markevil.hd Audio/SFX/Game/*.sad Audio/SFX/Creature/*.sad 'Plug Ins'/*.dll Profiles/Backup/*{.dll,.exe} | grep -i 'c:\\dev' | sort | uniq -i | less
import re
from pathlib import PureWindowsPath as BWPath
from collections import defaultdict

released_filepaths_from_strings = {
    BWPath(r"C:\Dev\libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DP3.cpp"),
    BWPath(r"c:\dev\libs\lionhead\lh3dlib\development\mfcdebug\lh3damemory.obj"),
    # BWPath(r"C:\Dev\black language\Script Library\Debug\ScriptLibraryD.pdb"),
    BWPath(r"c:\dev\black language\script library\scriptmachine.cpp"),
    BWPath(r"c:\dev\black language\script library\scriptmachine.h"),
    # BWPath(r"C:\dev\Black Plug Ins\Language Library\Debug\LanguageD.pdb"),
    BWPath(r"C:\Dev\black\SoundAction.h"),
    BWPath(r"C:\Dev\black\SoundAlignment.h"),
    BWPath(r"C:\Dev\black\SoundObject.h"),
    BWPath(r"C:\Dev\black\SoundSize.h"),
    BWPath(r"C:\Dev\black\SoundSurface.h"),
    # BWPath(r"c:\DEV\LIBS\LHALL\RELEASED\HEADERS\LHScreen.h"),
    BWPath(r"C:\DEV\LIBS\LHALL\RELEASED\HEADERS\LHTemplate.h"),
    BWPath(r"c:\DEV\LIBS\LHALL\RELEASED\HEADERS\LHTimer.h"),
    BWPath(r"C:\DEV\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DRender.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DTech.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DTech.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHMatrix.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHPoint.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHMath.h"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioAtmos.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioBank.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioHeap.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioMidi.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioMusic.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioRedbook.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioSample.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioSystem.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioWave.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LH_AudioBank.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LH_SamplePlayOptions.cpp"),
    # BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\Release\LHaudiodllR.pdb"),
    # BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\Debug\LHDialogLib.pdb"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\LHCameraParamsDialog.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\LHDialogLib.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\LHEditDialog.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\LHEditDialogSizable.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\LHProgressDialog.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\LHSystemSpecDialog.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\LHSystemSpecSummaryDialog.cpp"),
    BWPath(r"C:\Dev\LIBS\Lionhead\LHDLL\VER1.0\LHDLL.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHFILE\VER3.0\LHSegment.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHFILE\VER3.0\LHFile.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\LHFILE\VER3.0\LHFilePath.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHFILE\VER3.0\LHOSFile.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHFILE\VER3.0\Archive.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHFILE\VER3.0\LHParser.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHFlic.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHHeap2.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHMemoryLeak.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHMouse.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHScreen.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHScript.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHWin.cpp"),
    BWPath(r"C:\dev\libs\LIONHEAD\LHLog\VER4.0\LHAssert.cpp"),
    BWPath(r"C:\dev\libs\LIONHEAD\LHLog\VER4.0\LHGenLog.cpp"),
    BWPath(r"C:\dev\libs\LIONHEAD\LHLog\VER4.0\LHLogProps.cpp"),
    BWPath(r"C:\dev\libs\LIONHEAD\LHLog\VER4.0\LHVersion.cpp"),
    BWPath(r"C:\dev\libs\LIONHEAD\LHLog\VER4.0\LogUtils.cpp"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHConnectionServer.cpp"),
    # BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\Release\LHMultiplayerR.pdb"),
    BWPath(r"C:\dev\MP\Black\Abode.cpp"),
    BWPath(r"C:\dev\MP\Black\Abode.h"),
    BWPath(r"C:\dev\MP\Black\alexmfc.cpp"),
    BWPath(r"C:\dev\MP\Black\Alignment.cpp"),
    BWPath(r"C:\dev\MP\Black\Alignment.h"),
    BWPath(r"C:\dev\MP\Black\AnimalAnimation.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalCow.cpp"),
    BWPath(r"C:\dev\MP\Black\Animal.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalDove.cpp"),
    BWPath(r"C:\dev\MP\Black\Animal.h"),
    BWPath(r"C:\dev\MP\Black\AnimalLeopard.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalLion.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalReaction.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalSpellWolf.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalTiger.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalWolf.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimatedStatic.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimatedStatic.h"),
    BWPath(r"C:\dev\MP\Black\Animations.cpp"),
    BWPath(r"C:\dev\MP\Black\Arena.cpp"),
    BWPath(r"C:\dev\MP\Black\Arrow.cpp"),
    BWPath(r"C:\dev\MP\Black\Arrow.h"),
    BWPath(r"C:\dev\MP\Black\Artifact.cpp"),
    BWPath(r"C:\dev\MP\Black\Audio.cpp"),
    BWPath(r"C:\dev\MP\Black\AudioMusicThing.cpp"),
    BWPath(r"C:\dev\MP\Black\audiotag.cpp"),
    BWPath(r"C:\dev\MP\Black\Balance.cpp"),
    BWPath(r"C:\dev\MP\Black\Ball.cpp"),
    BWPath(r"C:\dev\MP\Black\Ball.h"),
    BWPath(r"C:\dev\MP\Black\Belief.cpp"),
    BWPath(r"C:\dev\MP\Black\Belief.h"),
    BWPath(r"C:\dev\MP\Black\BigForest.cpp"),
    BWPath(r"C:\dev\MP\Black\BigForest.h"),
    BWPath(r"C:\dev\MP\Black\Bonfire.cpp"),
    BWPath(r"C:\dev\MP\Black\Bookmark.cpp"),
    BWPath(r"C:\dev\MP\Black\BuildingSite.cpp"),
    BWPath(r"C:\dev\MP\Black\BWGameSpy.cpp"),
    BWPath(r"C:\dev\MP\Black\BWLan.cpp"),
    BWPath(r"C:\dev\MP\Black\Camera.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraEditor.cpp"),
    BWPath(r"C:\dev\MP\Black\camerahelp.cpp"),
    BWPath(r"C:\dev\MP\Black\camerahelp.h"),
    BWPath(r"C:\dev\MP\Black\CameraModeCitadel.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModeDance.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModeFlyAndClick.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModeFollow.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModeFollowHeading.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModeNew3.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModePath.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModeScript.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModeTwoObjects.cpp"),
    BWPath(r"C:\dev\MP\Black\ChallengeRoom.cpp"),
    BWPath(r"C:\dev\MP\Black\Citadel.cpp"),
    BWPath(r"C:\dev\MP\Black\Citadel.h"),
    BWPath(r"C:\dev\MP\Black\CitadelHeart.cpp"),
    BWPath(r"C:\dev\MP\Black\CitadelHeart.h"),
    BWPath(r"C:\dev\MP\Black\CitadelPart.h"),
    BWPath(r"C:\dev\MP\Black\citadelpeople.cpp"),
    BWPath(r"C:\dev\MP\Black\Collide.cpp"),
    BWPath(r"C:\dev\MP\Black\Config.cpp"),
    BWPath(r"C:\dev\MP\Black\Container.h"),
    BWPath(r"C:\dev\MP\Black\ControlHand.cpp"),
    BWPath(r"C:\dev\MP\Black\Creature3D.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureAction.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureAction.h"),
    BWPath(r"C:\dev\MP\Black\CreatureAttitudeToCreature.cpp"),
    BWPath(r"C:\dev\MP\Black\Creature.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureDevelopment.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureDirectControl.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureFace.cpp"),
    BWPath(r"C:\dev\MP\Black\Creature.h"),
    BWPath(r"C:\dev\MP\Black\CreatureHelp.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureInitialLesson.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureLessonChooser.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureLook.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalAttributeTest.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalBelief.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalBeliefs.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalDesire.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalDesire.h"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalDesireSource.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalDesireSource.h"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalExploration.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalLearnAction.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalLearnAction.h"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalLearn.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalMisc.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalSaveAndLoad.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMimic.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMimic.h"),
    BWPath(r"C:\dev\MP\Black\CreatureMorph.cpp"),
    BWPath(r"C:\dev\MP\Black\CreaturePen.cpp"),
    BWPath(r"C:\dev\MP\Black\CreaturePen.h"),
    BWPath(r"C:\dev\MP\Black\CreaturePhysical.cpp"),
    BWPath(r"C:\dev\MP\Black\CreaturePlan.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureReaction.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureReceiveSpell.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureRoom.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureScript.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureSelect.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureSubAction.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureSubActions.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureWhatToDoNext.cpp"),
    BWPath(r"C:\dev\MP\Black\Creche.cpp"),
    BWPath(r"C:\dev\MP\Black\Dance.cpp"),
    BWPath(r"C:\dev\MP\Black\Dance.h"),
    BWPath(r"C:\dev\MP\Black\DanceKey.cpp"),
    BWPath(r"C:\dev\MP\Black\DanceShape.cpp"),
    BWPath(r"C:\dev\MP\Black\DeadTree.cpp"),
    BWPath(r"C:\dev\MP\Black\DialogBoxKeyBinding.cpp"),
    BWPath(r"C:\dev\MP\Black\DialogBoxMain.cpp"),
    BWPath(r"C:\dev\MP\Black\DialogBoxOptions.cpp"),
    BWPath(r"C:\dev\MP\Black\DialogBoxSaveMessage.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorAnim.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorHug.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorIcon.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorIconBase.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorIconGraph.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorIconPDM.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorIconPDM.h"),
    BWPath(r"C:\dev\MP\Black\EditorIconPlace.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorIconStrip.cpp"),
    BWPath(r"C:\dev\MP\Black\Effect.h"),
    BWPath(r"C:\dev\MP\Black\ExtraFeatures.cpp"),
    BWPath(r"C:\dev\MP\Black\fallingspell.cpp"),
    BWPath(r"C:\dev\MP\Black\Feature.cpp"),
    BWPath(r"C:\dev\MP\Black\Feature.h"),
    BWPath(r"C:\dev\MP\Black\Field.cpp"),
    BWPath(r"C:\dev\MP\Black\Field.h"),
    BWPath(r"C:\dev\MP\Black\FireFly.cpp"),
    BWPath(r"C:\dev\MP\Black\FishFarm.cpp"),
    BWPath(r"C:\dev\MP\Black\FishFarm.h"),
    BWPath(r"C:\dev\MP\Black\Fixed.cpp"),
    BWPath(r"C:\dev\MP\Black\Fixed.h"),
    BWPath(r"C:\dev\MP\Black\Flock.cpp"),
    BWPath(r"C:\dev\MP\Black\FootBall.cpp"),
    BWPath(r"C:\dev\MP\Black\Football.h"),
    BWPath(r"C:\dev\MP\Black\Footpath.cpp"),
    BWPath(r"C:\dev\MP\Black\Forest.cpp"),
    BWPath(r"C:\dev\MP\Black\frontend.cpp"),
    BWPath(r"C:\dev\MP\Black\FrontEndSetupGame.cpp"),
    BWPath(r"C:\dev\MP\Black\FrontEndSetupMultiplayer.cpp"),
    BWPath(r"C:\dev\MP\Black\Furniture.cpp"),
    BWPath(r"C:\dev\MP\Black\Furniture.h"),
    BWPath(r"C:\dev\MP\Black\GameArea.h"),
    BWPath(r"C:\dev\MP\Black\Game.cpp"),
    BWPath(r"C:\dev\MP\Black\GameOSFile.cpp"),
    BWPath(r"C:\dev\MP\Black\GameOSFile.h"),
    BWPath(r"C:\dev\MP\Black\GameStats.cpp"),
    BWPath(r"C:\dev\MP\Black\GameStatsFrontEnd.cpp"),
    BWPath(r"C:\dev\MP\Black\GameStatsList.h"),
    BWPath(r"C:\dev\MP\Black\GatheringInterface.cpp"),
    BWPath(r"C:\dev\MP\Black\GatheringInterface.h"),
    BWPath(r"C:\dev\MP\Black\GenerateCreatureHTML.cpp"),
    BWPath(r"C:\dev\MP\Black\GJBaseUtils.inl"),
    BWPath(r"C:\dev\MP\Black\GJVnoise.cpp"),
    BWPath(r"C:\dev\MP\Black\GJPersistent.cpp"),
    BWPath(r"C:\dev\MP\Black\GJProperty.cpp"),
    BWPath(r"C:\dev\MP\Black\GJProperty.h"),
    BWPath(r"C:\dev\MP\Black\Global.cpp"),
    BWPath(r"C:\dev\MP\Black\GraveYard.cpp"),
    BWPath(r"C:\dev\MP\Black\GroupBehaviour.cpp"),
    BWPath(r"C:\dev\MP\Black\GSLobbybox.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpDudeControl.cpp"),
    BWPath(r"C:\dev\MP\Black\helpdude.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpDudeLipSync.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpEditor.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpProfile.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpSpirit.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpSpirit.h"),
    BWPath(r"C:\dev\MP\Black\HelpSystemBubble.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpSystem.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpSystem.h"),
    BWPath(r"C:\dev\MP\Black\HelpSystemToolTips.h"),
    BWPath(r"C:\dev\MP\Black\HelpText.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpText.h"),
    BWPath(r"C:\dev\MP\Black\Influence.cpp"),
    BWPath(r"C:\dev\MP\Black\Influence.h"),
    BWPath(r"C:\dev\MP\Black\Interface.cpp"),
    BWPath(r"C:\dev\MP\Black\InterfaceImmersion.cpp"),
    BWPath(r"C:\dev\MP\Black\InterfaceMessage.cpp"),
    BWPath(r"C:\dev\MP\Black\InterfaceStatus.cpp"),
    BWPath(r"C:\dev\MP\Black\IpSpecialDialog.cpp"),
    BWPath(r"C:\dev\MP\Black\JCGameBlock.cpp"),
    BWPath(r"C:\dev\MP\Black\JCMisc.cpp"),
    BWPath(r"C:\dev\MP\Black\Job.h"),
    BWPath(r"C:\dev\MP\Black\KeyBuffer.cpp"),
    BWPath(r"C:\dev\MP\Black\LandAlignement.cpp"),
    BWPath(r"C:\dev\MP\Black\LandFeature.cpp"),
    BWPath(r"C:\dev\MP\Black\Landscape.cpp"),
    BWPath(r"C:\dev\MP\Black\LevelOfDetail.cpp"),
    BWPath(r"C:\dev\MP\Black\LHInetWeather.cpp"),
    BWPath(r"C:\dev\MP\Black\LHNetBase.cpp"),
    BWPath(r"C:\dev\MP\Black\Living.cpp"),
    BWPath(r"C:\dev\MP\Black\Living.h"),
    BWPath(r"C:\dev\MP\Black\LivingProjectile.cpp"),
    BWPath(r"C:\dev\MP\Black\LivingReaction.cpp"),
    BWPath(r"C:\dev\MP\Black\LoaderAnon.cpp"),
    BWPath(r"C:\dev\MP\Black\LoadingScreen.cpp"),
    BWPath(r"C:\dev\MP\Black\Lobbybox.cpp"),
    BWPath(r"C:\dev\MP\Black\logo.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicCreatureSpellInfo.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicCreatureSpellInfo.h"),
    BWPath(r"C:\dev\MP\Black\MagicFood.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicFoodInfo.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicFoodInfo.h"),
    BWPath(r"C:\dev\MP\Black\MagicForestInfo.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicForestInfo.h"),
    BWPath(r"C:\dev\MP\Black\MagicInfo.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicInfo.h"),
    BWPath(r"C:\dev\MP\Black\MagicShieldInfo.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicShieldInfo.h"),
    BWPath(r"C:\dev\MP\Black\MagicTeleport.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicTeleport.h"),
    BWPath(r"C:\dev\MP\Black\MagicTree.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicVortex.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicVortex.h"),
    BWPath(r"C:\dev\MP\Black\MapCoords.cpp"),
    BWPath(r"C:\dev\MP\Black\Meeting.cpp"),
    BWPath(r"C:\dev\MP\Black\Mist.cpp"),
    BWPath(r"C:\dev\MP\Black\Mobile.h"),
    BWPath(r"C:\dev\MP\Black\MobileObject.cpp"),
    BWPath(r"C:\dev\MP\Black\MobileObject.h"),
    BWPath(r"C:\dev\MP\Black\MobileStatic.cpp"),
    BWPath(r"C:\dev\MP\Black\MobileStatic.h"),
    BWPath(r"C:\dev\MP\Black\MobileWallHug.cpp"),
    BWPath(r"C:\dev\MP\Black\MobileWallHug.h"),
    BWPath(r"C:\dev\MP\Black\MorphableObject.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEAlexDialog.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEAlexDialog.h"),
    BWPath(r"C:\dev\MP\Black\MPFEChannelData.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEChannelMessages.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEChannelSelector.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEChooseConnection.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEClanDetails.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEConditionMessages.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEFileTransfer.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEFindGame.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEGameStartMessages.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFELogin.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEMapMessages.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEPlayerDetails.cpp"),
    BWPath(r"C:\dev\MP\Black\MultiplayerDatabase.cpp"),
    BWPath(r"C:\dev\MP\Black\MusicMood.cpp"),
    BWPath(r"C:\dev\MP\Black\Network.cpp"),
    BWPath(r"C:\dev\MP\Black\Object.cpp"),
    BWPath(r"C:\dev\MP\Black\OOSDebug.cpp"),
    BWPath(r"C:\dev\MP\Black\Packet.cpp"),
    BWPath(r"C:\dev\MP\Black\ParticleContainer.cpp"),
    BWPath(r"C:\dev\MP\Black\PathCreator.cpp"),
    BWPath(r"C:\dev\MP\Black\PBall.cpp"),
    BWPath(r"C:\dev\MP\Black\PBall.h"),
    BWPath(r"C:\dev\MP\Black\PCInput.cpp"),
    BWPath(r"C:\dev\MP\Black\PCMain.cpp"),
    BWPath(r"C:\dev\MP\Black\PFootball.cpp"),
    BWPath(r"C:\dev\MP\Black\PFootball.h"),
    BWPath(r"C:\dev\MP\Black\PhysicsObject.cpp"),
    BWPath(r"C:\dev\MP\Black\PictureRoom.cpp"),
    BWPath(r"C:\dev\MP\Black\PlannedMultiMapFixed.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerAction.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerActions.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerComputer.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerComputerCreature.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerComputerInterface.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerComputerReact.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerComputerSpell.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerComputerTown.cpp"),
    BWPath(r"C:\dev\MP\Black\Player.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerMessage.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerProfile.h"),
    BWPath(r"C:\dev\MP\Black\PlaytimeDance.cpp"),
    BWPath(r"C:\dev\MP\Black\PlaytimeDance.h"),
    BWPath(r"C:\dev\MP\Black\Pot.cpp"),
    BWPath(r"C:\dev\MP\Black\Pot.h"),
    BWPath(r"C:\dev\MP\Black\PowerSpin.cpp"),
    BWPath(r"C:\dev\MP\Black\Prayer.h"),
    BWPath(r"C:\dev\MP\Black\PSys3d.cpp"),
    BWPath(r"C:\dev\MP\Black\PSys3d.h"),
    BWPath(r"C:\dev\MP\Black\PSysAtomCore.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysAtomCore.h"),
    BWPath(r"C:\dev\MP\Black\PSysCreature.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysExplosion.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysFireball.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysFireBall.h"),
    BWPath(r"C:\dev\MP\Black\PSysGeom.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysGesture.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysHandFX.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysHandFX.h"),
    BWPath(r"C:\dev\MP\Black\PSysInterface.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysLightning.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysMagicSystem.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysModifiers.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysPCreator.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysProperties.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysRenderParticle.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysShield.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysTornado.cpp"),
    BWPath(r"C:\dev\MP\Black\puzzlegame.cpp"),
    BWPath(r"C:\dev\MP\Black\RandomBuildingPlacement.cpp"),
    BWPath(r"C:\dev\MP\Black\RandomBuildingPlacementDefence.cpp"),
    BWPath(r"C:\dev\MP\Black\Rank.cpp"),
    BWPath(r"C:\dev\MP\Black\Reaction.cpp"),
    BWPath(r"C:\dev\MP\Black\Reaction.h"),
    BWPath(r"C:\dev\MP\Black\Reward.cpp"),
    BWPath(r"C:\dev\MP\Black\reward.h"),
    BWPath(r"C:\dev\MP\Black\Rock.cpp"),
    BWPath(r"C:\dev\MP\Black\RoutePlan.cpp"),
    BWPath(r"C:\dev\MP\Black\SaveGameRoom.cpp"),
    BWPath(r"C:\dev\MP\Black\Scaffold.cpp"),
    BWPath(r"C:\dev\MP\Black\Scaffold.h"),
    BWPath(r"C:\dev\MP\Black\ScriptCamera.cpp"),
    BWPath(r"C:\dev\MP\Black\ScriptContainer.cpp"),
    BWPath(r"C:\dev\MP\Black\Script.cpp"),
    BWPath(r"C:\dev\MP\Black\ScriptCreateOrCall.cpp"),
    BWPath(r"C:\dev\MP\Black\ScriptFunctions.cpp"),
    BWPath(r"C:\dev\MP\Black\ScriptGFX.cpp"),
    BWPath(r"C:\dev\MP\Black\Script.h"),
    BWPath(r"C:\dev\MP\Black\ScriptHighlight.cpp"),
    BWPath(r"C:\dev\MP\Black\ScriptHighlight.h"),
    BWPath(r"C:\dev\MP\Black\ScriptMarker.cpp"),
    BWPath(r"C:\dev\MP\Black\ScriptTimer.cpp"),
    BWPath(r"C:\dev\MP\Black\Serialise.cpp"),
    BWPath(r"C:\dev\MP\Black\Serialise.h"),
    BWPath(r"C:\dev\MP\Black\ServerLandscapeMap.cpp"),
    BWPath(r"C:\dev\MP\Black\ServerLandscapeMap.h"),
    BWPath(r"C:\dev\MP\Black\Setup.cpp"),
    BWPath(r"C:\dev\MP\Black\ShowNeeds.cpp"),
    BWPath(r"C:\dev\MP\Black\ShowNeeds.h"),
    BWPath(r"C:\dev\MP\Black\SLLTemplate.h"),
    BWPath(r"C:\dev\MP\Black\SoundConfirmation.cpp"),
    BWPath(r"C:\dev\MP\Black\SoundGuidance.cpp"),
    BWPath(r"C:\dev\MP\Black\SoundGuidance.h"),
    BWPath(r"C:\dev\MP\Black\SoundMap.h"),
    BWPath(r"C:\dev\MP\Black\SoundTag.cpp"),
    BWPath(r"C:\dev\MP\Black\SpecialVillager.cpp"),
    BWPath(r"C:\dev\MP\Black\SpecialVillager.h"),
    BWPath(r"C:\dev\MP\Black\SpellDispenser.cpp"),
    BWPath(r"C:\dev\MP\Black\SpellFlock.cpp"),
    BWPath(r"C:\dev\MP\Black\SpellFlock.h"),
    BWPath(r"C:\dev\MP\Black\SpellFood.cpp"),
    BWPath(r"C:\dev\MP\Black\SpellForest.cpp"),
    BWPath(r"C:\dev\MP\Black\SpellIcon.cpp"),
    BWPath(r"C:\dev\MP\Black\SpellIcon.h"),
    BWPath(r"C:\dev\MP\Black\SpellSeed.cpp"),
    BWPath(r"C:\dev\MP\Black\SpellSeedInfo.h"),
    BWPath(r"C:\dev\MP\Black\SpellShield.cpp"),
    BWPath(r"C:\dev\MP\Black\SpellShield.h"),
    BWPath(r"C:\dev\MP\Black\SpookyVoices.cpp"),
    BWPath(r"C:\dev\MP\Black\SpookyVoices.h"),
    BWPath(r"C:\dev\MP\Black\SpotVisualInfo.h"),
    BWPath(r"C:\dev\MP\Black\SpreadEffect.cpp"),
    BWPath(r"C:\dev\MP\Black\StoragePit.cpp"),
    BWPath(r"C:\dev\MP\Black\Stream.cpp"),
    BWPath(r"C:\dev\MP\Black\StreetLantern.cpp"),
    BWPath(r"C:\dev\MP\Black\StreetLight.cpp"),
    BWPath(r"C:\dev\MP\Black\Temple.cpp"),
    BWPath(r"C:\dev\MP\Black\TempleEngine.cpp"),
    BWPath(r"C:\dev\MP\Black\TempleRoomAddText.cpp"),
    BWPath(r"C:\dev\MP\Black\TempleRoom.cpp"),
    BWPath(r"C:\dev\MP\Black\Terrain.h"),
    BWPath(r"C:\dev\MP\Black\TOMnavigator.cpp"),
    BWPath(r"C:\dev\MP\Black\Totem.cpp"),
    BWPath(r"C:\dev\MP\Black\TotemStatue.cpp"),
    BWPath(r"C:\dev\MP\Black\TotemStatue.h"),
    BWPath(r"C:\dev\MP\Black\TownAttitudeToCreature.cpp"),
    BWPath(r"C:\dev\MP\Black\TownCentre.cpp"),
    BWPath(r"C:\dev\MP\Black\Town.cpp"),
    BWPath(r"C:\dev\MP\Black\TownDesire.cpp"),
    BWPath(r"C:\dev\MP\Black\TownDesire.h"),
    BWPath(r"C:\dev\MP\Black\Town.h"),
    BWPath(r"C:\dev\MP\Black\TownSpellIcon.cpp"),
    BWPath(r"C:\dev\MP\Black\Tree.cpp"),
    BWPath(r"C:\dev\MP\Black\Tree.h"),
    BWPath(r"C:\dev\MP\Black\Tribe.h"),
    BWPath(r"C:\dev\MP\Black\Utils.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerChild.cpp"),
    BWPath(r"C:\dev\MP\Black\Villager.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerFireman.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerFisherman.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerFootball.cpp"),
    BWPath(r"C:\dev\MP\Black\Villager.h"),
    BWPath(r"C:\dev\MP\Black\VillagerCivic.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerHome.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerHousewife.cpp"),
    BWPath(r"C:\dev\MP\Black\villagernames.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerReaction.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerReactionToCreature.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerScript.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerStates.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerStates.h"),
    BWPath(r"C:\dev\MP\Black\ViscousLiquid.cpp"),
    BWPath(r"C:\dev\MP\Black\VortexSave.cpp"),
    BWPath(r"C:\dev\MP\Black\Wallhug.cpp"),
    BWPath(r"C:\dev\MP\Black\WayPoint.cpp"),
    BWPath(r"C:\dev\MP\Black\Weather.cpp"),
    BWPath(r"C:\dev\MP\Black\Weather.h"),
    BWPath(r"C:\dev\MP\Black\WeatherRain.cpp"),
    BWPath(r"C:\dev\MP\Black\WeatherThing.cpp"),
    BWPath(r"C:\dev\MP\Black\Whale.cpp"),
    BWPath(r"C:\dev\MP\Black\Wonder.cpp"),
    BWPath(r"C:\dev\MP\Black\Workshop.cpp"),
    BWPath(r"C:\dev\MP\Black\WorldRoom.cpp"),
    BWPath(r"C:\dev\MP\Black\Worship.cpp"),
    BWPath(r"C:\dev\MP\Black\Worship.h"),
    BWPath(r"C:\dev\MP\Black\WorshipSiteUpgrade.cpp"),
    BWPath(r"C:\dev\MP\Black\WorshipSiteUpgrade.h"),
    BWPath(r"C:\dev\MP\Black\WorshipSpellIcon.cpp"),
    BWPath(r"C:\dev\MP\Black\WorshipTotem.cpp"),
    # BWPath(r"C:\DEV\MP\LIBS\LHALL\RELEASED\HEADERS\LH3DDivers.h"),
    BWPath(r"C:\dev\MP\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHConnectionServer.cpp"),
    # BWPath(r"C:\dev\MP\Libs\LIONHEAD\LHMultiplayer\VER4.0\Release\LHMultiplayerR.pdb"),
    BWPath(r"C:\dev\setup\D3DInformation.cpp"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Mesh.l3d"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Blink_Left.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Blink_Right.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Displeased.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Head_Turn_LR.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Head_Turn_UD.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Hover.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Hover_Stable.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Point_Left_In.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Point_Left_UD.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Point_Right_In.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Point_Right_UD.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Sad.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Scared.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Smile.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Speak_AAA.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Speak_EEE.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Speak_OOO.anmW"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Stand.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Turn_Left.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Turn_Right.anm"),
    BWPath(r"C:\Dev\tools\CreatureUpload\CreatureUploadDlg.cpp"),
    BWPath(r"C:\dev\Tools\Setup\Final Setup\D3DInformation.cpp"),
}

guessed_filepaths = {
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHMemory.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHJoypad.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHScreen.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHDDEnum.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DObject.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DMeshedObject.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DStaticObject.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DStaticMorphableObject.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DAnimatedObject.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DComplexObject.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DSpriteObject.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DMist.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DCitadel.h"),
    BWPath(r"C:\DEV\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DDivers.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHCoord.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHRegion.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHPixel.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHSurface.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DSprite.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHText.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHSystem.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DAnim.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DColor.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DHair.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DTexture.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DMaterial.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DVertex.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DVertexGroup.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DPrimitive.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DSubMesh.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DMesh.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DSmoke.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DCamera.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DCameraChecker.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\L3DBoundingBox.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DObjectHair.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DWay.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\Vertex3D.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\Zoomer.h"),

    BWPath(r"C:\Dev\Libs\LIONHEAD\LHFILE\VER3.0\LHReleasedFile.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHFILE\VER3.0\LHReleasedOSFile.h"),

    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHTransportInfo.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHTransport.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHPacketisableObject.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHPlayer.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHServerPlayer.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHSocket.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHSocketTCP.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHSession.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHSerial.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHLobbyServer.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHMPServerStartInfo.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHLobby.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHConnection.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHNetUser.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHNetEvent.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHPacket.h"),

    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\Name.h"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\Random.h"),

    BWPath(r"C:\DEV\LIBS\LHALL\RELEASED\HEADERS\VisitBlock.h"),
    BWPath(r"C:\DEV\LIBS\LHALL\RELEASED\HEADERS\RouteNode.h"),
    BWPath(r"C:\DEV\LIBS\LHALL\RELEASED\HEADERS\Route.h"),
    BWPath(r"C:\DEV\LIBS\LHALL\RELEASED\HEADERS\RPAvoid.h"),
    BWPath(r"C:\DEV\LIBS\LHALL\RELEASED\HEADERS\RPFollow.h"),
    BWPath(r"C:\DEV\LIBS\LHALL\RELEASED\HEADERS\RPlan.h"),
    BWPath(r"C:\DEV\LIBS\LHALL\RELEASED\HEADERS\RPHolder.h"),
    BWPath(r"C:\DEV\LIBS\LHALL\RELEASED\HEADERS\Heap.h"),

    BWPath(r"C:\Dev\black\Base.h"),
    BWPath(r"C:\Dev\black\BaseInfo.h"),
    BWPath(r"C:\Dev\black\LocalBase.h"),
    BWPath(r"C:\Dev\black\GameThing.h"),
    BWPath(r"C:\Dev\black\GameThingWithPos.h"),

    BWPath(r"C:\Dev\black\AllocatedBeliefList.h"),
    BWPath(r"C:\Dev\black\Bubble.h"),
    BWPath(r"C:\Dev\black\CameraExclusion.h"),
    BWPath(r"C:\Dev\black\CameraMode.h"),
    BWPath(r"C:\Dev\black\CameraModeFree.h"),
    BWPath(r"C:\Dev\Black\CameraModeCtrInteract.cpp"),
    BWPath(r"C:\Dev\Black\CameraModeNew.cpp"),
    BWPath(r"C:\Dev\Black\CameraModeNew1.cpp"),
    BWPath(r"C:\Dev\Black\CameraModeNew2.cpp"),
    BWPath(r"C:\Dev\black\ScriptedCamera.h"),
    BWPath(r"C:\Dev\black\ControlMap.h"),
    BWPath(r"C:\Dev\black\CHand.h"),
    BWPath(r"C:\Dev\black\Climate.h"),
    BWPath(r"C:\Dev\black\CreatureActionsKnownAbout.h"),
    BWPath(r"C:\Dev\black\CreatureAgenda.h"),
    BWPath(r"C:\Dev\black\CreatureAttitudeToPlayer.h"),
    BWPath(r"C:\Dev\black\CreatureBeliefList.h"),
    BWPath(r"C:\Dev\black\CreatureBeliefs.h"),
    BWPath(r"C:\Dev\black\CreatureBelief.h"),
    BWPath(r"C:\Dev\black\CreatureCommandState.h"),
    BWPath(r"C:\Dev\black\CreatureContext.h"),
    BWPath(r"C:\Dev\black\CreatureDamageMap.h"),
    BWPath(r"C:\Dev\black\CreatureDatabase.h"),
    BWPath(r"C:\Dev\black\CreatureDesires.h"),
    BWPath(r"C:\Dev\black\CreatureDecision.h"),
    BWPath(r"C:\Dev\black\CreatureExplorationMap.h"),
    BWPath(r"C:\Dev\black\CreatureLearning.h"),
    BWPath(r"C:\Dev\black\CreatureMental.h"),
    BWPath(r"C:\Dev\black\CreatureMentalDebug.h"),
    BWPath(r"C:\Dev\black\CreatureMimicState.h"),
    BWPath(r"C:\Dev\black\CreatureObjectsInspected.h"),
    BWPath(r"C:\Dev\black\CreaturePreviousActions.h"),
    BWPath(r"C:\Dev\black\CreaturePreviousLesson.h"),
    BWPath(r"C:\Dev\black\CreatureRoomCamera.h"),
    BWPath(r"C:\Dev\black\CreatureSubActionAgenda.h"),
    BWPath(r"C:\Dev\black\CreatureVisionState.h"),
    BWPath(r"C:\Dev\black\DanceGroup.h"),
    BWPath(r"C:\Dev\black\DancePathInfo.h"),
    BWPath(r"C:\Dev\black\DataForScriptRemind.h"),
    BWPath(r"C:\Dev\black\DataPath.h"),
    BWPath(r"C:\Dev\black\Guidance.h"),
    BWPath(r"C:\Dev\black\Data.h"),
    BWPath(r"C:\Dev\black\Debug.h"),
    BWPath(r"C:\Dev\black\DialogBoxBase.h"),
    BWPath(r"C:\Dev\black\DialogBoxImmersion.h"),
    BWPath(r"C:\Dev\black\DiscipleInfo.h"),
    BWPath(r"C:\Dev\black\DrawingObject.h"),
    BWPath(r"C:\Dev\black\EffectValues.h"),
    BWPath(r"C:\Dev\black\EarthQuake.h"),
    BWPath(r"C:\Dev\black\FixedObject.h"),
    BWPath(r"C:\Dev\black\FrontEnd.h"),
    BWPath(r"C:\Dev\black\AbodeInfo.h"),
    BWPath(r"C:\Dev\black\HistoryBox.h"),
    BWPath(r"C:\Dev\black\MultiplayerConditionBox.h"),
    BWPath(r"C:\Dev\black\EndGameBox.h"),
    BWPath(r"C:\Dev\black\StatsBox.h"),
    BWPath(r"C:\Dev\black\Plasma.h"),
    BWPath(r"C:\Dev\black\Game3DObject.h"),
    BWPath(r"C:\Dev\black\BallInfo.h"),
    BWPath(r"C:\Dev\black\BigForestInfo.h"),
    BWPath(r"C:\Dev\black\CitadelHeartInfo.h"),
    BWPath(r"C:\Dev\black\CitadelPartInfo.h"),
    BWPath(r"C:\Dev\black\ContainerInfo.h"),
    BWPath(r"C:\Dev\black\CreatureInfo.h"),
    BWPath(r"C:\Dev\black\DanceInfo.h"),
    BWPath(r"C:\Dev\black\EffectInfo.h"),
    BWPath(r"C:\Dev\black\FireEffect.h"),
    BWPath(r"C:\Dev\black\FieldTypeInfo.h"),
    BWPath(r"C:\Dev\black\FootpathFinder.h"),
    BWPath(r"C:\Dev\black\FootpathLink.h"),
    BWPath(r"C:\Dev\black\FootpathLinkSave.h"),
    BWPath(r"C:\Dev\black\FootpathNode.h"),
    BWPath(r"C:\Dev\black\Fragment.h"),
    BWPath(r"C:\Dev\black\GameBlock.h"),
    BWPath(r"C:\Dev\black\GameInfo.h"),
    BWPath(r"C:\Dev\black\GatheringText.h"),
    BWPath(r"C:\Dev\black\Guidance.h"),
    BWPath(r"C:\Dev\black\HairGroup.h"),
    BWPath(r"C:\Dev\black\InfluenceRing.h"),
    BWPath(r"C:\Dev\black\InfoTransform.h"),
    BWPath(r"C:\Dev\black\InterfaceCollide.h"),
    BWPath(r"C:\Dev\black\InterfaceFlags.h"),
    BWPath(r"C:\Dev\black\InterfaceMessageBuffer.h"),
    BWPath(r"C:\Dev\black\JPSysInterface.h"),
    BWPath(r"C:\Dev\black\Language.h"),
    BWPath(r"C:\Dev\black\LeashStatus.h"),
    BWPath(r"C:\Dev\black\LightSheet.h"),
    BWPath(r"C:\Dev\black\LivingInfo.h"),
    BWPath(r"C:\Dev\black\GlobalGameLists.h"),
    BWPath(r"C:\Dev\black\GestureSystem.h"),
    BWPath(r"C:\Dev\black\GestureSystemResult.h"),
    BWPath(r"C:\Dev\black\GestureSystemData.h"),
    BWPath(r"C:\Dev\black\GestureSystemDataList.h"),
    BWPath(r"C:\Dev\black\MagicEffectInfo.h"),
    BWPath(r"C:\Dev\black\MagicFireBall.h"),
    BWPath(r"C:\Dev\black\MagicHand.h"),
    BWPath(r"C:\Dev\black\Map.h"),
    BWPath(r"C:\Dev\black\MapShield.h"),
    BWPath(r"C:\Dev\black\MobileInfo.h"),
    BWPath(r"C:\Dev\black\MobileObjectInfo.h"),
    BWPath(r"C:\Dev\black\MobileWallHugInfo.h"),
    BWPath(r"C:\Dev\black\MultiMapFixedInfo.h"),
    BWPath(r"C:\Dev\black\ObjectInfo.h"),
    BWPath(r"C:\Dev\black\PlayerInfo.h"),
    BWPath(r"C:\Dev\black\PrayerIconInfo.h"),
    BWPath(r"C:\Dev\black\PuzzleGame.h"),
    BWPath(r"C:\dev\Black\PSysProcessInfo.cpp"),
    BWPath(r"C:\Dev\black\SaveLoadPtr.h"),
    BWPath(r"C:\Dev\black\ShowNeedsInfo.h"),
    BWPath(r"C:\Dev\black\SingleMapFixedInfo.h"),
    BWPath(r"C:\Dev\black\SpecialVillagerInfo.h"),
    BWPath(r"C:\Dev\black\SpellIconInfo.h"),
    BWPath(r"C:\Dev\black\TerrainMap.h"),
    BWPath(r"C:\Dev\black\TotemStatueInfo.h"),
    BWPath(r"C:\Dev\black\TownDesireInfo.h"),
    BWPath(r"C:\Dev\black\TownInfo.h"),
    BWPath(r"C:\Dev\black\TreeInfo.h"),
    BWPath(r"C:\Dev\black\TribeInfo.h"),
    BWPath(r"C:\Dev\black\VillagerInfo.h"),
    BWPath(r"C:\Dev\black\VillagerStateTableInfo.h"),
    BWPath(r"C:\Dev\black\VirtualInfluence.h"),
    BWPath(r"C:\Dev\black\WorshipSiteInfo.h"),
    BWPath(r"C:\Dev\black\HandState.h"),
    BWPath(r"C:\Dev\black\Global.h"),
    BWPath(r"C:\Dev\black\HandStateCamera.h"),
    BWPath(r"C:\Dev\black\HandStateCitadel.h"),
    BWPath(r"C:\Dev\black\HandStateCreature.h"),
    BWPath(r"C:\Dev\black\HandStateGrain.h"),
    BWPath(r"C:\Dev\black\HandStateHolding.h"),
    BWPath(r"C:\Dev\black\HandStateInvisible.h"),
    BWPath(r"C:\Dev\black\HandStateMultiPickUp.h"),
    BWPath(r"C:\Dev\black\HandStateNormal.h"),
    BWPath(r"C:\Dev\black\HandStatePlayAnim.h"),
    BWPath(r"C:\Dev\black\HandStateTotem.h"),
    BWPath(r"C:\Dev\black\HandStateTug.h"),
    BWPath(r"C:\Dev\black\HelpTextDataBase.h"),
    BWPath(r"C:\Dev\black\InnerCamera.h"),
    BWPath(r"C:\Dev\black\InterfaceHandState.h"),
    BWPath(r"C:\Dev\black\Landscape.h"),
    BWPath(r"C:\Dev\black\LandscapeVortex.h"),
    BWPath(r"C:\Dev\black\LayerCommunication.h"),
    BWPath(r"C:\Dev\black\Leash.h"),
    BWPath(r"C:\Dev\black\LiquidParticle.h"),
    BWPath(r"C:\Dev\black\LH3DCreature.h"),
    BWPath(r"C:\Dev\black\MiniDialogBoxOptions.h"),
    BWPath(r"C:\Dev\black\Morphable.h"),
    BWPath(r"C:\Dev\black\MultiMapFixed.h"),
    BWPath(r"C:\dev\Black\MPFEConnectionStatus.cpp"),
    BWPath(r"C:\Dev\black\Network.h"),
    BWPath(r"C:\Dev\black\OneOffSpellSeed.h"),
    BWPath(r"C:\Dev\black\PileFood.h"),
    BWPath(r"C:\Dev\black\PileResource.h"),
    BWPath(r"C:\Dev\black\PileWood.h"),
    BWPath(r"C:\Dev\black\PlannedAbode.h"),
    BWPath(r"C:\Dev\black\PlannedTownCentre.h"),
    BWPath(r"C:\Dev\black\PotStructure.h"),
    BWPath(r"C:\Dev\black\PSysBase.h"),
    BWPath(r"C:\Dev\black\PSysManager.h"),
    BWPath(r"C:\Dev\black\ReactionInfo.h"),
    BWPath(r"C:\Dev\black\ScriptDLL.h"),
    BWPath(r"C:\Dev\black\ScriptCreatureCurse.h"),
    BWPath(r"C:\Dev\black\Settings.h"),
    BWPath(r"C:\Dev\black\SetupBigButton.h"),
    BWPath(r"C:\Dev\black\SetupButton.h"),
    BWPath(r"C:\Dev\black\SetupCheckBox.h"),
    BWPath(r"C:\Dev\black\SetupColourPicker.h"),
    BWPath(r"C:\Dev\black\SetupBox.h"),
    BWPath(r"C:\Dev\black\SetupControl.h"),
    BWPath(r"C:\Dev\black\SetupEdit.h"),
    BWPath(r"C:\Dev\black\SetupHLineGraph.h"),
    BWPath(r"C:\Dev\black\SetupHSBarGraph.h"),
    BWPath(r"C:\Dev\black\SetupList.h"),
    BWPath(r"C:\Dev\black\SetupMP3Button.h"),
    BWPath(r"C:\Dev\black\SetupMultiList.h"),
    BWPath(r"C:\Dev\black\SetupPicture.h"),
    BWPath(r"C:\Dev\black\SetupRect.h"),
    BWPath(r"C:\Dev\black\SetupSlider.h"),
    BWPath(r"C:\Dev\black\SetupStaticText.h"),
    BWPath(r"C:\Dev\black\SetupStaticTextNoHit.h"),
    BWPath(r"C:\Dev\black\SetupTabButton.h"),
    BWPath(r"C:\Dev\black\SetupThing.h"),
    BWPath(r"C:\Dev\black\SetupVBarGraph.h"),
    BWPath(r"C:\Dev\black\ShowNeedsVisuals.h"),
    BWPath(r"C:\Dev\black\SingleMapFixed.h"),
    BWPath(r"C:\Dev\black\SoundMap.h"),
    BWPath(r"C:\Dev\black\Spell.h"),
    BWPath(r"C:\Dev\black\SpellSeedGraphic.h"),
    BWPath(r"C:\Dev\black\SpellWater.h"),
    BWPath(r"C:\Dev\black\SpellWithObjects.h"),
    BWPath(r"C:\dev\Black\StandardBuildingSite.h"),
    BWPath(r"C:\Dev\black\StartGameBox.h"),
    BWPath(r"C:\Dev\black\StatsDatabase.h"),
    BWPath(r"C:\Dev\black\TerrainMapInfo.h"),
    BWPath(r"C:\Dev\black\TerrainMapTypeInfo.h"),
    BWPath(r"C:\Dev\black\TownCentreSpellIcon.h"),
    BWPath(r"C:\Dev\black\TownDesireFlags.h"),
    BWPath(r"C:\Dev\black\TownStats.h"),
    BWPath(r"C:\Dev\black\ValueSpinner.h"),
    BWPath(r"C:\Dev\black\VillagerName.h"),
    BWPath(r"C:\Dev\black\Waterfall.h"),
    BWPath(r"C:\Dev\black\Waypoint.h"),
    BWPath(r"C:\Dev\black\WeatherInfo.h"),
    BWPath(r"C:\Dev\black\WorshipSite.h"),
    BWPath(r"C:\Dev\black\WorshipSpell.h"),
}

roomate_classes = {
    "LHPoint2D": "LHPoint",
    "MapCoordsSplit": "MapCoords",
    "MapCoordsFull": "MapCoords",
    "JustMapXZ": "MapCoords",
    "LHScriptPramX_c_": "LHScript",
    "LHScriptCommandX_c_": "LHScript",
    "LHScriptX_c_": "LHScript",
    "LHSys": "LHSystem",
    "LHSys_field_0x70c4_t": "LHSystem",
    "LHSys_field_0x70c4_t_field_0x0_t": "LHSystem",
    "TextureFormat": "LH3DTexture",
    "MaterialProperties": "LH3DMaterial",
    "LH3DMaterial__RenderMode": "LH3DMaterial",
    "LHSprite": "LH3DSprite",
    "LHSpriteList": "LH3DSprite",
    "LH_USER_ID": "LHNetUser",
    "LHPacketHeader": "LHPacket",
    "InnerRoom": "TempleRoom",
    "LiquidParticleGroup": "LiquidParticle",
    "sparklecbstub__FP19LiquidParticleGroupUl": "LiquidParticle",
    "GGuidance__LastThings": "GGuidance",
    "NewCollide": "Collide",
    "NewCollide__Obj": "Collide",
    "NewCollideDescriptor": "Collide",
    "NewCollide__List": "Collide",
    "ObjectCircleIterator": "Collide",
    "Point2DCompare": "Collide",
    "IntersectIntervalCircle": "Collide",
    "std__pair__pNewCollide__Obj__std__set__pMobileWallHug": "Collide",
    "std__map__pNewCollide__Obj__std__set__pMobileWallHug_iterator": "Collide",
    "std__map__pNewCollide__Obj__std__set__pMobileWallHug_node_list": "Collide",
    "std__map__pNewCollide__Obj__std__set__pMobileWallHug": "Collide",
    "SubCollideBlockPos": "Collide",
    "std__map__SubCollideBlockPosPNewCollide3Obj": "Collide",
    "std__map__SubCollideBlockPosPNewCollide3Obj_iterator": "Collide",
    "CircleHugStateInfo_field_0x44_node_list": "Collide",
    "LinearSquareSweepStruct": "Collide",
    "CircleHugInfo": "Collide",
    "LinearSquareSweepStruct": "Collide",
    "CircleHugStateInfoT": "Collide",
    "MeshIntersect": "Collide",
    "std__pair__pMobileWallHug__ulong": "Collide",
    "std__map__pMobileWallHug__ulong_node": "Collide",
    "std__map__pMobileWallHug__ulong_node_list": "Collide",
    "std__map__pMobileWallHug__ulong": "Collide",
    "std__set__pMobileWallHug_node": "Collide",
    "std__set__pMobileWallHug_node_list": "Collide",
    "std__set__pMobileWallHug": "Collide",
    "GMoveBy": "MobileWallHug",
    "Zoomer3d": "Zoomer",
    "SpellIcon__TChargingData": "SpellIcon",
    "WorshipTotem__TChargingData": "WorshipTotem",
    "EffectNumbers": "EffectValues",
    "Town_field_0x9fc": "Town",
    "TownArtifact": "Artifact",
    "GTownDesireFunction": "TownDesire",
    "LandBlock": "Landscape",
    "LandCell": "Landscape",
    "HandFX": "PSysHandFX",
    "Morphable_field_0x4314_t": "Morphable",
    "CHand__State__Named": "CHand",
    "CreatureDesiresSource": "CreatureDesires",
    "LH3DCreature_field_0x5184": "LH3DCreature",
    "LHDynamicQueue_pLHNetEvent_": "LHNetEvent",
    "LHDynamicQueueNode_pLHNetEvent_": "LHNetEvent",
    "HLineData": "SetupHLineGraph",
    "VBarData": "SetupVBarGraph",
    "Remove__VBarDataList": "SetupVBarGraph",
    "LH3DHair_field_0x34": "LH3DHair",
    "LH3DWay__Running": "LH3DWay",
    "Living__StateTableSubEntry": "Living",
    "Living__StateTableSubEntryState": "Living",
    "Living__StateTableSubEntryEntryState": "Living",
    "Living__StateTableEntry": "Living",
    "LivingAction": "Living",
    "LivingDLList": "Living",
    "Villager__StateTable": "Villager",
    "Animal__StateTable": "Animal",
    "ControlHandUpdateInfo": "CHand",
    "CreatureActionContextStart": "CreatureContext",
    "CreatureActionContext": "CreatureContext",
    "PreviousActionContextStack": "CreatureContext",
    "PreviousContextStack": "CreatureContext",
    "CreatureInnatePersonality": "CreatureMental",
    "CreaturePerceivedPlayerDesires": "CreatureAttitudeToPlayer",
    "CreaturePerceivedPlayerDesires_field_0x15c": "CreatureAttitudeToPlayer",
    "CreatureAttitudeToPlayer_field_0x1da4": "CreatureAttitudeToPlayer",
    "CreatureHelpState": "CreatureHelp",
    "CreatureHelpStackEntry": "CreatureHelp",
    "CreatureActionOpinions": "CreatureAction",
    "GestureSystemPacketData": "GestureSystem",
    "CreatureLookState": "CreatureLook",
    "CreatureInterestingThingToLookAt": "CreatureLook",
    "CreaturePlanState": "CreaturePlan",
    "DecisionTreeAgenda": "CreatureDecision",
    "DecisionTreeCollection": "CreatureDecision",
    "DecisionTreeAgendas": "CreatureDecision",
    "DecisionTree": "CreatureDecision",
    "DecisionTreeNode": "CreatureDecision",
    "AttributeTest": "CreatureDecision",
    "LHSegmentDesc": "LHSegment",
    "MultiChild": "MultiMapFixed",
    "MultiChildList": "MultiMapFixed",
    "PhysOb": "PhysicsObject",
    "CreatureFaceState": "CreatureFace",
    "LH3DAnimSet": "LH3DAnim",
    "CatInfo": "LH3DAnim",
    "CAnim": "LH3DAnim",
    "CFrame": "LH3DAnim",
    "CFrameData": "LH3DAnim",
    "AnimInfo": "LH3DAnim",
    "ANM_BaseHeader": "LH3DAnim",
    "MapCell": "Map",
    "MapCellIterator": "Map",
    "AgeToScale": "Creature",
    "DesireSort": "TownDesire",
    "ReactionDoneWhen": "Villager",
    "FootprintData": "Fixed",
    "BookmarkGraphic": "Bookmark",
    "CHand__State": "CHand",
    "LHSprite__Texels": "LH3DSprite",
    "DrawingObjectVftable": "DrawingObject",
    "NeedsBiggerText__Fv": "GatheringText",
    "GetMidTextSize__Fv": "GatheringText",
    "GetSmallTextSize__Fv": "GatheringText",
    "TurnOffMenu": "SetupThing",
    "LHRand__FlRU": "Random",
    "Random__Fff": "Random",
    "LHFileLength": "LHFile",
    "LHLoadData": "LHFile",
    "SetTurnOffMouseMove__Fb": "LHMouse",
    "DrawAndClip__F16D3DPRIMITIVETYPEUlP8Vertex3DUlPUsUl": "LH3DRender",
    "DrawAndClip2D__F16D3DPRIMITIVETYPEUlP8Vertex3DUlPUsUl": "LH3DRender",
    "ConfigGetFPS__Fv": "LH3DRender",
    "Report3D__FPCce": "LH3DRender",
    "ScanParameters__Fv": "PCMain",
    "IsACmdLineString__FPcPCc": "PCMain",
    "operator_new": "LHMemory",
    "__nw__FUl": "LHMemory",
    "__dl__FPv": "LHMemory",
    "__construct_new_array": "LHMemory",
    "__destroy_new_array": "LHMemory",
    "CHAR2WCHAR__FPc": "Utils",
    "RequestChangeTexture__FP6Object": "Object",
    "DoWallHuggerLookahead__Fv": "MobileWallHug",
    "Resolve__26IntersectIntervalCircle_0_Fv": "MobileWallHug",
    "Resolve__26IntersectIntervalCircle_1_Fv": "MobileWallHug",
    "get_villager_state_table": "Villager",
    "hypotenuse__Fll": "LHMath",
    "LHArcTan__Fll": "LHMath",
    "ConvertMapCoordsToPoint2D__FRC9MapCoords": "MapCoords",
    "stop_draw_sprite_to_screen__Fv": "MapCoords",
    "peerStartListingGames": "LHLobby",
    "LHJoypads": "LHJoypad",
    "FrameInfoLinkedList": "LHSystem",
    "LHConvert": "LHSystem",
}

unportable_dev_filepaths = released_filepaths_from_strings.union(guessed_filepaths)
dev_filepaths = {BWPath(str(a.parent).lower().replace("c:", "C:").replace("/mp/", "/").replace("\\mp\\", "\\")) / a.name for a in unportable_dev_filepaths}

def filter_paths(path: BWPath) -> BWPath:
    # Define parts to remove
    parts_to_remove = {'debug', 'release', 'mfcdebug', 'development', 'released', 'headers', 'mp'}
    # Convert to lower case and filter parts
    filtered_parts = [
        part.lower() for part in path.parts
        if part.lower() not in parts_to_remove and not re.match(r'version \d+\.\d+', part.lower()) and not re.match(r'ver\d+\.\d+', part.lower())
    ]
    return BWPath(*filtered_parts)


def get_project_paths() -> set[BWPath]:
    relatives = map(lambda x: x.relative_to(BWPath(r"C:\dev")).parent, dev_filepaths)
    debug_release_stripped = map(filter_paths, relatives)

    return set(debug_release_stripped)


def map_projects_to_object_files() -> dict[BWPath, set[BWPath]]:
    projects = defaultdict(set)
    project_paths = get_project_paths()
    for path in dev_filepaths:
        filtered_path = filter_paths(path.relative_to(BWPath(r"C:\dev")).parent)
        object_file = path.stem + ".obj"
        if filtered_path in project_paths:
            projects[filtered_path].add(object_file)
    return dict(projects)

def get_object_file_base_names() -> set[str]:
    return {i.stem for i in dev_filepaths}
