# strings *.{exe,dll} Data/HelpSprite/markevil.hd Audio/SFX/Game/*.sad Audio/SFX/Creature/*.sad 'Plug Ins'/*.dll Profiles/Backup/*{.dll,.exe} | grep -i 'c:\\dev' | sort | uniq -i | less
import re
from pathlib import PureWindowsPath as BWPath, Path
from collections import defaultdict
from demangler import demangle_type
from utils import LH_COLLECTION_TEMPLATES

released_sinits_in_lhall = {
    "__sinit_LHGenLog_cpp",
    "__sinit_LHLogMac_cpp",
    "__sinit_LHFilePath_cpp",
    "__sinit_LHFile_cpp",
    "__sinit_LHParser_cpp",
    "__sinit_LHText_cpp",
    "__sinit_LHSystem_cpp",
    "__sinit_LHSprite_cpp",
    "__sinit_LHScreen_cpp",
    "__sinit_LHMemoryLeak_cpp",
    "__sinit_LHAudioWave_cpp",
    "__sinit_LH3DFade_cpp",
    "__sinit_LHAudioSystem_cpp",
    "__sinit_LHAudioSample_cpp",
    "__sinit_LHAudioRedbook_cpp",
    "__sinit_LHAudioMusic_cpp",
    "__sinit_LH3DFragMesh_cpp",
    "__sinit_LH3DAnimation_cpp",
    "__sinit_LHAudioMidi_cpp",
    "__sinit_LHAudioHeap_cpp",
    "__sinit_LHAudioBank_cpp",
    "__sinit_LHAudioAtmos_cpp",
    "__sinit_LHTransport_cpp",
    "__sinit_LHTCPServerListener_cpp",
    "__sinit_LHSocket_cpp",
    "__sinit_LHSession_cpp",
    "__sinit_LHServerListener_cpp",
    "__sinit_LHPlayer_cpp",
    "__sinit_LHPacketisableObject_cpp",
    "__sinit_LHNetUtils_cpp",
    "__sinit_LHNetUser_cpp",
    "__sinit_LHNetTypes_cpp",
    "__sinit_LHNetEvent_cpp",
    "__sinit_LHMessageServer_cpp",
    "__sinit_LHLobbyServer_cpp",
    "__sinit_LHLobby_cpp",
    "__sinit_LHConnectionServer_cpp",
    "__sinit_LHConnection_cpp",
    "__sinit_LHChannel_cpp",
    "__sinit_LHDLL_cpp",
    "__sinit_LH3DWeather_cpp",
    "__sinit_LH3DWay_cpp",
    "__sinit_LH3DVideo_cpp",
    "__sinit_LH3DTexture_cpp",
    "__sinit_LH3DTech_cpp",
    "__sinit_LH3DDynamicLight_cpp",
    "__sinit_LH3DSmoke_cpp",
    "__sinit_LH3DSky_cpp",
    "__sinit_LH3DDivers_cpp",
    "__sinit_LH3DRender_cpp",
    "__sinit_LH3DPrimitive_cpp",
    "__sinit_LH3DCitadel_cpp",
    "__sinit_LH3DObject_cpp",
    "__sinit_LH3DMeshIntersect_cpp",
    "__sinit_LH3DMesh_cpp",
    "__sinit_LH3DMenu_cpp",
    "__sinit_LH3DIsland_cpp",
    "__sinit_LH3DHair_cpp",
}

released_sinits_in_black_white = {
    "__sinit_DisplayPicker_cpp",
    "__sinit_JCGameBlock_cpp",
    "__sinit_BWGameSpy_cpp",
    "__sinit_frontend_cpp",
    "__sinit_WorshipTotem_cpp",
    "__sinit_Worship_cpp",
    "__sinit_WorldRoom_cpp",
    "__sinit_WeatherRain_cpp",
    "__sinit_VillagerCivic_cpp",
    "__sinit_Game_cpp",
    "__sinit_TempleRoom_cpp",
    "__sinit_Temple_cpp",
    "__sinit_SpellShield_cpp",
    "__sinit_SpellSeed_cpp",
    "__sinit_SpellIcon_cpp",
    "__sinit_SpellFlock_cpp",
    "__sinit_Spell_cpp",
    "__sinit_SoundMap_cpp",
    "__sinit_SoundConfirmation_cpp",
    "__sinit_Setup_cpp",
    "__sinit_ScriptManage_cpp",
    "__sinit_ScriptHighlight_cpp",
    "__sinit_SaveGameRoom_cpp",
    "__sinit_RandomBuildingPlacement_cpp",
    "__sinit_PlayerProfile_cpp",
    "__sinit_PlayerActions_cpp",
    "__sinit_PlayerAction_cpp",
    "__sinit_Player_cpp",
    "__sinit_PlaceSupport_cpp",
    "__sinit_PSysTornado_cpp",
    "__sinit_PSysSound_cpp",
    "__sinit_PSysShield_cpp",
    "__sinit_PSysSave_cpp",
    "__sinit_PSysRenderParticle_cpp",
    "__sinit_PSysProperties_cpp",
    "__sinit_PSysPCreator_cpp",
    "__sinit_PSysModifiers_cpp",
    "__sinit_PSysMagicSystem_cpp",
    "__sinit_PSysLocal_cpp",
    "__sinit_PSysLoad_cpp",
    "__sinit_PSysLightning_cpp",
    "__sinit_PSysInterface_cpp",
    "__sinit_PSysHandFX_cpp",
    "__sinit_PSysGesture_cpp",
    "__sinit_PSysGeom_cpp",
    "__sinit_PSysFlock_cpp",
    "__sinit_PSysFireball_cpp",
    "__sinit_PSysExplosion_cpp",
    "__sinit_PSysEvents_cpp",
    "__sinit_PSysEditor_cpp",
    "__sinit_PSysDraw_cpp",
    "__sinit_PSysCreature_cpp",
    "__sinit_PSysBeam_cpp",
    "__sinit_PSysBaseModifiers_cpp",
    "__sinit_PSysBase_cpp",
    "__sinit_PSysAtomCore_cpp",
    "__sinit_PSys3d_cpp",
    "__sinit_PCInput_cpp",
    "__sinit_Object_cpp",
    "__sinit_MobileWallHug_cpp",
    "__sinit_MagicVortex_cpp",
    "__sinit_MagicTeleport_cpp",
    "__sinit_MPFELogin_cpp",
    "__sinit_MPFEFindGame_cpp",
    "__sinit_MPFEDatabase_cpp",
    "__sinit_MPFEConnectionStatus_cpp",
    "__sinit_MPFEChooseConnection_cpp",
    "__sinit_MPFEChannelSelector_cpp",
    "__sinit_MPFEChannelData_cpp",
    "__sinit_Living_cpp",
    "__sinit_ServerLandscapeMap_cpp",
    "__sinit_Landscape_cpp",
    "__sinit_LandFeature_cpp",
    "__sinit_LandBalance_cpp",
    "__sinit_LHNetBase_cpp",
    "__sinit_JCMisc_cpp",
    "__sinit_InterfaceMessage_cpp",
    "__sinit_InterfaceAction_cpp",
    "__sinit_Interface_cpp",
    "__sinit_alexmfc_cpp",
    "__sinit_HelpText_cpp",
    "__sinit_HelpSystem_cpp",
    "__sinit_helpdude_cpp",
    "__sinit_HandStateNormal_cpp",
    "__sinit_HandStateHolding_cpp",
    "__sinit_HandStateGrain_cpp",
    "__sinit_GatheringText_cpp",
    "__sinit_GatheringInterface_cpp",
    "__sinit_GameStats_cpp",
    "__sinit_GameOSFile_cpp",
    "__sinit_GameInfo_cpp",
    "__sinit_GameArea_cpp",
    "__sinit_GJSpline_cpp",
    "__sinit_GJProperty_cpp",
    "__sinit_GJPersistent_cpp",
    "__sinit_GJBaseUtils_cpp",
    "__sinit_EditorIconBase_cpp",
    "__sinit_DialogBoxKeyBinding_cpp",
    "__sinit_DanceLight_cpp",
    "__sinit_CreditText_cpp",
    "__sinit_CreatureSubActions_cpp",
    "__sinit_CreatureRoomCamera_cpp",
    "__sinit_CreatureRoom_cpp",
    "__sinit_CreatureReceiveSpell_cpp",
    "__sinit_CreatureMentalSaveAndLoad_cpp",
    "__sinit_CreatureMentalExploration_cpp",
    "__sinit_CreatureHelp_cpp",
    "__sinit_Creature3D_cpp",
    "__sinit_Creature_cpp",
    "__sinit_ControlMap_cpp",
    "__sinit_ControlHand_cpp",
    "__sinit_CitadelHeart_cpp",
    "__sinit_ChallengeRoom_cpp",
    "__sinit_CameraModeNew3_cpp",
    #"__sinit_camerahelp_cpp",
    "__sinit_BWLan_cpp",
    "__sinit_Debug_cpp",
    "__sinit_ViscousLiquid_cpp",
    "__sinit_VirtualInfluence_cpp",
    "__sinit_SpreadEffect_cpp",
    "__sinit_SpookyVoices_cpp",
    "__sinit_SecretCreature_cpp",
    "__sinit_Reaction_cpp",
    "__sinit_puzzlegame_cpp",
    "__sinit_Pot_cpp",
    "__sinit_PhysicsObject_cpp",
    "__sinit_PBall_cpp",
    "__sinit_OOSDebug_cpp",
    "__sinit_Network_cpp",
    "__sinit_MusicMood_cpp",
    "__sinit_logo_cpp",
    "__sinit_Influence_cpp",
    "__sinit_Footpath_cpp",
    "__sinit_FishFarm_cpp",
    "__sinit_FireFly_cpp",
    "__sinit_Field_cpp",
    "__sinit_ExclusionEditor_cpp",
    "__sinit_Draws_cpp",
    "__sinit_Config_cpp",
    "__sinit_Utils_cpp",
    "__sinit_Belief_cpp",
    "__sinit_Artifact_cpp",
    "__sinit_Alignment_cpp",
}

released_filepaths_from_strings = {
    BWPath(r"C:\Dev\libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DP3.cpp"),
    BWPath(r"c:\dev\libs\lionhead\lh3dlib\development\mfcdebug\lh3damemory.obj"),
    # BWPath(r"C:\Dev\black language\Script Library\Debug\ScriptLibraryD.pdb"),
    BWPath(r"c:\dev\black language\script library\scriptmachine.cpp"),
    BWPath(r"c:\dev\black language\script library\scriptmachine.h"),
    # BWPath(r"C:\dev\Black Plug Ins\Language Library\Debug\LanguageD.pdb"),
    BWPath(r"C:\Dev\black\SoundAction.h"),
    BWPath(r"C:\Dev\black\SoundAlignment.h"),
    BWPath(r"C:\Dev\black\SoundObject.h"),
    BWPath(r"C:\Dev\black\SoundSize.h"),
    BWPath(r"C:\Dev\black\SoundSurface.h"),
    # BWPath(r"c:\DEV\LIBS\LHALL\RELEASED\HEADERS\LHScreen.h"),
    BWPath(r"C:\DEV\LIBS\LHALL\RELEASED\HEADERS\LHTemplate.h"),
    BWPath(r"c:\DEV\LIBS\LHALL\RELEASED\HEADERS\LHTimer.h"),
    BWPath(r"C:\DEV\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DRender.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DTech.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DTech.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHMatrix.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHPoint.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHMath.h"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioAtmos.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioBank.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioHeap.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioMidi.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioMusic.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioRedbook.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioSample.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioSystem.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LHAudioWave.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LH_AudioBank.cpp"),
    BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\LH_SamplePlayOptions.cpp"),
    # BWPath(r"C:\dev\LIBS\LIONHEAD\LHAUDIO\VER7.0\Release\LHaudiodllR.pdb"),
    # BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\Debug\LHDialogLib.pdb"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\LHCameraParamsDialog.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\LHDialogLib.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\LHEditDialog.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\LHEditDialogSizable.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\LHProgressDialog.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\LHSystemSpecDialog.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHDialogLib\VERSION 1.0\LHSystemSpecSummaryDialog.cpp"),
    BWPath(r"C:\Dev\LIBS\Lionhead\LHDLL\VER1.0\LHDLL.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHFILE\VER3.0\LHSegment.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHFILE\VER3.0\LHFile.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\LHFILE\VER3.0\LHFilePath.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHFILE\VER3.0\LHOSFile.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHFILE\VER3.0\Archive.cpp"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHFILE\VER3.0\LHParser.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHFlic.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHHeap2.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHMemoryLeak.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHMouse.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHScreen.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHScript.cpp"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHWin.cpp"),
    BWPath(r"C:\dev\libs\LIONHEAD\LHLog\VER4.0\LHAssert.cpp"),
    BWPath(r"C:\dev\libs\LIONHEAD\LHLog\VER4.0\LHGenLog.cpp"),
    BWPath(r"C:\dev\libs\LIONHEAD\LHLog\VER4.0\LHLogProps.cpp"),
    BWPath(r"C:\dev\libs\LIONHEAD\LHLog\VER4.0\LHVersion.cpp"),
    BWPath(r"C:\dev\libs\LIONHEAD\LHLog\VER4.0\LogUtils.cpp"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHConnectionServer.cpp"),
    # BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\Release\LHMultiplayerR.pdb"),
    BWPath(r"C:\dev\MP\Black\Abode.cpp"),
    BWPath(r"C:\dev\MP\Black\Abode.h"),
    BWPath(r"C:\dev\MP\Black\alexmfc.cpp"),
    BWPath(r"C:\dev\MP\Black\Alignment.cpp"),
    BWPath(r"C:\dev\MP\Black\Alignment.h"),
    BWPath(r"C:\dev\MP\Black\AnimalAnimation.cpp"),
    BWPath(r"C:\dev\MP\Black\Animal.cpp"),
    BWPath(r"C:\dev\MP\Black\Animal.h"),
    BWPath(r"C:\dev\MP\Black\AnimalBat.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalCow.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalDove.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalLeopard.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalLion.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalSpellWolf.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalTiger.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalWolf.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimalReaction.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimatedStatic.cpp"),
    BWPath(r"C:\dev\MP\Black\AnimatedStatic.h"),
    BWPath(r"C:\dev\MP\Black\Animations.cpp"),
    BWPath(r"C:\dev\MP\Black\Arena.cpp"),
    BWPath(r"C:\dev\MP\Black\Arrow.cpp"),
    BWPath(r"C:\dev\MP\Black\Arrow.h"),
    BWPath(r"C:\dev\MP\Black\Artifact.cpp"),
    BWPath(r"C:\dev\MP\Black\Audio.cpp"),
    BWPath(r"C:\dev\MP\Black\AudioMusicThing.cpp"),
    BWPath(r"C:\dev\MP\Black\audiotag.cpp"),
    BWPath(r"C:\dev\MP\Black\Balance.cpp"),
    BWPath(r"C:\dev\MP\Black\Ball.cpp"),
    BWPath(r"C:\dev\MP\Black\Ball.h"),
    BWPath(r"C:\dev\MP\Black\Belief.cpp"),
    BWPath(r"C:\dev\MP\Black\Belief.h"),
    BWPath(r"C:\dev\MP\Black\BigForest.cpp"),
    BWPath(r"C:\dev\MP\Black\BigForest.h"),
    BWPath(r"C:\dev\MP\Black\Bonfire.cpp"),
    BWPath(r"C:\dev\MP\Black\Bookmark.cpp"),
    BWPath(r"C:\dev\MP\Black\BuildingSite.cpp"),
    BWPath(r"C:\dev\MP\Black\BWGameSpy.cpp"),
    BWPath(r"C:\dev\MP\Black\BWLan.cpp"),
    BWPath(r"C:\dev\MP\Black\Camera.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraEditor.cpp"),
    # BWPath(r"C:\dev\MP\Black\camerahelp.cpp"),
    # BWPath(r"C:\dev\MP\Black\camerahelp.h"),
    BWPath(r"C:\dev\MP\Black\CameraModeCitadel.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModeDance.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModeFlyAndClick.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModeFollow.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModeFollowHeading.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModeNew3.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModePath.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModeScript.cpp"),
    BWPath(r"C:\dev\MP\Black\CameraModeTwoObjects.cpp"),
    BWPath(r"C:\dev\MP\Black\ChallengeRoom.cpp"),
    BWPath(r"C:\dev\MP\Black\Citadel.cpp"),
    BWPath(r"C:\dev\MP\Black\Citadel.h"),
    BWPath(r"C:\dev\MP\Black\CitadelHeart.cpp"),
    BWPath(r"C:\dev\MP\Black\CitadelHeart.h"),
    BWPath(r"C:\dev\MP\Black\CitadelPart.h"),
    BWPath(r"C:\dev\MP\Black\citadelpeople.cpp"),
    BWPath(r"C:\dev\MP\Black\Collide.cpp"),
    BWPath(r"C:\dev\MP\Black\Config.cpp"),
    BWPath(r"C:\dev\MP\Black\Container.h"),
    BWPath(r"C:\dev\MP\Black\ControlHand.cpp"),
    BWPath(r"C:\dev\MP\Black\Creature3D.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureAction.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureAction.h"),
    BWPath(r"C:\dev\MP\Black\CreatureAttitudeToCreature.cpp"),
    BWPath(r"C:\dev\MP\Black\Creature.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureDevelopment.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureDirectControl.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureFace.cpp"),
    BWPath(r"C:\dev\MP\Black\Creature.h"),
    BWPath(r"C:\dev\MP\Black\CreatureHelp.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureInitialLesson.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureLessonChooser.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureLook.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalAttributeTest.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalBelief.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalBeliefs.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalDesire.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalDesire.h"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalDesireSource.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalDesireSource.h"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalExploration.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalLearnAction.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalLearnAction.h"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalLearn.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalMisc.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMentalSaveAndLoad.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMimic.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureMimic.h"),
    BWPath(r"C:\dev\MP\Black\CreatureMorph.cpp"),
    BWPath(r"C:\dev\MP\Black\CreaturePen.cpp"),
    BWPath(r"C:\dev\MP\Black\CreaturePen.h"),
    BWPath(r"C:\dev\MP\Black\CreaturePhysical.cpp"),
    BWPath(r"C:\dev\MP\Black\CreaturePlan.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureReaction.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureReceiveSpell.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureRoom.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureScript.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureSelect.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureSubAction.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureSubActions.cpp"),
    BWPath(r"C:\dev\MP\Black\CreatureWhatToDoNext.cpp"),
    BWPath(r"C:\dev\MP\Black\Creche.cpp"),
    BWPath(r"C:\dev\MP\Black\Dance.cpp"),
    BWPath(r"C:\dev\MP\Black\Dance.h"),
    BWPath(r"C:\dev\MP\Black\DanceKey.cpp"),
    BWPath(r"C:\dev\MP\Black\DanceShape.cpp"),
    BWPath(r"C:\dev\MP\Black\DeadTree.cpp"),
    BWPath(r"C:\dev\MP\Black\DialogBoxKeyBinding.cpp"),
    BWPath(r"C:\dev\MP\Black\DialogBoxMain.cpp"),
    BWPath(r"C:\dev\MP\Black\DialogBoxOptions.cpp"),
    BWPath(r"C:\dev\MP\Black\DialogBoxSaveMessage.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorAnim.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorHug.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorIcon.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorIconBase.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorIconGraph.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorIconPDM.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorIconPDM.h"),
    BWPath(r"C:\dev\MP\Black\EditorIconPlace.cpp"),
    BWPath(r"C:\dev\MP\Black\EditorIconStrip.cpp"),
    BWPath(r"C:\dev\MP\Black\Effect.h"),
    BWPath(r"C:\dev\MP\Black\ExtraFeatures.cpp"),
    BWPath(r"C:\dev\MP\Black\fallingspell.cpp"),
    BWPath(r"C:\dev\MP\Black\Feature.cpp"),
    BWPath(r"C:\dev\MP\Black\Feature.h"),
    BWPath(r"C:\dev\MP\Black\Field.cpp"),
    BWPath(r"C:\dev\MP\Black\Field.h"),
    BWPath(r"C:\dev\MP\Black\FireFly.cpp"),
    BWPath(r"C:\dev\MP\Black\FishFarm.cpp"),
    BWPath(r"C:\dev\MP\Black\FishFarm.h"),
    BWPath(r"C:\dev\MP\Black\Fixed.cpp"),
    BWPath(r"C:\dev\MP\Black\Fixed.h"),
    BWPath(r"C:\dev\MP\Black\Flock.cpp"),
    # BWPath(r"C:\dev\MP\Black\FootBall.cpp"),
    BWPath(r"C:\dev\MP\Black\Football.h"),
    BWPath(r"C:\dev\MP\Black\Footpath.cpp"),
    BWPath(r"C:\dev\MP\Black\Forest.cpp"),
    BWPath(r"C:\dev\MP\Black\frontend.cpp"),
    BWPath(r"C:\dev\MP\Black\FrontEndSetupGame.cpp"),
    BWPath(r"C:\dev\MP\Black\FrontEndSetupMultiplayer.cpp"),
    BWPath(r"C:\dev\MP\Black\Furniture.cpp"),
    BWPath(r"C:\dev\MP\Black\Furniture.h"),
    BWPath(r"C:\dev\MP\Black\GameArea.h"),
    BWPath(r"C:\dev\MP\Black\Game.cpp"),
    BWPath(r"C:\dev\MP\Black\GameOSFile.cpp"),
    BWPath(r"C:\dev\MP\Black\GameOSFile.h"),
    BWPath(r"C:\dev\MP\Black\GameStats.cpp"),
    BWPath(r"C:\dev\MP\Black\GameStatsFrontEnd.cpp"),
    BWPath(r"C:\dev\MP\Black\GameStatsList.h"),
    BWPath(r"C:\dev\MP\Black\GatheringInterface.cpp"),
    BWPath(r"C:\dev\MP\Black\GatheringInterface.h"),
    BWPath(r"C:\dev\MP\Black\GenerateCreatureHTML.cpp"),
    BWPath(r"C:\dev\MP\Black\GJBaseUtils.inl"),
    BWPath(r"C:\dev\MP\Black\GJVnoise.cpp"),
    BWPath(r"C:\dev\MP\Black\GJPersistent.cpp"),
    BWPath(r"C:\dev\MP\Black\GJProperty.cpp"),
    BWPath(r"C:\dev\MP\Black\GJProperty.h"),
    BWPath(r"C:\dev\MP\Black\Global.cpp"),
    BWPath(r"C:\dev\MP\Black\GraveYard.cpp"),
    BWPath(r"C:\dev\MP\Black\GroupBehaviour.cpp"),
    BWPath(r"C:\dev\MP\Black\GSLobbybox.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpDudeControl.cpp"),
    BWPath(r"C:\dev\MP\Black\helpdude.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpDudeLipSync.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpEditor.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpProfile.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpSpirit.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpSpirit.h"),
    BWPath(r"C:\dev\MP\Black\HelpSystemBubble.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpSystem.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpSystem.h"),
    BWPath(r"C:\dev\MP\Black\HelpSystemToolTips.h"),
    BWPath(r"C:\dev\MP\Black\HelpText.cpp"),
    BWPath(r"C:\dev\MP\Black\HelpText.h"),
    BWPath(r"C:\dev\MP\Black\Influence.cpp"),
    BWPath(r"C:\dev\MP\Black\Influence.h"),
    BWPath(r"C:\dev\MP\Black\Interface.cpp"),
    BWPath(r"C:\dev\MP\Black\InterfaceImmersion.cpp"),
    BWPath(r"C:\dev\MP\Black\InterfaceMessage.cpp"),
    BWPath(r"C:\dev\MP\Black\InterfaceStatus.cpp"),
    BWPath(r"C:\dev\MP\Black\IpSpecialDialog.cpp"),
    BWPath(r"C:\dev\MP\Black\JCGameBlock.cpp"),
    BWPath(r"C:\dev\MP\Black\JCMisc.cpp"),
    BWPath(r"C:\dev\MP\Black\Job.h"),
    BWPath(r"C:\dev\MP\Black\KeyBuffer.cpp"),
    BWPath(r"C:\dev\MP\Black\LandAlignement.cpp"),
    BWPath(r"C:\dev\MP\Black\LandFeature.cpp"),
    BWPath(r"C:\dev\MP\Black\Landscape.cpp"),
    BWPath(r"C:\dev\MP\Black\LevelOfDetail.cpp"),
    BWPath(r"C:\dev\MP\Black\LHInetWeather.cpp"),
    BWPath(r"C:\dev\MP\Black\LHNetBase.cpp"),
    BWPath(r"C:\dev\MP\Black\Living.cpp"),
    BWPath(r"C:\dev\MP\Black\Living.h"),
    BWPath(r"C:\dev\MP\Black\LivingProjectile.cpp"),
    BWPath(r"C:\dev\MP\Black\LivingReaction.cpp"),
    BWPath(r"C:\dev\MP\Black\LoaderAnon.cpp"),
    BWPath(r"C:\dev\MP\Black\LoadingScreen.cpp"),
    BWPath(r"C:\dev\MP\Black\Lobbybox.cpp"),
    BWPath(r"C:\dev\MP\Black\logo.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicCreatureSpellInfo.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicCreatureSpellInfo.h"),
    BWPath(r"C:\dev\MP\Black\MagicFood.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicFoodInfo.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicFoodInfo.h"),
    BWPath(r"C:\dev\MP\Black\MagicForestInfo.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicForestInfo.h"),
    BWPath(r"C:\dev\MP\Black\MagicInfo.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicInfo.h"),
    BWPath(r"C:\dev\MP\Black\MagicShieldInfo.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicShieldInfo.h"),
    BWPath(r"C:\dev\MP\Black\MagicTeleport.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicTeleport.h"),
    BWPath(r"C:\dev\MP\Black\MagicTree.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicVortex.cpp"),
    BWPath(r"C:\dev\MP\Black\MagicVortex.h"),
    BWPath(r"C:\dev\MP\Black\MapCoords.cpp"),
    BWPath(r"C:\dev\MP\Black\Meeting.cpp"),
    BWPath(r"C:\dev\MP\Black\Mist.cpp"),
    BWPath(r"C:\dev\MP\Black\Mobile.h"),
    BWPath(r"C:\dev\MP\Black\MobileObject.cpp"),
    BWPath(r"C:\dev\MP\Black\MobileObject.h"),
    BWPath(r"C:\dev\MP\Black\MobileStatic.cpp"),
    BWPath(r"C:\dev\MP\Black\MobileStatic.h"),
    BWPath(r"C:\dev\MP\Black\MobileWallHug.cpp"),
    BWPath(r"C:\dev\MP\Black\MobileWallHug.h"),
    BWPath(r"C:\dev\MP\Black\MorphableObject.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEAlexDialog.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEAlexDialog.h"),
    BWPath(r"C:\dev\MP\Black\MPFEChannelData.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEChannelMessages.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEChannelSelector.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEChooseConnection.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEClanDetails.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEConditionMessages.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEFileTransfer.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEFindGame.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEGameStartMessages.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFELogin.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEMapMessages.cpp"),
    BWPath(r"C:\dev\MP\Black\MPFEPlayerDetails.cpp"),
    BWPath(r"C:\dev\MP\Black\MultiplayerDatabase.cpp"),
    BWPath(r"C:\dev\MP\Black\MusicMood.cpp"),
    BWPath(r"C:\dev\MP\Black\Network.cpp"),
    BWPath(r"C:\dev\MP\Black\Object.cpp"),
    BWPath(r"C:\dev\MP\Black\OOSDebug.cpp"),
    BWPath(r"C:\dev\MP\Black\Packet.cpp"),
    BWPath(r"C:\dev\MP\Black\ParticleContainer.cpp"),
    BWPath(r"C:\dev\MP\Black\PathCreator.cpp"),
    BWPath(r"C:\dev\MP\Black\PBall.cpp"),
    BWPath(r"C:\dev\MP\Black\PBall.h"),
    BWPath(r"C:\dev\MP\Black\PCInput.cpp"),
    BWPath(r"C:\dev\MP\Black\PCMain.cpp"),
    BWPath(r"C:\dev\MP\Black\PFootball.cpp"),
    BWPath(r"C:\dev\MP\Black\PFootball.h"),
    BWPath(r"C:\dev\MP\Black\PhysicsObject.cpp"),
    BWPath(r"C:\dev\MP\Black\PictureRoom.cpp"),
    BWPath(r"C:\dev\MP\Black\PlannedMultiMapFixed.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerAction.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerActions.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerComputer.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerComputerCreature.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerComputerInterface.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerComputerReact.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerComputerSpell.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerComputerTown.cpp"),
    BWPath(r"C:\dev\MP\Black\Player.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerMessage.cpp"),
    BWPath(r"C:\dev\MP\Black\PlayerProfile.h"),
    BWPath(r"C:\dev\MP\Black\PlaytimeDance.cpp"),
    BWPath(r"C:\dev\MP\Black\PlaytimeDance.h"),
    BWPath(r"C:\dev\MP\Black\Pot.cpp"),
    BWPath(r"C:\dev\MP\Black\Pot.h"),
    BWPath(r"C:\dev\MP\Black\PowerSpin.cpp"),
    BWPath(r"C:\dev\MP\Black\Prayer.h"),
    BWPath(r"C:\dev\MP\Black\PSys3d.cpp"),
    BWPath(r"C:\dev\MP\Black\PSys3d.h"),
    BWPath(r"C:\dev\MP\Black\PSysAtomCore.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysAtomCore.h"),
    BWPath(r"C:\dev\MP\Black\PSysCreature.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysExplosion.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysFireball.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysFireBall.h"),
    BWPath(r"C:\dev\MP\Black\PSysGeom.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysGesture.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysHandFX.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysHandFX.h"),
    BWPath(r"C:\dev\MP\Black\PSysInterface.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysLightning.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysMagicSystem.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysModifiers.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysPCreator.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysProperties.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysRenderParticle.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysShield.cpp"),
    BWPath(r"C:\dev\MP\Black\PSysTornado.cpp"),
    BWPath(r"C:\dev\MP\Black\puzzlegame.cpp"),
    BWPath(r"C:\dev\MP\Black\RandomBuildingPlacement.cpp"),
    BWPath(r"C:\dev\MP\Black\RandomBuildingPlacementDefence.cpp"),
    BWPath(r"C:\dev\MP\Black\Rank.cpp"),
    BWPath(r"C:\dev\MP\Black\Reaction.cpp"),
    BWPath(r"C:\dev\MP\Black\Reaction.h"),
    BWPath(r"C:\dev\MP\Black\Reward.cpp"),
    BWPath(r"C:\dev\MP\Black\reward.h"),
    BWPath(r"C:\dev\MP\Black\Rock.cpp"),
    BWPath(r"C:\dev\MP\Black\RoutePlan.cpp"),
    BWPath(r"C:\dev\MP\Black\SaveGameRoom.cpp"),
    BWPath(r"C:\dev\MP\Black\Scaffold.cpp"),
    BWPath(r"C:\dev\MP\Black\Scaffold.h"),
    BWPath(r"C:\dev\MP\Black\ScriptCamera.cpp"),
    BWPath(r"C:\dev\MP\Black\ScriptContainer.cpp"),
    BWPath(r"C:\dev\MP\Black\Script.cpp"),
    BWPath(r"C:\dev\MP\Black\ScriptCreateOrCall.cpp"),
    BWPath(r"C:\dev\MP\Black\ScriptFunctions.cpp"),
    BWPath(r"C:\dev\MP\Black\ScriptGFX.cpp"),
    BWPath(r"C:\dev\MP\Black\Script.h"),
    BWPath(r"C:\dev\MP\Black\ScriptHighlight.cpp"),
    BWPath(r"C:\dev\MP\Black\ScriptHighlight.h"),
    BWPath(r"C:\dev\MP\Black\ScriptMarker.cpp"),
    BWPath(r"C:\dev\MP\Black\ScriptTimer.cpp"),
    BWPath(r"C:\dev\MP\Black\Serialise.cpp"),
    BWPath(r"C:\dev\MP\Black\Serialise.h"),
    BWPath(r"C:\dev\MP\Black\ServerLandscapeMap.cpp"),
    BWPath(r"C:\dev\MP\Black\ServerLandscapeMap.h"),
    BWPath(r"C:\dev\MP\Black\Setup.cpp"),
    BWPath(r"C:\dev\MP\Black\ShowNeeds.cpp"),
    BWPath(r"C:\dev\MP\Black\ShowNeeds.h"),
    BWPath(r"C:\dev\MP\Black\SLLTemplate.h"),
    BWPath(r"C:\dev\MP\Black\SoundConfirmation.cpp"),
    BWPath(r"C:\dev\MP\Black\SoundGuidance.cpp"),
    BWPath(r"C:\dev\MP\Black\SoundGuidance.h"),
    BWPath(r"C:\dev\MP\Black\SoundMap.h"),
    BWPath(r"C:\dev\MP\Black\SoundTag.cpp"),
    BWPath(r"C:\dev\MP\Black\SpecialVillager.cpp"),
    BWPath(r"C:\dev\MP\Black\SpecialVillager.h"),
    BWPath(r"C:\dev\MP\Black\SpellDispenser.cpp"),
    BWPath(r"C:\dev\MP\Black\SpellFlock.cpp"),
    BWPath(r"C:\dev\MP\Black\SpellFlock.h"),
    BWPath(r"C:\dev\MP\Black\SpellFood.cpp"),
    BWPath(r"C:\dev\MP\Black\SpellForest.cpp"),
    BWPath(r"C:\dev\MP\Black\SpellIcon.cpp"),
    BWPath(r"C:\dev\MP\Black\SpellIcon.h"),
    BWPath(r"C:\dev\MP\Black\SpellSeed.cpp"),
    BWPath(r"C:\dev\MP\Black\SpellSeedInfo.h"),
    BWPath(r"C:\dev\MP\Black\SpellShield.cpp"),
    BWPath(r"C:\dev\MP\Black\SpellShield.h"),
    BWPath(r"C:\dev\MP\Black\SpookyVoices.cpp"),
    BWPath(r"C:\dev\MP\Black\SpookyVoices.h"),
    BWPath(r"C:\dev\MP\Black\SpotVisualInfo.h"),
    BWPath(r"C:\dev\MP\Black\SpreadEffect.cpp"),
    BWPath(r"C:\dev\MP\Black\StoragePit.cpp"),
    BWPath(r"C:\dev\MP\Black\Stream.cpp"),
    BWPath(r"C:\dev\MP\Black\StreetLantern.cpp"),
    BWPath(r"C:\dev\MP\Black\StreetLight.cpp"),
    BWPath(r"C:\dev\MP\Black\Temple.cpp"),
    BWPath(r"C:\dev\MP\Black\TempleEngine.cpp"),
    BWPath(r"C:\dev\MP\Black\TempleRoomAddText.cpp"),
    BWPath(r"C:\dev\MP\Black\TempleRoom.cpp"),
    BWPath(r"C:\dev\MP\Black\Terrain.h"),
    BWPath(r"C:\dev\MP\Black\TOMnavigator.cpp"),
    BWPath(r"C:\dev\MP\Black\Totem.cpp"),
    BWPath(r"C:\dev\MP\Black\TotemStatue.cpp"),
    BWPath(r"C:\dev\MP\Black\TotemStatue.h"),
    BWPath(r"C:\dev\MP\Black\TownAttitudeToCreature.cpp"),
    BWPath(r"C:\dev\MP\Black\TownCentre.cpp"),
    BWPath(r"C:\dev\MP\Black\Town.cpp"),
    BWPath(r"C:\dev\MP\Black\TownDesire.cpp"),
    BWPath(r"C:\dev\MP\Black\TownDesire.h"),
    BWPath(r"C:\dev\MP\Black\Town.h"),
    BWPath(r"C:\dev\MP\Black\TownSpellIcon.cpp"),
    BWPath(r"C:\dev\MP\Black\Tree.cpp"),
    BWPath(r"C:\dev\MP\Black\Tree.h"),
    BWPath(r"C:\dev\MP\Black\Tribe.h"),
    BWPath(r"C:\dev\MP\Black\Utils.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerChild.cpp"),
    BWPath(r"C:\dev\MP\Black\Villager.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerFireman.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerFisherman.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerFootball.cpp"),
    BWPath(r"C:\dev\MP\Black\Villager.h"),
    BWPath(r"C:\dev\MP\Black\VillagerCivic.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerHome.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerHousewife.cpp"),
    BWPath(r"C:\dev\MP\Black\villagernames.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerReaction.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerReactionToCreature.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerScript.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerStates.cpp"),
    BWPath(r"C:\dev\MP\Black\VillagerStates.h"),
    BWPath(r"C:\dev\MP\Black\ViscousLiquid.cpp"),
    BWPath(r"C:\dev\MP\Black\VortexSave.cpp"),
    BWPath(r"C:\dev\MP\Black\Wallhug.cpp"),
    BWPath(r"C:\dev\MP\Black\WayPoint.cpp"),
    BWPath(r"C:\dev\MP\Black\Weather.cpp"),
    BWPath(r"C:\dev\MP\Black\Weather.h"),
    BWPath(r"C:\dev\MP\Black\WeatherRain.cpp"),
    BWPath(r"C:\dev\MP\Black\WeatherThing.cpp"),
    BWPath(r"C:\dev\MP\Black\Whale.cpp"),
    BWPath(r"C:\dev\MP\Black\Wonder.cpp"),
    BWPath(r"C:\dev\MP\Black\Workshop.cpp"),
    BWPath(r"C:\dev\MP\Black\WorldRoom.cpp"),
    BWPath(r"C:\dev\MP\Black\Worship.cpp"),
    BWPath(r"C:\dev\MP\Black\Worship.h"),
    BWPath(r"C:\dev\MP\Black\WorshipSiteUpgrade.cpp"),
    BWPath(r"C:\dev\MP\Black\WorshipSiteUpgrade.h"),
    BWPath(r"C:\dev\MP\Black\WorshipSpellIcon.cpp"),
    BWPath(r"C:\dev\MP\Black\WorshipTotem.cpp"),
    # BWPath(r"C:\DEV\MP\LIBS\LHALL\RELEASED\HEADERS\LH3DDivers.h"),
    BWPath(r"C:\dev\MP\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHConnectionServer.cpp"),
    # BWPath(r"C:\dev\MP\Libs\LIONHEAD\LHMultiplayer\VER4.0\Release\LHMultiplayerR.pdb"),
    BWPath(r"C:\dev\setup\D3DInformation.cpp"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Mesh.l3d"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Blink_Left.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Blink_Right.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Displeased.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Head_Turn_LR.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Head_Turn_UD.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Hover.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Hover_Stable.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Point_Left_In.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Point_Left_UD.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Point_Right_In.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Point_Right_UD.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Sad.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Scared.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Smile.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Speak_AAA.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Speak_EEE.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Speak_OOO.anmW"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Stand.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Turn_Left.anm"),
    # BWPath(r"C:\dev\TESTBED\DATA\Demon_Turn_Right.anm"),
    BWPath(r"C:\Dev\tools\CreatureUpload\CreatureUploadDlg.cpp"),
    BWPath(r"C:\dev\Tools\Setup\Final Setup\D3DInformation.cpp"),
}

guessed_filepaths = {
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DMem.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHDDEnum.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DObject.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DMeshIntersect.cpp"), # Validated by existance of __sinit_LH3DMeshIntersect_cpp
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DMeshedObject.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DStaticObject.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DStaticMorphableObject.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DAnimatedObject.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DComplexObject.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DSpriteObject.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DMist.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DCitadel.h"),
    BWPath(r"C:\DEV\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DDivers.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHCoord.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHRegion.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHPixel.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHSurface.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DSprite.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LHText.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DAnim.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DIsland.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DLandscape.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DColor.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DHair.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DTexture.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DMaterial.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DMapCoords.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DSky.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DVertex.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DVertexGroup.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DPrimitive.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DStorm.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DSubMesh.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DMesh.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DSmoke.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DCamera.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DCameraChecker.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DBoundingBox.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DObjectHair.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DWay.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\PhysOb.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\Prss.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\Zoomer.h"),
    BWPath(r"C:\DEV\Libs\LIONHEAD\LH3DLIB\DEVELOPMENT\LH3DVideo.cpp"),

    BWPath(r"C:\Dev\Libs\LIONHEAD\LHFILE\VER3.0\LHReleasedFile.h"),
    BWPath(r"C:\Dev\Libs\LIONHEAD\LHFILE\VER3.0\LHReleasedOSFile.h"),

    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHTransportInfo.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHTransport.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHPacketisableObject.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHPlayer.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHServerPlayer.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHSocket.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHSocketTCP.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHSession.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHSerial.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHLobbyServer.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHMPServerStartInfo.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHLobby.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHConnection.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHNetUser.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHNetUtils.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHNetEvent.h"),
    BWPath(r"C:\dev\Libs\LIONHEAD\LHMultiplayer\VER4.0\LHPacket.h"),

    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHJoypad.h"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHKey.h"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHReturn.h"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHRand.h"),
    BWPath(r"C:\Dev\Libs\lionhead\lhlib\VER5.0\LHSystem.h"),

    BWPath(r"C:\DEV\LIBS\LHALL\RELEASED\HEADERS\VisitBlock.h"),
    BWPath(r"C:\DEV\LIBS\LHALL\RELEASED\HEADERS\RouteNode.h"),
    BWPath(r"C:\DEV\LIBS\LHALL\RELEASED\HEADERS\Route.h"),
    BWPath(r"C:\DEV\LIBS\LHALL\RELEASED\HEADERS\RPAvoid.h"),
    BWPath(r"C:\DEV\LIBS\LHALL\RELEASED\HEADERS\RPFollow.h"),
    BWPath(r"C:\DEV\LIBS\LHALL\RELEASED\HEADERS\RPlan.h"),
    BWPath(r"C:\DEV\LIBS\LHALL\RELEASED\HEADERS\RPHolder.h"),
    BWPath(r"C:\DEV\LIBS\LHALL\RELEASED\HEADERS\Heap.h"),

    BWPath(r"C:\Dev\black\Base.h"),
    BWPath(r"C:\Dev\black\BaseInfo.h"),
    BWPath(r"C:\Dev\black\LocalBase.h"),
    BWPath(r"C:\Dev\black\GameThing.h"),
    BWPath(r"C:\Dev\black\GameThingWithPos.h"),

    BWPath(r"C:\dev\Black\CameraHelp.h"),
    BWPath(r"C:\Dev\black\Bubble.h"),
    BWPath(r"C:\Dev\black\CameraExclusion.h"),
    BWPath(r"C:\Dev\black\CameraMode.h"),
    BWPath(r"C:\Dev\black\CameraModeFree.h"),
    BWPath(r"C:\Dev\Black\CameraModeCtrInteract.cpp"),
    BWPath(r"C:\Dev\Black\CameraModeNew.cpp"),
    BWPath(r"C:\Dev\Black\CameraModeNew1.cpp"),
    BWPath(r"C:\Dev\Black\CameraModeNew2.cpp"),
    BWPath(r"C:\Dev\black\ScriptedCamera.h"),
    BWPath(r"C:\Dev\black\BindableAction.h"),
    BWPath(r"C:\Dev\black\ControlMap.h"),
    BWPath(r"C:\Dev\black\Cow.h"),
    BWPath(r"C:\Dev\black\Climate.h"),
    BWPath(r"C:\Dev\black\CPUCheck.h"),
    BWPath(r"C:\Dev\black\CreatureActionsKnownAbout.h"),
    BWPath(r"C:\Dev\black\CreatureAgenda.h"),
    BWPath(r"C:\Dev\black\CreatureAttitudeToPlayer.h"),
    BWPath(r"C:\Dev\black\CreatureCommandState.h"),
    BWPath(r"C:\Dev\black\CreatureContext.h"),
    BWPath(r"C:\Dev\black\CreatureDatabase.h"),
    BWPath(r"C:\Dev\black\CreatureExplorationMap.h"),
    BWPath(r"C:\Dev\black\CreatureLearning.h"),
    BWPath(r"C:\Dev\black\CreatureMental.h"),
    BWPath(r"C:\Dev\black\CreatureMentalDebug.h"),
    BWPath(r"C:\Dev\black\CreatureObjectsInspected.h"),
    BWPath(r"C:\Dev\black\CreaturePreviousLesson.h"),
    BWPath(r"C:\Dev\black\CreatureRoomCamera.h"),
    BWPath(r"C:\Dev\black\CreatureVisionState.h"),
    BWPath(r"C:\Dev\black\DanceGroup.h"),
    BWPath(r"C:\Dev\black\DancePathInfo.h"),
    BWPath(r"C:\Dev\black\DataPath.h"),
    BWPath(r"C:\Dev\black\Data.h"),
    BWPath(r"C:\Dev\black\Debug.h"),
    BWPath(r"C:\Dev\black\DialogBoxBase.h"),
    BWPath(r"C:\Dev\black\DialogBoxImmersion.h"),
    BWPath(r"C:\Dev\black\DrawingObject.h"),
    BWPath(r"C:\Dev\black\EffectValues.h"),
    BWPath(r"C:\Dev\black\EarthQuake.h"),
    BWPath(r"C:\Dev\black\Flower.h"),
    BWPath(r"C:\Dev\black\FrontEnd.h"),
    BWPath(r"C:\Dev\black\AbodeInfo.h"),
    BWPath(r"C:\Dev\black\HistoryBox.h"),
    BWPath(r"C:\Dev\black\MultiplayerConditionBox.h"),
    BWPath(r"C:\Dev\black\EndGameBox.h"),
    BWPath(r"C:\Dev\black\StatsBox.h"),
    BWPath(r"C:\Dev\black\ChannelBox.h"),
    BWPath(r"C:\Dev\black\EditingDebugBox.h"),
    BWPath(r"C:\Dev\black\SetupMultiplayerMain.h"),
    BWPath(r"C:\Dev\black\SetupOnlineLandscapes.h"),
    BWPath(r"C:\Dev\black\SkipBox.h"),
    BWPath(r"C:\Dev\black\CDBox.h"),
    BWPath(r"C:\Dev\black\GatheringBox.h"),
    BWPath(r"C:\Dev\black\LoadingBox.h"),
    BWPath(r"C:\Dev\black\LobbyBox.h"),
    BWPath(r"C:\Dev\black\RegisterBox.h"),
    BWPath(r"C:\Dev\black\LoginBox.h"),
    BWPath(r"C:\Dev\black\TattooEditor.h"),
    BWPath(r"C:\Dev\black\NewProfileBox.h"),
    BWPath(r"C:\Dev\black\MainMenu.h"),
    BWPath(r"C:\Dev\black\ProfileEditor.h"),
    BWPath(r"C:\Dev\black\SkirmishGameBox.h"),
    BWPath(r"C:\Dev\black\SLobbyBox.h"),
    BWPath(r"C:\Dev\black\MobileStaticInfo.h"),
    BWPath(r"C:\Dev\black\Plasma.h"),
    BWPath(r"C:\Dev\black\Game3DObject.h"),
    BWPath(r"C:\Dev\black\BallInfo.h"),
    BWPath(r"C:\Dev\black\BigForestInfo.h"),
    BWPath(r"C:\Dev\black\CitadelHeartInfo.h"),
    BWPath(r"C:\Dev\black\CitadelPartInfo.h"),
    BWPath(r"C:\Dev\black\ContainerInfo.h"),
    BWPath(r"C:\Dev\black\CreatureInfo.h"),
    BWPath(r"C:\Dev\black\DanceInfo.h"),
    BWPath(r"C:\Dev\black\EffectInfo.h"),
    BWPath(r"C:\Dev\black\FelledTree.h"),
    BWPath(r"C:\Dev\black\FireEffect.h"),
    BWPath(r"C:\Dev\black\FieldTypeInfo.h"),
    BWPath(r"C:\Dev\black\FootpathFinder.h"),
    BWPath(r"C:\Dev\black\FootpathLink.h"),
    BWPath(r"C:\Dev\black\FootpathLinkSave.h"),
    BWPath(r"C:\Dev\black\FootpathNode.h"),
    BWPath(r"C:\Dev\black\Fragment.h"),
    BWPath(r"C:\Dev\black\GameInfo.h"),
    BWPath(r"C:\Dev\black\GatheringText.h"),
    BWPath(r"C:\Dev\black\Guidance.h"),
    BWPath(r"C:\Dev\black\HairGroup.h"),
    BWPath(r"C:\Dev\black\InterfaceCollide.h"),
    BWPath(r"C:\Dev\black\InterfaceFlags.h"),
    BWPath(r"C:\Dev\black\InterfaceMessageBuffer.h"),
    BWPath(r"C:\Dev\black\JPSysInterface.h"),
    BWPath(r"C:\Dev\black\Language.h"),
    BWPath(r"C:\Dev\black\LeashStatus.h"),
    BWPath(r"C:\Dev\black\LightSheet.h"),
    BWPath(r"C:\Dev\black\LivingAction.h"),
    BWPath(r"C:\Dev\black\LivingInfo.h"),
    BWPath(r"C:\Dev\black\GlobalGameLists.h"),
    BWPath(r"C:\Dev\black\GestureSystem.h"),
    BWPath(r"C:\Dev\black\GestureSystemResult.h"),
    BWPath(r"C:\Dev\black\GestureSystemData.h"),
    BWPath(r"C:\Dev\black\GestureSystemDataList.h"),
    BWPath(r"C:\Dev\black\MagicEffectInfo.h"),
    BWPath(r"C:\Dev\black\MagicFireBall.h"),
    BWPath(r"C:\Dev\black\MagicHand.h"),
    BWPath(r"C:\Dev\black\Map.h"),
    BWPath(r"C:\Dev\black\MapShield.h"),
    BWPath(r"C:\Dev\black\MobileInfo.h"),
    BWPath(r"C:\Dev\black\MobileObjectInfo.h"),
    BWPath(r"C:\Dev\black\MobileWallHugInfo.h"),
    BWPath(r"C:\Dev\black\MultiMapFixedInfo.h"),
    BWPath(r"C:\Dev\black\Name.h"),
    BWPath(r"C:\Dev\black\ObjectInfo.h"),
    BWPath(r"C:\Dev\black\PhysicsSaveInfo.cpp"),
    BWPath(r"C:\Dev\black\PlaytimeInfo.h"),
    BWPath(r"C:\Dev\black\Playtime.h"),
    BWPath(r"C:\Dev\black\PlayerInfo.h"),
    BWPath(r"C:\Dev\black\PrayerIconInfo.h"),
    BWPath(r"C:\Dev\black\PuzzleGame.h"),
    BWPath(r"C:\dev\Black\PSysEditor.cpp"),
    BWPath(r"C:\dev\Black\PSysProcessInfo.cpp"),
    BWPath(r"C:\Dev\black\Rand.h"),
    BWPath(r"C:\Dev\black\SaveLoadPtr.h"),
    BWPath(r"C:\Dev\black\ShowNeedsInfo.h"),
    BWPath(r"C:\Dev\black\SingleMapFixedInfo.h"),
    BWPath(r"C:\Dev\black\SpecialVillagerInfo.h"),
    BWPath(r"C:\Dev\black\SpellIconInfo.h"),
    BWPath(r"C:\Dev\black\TotemStatueInfo.h"),
    BWPath(r"C:\Dev\black\TownDesireInfo.h"),
    BWPath(r"C:\Dev\black\TownInfo.h"),
    BWPath(r"C:\Dev\black\TreeInfo.h"),
    BWPath(r"C:\Dev\black\TribeInfo.h"),
    BWPath(r"C:\Dev\black\VillagerNames.h"),
    BWPath(r"C:\Dev\black\VillagerInfo.h"),
    BWPath(r"C:\Dev\black\VillagerStateTableInfo.h"),
    BWPath(r"C:\Dev\black\VirtualInfluence.h"),
    BWPath(r"C:\Dev\black\WorshipSiteInfo.h"),
    BWPath(r"C:\Dev\black\HandState.h"),
    BWPath(r"C:\Dev\black\Global.h"),
    BWPath(r"C:\Dev\black\HandStateCamera.h"),
    BWPath(r"C:\Dev\black\HandStateCitadel.h"),
    BWPath(r"C:\Dev\black\HandStateCreature.h"),
    BWPath(r"C:\Dev\black\HandStateGrain.h"),
    BWPath(r"C:\Dev\black\HandStateHolding.h"),
    BWPath(r"C:\Dev\black\HandStateInvisible.h"),
    BWPath(r"C:\Dev\black\HandStateMultiPickUp.h"),
    BWPath(r"C:\Dev\black\HandStateNormal.h"),
    BWPath(r"C:\Dev\black\HandStatePlayAnim.h"),
    BWPath(r"C:\Dev\black\HandStateTotem.h"),
    BWPath(r"C:\Dev\black\HandStateTug.h"),
    BWPath(r"C:\Dev\black\HelpSpritesGuidance.h"),
    BWPath(r"C:\Dev\black\InnerCamera.h"),
    BWPath(r"C:\Dev\black\InterfaceHandState.h"),
    BWPath(r"C:\Dev\black\Landscape.h"),
    BWPath(r"C:\Dev\black\LayerCommunication.h"),
    BWPath(r"C:\Dev\black\Leash.h"),
    BWPath(r"C:\Dev\black\LiquidParticle.h"),
    BWPath(r"C:\Dev\black\MiniDialogBoxOptions.h"),
    BWPath(r"C:\Dev\black\Morphable.h"),
    BWPath(r"C:\Dev\black\MultiMapFixed.h"),
    BWPath(r"C:\dev\Black\MPFEConnectionStatus.cpp"),
    BWPath(r"C:\dev\Black\MPFEDownloads.cpp"),
    BWPath(r"C:\dev\Black\MPFEMessageObject.cpp"),
    BWPath(r"C:\dev\Black\MPFEAskJoinMessage.h"),
    BWPath(r"C:\dev\Black\MPFECancelStartMessage.h"),
    BWPath(r"C:\dev\Black\MPFEChangeClanRequest.h"),
    BWPath(r"C:\dev\Black\MPFEChangedMapMessage.h"),
    BWPath(r"C:\dev\Black\MPFEChangedTeamRequestMessage.h"),
    BWPath(r"C:\dev\Black\MPFEClanList.h"),
    BWPath(r"C:\dev\Black\MPFECondtionUpdateMessage.h"),
    BWPath(r"C:\dev\Black\MPFECreateGame.h"),
    BWPath(r"C:\dev\Black\MPFEDatabaseID.h"),
    BWPath(r"C:\dev\Black\MPFEDisconnectNowMessage.h"),
    BWPath(r"C:\dev\Black\MPFEFileTransferMessage.h"),
    BWPath(r"C:\dev\Black\MPFEHasCreature.h"),
    BWPath(r"C:\dev\Black\MPFEInviteToTeamMessage.h"),
    BWPath(r"C:\dev\Black\MPFEKickMessage.h"),
    BWPath(r"C:\dev\Black\MPFEKickMessageRequest.h"),
    BWPath(r"C:\dev\Black\MPFEMapErrorMessage.h"),
    BWPath(r"C:\dev\Black\MPFEPrivateChatMessage.h"),
    BWPath(r"C:\dev\Black\MPFEPublicChatMessage.h"),
    BWPath(r"C:\dev\Black\MPFEReadyMessage.h"),
    BWPath(r"C:\dev\Black\MPFEReplyToInviteMessage.h"),
    BWPath(r"C:\dev\Black\MPFEReplyToJoinMessage.h"),
    BWPath(r"C:\dev\Black\MPFEStartGameNowMessage.h"),
    BWPath(r"C:\dev\Black\MPFEStartGameOkayToStartMessage.h"),
    BWPath(r"C:\dev\Black\MPFEStartGameReadyMessage.h"),
    BWPath(r"C:\dev\Black\MPFEStartGameTransferFilesMessage.h"),
    BWPath(r"C:\dev\Black\MPFETeamsReadyList.h"),
    BWPath(r"C:\dev\Black\MPFEUserTeamList.h"),
    BWPath(r"C:\Dev\black\Network.h"),
    BWPath(r"C:\Dev\black\OneOffSpellSeed.h"),
    BWPath(r"C:\Dev\black\PileFood.h"),
    BWPath(r"C:\Dev\black\PileResource.h"),
    BWPath(r"C:\Dev\black\PileWood.h"),
    BWPath(r"C:\Dev\black\PlannedAbode.h"),
    BWPath(r"C:\Dev\black\PlannedCitadelHeart.h"),
    BWPath(r"C:\Dev\black\PlannedCitadelPart.h"),
    BWPath(r"C:\Dev\black\PlannedCreaturePen.h"),
    BWPath(r"C:\Dev\black\PlannedFeature.h"),
    BWPath(r"C:\Dev\black\PlannedTownCentre.h"),
    BWPath(r"C:\Dev\black\PlannedTownCitadelHeart.h"),
    BWPath(r"C:\Dev\black\PlannedWorshipSite.h"),
    BWPath(r"C:\Dev\black\PlannedWorshipSiteUpgrade.h"),
    BWPath(r"C:\Dev\black\PotStructure.h"),
    BWPath(r"C:\Dev\black\PSysBase.h"),
    BWPath(r"C:\Dev\black\PSysManager.h"),
    BWPath(r"C:\Dev\black\ReactionInfo.h"),
    BWPath(r"C:\Dev\black\ScriptDLL.h"),
    BWPath(r"C:\Dev\black\ScriptCreatureCurse.h"),
    BWPath(r"C:\Dev\black\Settings.h"),
    BWPath(r"C:\Dev\black\SetupBigButton.h"),
    BWPath(r"C:\Dev\black\SetupButton.h"),
    BWPath(r"C:\Dev\black\SetupCheckBox.h"),
    BWPath(r"C:\Dev\black\SetupColourPicker.h"),
    BWPath(r"C:\Dev\black\SetupBox.h"),
    BWPath(r"C:\Dev\black\SetupControl.h"),
    BWPath(r"C:\Dev\black\SetupEdit.h"),
    BWPath(r"C:\Dev\black\SetupHLineGraph.h"),
    BWPath(r"C:\Dev\black\SetupHSBarGraph.h"),
    BWPath(r"C:\Dev\black\SetupList.h"),
    BWPath(r"C:\Dev\black\SetupMP3Button.h"),
    BWPath(r"C:\Dev\black\SetupMultiList.h"),
    BWPath(r"C:\Dev\black\SetupPicture.h"),
    BWPath(r"C:\Dev\black\SetupRect.h"),
    BWPath(r"C:\Dev\black\SetupSlider.h"),
    BWPath(r"C:\Dev\black\SetupStaticText.h"),
    BWPath(r"C:\Dev\black\SetupStaticTextNoHit.h"),
    BWPath(r"C:\Dev\black\SetupTabButton.h"),
    BWPath(r"C:\Dev\black\SetupThing.h"),
    BWPath(r"C:\Dev\black\SetupVBarGraph.h"),
    BWPath(r"C:\Dev\black\ShowNeedsVisuals.h"),
    BWPath(r"C:\Dev\black\SoundMap.h"),
    BWPath(r"C:\Dev\black\Spell.h"),
    BWPath(r"C:\Dev\black\SpellSeedGraphic.h"),
    BWPath(r"C:\Dev\black\SpellWater.h"),
    BWPath(r"C:\Dev\black\SpellWithObjects.h"),
    BWPath(r"C:\Dev\black\SpellCreature"),
    BWPath(r"C:\Dev\black\SpellFlockFlying"),
    BWPath(r"C:\Dev\black\SpellFlockGround"),
    BWPath(r"C:\Dev\black\SpellHeal"),
    BWPath(r"C:\Dev\black\SpellPointInf"),
    BWPath(r"C:\Dev\black\SpellResource"),
    BWPath(r"C:\Dev\black\SpellSetupBox"),
    BWPath(r"C:\Dev\black\SpellStormAndTornado"),
    BWPath(r"C:\Dev\black\SpellTeleport"),
    BWPath(r"C:\dev\black\SpookyVoicesInfo.h"),
    BWPath(r"C:\dev\Black\CitadelBuildingSite.h"),
    BWPath(r"C:\dev\Black\StandardBuildingSite.h"),
    BWPath(r"C:\dev\Black\WorkshopBuildingSite.h"),
    BWPath(r"C:\Dev\black\StartGameBox.h"),
    BWPath(r"C:\Dev\black\StatsDatabase.h"),
    BWPath(r"C:\Dev\black\TerrainMap.h"),
    BWPath(r"C:\Dev\black\TerrainMapInfo.h"),
    BWPath(r"C:\Dev\black\TerrainMapTypeInfo.h"),
    BWPath(r"C:\Dev\black\ToolTipsInfo.h"),
    BWPath(r"C:\Dev\black\TownDesireFlags.h"),
    BWPath(r"C:\Dev\black\TownStats.h"),
    BWPath(r"C:\Dev\black\ValueSpinner.h"),
    BWPath(r"C:\Dev\black\Waterfall.h"),
    BWPath(r"C:\Dev\black\Graveyard.h"),
    BWPath(r"C:\Dev\black\Windmill.h"),
    BWPath(r"C:\Dev\black\WeatherInfo.h"),
    BWPath(r"C:\Dev\black\CreatureActionInfo.h"),
    BWPath(r"C:\Dev\black\CreatureInitialDesireInfo.h"),
    BWPath(r"C:\Dev\black\CreatureInitialSourceInfo.h"),
    BWPath(r"C:\Dev\black\CreatureMimicInfo.h"),
    BWPath(r"C:\Dev\black\CreatureSourceBoundsInfo.h"),
    BWPath(r"C:\Dev\black\DifferentCreatureInfo.h"),
    BWPath(r"C:\Dev\black\HelpSpiritInfo.h"),
    BWPath(r"C:\Dev\black\HelpSystemInfo.h"),
    BWPath(r"C:\Dev\black\ThingMusicInfo.h"),
    BWPath(r"C:\Dev\black\TownCreatureInfo.h"),
    BWPath(r"C:\Dev\black\AlignmentInfo.h"),
    BWPath(r"C:\Dev\black\AnimalInfo.h"),
    BWPath(r"C:\Dev\black\AnimalStateTableInfo.h"),
    BWPath(r"C:\Dev\black\AnimatedStaticInfo.h"),
    BWPath(r"C:\Dev\black\ArrowInfo.h"),
    BWPath(r"C:\Dev\black\BeliefInfo.h"),
    BWPath(r"C:\Dev\black\CitadelInfo.h"),
    BWPath(r"C:\Dev\black\ClimateInfo.h"),
    BWPath(r"C:\Dev\black\ClimateRainInfo.h"),
    BWPath(r"C:\Dev\black\CreaturePenInfo.h"),
    BWPath(r"C:\Dev\black\FeatureInfo.h"),
    BWPath(r"C:\Dev\black\FieldInfo.h"),
    BWPath(r"C:\Dev\black\FishFarmInfo.h"),
    BWPath(r"C:\Dev\black\FlowersInfo.h"),
    BWPath(r"C:\Dev\black\FootballPositionInfo.h"),
    BWPath(r"C:\Dev\black\ForestInfo.h"),
    BWPath(r"C:\Dev\black\FurnitureInfo.h"),
    BWPath(r"C:\Dev\black\InfluenceInfo.h"),
    BWPath(r"C:\Dev\black\JobInfo.h"),
    BWPath(r"C:\Dev\black\LeashSelectorInfo.h"),
    BWPath(r"C:\Dev\black\MagicFireBallInfo.h"),
    BWPath(r"C:\Dev\black\MagicFlockFlyingInfo.h"),
    BWPath(r"C:\Dev\black\MagicFlockGroundInfo.h"),
    BWPath(r"C:\Dev\black\MagicHealInfo.h"),
    BWPath(r"C:\Dev\black\MagicLivingInfo.h"),
    BWPath(r"C:\Dev\black\MagicObjectInfo.h"),
    BWPath(r"C:\Dev\black\MagicRadiusSpellInfo.h"),
    BWPath(r"C:\Dev\black\MagicResourceInfo.h"),
    BWPath(r"C:\Dev\black\MagicStormAndTornadoInfo.h"),
    BWPath(r"C:\Dev\black\MagicTeleportInfo.h"),
    BWPath(r"C:\Dev\black\MagicWaterInfo.h"),
    BWPath(r"C:\Dev\black\MapShieldInfo.h"),
    BWPath(r"C:\Dev\black\PotInfo.h"),
    BWPath(r"C:\Dev\black\PrayerSiteInfo.h"),
    BWPath(r"C:\Dev\black\RankInfo.h"),
    BWPath(r"C:\Dev\black\RewardInfo.h"),
    BWPath(r"C:\Dev\black\ScaffoldInfo.h"),
    BWPath(r"C:\Dev\black\ScriptHighlightInfo.h"),
    BWPath(r"C:\Dev\black\SoundInfo.h"),
    BWPath(r"C:\Dev\black\SpellSystemInfo.h"),
    BWPath(r"C:\Dev\black\SpookyVoiceInfo.h"),
    BWPath(r"C:\Dev\black\SquadInfo.h"),
    BWPath(r"C:\Dev\black\TerrainMaterialInfo.h"),
    BWPath(r"C:\Dev\black\VortexInfo.h"),
    BWPath(r"C:\Dev\black\WorshipSiteUpgradeInfo.h"),
    BWPath(r"C:\Dev\black\BallInfo.h"),
    BWPath(r"C:\Dev\black\FootballInfo.h"),
    BWPath(r"C:\Dev\black\FootballPositionInfo.h"),
    BWPath(r"C:\Dev\black\WorshipSite.h"),
    BWPath(r"C:\Dev\black\WorshipSpell.h"),
    BWPath(r"C:\Dev\black\Persistent.h"),
    BWPath(r"C:\Dev\black\Property.h"),
    BWPath(r"C:\Dev\black\SecretCreature.h"),
    BWPath(r"C:\Dev\black\SubArgument.h"),
    BWPath(r"C:\Dev\black\SubOptionEntry.h"),
    BWPath(r"C:\Dev\black\AnimalCrow.cpp"),
    BWPath(r"C:\Dev\black\AnimalGoat.cpp"),
    BWPath(r"C:\Dev\black\AnimalHorse.cpp"),
    BWPath(r"C:\Dev\black\AnimalPig.cpp"),
    BWPath(r"C:\Dev\black\AnimalPigeon.cpp"),
    BWPath(r"C:\Dev\black\AnimalSeagull.cpp"),
    BWPath(r"C:\Dev\black\AnimalSheep.cpp"),
    BWPath(r"C:\Dev\black\AnimalSwallow.cpp"),
    BWPath(r"C:\Dev\black\AnimalTortoise.cpp"),
    BWPath(r"C:\Dev\black\AnimalVulture.cpp"),
    BWPath(r"C:\Dev\black\AnimalZebra.cpp"),
    BWPath(r"C:\Dev\black\VortexObjectInfo.cpp"),
    BWPath(r"C:\Dev\black\Particle3DAnim.h"),
    BWPath(r"C:\Dev\black\Particle3DAnimWithCamera.h"),
    BWPath(r"C:\Dev\black\Particle3DObj.h"),
    BWPath(r"C:\Dev\black\Particle3DObjAnimTextured.h"),
    BWPath(r"C:\Dev\black\Particle3DPnt.h"),
    BWPath(r"C:\Dev\black\Particle3DSprite.h"),
    BWPath(r"C:\Dev\black\ParticleBaseMeshCreator.h"),
    BWPath(r"C:\Dev\black\ParticleChainJoint.h"),
    BWPath(r"C:\Dev\black\ParticleCreator.h"),
    BWPath(r"C:\Dev\black\ParticleLightMap.h"),
    BWPath(r"C:\Dev\black\ParticlePlayerSymbol.h"),
    BWPath(r"C:\Dev\black\ParticleContainer.h"),
    BWPath(r"C:\Dev\black\ChallengeRoomCamera.h"),
    BWPath(r"C:\Dev\black\GameOptionsRoom.h"),
    BWPath(r"C:\Dev\black\HelpDude.h"),
    BWPath(r"C:\Dev\black\HanoiBlock.h"),
    BWPath(r"C:\Dev\black\FireGraphic.h"),
    BWPath(r"C:\Dev\black\Flowers.h"),
    BWPath(r"C:\Dev\black\Chain.h"),
    BWPath(r"C:\Dev\black\Poo.h"),
    BWPath(r"C:\Dev\black\FieldCrop.h"),
    BWPath(r"C:\Dev\black\DefensiveSphere.h"),
    BWPath(r"C:\Dev\black\DefensiveShield.h"),
    BWPath(r"C:\Dev\black\PhysicalShield.h"),
    BWPath(r"C:\Dev\black\MagicShield.h"),
    BWPath(r"C:\Dev\black\MagicWood.h"),
    BWPath(r"C:\Dev\black\CitadelEntrance.h"),
    BWPath(r"C:\Dev\black\PrayerSite.h"),
    BWPath(r"C:\Dev\black\FuncT.h"),
    BWPath(r"C:\Dev\libs\ifc\ImmDevice.h"),
    BWPath(r"C:\dev\black\_libcmt_helper.h"), # C-accessible c++ functions
}

ROOMMATE_CLASS_MAP = {
    "FixedObject": "Fixed",  # Called Fixed in x86 and FixedObject in ppc (validated by func name vs rtti name)
    "SingleMapFixed": "Fixed",  # Validated by a __nw__FUl(__FILE__l, ...) reference in Fixed.cpp
    "Point2D": "LHPoint",
    "LH3DMapCoordsSplit": "LH3DMapCoords",
    "LH3DMapCoordsFull": "LH3DMapCoords",
    "MapCoordsSplit": "MapCoords",
    "MapCoordsFull": "MapCoords",
    "JustWholeMapXZ": "MapCoords",
    "JustMapXZ": "MapCoords",
    "LHScriptPramX_c_": "LHScript",
    "LHScriptCommandX_c_": "LHScript",
    "LHScriptX": "LHScript",
    "LHScriptX_c_": "LHScript",
    "LHScriptX_w_": "LHScript",
    "LHSys": "LHSystem",
    "LHSys_field_0x70c4_t": "LHSystem",
    "LHSys_field_0x70c4_t_field_0x0_t": "LHSystem",
    "InfoTransform": "LH3DTech",
    "TextureFormat": "LH3DTexture",
    "MaterialProperties": "LH3DMaterial",
    "LH3DMaterial__RenderMode": "LH3DMaterial",
    "LHSprite": "LH3DSprite",
    "LHSpriteList": "LH3DSprite",
    "LH_USER_ID": "LHNetUser",
    "LHNetGetCurrentUsedProfile__Fv": "LHNetUtils",
    "LHNetGetCurrentProfileNameFromRegistry__Fv": "LHNetUtils",
    "LHPacketHeader": "LHPacket",
    "InnerRoom": "TempleRoom",
    "LiquidParticleGroup": "LiquidParticle",
    "sparklecbstub__FP19LiquidParticleGroupUl": "LiquidParticle",
    "GGuidance": "SoundGuidance", # Validated in Init__9GGuidanceFR16GInterfaceStatus
    "GGuidance__LastThings": "SoundGuidance",
    "NewCollide": "Collide",
    "NewCollideDescriptor": "Collide",
    "ObjectCircleIterator": "Collide",
    "Point2DCompare": "Collide",
    "IntersectIntervalCircle": "Collide",
    "std__pair__pQ210NewCollide3Obj__std__set__pMobileWallHug": "MobileWallHug",
    "std__map__pQ210NewCollide3Obj__std__set__pMobileWallHug_iterator": "MobileWallHug",
    "std__map__pQ210NewCollide3Obj__std__set__pMobileWallHug_node_list": "MobileWallHug",
    "std::map<NewCollide::Obj*, std::set<MobileWallHug*>>": "MobileWallHug",
    "std__map__pQ210NewCollide3Obj__std__set__pMobileWallHug": "MobileWallHug",
    "SubCollideBlockPos": "MobileWallHug",
    "std::map<SubCollideBlockPos, NewCollide3Obj*>": "MobileWallHug",
    "std__map__SubCollideBlockPosPNewCollide3Obj": "MobileWallHug",
    "std__map__SubCollideBlockPosPNewCollide3Obj_iterator": "MobileWallHug",
    "CircleHugStateInfo_field_0x44_node_list": "MobileWallHug",
    "CircleHugInfo": "Collide",
    "LinearSquareSweepStruct": "MobileWallHug",
    "CircleHugStateInfoT": "MobileWallHug",
    "MeshIntersect": "LH3DMeshIntersect",
    "std__pair__pMobileWallHug__ulong": "MobileWallHug",
    "std__map__pMobileWallHug__ulong_node": "MobileWallHug",
    "std__map__pMobileWallHug__ulong_node_list": "MobileWallHug",
    "std__map__pMobileWallHug__ulong": "MobileWallHug",
    "std__set__pMobileWallHug_node": "MobileWallHug",
    "std__set__pMobileWallHug_node_list": "MobileWallHug",
    "std__set__pMobileWallHug": "MobileWallHug",
    "GMoveBy": "MobileWallHug",
    "Zoomer3d": "Zoomer",
    "SpellIcon__TChargingData": "SpellIcon",
    "WorshipTotem__TChargingData": "WorshipTotem",
    "FragVertex": "ViscousLiquid",
    "FragTriangle": "ViscousLiquid",
    "FragPrimitive": "ViscousLiquid", # Validated by __FILE__ in __nw__FUl
    "FragMesh": "ViscousLiquid", # Validated by __FILE__ in __nw__FUl
    "EffectNumbers": "EffectValues",
    "Town_field_0x9fc": "Town",
    "TownArtifact": "Artifact",
    "GTownDesireFunction": "TownDesire",
    "LandBlock": "LH3DIsland",
    "LandCell": "LH3DIsland",
    "PictureRoomBase": "PictureRoom",
    "PHandFX": "PSysHandFX", # Validated in DoRemoveFromHandVisual__7PHandFXFv
    "GJUtils": "GJBaseUtils",
    "GameBlock": "JCGameBlock",
    "Morphable_field_0x4314_t": "Morphable",
    "CHand": "ControlHand",
    "CHand__State": "ControlHand",
    "CHand__State__Named": "ControlHand",
    "CreatureDesires": "CreatureMentalDesire",
    "CreatureDesireActionEntry": "CreatureMentalDesire",
    "CreatureDesireAttributeEntry": "CreatureMentalDesire",
    "CreatureDesireDependency": "CreatureMentalDesire",
    "CreatureDesireForType": "CreatureMentalDesire",
    "CreatureDesireSourceTable": "CreatureMentalDesire",
    "CreatureDesiresSource": "CreatureMentalDesireSource",
    "CreatureDevelopmentDurationEntry": "CreatureDevelopment",
    "CreatureDevelopmentPhaseEntry": "CreatureDevelopment",
    "CreatureExplorationRegionEntry": "CreatureExplorationMap",
    "CreatureGlobalExplorationMap": "CreatureExplorationMap",
    "CreatureMimicState": "CreatureMimic",
    "CreatureSubActionAgenda": "CreatureSubAction",
    "AllocatedBeliefList": "CreatureMentalBeliefs",
    "CreatureBeliefList": "CreatureMentalBeliefs",
    "CreatureBeliefs": "CreatureMentalBeliefs",
    "CreatureBelief": "CreatureMentalBelief",
    "CreatureBeliefAboutAbode": "CreatureMentalBelief",
    "CreatureBeliefAboutCitadel": "CreatureMentalBelief",
    "CreatureBeliefAboutContext": "CreatureMentalBelief",
    "CreatureBeliefAboutCreature": "CreatureMentalBelief",
    "CreatureBeliefAboutFlock": "CreatureMentalBelief",
    "CreatureBeliefAboutForest": "CreatureMentalBelief",
    "CreatureBeliefAboutMobileObject": "CreatureMentalBelief",
    "CreatureBeliefAboutTown": "CreatureMentalBelief",
    "CreatureBeliefAboutVillager": "CreatureMentalBelief",
    "CreatureBeliefSmall": "CreatureMentalBelief",
    "LH3DCreature": "CreatureMorph",  # Validated by __nw__FUl(..., __FILE, ...) in LoadBase__12LH3DCreatureFPc
    "LH3DCreature_field_0x5184": "CreatureMorph",
    "LHDynamicQueue_pLHNetEvent_": "LHNetEvent",
    "LHDynamicQueueNode_pLHNetEvent_": "LHNetEvent",
    "HLineData": "SetupHLineGraph",
    "VBarData": "SetupVBarGraph",
    "Remove__VBarDataList": "SetupVBarGraph",
    "MPFELoginDatabase": "MPFELogin",
    "LH3DWay__Running": "LH3DWay",
    "Living__StateTableSubEntry": "LivingAction",
    "Living__StateTableSubEntryState": "LivingAction",
    "Living__StateTableSubEntryEntryState": "LivingAction",
    "Living__StateTableEntry": "LivingAction",
    "LivingDLList": "Living",
    "DataForScriptRemind": "Living", # Validated in Create__19DataForScriptRemindFv
    "Villager__StateTable": "Villager",
    "FootballerSubstateTableEntry": "Villager",
    "GetNextDstPromemade__FP6CrecheRlP9MapCoordsRC9MapCoords": "Villager",
    "Animal__StateTable": "Animal",
    "Cow": "AnimalCow",
    "Dove": "AnimalDove",
    "Lion": "AnimalLion",
    "Goat": "AnimalGoat",
    "Horse": "AnimalHorse",
    "Pig": "AnimalPig",
    "Sheep": "AnimalSheep",
    "Tortoise": "AnimalTortoise",
    "Zebra": "AnimalZebra",
    "Bat": "AnimalBat",
    "Crow": "AnimalCrow",
    "Pigeon": "AnimalPigeon",
    "Seagull": "AnimalSeagull",
    "Swallow": "AnimalSwallow",
    "Vulture": "AnimalVulture",
    "Leopard": "AnimalLeopard",
    "Tiger": "AnimalTiger",
    "Wolf": "AnimalWolf",
    "Zebra": "AnimalZebra",
    "SpellBat": "AnimalBat",
    "SpellDove": "AnimalDove",
    "SpellWolf": "AnimalWolf",
    "PieceCow": "PuzzleGame",
    "PieceHorse": "PuzzleGame",
    "PieceLion": "PuzzleGame",
    "PiecePig": "PuzzleGame",
    "PieceSheep": "PuzzleGame",
    "PieceTortoise": "PuzzleGame",
    "PieceVillager": "PuzzleGame",
    "PieceWolf": "PuzzleGame",
    "PuzzleCow": "PuzzleGame",
    "PuzzleHorse": "PuzzleGame",
    "PuzzleLion": "PuzzleGame",
    "PuzzlePig": "PuzzleGame",
    "PuzzleSheep": "PuzzleGame",
    "PuzzleTortoise": "PuzzleGame",
    "PuzzleWolf": "PuzzleGame",
    "PuzzleMobileObject": "PuzzleGame",
    "PuzzleTotem": "PuzzleGame",
    "PuzzleVillager": "PuzzleGame",
    "PuzzleGrain": "PuzzleGame",
    "ChessGamePuzzle": "PuzzleGame",
    "ChessPiece": "PuzzleGame",
    "ChessKing": "PuzzleGame",
    "ChessKnight": "PuzzleGame",
    "ChessMad": "PuzzleGame",
    "ChessPion": "PuzzleGame",
    "ChessQueen": "PuzzleGame",
    "ChessTower": "PuzzleGame",
    "TownCentreSpellIcon": "TownSpellIcon",
    "ControlHandUpdateInfo": "ControlHand",
    "CreatureActionContextStart": "CreatureAction",
    "CreatureActionContext": "CreatureAction",
    "CreatureFalling": "CreatureAction",
    "PreviousActionContextStack": "CreatureAction",
    "CreaturePreviousActions": "CreatureAction",
    "PreviousContextStack": "CreatureContext",
    "CreatureInnatePersonality": "CreatureMental",
    "CreaturePerceivedPlayerDesires": "CreatureAttitudeToPlayer",
    "CreaturePerceivedPlayerDesires_field_0x15c": "CreatureAttitudeToPlayer",
    "CreatureAttitudeToPlayer_field_0x1da4": "CreatureAttitudeToPlayer",
    "GetRemapedPlayer__FUl": "Player",
    "HELP_EVENT_TYPE": "HelpSystem",
    "HELP_SET_CATEGORY": "HelpSystem",
    "HelpTextDataBase": "HelpText",
    "CreatureHelpState": "CreatureHelp",
    "CreatureHelpState__field_0x88": "CreatureHelp",
    "CreatureHelpStackEntry": "CreatureHelp",
    "CreatureActionOpinions": "CreatureAction",
    "CreatureMagicActionKnownAboutEntry": "CreatureAction",
    "GestureSystemPacketData": "GestureSystem",
    "CreatureLookState": "CreatureLook",
    "CreatureInterestingThingToLookAt": "CreatureVisionState",
    "CreaturePlanState": "CreaturePlan",
    "CreatureTimeToWait": "CreaturePlan",
    "CreatureDamageMap": "CreaturePhysical",
    "CreatureLearningEpisode": "CreatureLearning",
    "CreatureLearningContext": "CreatureLearning",
    "AttributeTest": "CreatureMentalAttributeTest",
    "DecisionTree": "CreatureMentalAttributeTest", # Validated by new call in constructor
    "DecisionTreeNode": "CreatureMentalAttributeTest",
    "DecisionTreeAgenda": "CreatureMentalAttributeTest",
    "DecisionTreeAgendas": "CreatureMentalAttributeTest",
    "DecisionTreeCollection": "CreatureMentalAttributeTest", # Validated by new call in constructor
    "Attribute": "CreatureMentalAttributeTest",
    "AttributeAbodeBeingBuilt": "CreatureMentalAttributeTest",
    "AttributeAbodeType": "CreatureMentalAttributeTest",
    "AttributeAllegiance": "CreatureMentalAttributeTest",
    "AttributeAnimate": "CreatureMentalAttributeTest",
    "AttributeCreatureDominantDesire": "CreatureMentalAttributeTest",
    "AttributeCreatureHeight": "CreatureMentalAttributeTest",
    "AttributeCreatureSpellKnowledge": "CreatureMentalAttributeTest",
    "AttributeCreatureType": "CreatureMentalAttributeTest",
    "AttributeCreatureWhatHeIsCarrying": "CreatureMentalAttributeTest",
    "AttributeForestSize": "CreatureMentalAttributeTest",
    "AttributeIsHarderThanMe": "CreatureMentalAttributeTest",
    "AttributeLife": "CreatureMentalAttributeTest",
    "AttributeMobileObjectType": "CreatureMentalAttributeTest",
    "AttributeOnFire": "CreatureMentalAttributeTest",
    "AttributeOrigin": "CreatureMentalAttributeTest",
    "AttributePlayerNumber": "CreatureMentalAttributeTest",
    "AttributeSex": "CreatureMentalAttributeTest",
    "AttributeTownReligiousBeliefInYou": "CreatureMentalAttributeTest",
    "AttributeTownSize": "CreatureMentalAttributeTest",
    "AttributeTribe": "CreatureMentalAttributeTest",
    "AttributeType": "CreatureMentalAttributeTest",
    "AttributeVillagerJob": "CreatureMentalAttributeTest",
    "AttributeWhatTownNeedsMost": "CreatureMentalAttributeTest",
    "LHSegmentDesc": "LHSegment",
    "ControlKey": "BindableAction",
    "ControlMouse": "BindableAction",
    "CMouse": "BindableAction",
    "TempleChallenge": "ChallengeRoom",
    "VMType": "ScriptDLL",
    "VMScriptType": "ScriptDLL",
    "STATE_TYPE": "ScriptDLL",
    "MultiChild": "MultiMapFixed",
    "MultiChildList": "MultiMapFixed",
    "CreatureFaceState": "CreatureFace",
    "Vertex3D": "LH3DVertex",
    "ANM_Name": "LH3DAnim",
    "LH3DAnimSet": "LH3DAnim",
    "CatInfo": "LH3DAnim",
    "CAnim": "LH3DAnim",
    "CFrame": "LH3DAnim",
    "CFrameData": "LH3DAnim",
    "AnimInfo": "LH3DAnim",
    "ANM_BaseHeader": "LH3DAnim",
    "GSaveLoadPtrList": "SaveLoadPtr",
    "VillagerName": "VillagerNames",
    "VillagerNameBlock": "VillagerNames",
    "MapCell": "Map",
    "MapCellIterator": "Map",
    "AgeToScale": "VillagerInfo",
    "DiscipleInfo": "VillagerInfo",
    "DesireSort": "TownDesire",
    "BMan_Check__FP4Prssiii": "Prss",
    "LeashObj": "CitadelHeart",
    "TempleLeash": "CitadelHeart", # Validated in __ct__11TempleLeashFP10LH3DObjectUl
    "ReactionDoneWhen": "Reaction", # Validated by looking in SetReactionDoneWhen__6LivingF8REACTION, inferring some inlining
    "FootprintData": "LH3DMesh",
    "BookmarkGraphic": "Bookmark",
    "LHSprite__Texels": "LH3DSprite",
    "NeedsBiggerText__Fv": "GatheringText",
    "GetMidTextSize__Fv": "GatheringText",
    "GetSmallTextSize__Fv": "GatheringText",
    "TurnOffMenu": "SetupThing",
    "LHRand__FlRU": "LHRand",
    "Random__Fff": "LHRand",
    "LHFileLength": "LHFile",
    "LHLoadData__FPcPvUlPUl": "LHFile",
    "PSysEditorInterface": "PSysEditor",
    "AtomCollection": "PSysAtomCore",
    "AtomCore": "PSysAtomCore",
    "UR_GesturingRecognised": "PSysAtomCore",
    "UR_Plasma": "PSysAtomCore",
    "BaseAtomModifierData": "PSysModifiers",
    "BaseCollectionModifierData": "PSysModifiers",
    "DrawOffset": "PSysModifiers",
    "DrawOffsetDecay": "PSysModifiers",
    "DrawOffsetLT": "PSysModifiers",
    "SetTurnOffMouseMove__Fb": "LHMouse",
    "DrawAndClip__F16D3DPRIMITIVETYPEUlP8Vertex3DUlPUsUl": "LH3DRender",
    "DrawAndClip2D__F16D3DPRIMITIVETYPEUlP8Vertex3DUlPUsUl": "LH3DRender",
    "DrawMouseCross__Fv": "LH3DRender",
    "BMan_Display__Fv": "LH3DRender",
    "ConfigGetFPS__Fv": "Config",
    "Report3D__FPCce": "LH3DTech",
    "WinMain": "PCMain",
    "ScanParameters__Fv": "PCMain",
    "IsACmdLineString__FPcPCc": "PCMain",
    "LoadAllAnimations__Fv": "GGame",
    "StartTipOfTheDayText__Fv": "GGame",
    "InitStaticsValues__Fv": "GGame",
    "operator_new": "_libcmt_helper",
    "__nw__FUl": "_libcmt_helper",
    "__dl__FPv": "_libcmt_helper",
    "__construct_new_array": "_libcmt_helper",
    "__destroy_new_array": "_libcmt_helper",
    "_purecall": "_libcmt_helper",
    "CHAR2WCHAR__FPc": "Utils",
    "FUN_0074f620": "Utils",
    "InfluenceRing": "Influence", # Validated with a __nw__4BaseFUl(..., __FILE__, ...) in Create__13InfluenceRingFRC9MapCoordsP7GPlayerfi
    "CreatureDesireSource": "CreatureMentalDesireSource",
    "CreatureEmotionsForMusic": "Creature",
    "Creed": "Creature",
    "CameraHelpAccumulator": "HelpProfile",
    "PlayerTownInteract": "Town",
    "RequestChangeTexture__FP6Object": "Object",
    "DoWallHuggerLookahead__Fv": "MobileWallHug",
    "Resolve__26IntersectIntervalCircle_0_Fv": "MobileWallHug",
    "Resolve__26IntersectIntervalCircle_1_Fv": "MobileWallHug",
    "MobileWallHug_InCircleStuff": "MobileWallHug",
    "get_villager_state_table": "Villager",
    "SortedObject": "Villager",
    "ChildBorn__FR8Villager": "Villager",
    "ClearAreaPoint": "Villager",
    "Glocation": "Villager",
    "GetViaPoint__FRC9MapCoordsRC9MapCoordsRC9MapCoordsfR9MapCoordsfPbPbf": "Villager",
    "POWER_f___FfUl": "Villager",
    "CPController": "Citadel",
    "hypotenuse__Fll": "LHMath",
    "LHArcTan__Fll": "LHMath",
    "LHFileLength__FPcPUl": "LHFile",
    "ConvertMapCoordsToPoint2D__FRC9MapCoords": "MapCoords",
    "ConvertPoint2DToMapCoords__FRC7Point2D": "MapCoords",
    "ConvertPointToMapCoords__FRC7Point": "MapCoords",
    "RenderLoadingFrame__Fb": "LH3DRender",
    "RenderLoadingFrame__FPc": "LH3DRender",
    "stop_draw_sprite_to_screen__Fv": "LH3DRender",
    "peerStartListingGames": "LHLobby",
    "LHJoypads": "LHJoypad",
    "FrameInfoLinkedList": "LHSystem",
    "LHConvert": "LHSystem",
    "slim": "LHSystem",
    "DanceKeyFrame": "DanceKey",
    "LHTransportRemote": "LHTransport",
    "FUN_00535a80": "Footpath",
    "FUN_00536fa0": "GFootpathLinkSave",
    "FUN_00613790": "MobileWallHug",
    "LHIlib": "LHDLL",
    "LandscapeVortex": "MagicVortex", # Validated in ProcessContentsOfVortex
    "LandscapeVortexIn": "MagicVortex",
    "LandscapeVortexOut": "MagicVortex",
    "LandscapeVortexVolc": "MagicVortex",
    "RenderParticle": "PSysRenderParticle",
    "FOOD_TYPE": "Object",
    "ObjectCircleIteratorDirection": "Collide",
    "MOVE_TO_STATES": "MobileWallHug",
    "LESSON_TYPE": "CreatureLessonChooser",
    "TEXTJUSTIFY": "GatheringText",
    "TextureFormat_": "LH3DTexture",
    "BBSTYLE": "SetupThing",
    "BINDABLE_ACTIONS": "BindableAction",
    "CameraHelpReason": "CameraHelp",
    "AnimInfoType": "LH3DAnim",
    "LH_SEEK_MODE": "LHFile",
    "LH_OPERATING_MODE": "LHLobby",
    "LHKeyMod": "LHKey",
    "UniqueKeyHeap": "Heap",
    "HeapWithPools": "Heap",
    "HeapStore": "Heap",
    "CPDesireNodeInfo": "GPlayerInfo",
    "BoolProperty": "Property",
    "SoundActionProperty": "Property",
    "StringProperty": "Property",
    "TPointerProperty": "Property",
    "UR_Tornado": "PSysTornado",
    "EmitterRule": "PSysProperties",
    "EmitterRuleLightningSprite": "PSysProperties",
    "ER_BurstFromParentAtom": "PSysProperties",
    "ER_EmitFromParentAtom": "PSysProperties",
    "ER_GlintsOnTarget": "PSysProperties",
    "ER_GlintsOnTarget": "PSysProperties",
    "ER_MultiPickup": "PSysProperties",
    "ER_MultiPickup": "PSysProperties",
    "AR_FadeOutOnceConditionTrue": "PSysProperties",
    "AddSoundToAtom": "PSysProperties",
    "AddSubCollectionsToAtom": "PSysProperties",
    "AttatchFireBallToAtom": "PSysProperties",
    "CheckShieldDeflections": "PSysProperties",
    "CreateNewBaseAtom": "PSysProperties",
    "ER_GlintsOnTarget": "PSysProperties",
    "ER_GlintsOnTarget": "PSysProperties",
    "ER_MultiPickup": "PSysProperties",
    "RemoveRuleAfterConditionTrue": "PSysProperties",
    "RemoveSoundFromAtom": "PSysProperties",
    "UR_Articulate": "PSysProperties",
    "UR_BankedTurning": "PSysProperties",
    "UR_BeliefSprite": "PSysProperties",
    "UR_CloudGather": "PSysProperties",
    "UR_CreatureSpellGeneric": "PSysProperties",
    "UR_Explosion": "PSysProperties",
    "UR_FollowTargets": "PSysProperties",
    "UR_ForestPath": "PSysProperties",
    "UR_HealSpellChakra": "PSysProperties",
    "UR_InitialSpin": "PSysProperties",
    "UR_LightSheetOnObject": "PSysProperties",
    "UR_LightningStrike": "PSysProperties",
    "UR_ManaPathNew": "PSysProperties",
    "UR_ObjectArcer": "PSysProperties",
    "UR_OrientSpriteWithRandomAngle": "PSysProperties",
    "UR_OrientSpriteWithVelocity": "PSysProperties",
    "UR_OrientWithVelocity": "PSysProperties",
    "UR_SideSpin": "PSysProperties",
    "UR_SimpleBeam": "PSysProperties",
    "UR_SphereSurfaceTracer": "PSysProperties",
    "UR_StormCast": "PSysProperties",
    "UR_TownCentreBelief": "PSysProperties",
    "UR_VapourEndEffect": "PSysProperties",
    "UR_VolFXOnObject": "PSysProperties",
    "UR_VortexAttract": "PSysProperties",
    "UpdateRuleGravityWithFloor": "PSysProperties",
    "UpdateRuleShieldSpark": "PSysProperties",
    "ZR_ChainGesture": "PSysProperties",
    "UR_Lightning_CollectionData": "PSysProperties",
    "LightningForkFlicker": "PSysProperties",
    "UR_AddDefensiveSphere": "PSysProperties",
    "UR_AtomsAtEPTarget": "PSysProperties",
    "UR_CloudMoverNew": "PSysProperties",
    "UR_CreatureSpell": "PSysProperties",
    "UR_CreatureSpellCompassion": "PSysProperties",
    "UR_CreatureSpellFreeze": "PSysProperties",
    "UR_CreatureSpellItch": "PSysProperties",
    "UR_Flocking": "PSysProperties",
    "UR_HandSprinkle": "PSysProperties",
    "UR_RingSpin": "PSysProperties",
    "UR_Rope": "PSysProperties",
    "UR_Trail": "PSysProperties",
    "UR_WillowWisp": "PSysProperties",
    "ZR_SurfRevol": "PSysProperties",
    "UR_PlasmaInf": "PSysProperties",
    "SubOptionEntryButton": "SubOptionEntry",
    "SubOptionEntryCheckBoxChecked": "SubOptionEntry",
    "SubOptionEntryCheckBoxUnChecked": "SubOptionEntry",
    "SubOptionEntryFrame": "SubOptionEntry",
    "SubOptionEntryListBox": "SubOptionEntry",
    "SubOptionEntryPicture": "SubOptionEntry",
    "SubOptionEntryScroll": "SubOptionEntry",
    "SubOptionEntrySlider": "SubOptionEntry",
    "SubOptionEntryText": "SubOptionEntry",
    "SubArgumentInteger": "CreatureScript",
    "SubArgumentObjectAndInteger": "CreatureScript",
    "SubArgumentPoint": "CreatureScript",
    "RenderParticleCreatureRef": "PSysPCreator",
    "RenderParticleGJMesh": "PSysPCreator",
    "RenderParticleGJMeshRotatingUV": "PSysPCreator",
    "RenderParticleGameObject": "PSysPCreator",
    "RenderParticleGameObjectRef": "PSysPCreator",
    "RenderParticleGoldenShower": "PSysPCreator",
    "RenderParticleMist": "PSysPCreator",
    "RenderParticleVolBlendMesh": "PSysPCreator",
    "CreatureActionKnownAbout": "CreatureAction",
    "CreatureActionKnownAboutEntry": "CreatureAction",
    "CREATURE_SUB_STATE_ACTIONS": "CreatureAction",
    "CreatureCommand": "CreatureDirectControl",
    "TestFunnel": "PSysGeom",
    "TestFunnelParab": "PSysGeom",
    "TestFunnelSpout": "PSysGeom",
    "AnimEdit": "EditorAnim",
    "ArenaSpellIcon": "Arena",
    "PrayerIcon": "WorshipSpellIcon",
    "GComputerAttitudeToPlayer": "PlayerComputer",
    "GComputerPlayer": "PlayerComputer",
    "GComputerPlayerQueue": "PlayerComputer",
    "GComputerSeen": "PlayerComputer",
    "GComputerSpellCast": "PlayerComputer",
    "PlayerActionState": "PlayerComputer",
    "PlayerSubAction": "PlayerComputer",
    "PlayerSubActionArgument": "PlayerComputer",
    "GBaseOnly": "MobileStatic",
    "DanceEditState": "GroupBehaviour",
    "DanceKeyAction": "GroupBehaviour",
    "IPSpecialDialog": "IpSpecialDialog",
    "GKeyInput": "KeyBuffer",
    "GRewardProgress": "Reward",
    "GScriptOpposingCreature": "GScript",
    "PPlannedFootball": "PFootball",
    "PlaytimeElement": "PlaytimeDance",
    "PowerSpinRunner": "PowerSpin",
    "SetupLandscapeBox": "FrontEndSetupMultiplayer",
    "FloatProvider": "Persistent",
    "GConfirmation": "SoundConfirmation",
    "GJAnimVolFX": "PSysModifiers",
    "GSpeedThreshold": "MobileObject",
    "MissionaryControl": "Villager",
    "CImmDevice": "ImmDevice",
    "GAlignmentInfo": "AlignmentInfo",
    "GPBallInfo": "BallInfo",
    "GPFootballInfo": "FootballInfo",
    "GPFootballPositionInfo": "FootballPositionInfo",
    "Waypoint": "WayPoint",
    "AddSpecialRPObjects__FP8RPHolder": "RPHolder",
    "CheckSquareFunction__FiiP8RPHolder": "RPHolder",
    "GFlockInfo": "Flock",
    "DoCitadelMultiplayer__Fv": "Game",
    "MakeTipVideo__Fv": "LoadingScreen",
    "PlayPreIntroVideo__Fv": "PCMain",
    "PlayLogoScreens__Fv": "PCMain",
    "start_system__Fv": "PCMain",
    "free_system__Fv": "PCMain",
    "FreeFonts__Fv": "PCMain",
    "LivingMapCell": "Living",
}


ROOMMATE_CONTAINED_CLASS_SUFFIXES = {
    "__AtomData",
    "__FlyingAtomData",
    "__ParentAtomData",
    "__AtomDataRipple",
    "__CollectionData",
    "__SubCollectionData",
    "__DebrisCollectionData",
    "__FlyingCollectionData",
    "__ParentCollectionData",
    "__Band",
}


def resolve_roommate(struct_name):
    for suffix in ROOMMATE_CONTAINED_CLASS_SUFFIXES:
        if struct_name.endswith(suffix):
            return resolve_roommate(struct_name.removesuffix(suffix))
    struct_name = demangle_type(struct_name)
    if "::" in struct_name:
        split = struct_name.split("::")[0]
        if not "<" in struct_name and not ">" in struct_name:
            return ROOMMATE_CLASS_MAP.get(split, split)
    match = re.search(rf"^({"|".join(LH_COLLECTION_TEMPLATES)})<([^<>\*]+)\*?>", struct_name)
    if match:
        struct_name = match.group(2)
    if '<' in struct_name and not "":
        split = struct_name.split('<')
        if "," not in split[1]:
            struct_name = split[0]
    return ROOMMATE_CLASS_MAP.get(struct_name, ROOMMATE_CLASS_MAP.get(struct_name.replace("::", "__"), struct_name))


def get_released_filepaths():
    file_paths_from_black_white_sinits = {BWPath(r"C:\Dev\black") / i.removeprefix("__sinit_").replace("_cpp", ".cpp") for i in released_sinits_in_black_white}
    # TODO: Guess paths with sinits of LH_Combined_Release_Shared
    return released_filepaths_from_strings.union(file_paths_from_black_white_sinits)


unportable_dev_filepaths = get_released_filepaths().union(guessed_filepaths)
dev_filepaths = {BWPath(str(a.parent).lower().replace("c:", "C:").replace("/mp/", "/").replace("\\mp\\", "\\")) / a.name for a in unportable_dev_filepaths}
regular_filepaths = {Path(a.relative_to(BWPath(r"C:\dev"))) for a in dev_filepaths}
class_to_header_map = {a.stem: a.with_suffix(".h") for a in regular_filepaths}

def filter_paths(path: BWPath) -> BWPath:
    # Define parts to remove
    parts_to_remove = {'debug', 'release', 'mfcdebug', 'mp'}
    # Convert to lower case and filter parts
    filtered_parts = [part.lower() for part in path.parts if part.lower() not in parts_to_remove]
    return BWPath(*filtered_parts)


def get_project_paths() -> set[BWPath]:
    relatives = map(lambda x: x.relative_to(BWPath(r"C:\dev")).parent, dev_filepaths)
    debug_release_stripped = map(filter_paths, relatives)

    return set(debug_release_stripped)


def map_projects_to_object_files() -> dict[BWPath, set[BWPath]]:
    projects = defaultdict(set)
    project_paths = get_project_paths()
    for path in dev_filepaths:
        filtered_path = filter_paths(path.relative_to(BWPath(r"C:\dev")).parent)
        object_file = path.stem + ".obj"
        if filtered_path in project_paths:
            projects[filtered_path].add(object_file)
    return dict(projects)

def get_object_file_base_names() -> set[str]:
    return {i.stem for i in dev_filepaths}

def resolve_vanilla_path(struct_name: str, header_version: bool) -> Path:
    roomate_class_name = resolve_roommate(struct_name)
    if roomate_class_name[0] == 'G' and roomate_class_name[1].isupper():
        roomate_class_name = roomate_class_name[1:]
        if roomate_class_name[0] == 'P' and roomate_class_name[1].isupper():
            roomate_class_name = roomate_class_name[1:]
    if roomate_class_name[1:3] == 'R_' and roomate_class_name[0].isupper():
        roomate_class_name = roomate_class_name[3:]
    return class_to_header_map.get(roomate_class_name)
