#ifndef BW1_DECOMP_BINDABLE_ACTION_INCLUDED_H
#define BW1_DECOMP_BINDABLE_ACTION_INCLUDED_H

#include <assert.h> /* For static_assert */
#include <stdint.h> /* For uint32_t */
#include <uchar.h>  /* For char16_t */

#include <chlasm/LHKeyBoard.h> /* For enum LH_KEY */

enum BINDABLE_ACTIONS
{
	BINDABLE_ACTION_HELP = 0x0,
	BINDABLE_ACTION_MOVE = 0x1,
	BINDABLE_ACTION_ACTION = 0x2,
	BINDABLE_ACTION_ZOOM_OUT = 0x3,
	BINDABLE_ACTION_ZOOM_IN = 0x4,
	BINDABLE_ACTION_TALK = 0x5,
	BINDABLE_ACTION_ZOOM_ON = 0x6,
	BINDABLE_ACTION_MOVE_LEFT = 0x7,
	BINDABLE_ACTION_MOVE_RIGHT = 0x8,
	BINDABLE_ACTION_MOVE_FORWARDS = 0x9,
	BINDABLE_ACTION_MOVE_BACKWARDS = 0xa,
	BINDABLE_ACTION_TILT_UP = 0xb,
	BINDABLE_ACTION_TILT_DOWN = 0xc,
	BINDABLE_ACTION_ROTATE_LEFT = 0xd,
	BINDABLE_ACTION_ROTATE_RIGHT = 0xe,
	BINDABLE_ACTION_ROTATE_ON = 0xf,
	BINDABLE_ACTION_ROTATE_AROUND_MOUSE_ON = 0x10,
	BINDABLE_ACTION_ZOOM_TO_TEMPLE = 0x11,
	BINDABLE_ACTION_ZOOM_TO_CREATURE = 0x12,
	BINDABLE_ACTION_ZOOM_TO_REALM = 0x13,
	BINDABLE_ACTION_ZOOM_TO_INSIDE_TEMPLE = 0x14,
	BINDABLE_ACTION_ZOOM_TO_CREATURE_ROOM = 0x15,
	BINDABLE_ACTION_ZOOM_TO_CHALLENGE_ROOM = 0x16,
	BINDABLE_ACTION_ZOOM_TO_SAVE_GAME_ROOM = 0x17,
	BINDABLE_ACTION_ZOOM_TO_OPTIONS_ROOM = 0x18,
	BINDABLE_ACTION_ZOOM_TO_LIBRARY = 0x19,
	BINDABLE_ACTION_LEASH_UNLEASH_CREATURE = 0x1a,
	BINDABLE_ACTION_SHOW_VILLAGER_NAMES = 0x1b,
	BINDABLE_ACTION_SHOW_VILLAGER_DETAILS = 0x1c,
	BINDABLE_ACTION_QUICK_SAVE = 0x1d,
	BINDABLE_ACTION_QUICK_LOAD = 0x1e,
	BINDABLE_ACTION_PREVIOUS_LEASH = 0x1f,
	BINDABLE_ACTION_NEXT_LEASH = 0x20,
	_BINDABLE_ACTION_SIZE = 0x21,
	_BINDABLE_ACTIONS_COUNT = 0x22
};

struct CMouse
{
	uint32_t field_0x0;

	// Non-virtual methods

	// BW1W120 0061a150 BW1M119 01092f50
	void ProcessButtons();
	// BW1W120 0061a110 BW1M119 01007c90
	void ProcessPosition();
};

struct ControlKey
{
	LH_KEY   key; /* 0x0 */
	char16_t KeyDisplayText[0x40];
	LH_KEY   keymod; /* 0x84 */
	char16_t KeymodDisplayText[0x40];

	// Non-virtual methods

	// BW1W120 0046efe0 BW1M119 inlined
	void GetDisplayText(char16_t* out_text);
};

struct ControlMouse
{
	uint32_t code; /* 0x0 */
	char16_t DisplayText[0x80];

	// Non-virtual methods

	// BW1W120 0046f180 BW1M119 011d4130
	void GetDisplayText(char16_t* out_text);
};

struct BindableAction
{
	char16_t     name[0x80]; /* 0x0 */
	ControlKey   key;        /* 0x100 */
	ControlMouse mouse;      /* 0x208 */

	// Static methods

	// BW1W120 0046f3c0 BW1M119 01092e60
	static bool IsKeyDown(LH_KEY key);

	// Constructors

	// BW1W120 0046f1a0 BW1M119 011d40a0
	BindableAction();

	// Non-virtual methods

	// BW1W120 0046f4c0 BW1M119 01092db0
	bool IsKeyBeingPressed();
};

#endif /* BW1_DECOMP_BINDABLE_ACTION_INCLUDED_H */
