#ifndef BW1_DECOMP_CAMERA_MODE_INCLUDED_H
#define BW1_DECOMP_CAMERA_MODE_INCLUDED_H

#include <assert.h> /* For static_assert */
#include <stdint.h> /* For uint16_t, uint32_t */

enum CAMERA_MODE_HAND_STATUS
{
  CAMERA_MODE_HAND_STATUS_NORMAL = 0x0,
  CAMERA_MODE_HAND_STATUS_ZOOMING = 0x1,
  CAMERA_MODE_HAND_STATUS_TILT_ON = 0x2,
  CAMERA_MODE_HAND_STATUS_GRABBING_LAND = 0x3,
  CAMERA_MODE_HAND_STATUS_PANNING = 0x4,
  CAMERA_MODE_HAND_STATUS_TILTING = 0x5,
  CAMERA_MODE_HAND_STATUS_0x6 = 0x6,
  CAMERA_MODE_HAND_STATUS_0x7 = 0x7,
  CAMERA_MODE_HAND_STATUS_0x8 = 0x8,
  _CAMERA_MODE_HAND_STATUS_COUNT = 0x9
};

enum CAMERA_MODE_MOUSE_STATUS
{
  CAMERA_MODE_MOUSE_STATUS_NONE = 0x0,
  CAMERA_MODE_MOUSE_STATUS_LEFT = 0x1,
  CAMERA_MODE_MOUSE_STATUS_MIDDLE = 0x2,
  _CAMERA_MODE_MOUSE_STATUS_COUNT = 0x3
};

// Forward Declares

class GCamera;
class GameOSFile;
struct LHCoord;

class CameraMode
{
public:
    GCamera* camera; /* 0x4 */
};

#endif /* BW1_DECOMP_CAMERA_MODE_INCLUDED_H */
