#ifndef BW1_DECOMP_CAMERA_HELP_TYPES_INCLUDED_H
#define BW1_DECOMP_CAMERA_HELP_TYPES_INCLUDED_H

enum CH_ANIMTYPE
{
	CH_ANIMTYPE_0x0 = 0x0,
};

enum KEYALIGN
{
	KEYALIGN_0x0 = 0x0,
	KEYALIGN_0x11 = 0x11,
	KEYALIGN_0x300 = 0x300,
	KEYALIGN_0xf00 = 0xf00,
};

#endif /* BW1_DECOMP_CAMERA_HELP_TYPES_INCLUDED_H */
