#ifndef BW1_DECOMP_CREATURE_ACTION_INCLUDED_H
#define BW1_DECOMP_CREATURE_ACTION_INCLUDED_H

#include <assert.h> /* For static_assert */
#include <stdint.h> /* For uint32_t */

#include <chlasm/CreatureEnum.h> /* For NUM_CREATURE_ACTIONS, enum CREATURE_ACTION */
#include <chlasm/Enum.h>         /* For enum MAGIC_TYPE */
#include <re_common.h>           /* For bool32_t */

#include "Base.h"             /* For struct Base */
#include "BaseInfo.h"         /* For struct GBaseInfo */
#include "CreatureMorph.h"    /* For struct LH3DCreature */
#include "GameThingWithPos.h" /* For struct GameThingWithPos */

// The names come from the sub state table (CreatureSubAction::GetSubStateTable on Mac).
enum CREATURE_SUB_STATE_ACTIONS
{
	CREATURE_SUB_STATE_ACTIONS_PICKUP = 0x0,
	CREATURE_SUB_STATE_ACTIONS_DISCARD = 0x1,
	CREATURE_SUB_STATE_ACTIONS_EAT = 0x2,
	CREATURE_SUB_STATE_ACTIONS_HELD_OBJECT_ACTION = 0x3,
	CREATURE_SUB_STATE_ACTIONS_STATIC_ACTION = 0x4,
	CREATURE_SUB_STATE_ACTIONS_THROW = 0x5,
	CREATURE_SUB_STATE_ACTIONS_TURN_TO_FACE_OBJECT = 0x6,
	CREATURE_SUB_STATE_ACTIONS_TURN_TO_FACE_POS = 0x7,
	CREATURE_SUB_STATE_ACTIONS_MOVE_TO_POS = 0x8,
	CREATURE_SUB_STATE_ACTIONS_RUN_AWAY = 0x9,
	CREATURE_SUB_STATE_ACTIONS_INDIVIDUAL_ACTION = 0xa,
	CREATURE_SUB_STATE_ACTIONS_CHOOSE_OBJECT_TO_HURL = 0xb,
	CREATURE_SUB_STATE_ACTIONS_ADD_VILLAGERS_TO_DANCE = 0xc,
	CREATURE_SUB_STATE_ACTIONS_FACIAL_ANIMATION = 0xd,
	CREATURE_SUB_STATE_ACTIONS_FAINT = 0xe,
	CREATURE_SUB_STATE_ACTIONS_POO = 0xf,
	CREATURE_SUB_STATE_ACTIONS_MOVE_TO_THROW_POS = 0x10,
	CREATURE_SUB_STATE_ACTIONS_STOMP = 0x11,
	CREATURE_SUB_STATE_ACTIONS_LOOK_AT_HAND = 0x12,
	CREATURE_SUB_STATE_ACTIONS_RENDER_IMMOBILE = 0x13,
	CREATURE_SUB_STATE_ACTIONS_ADD_TO_SHAPE = 0x14,
	CREATURE_SUB_STATE_ACTIONS_MOVE_TO_DROP_POS = 0x15,
	CREATURE_SUB_STATE_ACTIONS_TURN_TO_FACE_AWAY_FROM_OBJECT = 0x16,
	CREATURE_SUB_STATE_ACTIONS_DANCE = 0x17,
	CREATURE_SUB_STATE_ACTIONS_WAIT = 0x18,
	CREATURE_SUB_STATE_ACTIONS_WAIT_FOR_DANCERS_TO_STOP_MOVING = 0x19,
	CREATURE_SUB_STATE_ACTIONS_WAIT_FOR_DANCERS_TO_START_DANCING = 0x1a,
	CREATURE_SUB_STATE_ACTIONS_HEAL = 0x1b,
	CREATURE_SUB_STATE_ACTIONS_FIGHT = 0x1c,
	CREATURE_SUB_STATE_ACTIONS_STOP_MOVING = 0x1d,
	CREATURE_SUB_STATE_ACTIONS_FOLLOW_CAMERA = 0x1e,
	CREATURE_SUB_STATE_ACTIONS_TURN_TO_FACE_CAMERA = 0x1f,
	CREATURE_SUB_STATE_ACTIONS_COMMUNICATE_TO_PLAYER = 0x20,
	CREATURE_SUB_STATE_ACTIONS_REDUCE_DESIRE = 0x21,
	CREATURE_SUB_STATE_ACTIONS_LOOP = 0x22,
	CREATURE_SUB_STATE_ACTIONS_WALK_ALONG_COAST = 0x23,
	CREATURE_SUB_STATE_ACTIONS_CHECK_VALUE = 0x24,
	CREATURE_SUB_STATE_ACTIONS_REPAIR = 0x25,
	CREATURE_SUB_STATE_ACTIONS_DESTROY_OBJECT = 0x26,
	CREATURE_SUB_STATE_ACTIONS_CAST_SPELL_AT_OBJECT = 0x27,
	CREATURE_SUB_STATE_ACTIONS_CAST_SPELL_AT_POS = 0x28,
	CREATURE_SUB_STATE_ACTIONS_PUT_OUT_FIRE = 0x29,
	CREATURE_SUB_STATE_ACTIONS_DANCING_DURING_EDITOR = 0x2a,
	CREATURE_SUB_STATE_ACTIONS_CAST_SPOT_VISUAL = 0x2b,
	CREATURE_SUB_STATE_ACTIONS_START_THE_DANCE = 0x2c,
	CREATURE_SUB_STATE_ACTIONS_TELL_VILLAGERS_TO_GO_TO_POS = 0x2d,
	CREATURE_SUB_STATE_ACTIONS_TELL_VILLAGERS_TO_DANCE = 0x2e,
	CREATURE_SUB_STATE_ACTIONS_START_LOOKING = 0x2f,
	CREATURE_SUB_STATE_ACTIONS_STOP_LOOKING = 0x30,
	CREATURE_SUB_STATE_ACTIONS_RAISE_TOTEM = 0x31,
	CREATURE_SUB_STATE_ACTIONS_LOWER_TOTEM = 0x32,
	CREATURE_SUB_STATE_ACTIONS_DRINK = 0x33,
	CREATURE_SUB_STATE_ACTIONS_HEAL_HIMSELF = 0x34,
	CREATURE_SUB_STATE_ACTIONS_INSPECT_CREATURE = 0x35,
	CREATURE_SUB_STATE_ACTIONS_CREATE_HAND_OBJECT_FROM_OBJECT = 0x36,
	CREATURE_SUB_STATE_ACTIONS_PICKUP_CREATED_OBJECT = 0x37,
	CREATURE_SUB_STATE_ACTIONS_THROW_AT_POS = 0x38,
	CREATURE_SUB_STATE_ACTIONS_ADD_REACTION_TO_OBJECT = 0x39,
	CREATURE_SUB_STATE_ACTIONS_REQUEST_CREATURE_DO_SOMETHING_WITH_OBJECT = 0x3a,
	CREATURE_SUB_STATE_ACTIONS_RUN_AWAY_FROM_PLAYER = 0x3b,
	CREATURE_SUB_STATE_ACTIONS_START_FIRE = 0x3c,
	CREATURE_SUB_STATE_ACTIONS_GO_NEAR_OBJECT = 0x3d,
	CREATURE_SUB_STATE_ACTIONS_OBSERVE_OBJECT = 0x3e,
	CREATURE_SUB_STATE_ACTIONS_FOLLOW_INTERESTING_OBJECT = 0x3f,
	CREATURE_SUB_STATE_ACTIONS_IN_SCRIPT = 0x40,
	CREATURE_SUB_STATE_ACTIONS_LOOK_AT_FLYING_OBJECT = 0x41,
	CREATURE_SUB_STATE_ACTIONS_LOOK_AT_CAMERA = 0x42,
	CREATURE_SUB_STATE_ACTIONS_FOLLOW_HAND = 0x43,
	CREATURE_SUB_STATE_ACTIONS_FACE_DOWN_SLOPE = 0x44,
	CREATURE_SUB_STATE_ACTIONS_ADD_TO_HOME = 0x45,
	CREATURE_SUB_STATE_ACTIONS_WAIT_FOR_OBJECT = 0x46,
	CREATURE_SUB_STATE_ACTIONS_SEE_WHO_WINS_GAME = 0x47,
	CREATURE_SUB_STATE_ACTIONS_RESPOND_AFTER_FIGHT = 0x48,
	CREATURE_SUB_STATE_ACTIONS_CREATE_FOOT_PRINT = 0x49,
	CREATURE_SUB_STATE_ACTIONS_ORDER_CREATURE = 0x4a,
	CREATURE_SUB_STATE_ACTIONS_WAIT_FOR_CREATURE_TO_PICK_UP = 0x4b,
	CREATURE_SUB_STATE_ACTIONS_DEMOBILISE_OBJECT = 0x4c,
	CREATURE_SUB_STATE_ACTIONS_REMOBILISE_OBJECT = 0x4d,
	CREATURE_SUB_STATE_ACTIONS_WAIT_FOREVER = 0x4e,
	CREATURE_SUB_STATE_ACTIONS_KISS = 0x4f,
	CREATURE_SUB_STATE_ACTIONS_POINT_AT_POINT = 0x50,
	CREATURE_SUB_STATE_ACTIONS_POINT_AT_OBJECT = 0x51,
	CREATURE_SUB_STATE_ACTIONS_DO_TELEPORT = 0x52,
	CREATURE_SUB_STATE_ACTIONS_STOP_REACTING = 0x53,
	CREATURE_SUB_STATE_ACTIONS_SET_SPEED = 0x54,
	CREATURE_SUB_STATE_ACTIONS_TURN_TO_FACE_HAND = 0x55,
	CREATURE_SUB_STATE_ACTIONS_PICK_UP_FROM_HAND = 0x56,
	CREATURE_SUB_STATE_ACTIONS_TURN_TO_FACE_OTHER_PLAYERS_CAMERA = 0x57,
	CREATURE_SUB_STATE_ACTIONS_GESTURE = 0x58,
	CREATURE_SUB_STATE_ACTIONS_REQUEST_PARTNER = 0x59,
	CREATURE_SUB_STATE_ACTIONS_WAIT_FOR_CREATURE_TO_BE_FREE = 0x5a,
	CREATURE_SUB_STATE_ACTIONS_ACT_ON_OBJECT_IN_HAND = 0x5b,
	CREATURE_SUB_STATE_ACTIONS_CREATE_FISH_FROM_SEA = 0x5c,
	CREATURE_SUB_STATE_ACTIONS_TRANSPORTED_BY_TELEPORT = 0x5d,
	CREATURE_SUB_STATE_ACTIONS_PRACTICE_DANCE = 0x5e,
	CREATURE_SUB_STATE_ACTIONS_THROW_IN_PILE = 0x5f,
	CREATURE_SUB_STATE_ACTIONS_LOOP_ACTION = 0x60,
	CREATURE_SUB_STATE_ACTIONS_CONSIDER_ACTION_COMPLETED = 0x61,
	CREATURE_SUB_STATE_ACTIONS_CREATE_ARENA = 0x62,
	CREATURE_SUB_STATE_ACTIONS_MOVE_TO_ARENA = 0x63,
	CREATURE_SUB_STATE_ACTIONS_TELL_VILLAGERS_TO_ENTER_STATE = 0x64,
	CREATURE_SUB_STATE_ACTIONS_RESURRECT = 0x65,
	CREATURE_SUB_STATE_ACTIONS_SWAP_MIND_WITH_OTHER_CREATURE = 0x66,
	CREATURE_SUB_STATE_ACTIONS_FAIL = 0x67,
	CREATURE_SUB_STATE_ACTIONS_WAIT_FOR_OBJECT_TO_BE_IN_MAP = 0x68,
	CREATURE_SUB_STATE_ACTIONS_SET_POS = 0x69,
	CREATURE_SUB_STATE_ACTIONS_HIDE_OBJECT_IN_HAND = 0x6a,
	CREATURE_SUB_STATE_ACTIONS_DESTROY_OBJECT_TO_USE = 0x6b,
	CREATURE_SUB_STATE_ACTIONS_CLEAR_OBJECT_TO_ACT_ON = 0x6c,
	CREATURE_SUB_STATE_ACTIONS_CLEAR_OBJECT_TO_USE = 0x6d,
	CREATURE_SUB_STATE_ACTIONS_CATCH = 0x6e,
	CREATURE_SUB_STATE_ACTIONS_KICK_OBJECT = 0x6f,
	CREATURE_SUB_STATE_ACTIONS_TRANPORT_HOME = 0x70,
	CREATURE_SUB_STATE_ACTIONS_REMOVE_AND_CREATE_SPELL_FROM_TOTEM_STATUE = 0x71,
	CREATURE_SUB_STATE_ACTIONS_ADD_AND_DESTROY_SPELL_FROM_TOTEM_STATUE = 0x72,
	CREATURE_SUB_STATE_ACTIONS_MOVE_TO_THROW_AT_POS = 0x73,
	CREATURE_SUB_STATE_ACTIONS_LIGHTBULB = 0x74,
	CREATURE_SUB_STATE_ACTIONS_SHATTER_ROCK = 0x75,
	CREATURE_SUB_STATE_ACTIONS_PICK_UP_OBJECT_CREATED_BY_CREATURE = 0x76,
	CREATURE_SUB_STATE_ACTIONS_DESTROY_CREATED_OBJECT = 0x77,
	CREATURE_SUB_STATE_ACTIONS_CREATED_HAND_OBJECT_EX_NIHILO = 0x78,
	CREATURE_SUB_STATE_ACTIONS_APPLY_DESIRE_TO_OBJECT = 0x79,
	CREATURE_SUB_STATE_ACTIONS_MOVE_TO_WATER = 0x7a,
	CREATURE_SUB_STATE_ACTIONS_STOP_CONTROLLED_BY_TELEPORT = 0x7b,
	CREATURE_SUB_STATE_ACTIONS_WATCH_PLAYER_WHILE_HE_HAS_YOUR_ATTENTION = 0x7c,
	CREATURE_SUB_STATE_ACTIONS_MAKE_DISCIPLE = 0x7d,
	CREATURE_SUB_STATE_ACTIONS_SET_DANCE = 0x7e,
	CREATURE_SUB_STATE_ACTIONS_SINGLE_KISS = 0x7f,
	CREATURE_SUB_STATE_ACTIONS_EAT_CREATED_OBJECT = 0x80,
	CREATURE_SUB_STATE_ACTIONS_POINT_AT_ARENA = 0x81,
	CREATURE_SUB_STATE_ACTIONS_REST_TO_GET_BETTER = 0x82,
	CREATURE_SUB_STATE_ACTIONS_TELL_VILLAGERS_TO_GO_TO_START_DANCE_POS = 0x83,
	CREATURE_SUB_STATE_ACTIONS_SLEEP = 0x84,
	CREATURE_SUB_STATE_ACTIONS_WAIT_UNTIL_FREE = 0x85,
	CREATURE_SUB_STATE_ACTIONS_STOP_BEING_ON_FIRE = 0x86,
	CREATURE_SUB_STATE_ACTIONS_GET_AWAY_FROM_OBJECT = 0x87,
	CREATURE_SUB_STATE_ACTIONS_LOOK_AT_CAMERA_IN_WIDE_SCREEN = 0x88,
	CREATURE_SUB_STATE_ACTIONS_TALK = 0x89,
	CREATURE_SUB_STATE_ACTIONS_CREATE_PICK_UP_THEN_REMOVE = 0x8a,
	CREATURE_SUB_STATE_ACTIONS_WAIT_FOR_SPELLS_TO_WEAR_OFF = 0x8b,
	CREATURE_SUB_STATE_ACTIONS_CREATE_MAGIC_FOOD = 0x8c,
	CREATURE_SUB_STATE_ACTIONS_BUILD = 0x8d,
	CREATURE_SUB_STATE_ACTIONS_EAT_NEAREST_FOOD_PILE = 0x8e,
	CREATURE_SUB_STATE_ACTIONS_LAST = 0x8f
};

// Forward Declares

class Creature;
class CreatureAgenda;
class CreatureContext;
class CreaturePlan;
class Morphable;
struct CreatureActionContext;

struct CreatureActionTableEntry;

struct CreatureActionContextStart
{
	uint32_t               field_0x0;
	CreatureActionContext* field_0x4;
	uint32_t               field_0x8;
	uint32_t               field_0xc;
	uint32_t               field_0x10;
};

struct CreatureActionContext
{
	CreatureActionContextStart start; /* 0x0 */
	float                      field_0x14;

	// Constructors

	// BW1W120 004c3960 BW1M119 01235210
	CreatureActionContext(CreatureContext& context, float param_2);
};

struct PreviousActionContextStack
{
	uint32_t              indexes[0x2][0x148]; /* 0x0 */
	CreatureActionContext stack[0x148][0xa];   /* 0xa40 */
};

struct CreatureActionOpinions
{
	uint32_t entries[NUM_CREATURE_ACTIONS]; /* 0x0 */

	// Constructors

	// BW1W120 004c3930 BW1M119 01235290
	CreatureActionOpinions();
};

class CreaturePreviousActions : public Base
{
public:
	float field_0x8[NUM_CREATURE_ACTIONS];

	// Override methods

	// BW1W120 004f2040 BW1M119 0124aef0
	virtual ~CreaturePreviousActions();
};

class CreatureActionKnownAbout : public Base
{
public:
	// Override methods

	// BW1W120 004e29b0 BW1M119 0126a9e0
	virtual ~CreatureActionKnownAbout();
};

class CreatureActionKnownAboutEntry : public GBaseInfo
{
public:
	// Override methods

	// BW1W120 004e2db0 BW1M119 0126b4a0
	virtual ~CreatureActionKnownAboutEntry();
	// BW1W120 004e2d50 BW1M119 0126b710
	virtual GBaseInfo* GetBaseInfo(uint32_t& param_1);
};

class CreatureFalling : public LH3DCreature
{
public:
	// Override methods

	// The Windows table uses LH3DCreature::SetAnimTime, not a separate override.
};

class CreatureMagicActionKnownAboutEntry : public CreatureActionKnownAboutEntry
{
public:
	// Override methods

	// BW1W120 004e2e50 BW1M119 0126b370
	virtual ~CreatureMagicActionKnownAboutEntry();
};

#endif /* BW1_DECOMP_CREATURE_ACTION_INCLUDED_H */
