#ifndef BW1_DECOMP_GAME_LANGUAGE_INCLUDED_H
#define BW1_DECOMP_GAME_LANGUAGE_INCLUDED_H

enum GAME_LANGUAGE
{
	GAME_LANGUAGE_UK_ENGLISH = 0,
	GAME_LANGUAGE_US_ENGLISH = 1,
	GAME_LANGUAGE_FRENCH = 2,
	GAME_LANGUAGE_GERMAN = 3,
	GAME_LANGUAGE_SWEDISH = 4,
	GAME_LANGUAGE_SPANISH = 5,
	GAME_LANGUAGE_JAPANESE = 6,
	GAME_LANGUAGE_DUTCH = 7,
	GAME_LANGUAGE_BRAZILIAN_PORTUGUESE = 8,
	GAME_LANGUAGE_ITALIAN = 9,
	GAME_LANGUAGE_SIMPLIFIED_CHINESE = 10,
	GAME_LANGUAGE_TRADITIONAL_CHINESE = 11,
	GAME_LANGUAGE_POLISH = 12,
	GAME_LANGUAGE_KOREAN = 13,
	GAME_LANGUAGE_THAI = 14
};

#endif /* BW1_DECOMP_GAME_LANGUAGE_INCLUDED_H */
