#ifndef BW1_DECOMP_GESTURE_CONSTANTS_INCLUDED_H
#define BW1_DECOMP_GESTURE_CONSTANTS_INCLUDED_H

#include <Lionhead/LH3DLib/development/LH3DMath.h> /* For EIGHTH_PI_F */

const float GESTURE_HALF_SECTOR_ANGLE = EIGHTH_PI_F;
const float GESTURE_ANGLE_TOLERANCE = (GESTURE_HALF_SECTOR_ANGLE * 3) / 4;
const float GESTURE_SECTOR_ANGLE = GESTURE_HALF_SECTOR_ANGLE * 2;
const float GESTURE_SECTOR_TOLERANCE = (GESTURE_SECTOR_ANGLE * 7) / 8;
const float GESTURE_WIDE_ANGLE_TOLERANCE = (GESTURE_ANGLE_TOLERANCE * 7) / 4;
const float GESTURE_DOUBLE_ANGLE_TOLERANCE = GESTURE_ANGLE_TOLERANCE * 2;

#endif /* BW1_DECOMP_GESTURE_CONSTANTS_INCLUDED_H */
