#include <re_common.h>

#include <chlasm/GStates.h> /* For enum VILLAGER_STATES, VILLAGER_STATE_LAST_STATE, ANIMAL_STATE_LAST_STATE */

class Animal;
class GameOSFile;
class Villager;

template <typename T> struct LivingStateTableEntry
{
	uint32_t (T::*state)();
	uint32_t (T::*EntryState)(uint8_t, uint8_t);
	uint32_t (T::*ExitState)(uint8_t);
	uint32_t (T::*SaveState)(GameOSFile&);
	uint32_t (T::*LoadState)(GameOSFile&);
	uint32_t (T::*ReactToTownEmergency)();
	uint32_t (T::*Animation)();
	uint32_t (T::*TransitionAnimation)(uint8_t, uint8_t);
	void (T::*validate)();
};

// Instantiates both specialisations while Villager and Animal are still incomplete,
// forcing MSVC's most-general 16-byte pointer-to-member form and a 144-byte entry.
// Once the definitions below are visible the classes look single-inheritance and the
// pointers would shrink to 4. Do not move the includes above this.
enum
{
	VillagerEntrySize = sizeof(LivingStateTableEntry<Villager>),
	AnimalEntrySize = sizeof(LivingStateTableEntry<Animal>),
};

#include "Animal.h"
#include "Living.h"
#include "Villager.h"

// clang-format off
// BW1W120 00D09198 BW1M100 
LivingStateTableEntry<Villager> g_VillagerStateTable[VILLAGER_STATE_LAST_STATE] = {
	{&Living::InvalidState, 0, 0, 0, 0, 0, 0, 0, 0},
	{&Living::MoveToPos, 0, &Living::ExitMoveToPos, 0, 0, &Villager::AlwaysReactToTownEmergency, &Villager::MoveToPosAnimation, &Villager::MoveToPosIntoOutofAnimation, &Villager::WallhugValidate},
	{&Living::MoveToObject, 0, &Living::ExitMoveToPos, 0, 0, &Villager::AlwaysReactToTownEmergency, &Villager::MoveToPosAnimation, &Villager::MoveToPosIntoOutofAnimation, &Villager::MoveToObjectValidate},
	{&Living::MoveOnStructure, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, &Villager::MoveToPosAnimation, &Villager::MoveToPosIntoOutofAnimation, &Villager::MoveOnStructureValidate},
	{&Living::StateInScript, &Living::EnterInScript, &Living::ExitInScript, &Villager::SaveInScript, &Villager::LoadInScript, 0, 0, 0, 0},
	{&Living::StateInDance, &Living::EnterDanceInScript, &Living::ExitDanceInScript, &Villager::SaveDance, &Villager::LoadDance, 0, &Villager::DanceAnimation, 0, 0},
	{&Living::StateFleeingFromObjectReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, &Villager::MoveToPosAnimation, &Villager::MoveToPosIntoOutofAnimation, &Villager::ReactionValidate},
	{&Living::StateLookingAtObjectReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Living::StateFollowingObjectReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Living::StateInspectObjectReaction, 0, &Living::ExitReaction, &Villager::SaveInspectionReaction, &Villager::LoadInspectionReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Living::Flying, 0, &Living::ExitInFlying, &Villager::SaveInFlying, &Villager::LoadInFlying, 0, &Villager::ThrownAnimation, 0, 0},
	{&Villager::Landed, 0, &Living::ExitInLanded, &Villager::SaveLanded, &Villager::LoadLanded, 0, &Villager::LandedAnimation, 0, 0},
	{&Living::StateLookingAtFlyingObjectReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, &Villager::LookAtFlyingObjectAnimation, 0, &Villager::ReactionValidate},
	{&Living::StateSetDying, 0, 0, &Villager::SaveDead, &Villager::LoadDead, 0, 0, 0, 0},
	{&Living::StateDying, 0, 0, &Villager::SaveDead, &Villager::LoadDead, 0, &Villager::DyingAnimation, 0, 0},
	{&Living::StateDead, 0, &Living::CannotExitState, &Villager::SaveDead, &Villager::LoadDead, 0, &Villager::DeadAnimation, 0, 0},
	{&Villager::Drowning, &Villager::EnterDrowning, &Villager::ExitDrowning, 0, 0, 0, 0, 0, 0},
	{&Living::StateDowned, 0, 0, 0, 0, 0, 0, 0, 0},
	{&Living::StateBeingEaten, 0, &Living::ExitBeingEaten, 0, 0, 0, 0, 0, 0},
	{&Living::StateGoToFoodReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Living::StateArrivesAtFoodReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, 0, &Villager::ArrivesAtResourceIntoOutofAnimation, &Villager::ReactionValidate},
	{&Living::StateGoToWoodReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Living::StateArrivesAtWoodReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, 0, &Villager::ArrivesAtResourceIntoOutofAnimation, &Villager::ReactionValidate},
	{&Living::WaitForAnimation, 0, 0, &Villager::SaveWaitForAnim, &Villager::LoadWaitForAnim, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Living::StateInHand, &Villager::EnterInHand, &Living::ExitInHand, &Villager::SaveInHand, &Villager::LoadInHand, 0, 0, 0, 0},
	{&Living::GotoPickupBallReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Villager::ArrivesAtPickupBallReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Living::StateMoveInFlock, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Living::StateAlongPath, &Living::EnterInScript, &Living::ExitInScript, &Villager::SaveFootPath, &Villager::LoadFootPath, &Villager::AlwaysReactToTownEmergency, &Villager::MoveToPosAnimation, &Villager::MoveToPosIntoOutofAnimation, 0},
	{&Living::MoveOnFootpath, &Living::EnterMoveOnPath, &Living::ExitMoveOnPath, &Villager::SaveFootPath, &Villager::LoadFootPath, &Villager::AlwaysReactToTownEmergency, &Villager::MoveToPosAnimation, &Villager::MoveToPosIntoOutofAnimation, 0},
	{&Living::StateFleeingAndLookingAtObjectReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Villager::GotoStoragePitForDropOff, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ArrivesAtStoragePitForDropOff, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::GotoStoragePitForFood, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ArrivesAtStoragePitForFood, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ArrivesAtHomeWithFood, 0, &Villager::ExitAtHome, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::GoHome, 0, &Villager::ExitAtHome, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ArrivesHome, 0, &Villager::ExitAtHome, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::AtHome, 0, &Villager::ExitAtHome, 0, 0, 0, 0, 0, 0},
	{&Villager::ArrivesAtStoragePitForBuildingMaterials, &Villager::EnterBuilding, &Villager::ExitBuilding, &Villager::SaveBuilding, &Villager::LoadBuilding, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ArrivesAtBuildingSite, &Villager::EnterBuilding, &Villager::ExitBuilding, &Villager::SaveBuilding, &Villager::LoadBuilding, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::Building, &Villager::EnterBuilding, &Villager::ExitBuilding, &Villager::SaveBuilding, &Villager::LoadBuilding, &Villager::AlwaysReactToTownEmergency, &Villager::BuildingAnimation, &Villager::BuildingIntoOutofAnimation, 0},
	{&Villager::GotoStoragePitForWorshipSupplies, 0, &Villager::ExitMoveToWorshipSiteWithSupplies, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ArrivesAtStoragePitForWorshipSupplies, 0, &Villager::ExitMoveToWorshipSiteWithSupplies, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::GotoWorshipSiteWithSupplies, 0, &Villager::ExitMoveToWorshipSiteWithSupplies, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::MoveToWorshipSiteWithSupplies, 0, &Villager::ExitMoveToWorshipSiteWithSupplies, 0, 0, &Villager::AlwaysReactToTownEmergency, &Villager::MoveToPosAnimation, &Villager::MoveToPosIntoOutofAnimation, 0},
	{&Villager::ArrivesAtWorshipSiteWithSupplies, 0, &Villager::ExitMoveToWorshipSiteWithSupplies, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ForesterMoveToForest, 0, &Villager::ExitForesting, 0, 0, &Villager::AlwaysReactToTownEmergency, &Villager::MoveToPosAnimation, &Villager::MoveToPosIntoOutofAnimation, &Villager::WallhugValidate},
	{&Villager::ForesterGotoForest, 0, &Villager::ExitForesting, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ForesterArrivesAtForest, 0, &Villager::ExitForesting, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ForesterChopsTree, 0, &Villager::ExitForesting, &Villager::SaveForesting, &Villager::LoadForesting, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ForesterChopsTreeForBuilding, &Villager::EnterBuilding, &Villager::ExitBuilding, &Villager::SaveBuilding, &Villager::LoadBuilding, &Villager::AlwaysReactToTownEmergency, &Villager::ForesteringAnimation, 0, 0},
	{&Villager::ForesterFinishedForestering, 0, &Villager::ExitForesting, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ArrivesAtBigForest, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ArrivesAtBigForestForBuilding, &Villager::EnterBuilding, &Villager::ExitBuilding, &Villager::SaveBuilding, &Villager::LoadBuilding, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::FishermanArrivesAtFishing, &Villager::EnterFishing, &Villager::ExitFishing, &Villager::SaveFishing, &Villager::LoadFishing, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::Fishing, &Villager::EnterFishing, &Villager::ExitFishing, &Villager::SaveFishing, &Villager::LoadFishing, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Living::WaitForCounter, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::GotoWorshipSiteForWorship, 0, &Villager::ExitMoveToWorshipSite, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ArrivesAtWorshipSiteForWorship, 0, &Villager::ExitMoveToWorshipSite, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::WorshippingAtWorshipSite, 0, &Villager::ExitAtWorshipSite, &Villager::SaveWorship, &Villager::LoadWorship, &Villager::AlwaysReactToTownEmergency, &Villager::DanceAnimation, 0, 0},
	{&Villager::GotoAltarForRest, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ArrivesAtAltarForRest, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::AtAltarRest, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, &Villager::PrayIntoOutofAnimation, 0},
	{&Villager::AtAltarFinishedRest, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::RestartWorshippingAtWorshipSite, 0, &Villager::ExitGetFoodAtWorship, 0, 0, &Villager::AlwaysReactToTownEmergency, &Villager::DanceAnimation, 0, 0},
	{&Villager::RestartWorshippingCreature, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, &Villager::DanceAnimation, 0, 0},
	{&Villager::FarmerArrivesAtFarm, &Villager::EnterFarming, &Villager::ExitFarming, &Villager::SaveFarming, &Villager::LoadFarming, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::FarmerPlantsCrop, &Villager::EnterFarming, &Villager::ExitFarming, &Villager::SaveFarming, &Villager::LoadFarming, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::FarmerDigsUpCrop, &Villager::EnterFarming, &Villager::ExitFarming, &Villager::SaveFarming, &Villager::LoadFarming, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::MoveToFootballPitchConstruction, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::FootballWalkToPosition, 0, &Villager::ExitFootball, &Villager::SaveFootball, &Villager::LoadFootball, &Villager::AlwaysReactToTownEmergency, &Villager::MoveToPosAnimation, &Villager::MoveToPosIntoOutofAnimation, &Villager::WallhugValidate},
	{&Villager::WaitForKickOff, 0, &Villager::ExitFootball, &Villager::SaveFootball, &Villager::LoadFootball, &Villager::AlwaysReactToTownEmergency, &Villager::FootballWaitForKickOffAnimation, 0, 0},
	{&Villager::FootballAttacker, 0, &Villager::ExitFootball, &Villager::SaveFootball, &Villager::LoadFootball, &Villager::AlwaysReactToTownEmergency, &Villager::FootballAttackerAnimation, 0, 0},
	{&Villager::FootballGoalie, 0, &Villager::ExitFootball, &Villager::SaveFootball, &Villager::LoadFootball, &Villager::AlwaysReactToTownEmergency, &Villager::FootballGoalKeeperAnimation, 0, 0},
	{&Villager::FootballDefender, 0, &Villager::ExitFootball, &Villager::SaveFootball, &Villager::LoadFootball, &Villager::AlwaysReactToTownEmergency, &Villager::FootballDefenderAnimation, 0, 0},
	{&Villager::FootballWonGoal, 0, &Villager::ExitFootball, &Villager::SaveFootball, &Villager::LoadFootball, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::FootballLostGoal, 0, &Villager::ExitFootball, &Villager::SaveFootball, &Villager::LoadFootball, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::StartMoveToPickUpBallForDeadBall, 0, &Villager::ExitFootball, &Villager::SaveFootball, &Villager::LoadFootball, &Villager::AlwaysReactToTownEmergency, &Villager::MoveToPosAnimation, &Villager::MoveToPosIntoOutofAnimation, 0},
	{&Villager::ArrivedAtPickUpBallForDeadBall, 0, &Villager::ExitFootball, &Villager::SaveFootball, &Villager::LoadFootball, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ArrivedAtPutDownBallForDeadBallStart, 0, &Villager::ExitFootball, &Villager::SaveFootball, &Villager::LoadFootball, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ArrivedAtPutDownBallForDeadBallEnd, 0, &Villager::ExitFootball, &Villager::SaveFootball, &Villager::LoadFootball, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::FootballMatchPaused, 0, &Villager::ExitFootball, &Villager::SaveFootball, &Villager::LoadFootball, &Villager::AlwaysReactToTownEmergency, &Villager::FootballMatchPausedAnimation, 0, 0},
	{&Villager::FootballWatchMatch, 0, &Villager::ExitFootball, &Villager::SaveFootball, &Villager::LoadFootball, &Villager::AlwaysReactToTownEmergency, &Villager::FootballWatchMatchAnimation, 0, 0},
	{&Villager::FootballMexicanWave, 0, &Villager::ExitFootball, &Villager::SaveFootball, &Villager::LoadFootball, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::VillagerCreated, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ArrivesInAbodeToTrade, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ArrivesInAbodeToPickUpExcess, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::MakeScaredStiff, 0, 0, 0, 0, 0, 0, 0, 0},
	{&Villager::ScaredStiff, 0, 0, 0, 0, 0, 0, 0, 0},
	{&Villager::WorshippingCreature, 0, &Villager::ExitDance, &Villager::SaveDance, &Villager::LoadDance, &Villager::AlwaysReactToTownEmergency, &Villager::DanceAnimation, 0, 0},
	{&Villager::ShepherdLookForFlock, 0, &Villager::ExitShepherding, &Villager::SaveShepherd, &Villager::LoadShepherd, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ShepherdMoveFlockToWater, 0, &Villager::ExitShepherding, &Villager::SaveShepherd, &Villager::LoadShepherd, &Villager::AlwaysReactToTownEmergency, &Villager::MoveToPosAnimation, &Villager::MoveToPosIntoOutofAnimation, 0},
	{&Villager::ShepherdMoveFlockToFood, 0, &Villager::ExitShepherding, &Villager::SaveShepherd, &Villager::LoadShepherd, &Villager::AlwaysReactToTownEmergency, &Villager::MoveToPosAnimation, &Villager::MoveToPosIntoOutofAnimation, 0},
	{&Villager::ShepherdMoveFlockBack, 0, &Villager::ExitShepherding, &Villager::SaveShepherd, &Villager::LoadShepherd, &Villager::AlwaysReactToTownEmergency, &Villager::MoveToPosAnimation, &Villager::MoveToPosIntoOutofAnimation, 0},
	{&Villager::ShepherdDecideWhatToDoWithFlock, 0, &Villager::ExitShepherding, &Villager::SaveShepherd, &Villager::LoadShepherd, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ShepherdWaitForFlock, 0, &Villager::ExitShepherding, &Villager::SaveShepherd, &Villager::LoadShepherd, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ShepherdSlaughterAnimal, 0, &Villager::ExitShepherding, &Villager::SaveShepherd, &Villager::LoadShepherd, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ShepherdFetchStray, 0, &Villager::ExitShepherding, &Villager::SaveShepherd, &Villager::LoadShepherd, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ShepherdGotoFlock, 0, &Villager::ExitShepherding, &Villager::SaveShepherd, &Villager::LoadShepherd, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::HousewifeAtHome, 0, &Villager::ExitAtHome, 0, 0, 0, 0, 0, 0},
	{&Villager::HousewifeGotoStoragePit, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::HousewifeArrivesAtStoragePit, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::HousewifePickupFromStoragePit, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::HousewifeReturnHomeWithFood, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::HousewifeMakeDinner, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::HousewifeServesDinner, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::HousewifeClearsAwayDinner, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::HousewifeDoesHousework, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::HousewifeGossipsAroundStoragePit, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::HousewifeStartsGivingBirth, 0, 0, 0, 0, 0, 0, 0, 0},
	{&Villager::HousewifeGivingBirth, 0, 0, 0, 0, 0, 0, 0, 0},
	{&Villager::HousewifeGivenBirth, 0, 0, 0, 0, 0, 0, 0, 0},
	{&Villager::ChildAtCreche, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ChildFollowsMother, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ChildBecomesAdult, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::SitsDownToDinner, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::EatFood, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::EatFoodAtHome, 0, &Villager::ExitAtHome, 0, 0, 0, 0, 0, 0},
	{&Villager::GotoBedAtHome, 0, &Villager::ExitAtHome, 0, 0, 0, 0, 0, 0},
	{&Villager::SleepingAtHome, 0, &Villager::ExitAtHome, 0, 0, 0, 0, 0, 0},
	{&Villager::WakeUpAtHome, 0, &Villager::ExitAtHome, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::StartHavingSex, &Villager::EnterSex, &Villager::ExitSex, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::SexValidate},
	{&Villager::HavingSex, &Villager::EnterSex, &Villager::ExitSex, 0, 0, &Villager::AlwaysReactToTownEmergency, &Villager::KissingAnimation, 0, 0},
	{&Villager::StopHavingSex, &Villager::EnterSex, &Villager::ExitSex, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::StartHavingSexAtHome, 0, &Villager::ExitAtHome, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::HavingSexAtHome, 0, &Villager::ExitAtHome, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::StopHavingSexAtHome, 0, &Villager::ExitAtHome, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::WaitForDinner, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::HomelessStart, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::VagrantStart, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::MornDeath, 0, 0, 0, 0, 0, 0, &Villager::MournIntoOutofAnimation, 0},
	{&Villager::PerformInspectionReaction, 0, 0, &Villager::SaveInspectionReaction, &Villager::LoadInspectionReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ApproachObjectReaction, 0, 0, &Villager::SaveInspectionReaction, &Villager::LoadInspectionReaction, &Villager::AlwaysReactToTownEmergency, &Villager::MoveToPosAnimation, &Villager::MoveToPosIntoOutofAnimation, 0},
	{&Villager::InitialiseTellOthersAboutObject, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::TellOthersAboutInterestingObject, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ApproachVillagerToTalkTo, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, &Villager::MoveToPosAnimation, &Villager::MoveToPosIntoOutofAnimation, 0},
	{&Villager::TellParticularVillagerAboutObject, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::InitialiseLookAroundForVillagerToTell, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::LookAroundForVillagerToTell, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::MoveTowardsObjectToLookAt, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, &Villager::MoveToPosAnimation, &Villager::MoveToPosIntoOutofAnimation, &Villager::WallhugAndReactionValidate},
	{&Villager::InitialiseImpressedReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Villager::PerformImpressedReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, 0, &Villager::PrayIntoOutofAnimation, &Villager::ReactionValidate},
	{&Villager::InitialiseFightReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Villager::PerformFightReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, &Villager::WatchFightAnimation, 0, &Villager::ReactionValidate},
	{&Villager::HomelessEatDinner, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::InspectCreatureReaction, 0, &Living::ExitReaction, &Villager::SaveInspectionReaction, &Villager::LoadInspectionReaction, &Villager::AlwaysReactToTownEmergency, &Villager::InspectCreatureAnimation, 0, &Villager::ReactionValidate},
	{&Villager::PerformInspectCreatureReaction, 0, &Living::ExitReaction, &Villager::SaveInspectionReaction, &Villager::LoadInspectionReaction, &Villager::AlwaysReactToTownEmergency, &Villager::InspectCreatureAnimation, 0, &Villager::ReactionValidate},
	{&Villager::ApproachCreatureReaction, 0, &Living::ExitReaction, &Villager::SaveInspectionReaction, &Villager::LoadInspectionReaction, &Villager::AlwaysReactToTownEmergency, &Villager::InspectCreatureAnimation, 0, &Villager::ReactionValidate},
	{&Villager::InitialiseBewilderedByMagicTreeReaction, 0, &Living::ExitReaction, &Villager::SaveMagicTreeReaction, &Villager::LoadMagicTreeReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Villager::PerformBewilderedByMagicTreeReaction, 0, &Living::ExitReaction, &Villager::SaveMagicTreeReaction, &Villager::LoadMagicTreeReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Villager::TurnToFaceMagicTree, 0, &Living::ExitReaction, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Villager::LookAtMagicTree, 0, &Living::ExitReaction, 0, 0, &Villager::AlwaysReactToTownEmergency, &Villager::LookAtLargeObjectAnimation, 0, &Villager::ReactionValidate},
	{&Villager::DanceForEditingPurposes, 0, &Villager::ExitDance, &Villager::SaveDance, &Villager::LoadDance, &Villager::AlwaysReactToTownEmergency, &Villager::DanceAnimation, 0, 0},
	{&Villager::MoveToDancePos, 0, 0, &Villager::SaveDance, &Villager::LoadDance, &Villager::AlwaysReactToTownEmergency, &Villager::MoveToPosAnimation, &Villager::MoveToPosIntoOutofAnimation, &Villager::WallhugValidate},
	{&Villager::InitialiseRespectCreatureReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, &Villager::RespectCreatureAnimation, 0, &Villager::ReactionValidate},
	{&Villager::PerformRespectCreatureReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, &Villager::RespectCreatureAnimation, 0, &Villager::ReactionValidate},
	{&Villager::FinishRespectCreatureReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, &Villager::RespectCreatureAnimation, 0, &Villager::ReactionValidate},
	{&Villager::ApproachHandReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Villager::FleeingFromCreatureReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Villager::TurnToFaceCreatureReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, &Villager::InspectCreatureAnimation, 0, &Villager::ReactionValidate},
	{&Villager::WatchFlyingObjectReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, &Villager::LookAtFlyingObjectAnimation, 0, &Villager::ReactionValidate},
	{&Villager::PointAtFlyingObjectReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, &Villager::PointAtFlyingObjectAnimation, 0, &Villager::ReactionValidate},
	{&Living::DecideWhatToDo, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::InteractDecideWhatToDo, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::EatOutside, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::RunAwayFromObjectReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Villager::MoveTowardsCreatureReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, &Villager::MoveToPosAnimation, &Villager::MoveToPosIntoOutofAnimation, &Villager::WallhugAndReactionValidate},
	{&Villager::AmazedByMagicShieldReaction, 0, &Living::ExitReaction, &Villager::SaveShieldReaction, &Villager::LoadShieldReaction, 0, &Villager::AmazedByShieldAnimation, 0, &Villager::ReactionValidate},
	{&Villager::VillagerGossips, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::CheckInteractWithAnimal, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::CheckInteractWithWorshipSite, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::CheckInteractWithAbode, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::CheckInteractWithField, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::CheckInteractWithFishFarm, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::CheckInteractWithTree, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::CheckInteractWithBall, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::CheckInteractWithPot, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::CheckInteractWithFootBall, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::CheckInteractWithVillager, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::CheckInteractWithMagicLiving, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::CheckInteractWithRock, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ArrivesAtRockForWood, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, &Villager::ForesteringAnimation, 0, 0},
	{&Villager::GotWoodFromRock, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, &Villager::ForesteringAnimation, 0, 0},
	{&Villager::ReenterBuildingState, &Villager::EnterBuilding, &Villager::ExitBuilding, &Villager::SaveBuilding, &Villager::LoadBuilding, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ArriveAtPushObject, 0, 0, &Villager::SaveClearArea, &Villager::LoadClearArea, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::TakeWoodFromTree, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, &Villager::ForesteringAnimation, 0, 0},
	{&Villager::TakeWoodFromPot, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, &Villager::ForesteringAnimation, 0, 0},
	{&Villager::TakeWoodFromTreeForBuilding, &Villager::EnterBuilding, &Villager::ExitBuilding, &Villager::SaveBuilding, &Villager::LoadBuilding, &Villager::AlwaysReactToTownEmergency, &Villager::ForesteringAnimation, 0, 0},
	{&Villager::TakeWoodFromPotForBuilding, &Villager::EnterBuilding, &Villager::ExitBuilding, &Villager::SaveBuilding, &Villager::LoadBuilding, &Villager::AlwaysReactToTownEmergency, &Villager::ForesteringAnimation, 0, 0},
	{&Villager::ShepherdTakeAnimalForSlaughter, 0, &Villager::ExitShepherding, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ShepherdTakesControlOfFlock, 0, &Villager::ExitShepherding, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ShepherdReleasesControlOfFlock, 0, &Villager::ExitShepherding, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::DanceButNotWorship, 0, &Villager::ExitDance, &Villager::SaveDance, &Villager::LoadDance, &Villager::AlwaysReactToTownEmergency, &Villager::DanceAnimation, 0, 0},
	{&Villager::FaintingReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, 0, 0, 0, &Villager::ReactionValidate},
	{&Villager::StartConfusedReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, 0, 0, 0, &Villager::ReactionValidate},
	{&Villager::ConfusedReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, 0, 0, 0, &Villager::ReactionValidate},
	{&Villager::AfterTapOnAbode, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, &Villager::YawnAnimation, 0, 0},
	{&Villager::WeakOnGround, 0, &Living::ExitNoChangeState, 0, 0, 0, 0, 0, 0},
	{&Villager::ScriptWanderAroundPos, &Living::EnterScriptWander, &Living::ExitScriptWander, &Villager::SaveScriptPos, &Villager::LoadScriptPos, 0, 0, 0, 0},
	{&Villager::ScriptPlayAnim, &Living::EnterPlayAnim, &Living::ExitPlayAnim, &Villager::SaveScriptPos, &Villager::LoadScriptPos, 0, &Villager::ScriptAnimation, 0, 0},
	{&Villager::GoToTeleportReaction, 0, &Villager::ExitReactToTeleport, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Villager::TeleportReaction, 0, &Villager::ExitReactToTeleport, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Villager::DanceWhileReacting, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, &Villager::DanceAnimation, 0, &Villager::ReactionValidate},
	{&Villager::ControlledByCreature, 0, &Villager::ExitControlledByCreature, 0, 0, &Villager::AlwaysReactToTownEmergency, &Villager::ControlledByCreatureAnimation, 0, 0},
	{&Villager::PointAtDeadPerson, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, 0, 0, 0, &Villager::ReactionValidate},
	{&Villager::GoTowardsDeadPerson, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, 0, 0, 0, &Villager::ReactionValidate},
	{&Villager::LookAtDeadPerson, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, 0, 0, 0, &Villager::ReactionValidate},
	{&Villager::MournDeadPerson, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, 0, 0, &Villager::MournIntoOutofAnimation, &Villager::ReactionValidate},
	{&Villager::NothingToDo, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ArrivesAtWorkshopForDropOff, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ArrivesAtStoragePitForWorkshopMaterials, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ShowPoisoned, 0, 0, 0, 0, 0, 0, 0, 0},
	{&Villager::HidingAtWorshipSite, 0, &Villager::ExitAtWorshipSite, &Villager::SaveWorship, &Villager::LoadWorship, 0, 0, 0, 0},
	{&Villager::CrowdReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Villager::ReactToFire, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, 0, 0, 0, &Villager::ReactionValidate},
	{&Villager::PutOutFireByBeating, &Villager::EnterPutOutFire, &Villager::ExitPutOutFire, &Villager::SaveFire, &Villager::LoadFire, 0, 0, 0, &Villager::ReactionValidate},
	{&Villager::PutOutFireWithWater, &Villager::EnterPutOutFire, &Villager::ExitPutOutFire, &Villager::SaveFire, &Villager::LoadFire, 0, 0, 0, &Villager::ReactionValidate},
	{&Villager::GetWaterToPutOutFire, &Villager::EnterPutOutFire, &Villager::ExitPutOutFire, &Villager::SaveFire, &Villager::LoadFire, 0, 0, 0, &Villager::ReactionValidate},
	{&Villager::OnFire, &Villager::EnterOnFire, &Villager::ExitOnFire, &Villager::SaveFire, &Villager::LoadFire, 0, 0, 0, 0},
	{&Villager::MoveAroundFire, &Villager::EnterPutOutFire, &Villager::ExitPutOutFire, &Villager::SaveFire, &Villager::LoadFire, &Villager::LookAtPreviousStateReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Villager::DiscipleNothingToDo, &Villager::EnterDiscipleNothingToDo, 0, &Villager::SaveDiscipleNothingToDo, &Villager::LoadDiscipleNothingToDo, &Villager::AlwaysReactToTownEmergency, 0, &Villager::PrayIntoOutofAnimation, 0},
	{&Villager::FootballMoveToBall, 0, &Living::ExitMoveToPos, &Villager::SaveFootball, &Villager::LoadFootball, &Villager::AlwaysReactToTownEmergency, &Villager::MoveToPosAnimation, &Villager::MoveToPosIntoOutofAnimation, 0},
	{&Villager::ArrivesAtStoragePitForTraderPickUp, 0, 0, &Villager::SaveTrader, &Villager::LoadTrader, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ArrivesAtStoragePitForTraderDropOff, 0, 0, &Villager::SaveTrader, &Villager::LoadTrader, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::BreederDisciple, &Villager::EnterBreeder, &Villager::ExitBreeder, &Villager::SaveBreeder, &Villager::LoadBreeder, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::SexValidate},
	{&Villager::MissionaryDisciple, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ReactToBreeder, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Villager::ShepherdCheckAnimalForSlaughter, 0, &Villager::ExitShepherding, &Villager::SaveShepherd, &Villager::LoadShepherd, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::InteractDecideWhatToDoForOtherVillager, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ArtifactDance, 0, &Villager::ExitDance, &Villager::SaveDance, &Villager::LoadDance, &Villager::AlwaysReactToTownEmergency, &Villager::DanceAnimation, 0, 0},
	{&Villager::FleeingFromPredatorReaction, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, &Villager::MoveToPosAnimation, &Villager::MoveToPosIntoOutofAnimation, &Villager::ReactionValidate},
	{&Villager::WaitForWood, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::InspectObject, 0, 0, &Villager::SaveInspectObject, &Villager::LoadInspectObject, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ClosestObjectValidate},
	{&Villager::GoHomeAndChange, 0, &Villager::ExitGoHomeAndChange, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::WaitForMate, 0, &Living::ExitReaction, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Villager::GoAndHideInNearbyBuilding, 0, &Living::ExitReaction, &Villager::SaveHideInBuilding, &Villager::LoadHideInBuilding, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Villager::LookToSeeIfItIsSafe, 0, &Living::ExitReaction, &Villager::SaveHideInBuilding, &Villager::LoadHideInBuilding, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Villager::SleepInTent, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, &Villager::SleepInTentIntoOutofAnimation, 0},
	{&Villager::PauseForASecond, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, &Villager::PauseForASecondAnimation, 0, 0},
	{&Villager::PanicReaction, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::GetFoodAtWorshipSite, 0, &Villager::ExitGetFoodAtWorship, &Villager::SaveWorship, &Villager::LoadWorship, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::GotoCongregateInTownAfterEmergency, 0, 0, 0, 0, 0, 0, 0, 0},
	{&Villager::CongregateInTownAfterEmergency, 0, 0, 0, 0, 0, &Villager::TownEmergencyAnimation, 0, 0},
	{&Villager::ScriptInCrowd, 0, 0, &Villager::SaveScriptPos, &Villager::LoadScriptPos, 0, &Villager::RandomCrowdAnimation, 0, 0},
	{&Villager::GoAndChilloutOutsideHome, 0, 0, 0, 0, 0, 0, 0, 0},
	{&Villager::SitAndChillout, &Villager::EnterSitAndChillOut, 0, 0, 0, 0, &Villager::SitDownAnimation, &Villager::SitDownIntoOutOfAnimation, 0},
	{&Villager::ScriptGoAndMoveAlongPath, &Living::EnterInScript, &Living::ExitInScript, 0, 0, 0, 0, 0, 0},
	{&Villager::GoHomeFromWorship, 0, &Villager::ExitAtHome, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::ArrivesHomeFromWorship, 0, &Villager::ExitAtHome, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
	{&Villager::SleepInTentFromWorship, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, &Villager::SleepInTentIntoOutofAnimation, 0},
	{&Villager::GoToTeleportReactionQuickly, 0, &Villager::ExitReactToTeleport, &Villager::SaveReaction, &Villager::LoadReaction, &Villager::AlwaysReactToTownEmergency, 0, 0, &Villager::ReactionValidate},
	{&Villager::GoAndChilloutInTown, 0, 0, 0, 0, 0, 0, 0, 0},
	{&Villager::WaitForArtifactDance, &Villager::EnterWaitForArtifactDance, &Villager::ExitDance, &Villager::SaveDance, &Villager::LoadDance, &Villager::AlwaysReactToTownEmergency, &Villager::DanceAnimation, 0, 0},
	{&Villager::BreederJustLanded, 0, 0, 0, 0, &Villager::AlwaysReactToTownEmergency, 0, 0, 0},
};

LivingStateTableEntry<Animal> g_AnimalStateTable[ANIMAL_STATE_LAST_STATE] = {
	{&Living::InvalidState, 0, 0, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Animal::MoveToPos, 0, &Living::ExitMoveToPos, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Living::MoveToObject, 0, &Living::ExitMoveToPos, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Living::MoveOnStructure, 0, &Living::ExitMoveToPos, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Living::StateInScript, 0, &Living::ExitInScript, 0, 0, 0, &Animal::StandAnimation, 0, 0},
	{&Living::StateInDance, 0, 0, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Living::StateFleeingFromObjectReaction, 0, &Living::ExitReaction, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Living::StateLookingAtObjectReaction, 0, &Living::ExitReaction, 0, 0, 0, &Animal::StandAnimation, 0, 0},
	{&Living::StateFollowingObjectReaction, 0, &Living::ExitReaction, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Living::StateInspectObjectReaction, 0, &Living::ExitReaction, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Living::Flying, 0, &Living::ExitInFlying, 0, 0, 0, &Animal::ThrownAnimation, 0, 0},
	{&Animal::Landed, 0, &Living::ExitInLanded, 0, 0, 0, &Animal::LandedAnimation, 0, 0},
	{&Living::StateLookingAtFlyingObjectReaction, 0, 0, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Living::StateSetDying, 0, 0, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Living::StateDying, 0, 0, 0, 0, 0, &Animal::DyingAnimation, 0, 0},
	{&Living::StateDead, 0, 0, 0, 0, 0, &Animal::DeadAnimation, 0, 0},
	{&Living::StateDying, 0, 0, 0, 0, 0, &Animal::DyingAnimation, 0, 0},
	{&Living::StateDowned, 0, 0, 0, 0, 0, &Animal::DyingAnimation, 0, 0},
	{&Living::StateBeingEaten, 0, &Living::ExitBeingEaten, 0, 0, 0, &Animal::DeadAnimation, 0, 0},
	{&Living::StateGoToFoodReaction, 0, &Living::ExitReaction, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Living::StateArrivesAtFoodReaction, 0, &Living::ExitReaction, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Living::StateGoToWoodReaction, 0, &Living::ExitReaction, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Living::StateArrivesAtWoodReaction, 0, &Living::ExitReaction, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Living::WaitForAnimation, 0, 0, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Living::StateInHand, 0, &Living::ExitInHand, 0, 0, 0, &Animal::InHandAnimation, 0, 0},
	{&Living::GotoPickupBallReaction, 0, &Living::ExitReaction, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Living::ArrivesAtPickupBallReaction, 0, &Living::ExitReaction, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Living::StateMoveInFlock, 0, &Living::ExitMoveToPos, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Living::MoveToPos, 0, &Living::ExitMoveToPos, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Living::MoveOnFootpath, 0, &Living::ExitMoveToPos, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Living::StateFleeingAndLookingAtObjectReaction, 0, &Living::ExitReaction, 0, 0, 0, &Animal::StandAnimation, 0, 0},
	{&Animal::StartWander, 0, 0, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Animal::Wander, &Animal::EnterWandering, 0, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Animal::Eat, 0, 0, 0, 0, 0, &Animal::EatAnimation, 0, 0},
	{&Animal::SeekSleep, 0, 0, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Animal::Sleeps, &Animal::EnterSleep, 0, 0, 0, 0, &Animal::SleepAnimation, 0, 0},
	{&Animal::SeekEnvironment, 0, 0, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Animal::StandardAction, 0, 0, 0, 0, 0, &Animal::StandardAnimation, 0, 0},
	{&Animal::StartToEat, 0, 0, 0, 0, 0, &Animal::StartToEatAnimation, 0, 0},
	{&Animal::FinishEating, 0, 0, 0, 0, 0, &Animal::FinishEatingAnimation, 0, 0},
	{&Animal::TargetPounce, 0, 0, 0, 0, 0, &Animal::PounceAnimation, 0, 0},
	{&Animal::HuntingMoveToPos, 0, &Living::ExitMoveToPos, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Animal::MoveToPosAndLookAround, 0, &Living::ExitMoveToPos, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Living::DecideWhatToDo, 0, 0, 0, 0, 0, &Animal::DecideAnimation, 0, 0},
	{&Animal::SpecialMoveToPos, 0, &Living::ExitMoveToPos, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Animal::FollowFlock, 0, 0, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Animal::LandOnObject, 0, 0, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Animal::LandAtPos, 0, 0, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Animal::InteractDecideWhatToDo, 0, 0, 0, 0, 0, &Animal::StandAnimation, 0, 0},
	{&Animal::FleeingFromPredatorReaction, 0, &Living::ExitReaction, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
	{&Animal::GivesBirth, 0, 0, 0, 0, 0, &Animal::StandAnimation, 0, 0},
	{&Animal::HideInLair, &Animal::EnterHideInLair, 0, 0, 0, 0, &Animal::SleepAnimation, 0, 0},
	{&Animal::SeekFood, &Animal::EnterSeekFood, 0, 0, 0, 0, &Animal::MoveAnimation, 0, 0},
};
// clang-format on
