#ifndef BW1_DECOMP_INTERFACE_HAND_STATE_INCLUDED_H
#define BW1_DECOMP_INTERFACE_HAND_STATE_INCLUDED_H

#include <assert.h> /* For static_assert */
#include <stdint.h> /* For uint32_t */

#include "Base.h" /* For struct Base */

enum HAND_STATE
{
	HAND_STATE_NONE = 0x0,
	HAND_STATE_POINTER_NORMAL = 0x1,
	HAND_STATE_POINTER_SELECT = 0x2,
	HAND_STATE_NORMAL = 0x3,
	HAND_STATE_CAN_SELECT = 0x4,
	HAND_STATE_HAS_MAGIC = 0x5,
	HAND_STATE_HAS_MAGIC_CONTROL = 0x6,
	HAND_STATE_GETTING_INFO = 0x7,
	HAND_STATE_CAN_APPLY = 0x8,
	HAND_STATE_CAN_PICK_UP = 0x9,
	HAND_STATE_APPLYING = 0xa,
	HAND_STATE_DROPPING_OBJECT = 0xb,
	HAND_STATE_OVER_GAME_PANEL = 0xc,
	HAND_STATE_CAN_SELECT_LOCK = 0xd,
	HAND_STATE_SELECT_LOCK = 0xe,
	HAND_STATE_CAN_APPLY_LOCK = 0xf,
	HAND_STATE_APPLY_LOCK = 0x10,
	HAND_STATE_USING_GESTURE = 0x11,
	HAND_STATE_OVER_OBJECT = 0x12,
	HAND_STATE_CREATURE_INTERACTION = 0x13,
	HAND_STATE_GRIP_LANDSCAPE = 0x14,
	HAND_STATE_ROTATE_LANDSCAPE = 0x15,
	HAND_STATE_ZOOM_LANDSCAPE = 0x16,
	HAND_STATE_IN_THROW = 0x17,
	HAND_STATE_OBJECT_IN_HAND = 0x18,
	HAND_STATE_OFF = 0x19,
	HAND_STATE_WAIT_FOR_GIVE = 0x1a,
	HAND_STATE_FIGHT = 0x1b,
	HAND_STATE_OVER_BUBBLE = 0x1c,
	HAND_STATE_BUBBLE_GRIP = 0x1d,
	HAND_STATE_INSIDE_CITADEL = 0x1e,
	HAND_STATE_LEASH_INTERACT = 0x1f,
	HAND_STATE_OVER_LEASH = 0x20,
	HAND_STATE_UNKNOWN = 0x21,
};

class InterfaceHandState : public Base
{
public:
	HAND_STATE hand_state; /* 0x8 */

	// Override methods

	// BW1W120 005ce360 BW1M119 01364200
	virtual ~InterfaceHandState();

	// Non-virtual methods

	// BW1W120 inlined BW1M119 01023650
	HAND_STATE GetState() { return hand_state; }
};

#endif /* BW1_DECOMP_INTERFACE_HAND_STATE_INCLUDED_H */
