#include <string.h> /* For strncpy */

#include "Script.h"

#include "Game.h"
#include "GameThingWithPos.h"
#include "Object.h"
#include "ScriptDLL.h"

#include <Lionhead/LH3DLib/development/LHPoint.h>

// The Mac build names the type -- ScriptDLL::Initialise(ScriptFunctionTable *,
// ...) -- and it is POD there, so on Mac this table is plain static data.
struct ScriptFunctionEntry
{
	void(__cdecl* handler)(); /* 0x00 */
	uint32_t argCount;        /* 0x04 */
	uint32_t field_0x8;
	uint32_t field_0xc;
	char     name[128]; /* 0x10 */
};

// Native script function table.
//
// Only the head of this initialiser reaches .data. MSVC 6 lays an element out
// statically only while every initialiser in it is an address constant, and the
// address of an overloaded function is not one. SET_SCRIPT_STATE, the 18th
// element (index 17), is the first handler here whose name is overloaded, so it
// and everything after it are deferred to run time: indices 0-16 sit in .data at
// 0x00C0DB98, 17-463 are zero, and the compiler synthesises a function
// (0x006FFFD0, 0x8C30 bytes) registered in .CRT$XCU for _cinit to run at startup.
//
// There each element is stored field by field, and the char[128] name gets the
// usual aggregate-initialisation treatment: copy the literal including its
// terminator, zero the rest of the array. For index 27, "CREATE", that is
//
//     memcpy(name, "CREATE", sizeof("CREATE"));                       /* 7   */
//     memset(name + sizeof("CREATE"), 0, sizeof(name) - sizeof("CREATE")); /* 121 */
//
// which the compiler emits inline, the tail as a rep stosd:
//
//     007003A2  mov  ecx, 0x1E        ; 30 dwords + 1 byte = 121
//     007003A7  mov  edi, 0x00C0EADF  ; name + 7
//     007003AC  rep  stosd
//     007003AE  stosb
ScriptFunctionEntry g_scriptFunctionTable[464] = {
	{NULL, 0, 0, 0, "NONE"},
	{GScript::SetCameraPos, 3, 0, 0, "SET_CAMERA_POSITION"},
	{GScript::SetCameraFocus, 3, 0, 0, "SET_CAMERA_FOCUS"},
	{GScript::MoveCameraPos, 4, 0, 0, "MOVE_CAMERA_POSITION"},
	{GScript::MoveCameraFocus, 4, 0, 0, "MOVE_CAMERA_FOCUS"},
	{GScript::GetCameraPos, 0, 3, 0, "GET_CAMERA_POSITION"},
	{GScript::GetCameraFocus, 0, 3, 0, "GET_CAMERA_FOCUS"},
	{GScript::SpiritEject, 1, 0, 0, "SPIRIT_EJECT"},
	{GScript::SpiritHome, 1, 0, 0, "SPIRIT_HOME"},
	{GScript::SpiritPointAtPos, 5, 0, 0, "SPIRIT_POINT_POS"},
	{GScript::SpiritPointAtGameThing, 3, 0, 0, "SPIRIT_POINT_GAME_THING"},
	{GScript::IsGameThingFieldOfView, 1, 1, 0, "GAME_THING_FIELD_OF_VIEW"},
	{GScript::IsPosFieldOfView, 3, 1, 0, "POS_FIELD_OF_VIEW"},
	{GScript::RunText, 3, 0, 0, "RUN_TEXT"},
	{GScript::TempText, 3, 0, 0, "TEMP_TEXT"},
	{GScript::TextRead, 0, 1, 0, "TEXT_READ"},
	{GScript::GameThingClicked, 1, 1, 0, "GAME_THING_CLICKED"},
	{GScript::SetScriptState, 2, 0, 1, "SET_SCRIPT_STATE"},
	{GScript::SetScriptStatePos, 4, 0, 1, "SET_SCRIPT_STATE_POS"},
	{GScript::SetScriptStateFloat, 2, 0, 1, "SET_SCRIPT_FLOAT"},
	{GScript::SetScriptStateULData, 3, 0, 1, "SET_SCRIPT_ULONG"},
	{GScript::GetProperty, 2, 1, 0, "GET_PROPERTY"},
	{GScript::SetProperty, 3, 0, 0, "SET_PROPERTY"},
	{GScript::GetPosition, 1, 3, 0, "GET_POSITION"},
	{GScript::SetPosition, 4, 0, 0, "SET_POSITION"},
	{GScript::GetDistance, 6, 1, 0, "GET_DISTANCE"},
	{GScript::Call, 6, 1, 0, "CALL"},
	{GScript::CreateThing, 5, 1, 0, "CREATE"},
	{GScript::Random, 2, 1, 0, "RANDOM"},
	{NULL, 0, 1, 0, "DLL_GETTIME"},
	{GScript::StartCameraControl, 0, 1, 0, "START_CAMERA_CONTROL"},
	{GScript::EndCameraControl, 0, 0, 0, "END_CAMERA_CONTROL"},
	{GScript::SetWideScreen, 1, 0, 0, "SET_WIDESCREEN"},
	{GScript::MoveGameThing, 5, 0, 1, "MOVE_GAME_THING"},
	{GScript::SetFocus, 4, 0, 0, "SET_FOCUS"},
	{GScript::HasCameraArrived, 0, 1, 0, "HAS_CAMERA_ARRIVED"},
	{GScript::CreateFlock, 3, 1, 0, "FLOCK_CREATE"},
	{GScript::AttachToId, 3, 1, 1, "FLOCK_ATTACH"},
	{GScript::DetachFromId, 2, 1, 0, "FLOCK_DETACH"},
	{GScript::DisbandId, 1, 0, 0, "FLOCK_DISBAND"},
	{GScript::GetIdSize, 1, 1, 0, "ID_SIZE"},
	{GScript::IsFlockMember, 2, 1, 0, "FLOCK_MEMBER"},
	{GScript::GetHandPosition, 0, 3, 0, "GET_HAND_POSITION"},
	{GScript::PlaySoundEffect, 6, 0, 0, "PLAY_SOUND_EFFECT"},
	{GScript::StartMusic, 1, 0, 0, "START_MUSIC"},
	{GScript::StopMusic, 0, 0, 0, "STOP_MUSIC"},
	{GScript::AttachMusic, 2, 0, 0, "ATTACH_MUSIC"},
	{GScript::DetachMusic, 1, 0, 0, "DETACH_MUSIC"},
	{GScript::DeleteObject, 2, 0, 0, "OBJECT_DELETE"},
	{GScript::MoveCameraFocusFollow, 1, 0, 0, "FOCUS_FOLLOW"},
	{GScript::MoveCameraThingFollow, 1, 0, 0, "POSITION_FOLLOW"},
	{GScript::CallNear, 7, 1, 0, "CALL_NEAR"},
	{GScript::SpecialEffectOnPos, 5, 1, 0, "SPECIAL_EFFECT_POSITION"},
	{GScript::SpecialEffectOnId, 3, 1, 0, "SPECIAL_EFFECT_OBJECT"},
	{GScript::CreateDance, 6, 1, 0, "DANCE_CREATE"},
	{GScript::CallFromId, 4, 1, 0, "CALL_IN"},
	{GScript::ChangeObjectProperties, 4, 0, 0, "CHANGE_INNER_OUTER_PROPERTIES"},
	{GScript::SnapShot, 0xFFFFFFFF, 0, 0, "SNAPSHOT"},
	{GScript::GetAlignment, 1, 1, 0, "GET_ALIGNMENT"},
	{GScript::UpdateAlignment, 2, 0, 0, "SET_ALIGNMENT"},
	{GScript::CreateInfluenceOnObject, 4, 1, 0, "INFLUENCE_OBJECT"},
	{GScript::CreateInfluenceOnPos, 6, 1, 0, "INFLUENCE_POSITION"},
	{GScript::GetInfluence, 5, 1, 0, "GET_INFLUENCE"},
	{GScript::SetInterfaceInteraction, 1, 0, 0, "SET_INTERFACE_INTERACTION"},
	{GScript::HasPlayed, 1, 1, 0, "PLAYED"},
	{GScript::RandomULONG, 2, 1, 0, "RANDOM_ULONG"},
	{GScript::SetGameSpeed, 1, 0, 0, "SET_GAMESPEED"},
	{GScript::CallInNear, 8, 1, 0, "CALL_IN_NEAR"},
	{GScript::OverrideStateAnimation, 2, 0, 0, "OVERRIDE_STATE_ANIMATION"},
	{GScript::CreateCreatureFromCreature, 6, 1, 0, "CREATURE_CREATE_RELATIVE_TO_CREATURE"},
	{GScript::CreatureLearnEverything, 1, 0, 0, "CREATURE_LEARN_EVERYTHING"},
	{GScript::CreatureSetKnowsAction, 4, 0, 0, "CREATURE_SET_KNOWS_ACTION"},
	{GScript::CreatureSetAgendaPriority, 2, 0, 0, "CREATURE_SET_AGENDA_PRIORITY"},
	{GScript::CreatureTurnOffAllDesires, 1, 0, 0, "CREATURE_TURN_OFF_ALL_DESIRES"},
	{GScript::CreatureLearnDistinction, 4, 0, 0, "CREATURE_LEARN_DISTINCTION_ABOUT_ACTIVITY_OBJECT"},
	{GScript::CreatureDoAction, 4, 0, 0, "CREATURE_DO_ACTION"},
	{GScript::InCreatureHand, 2, 1, 0, "IN_CREATURE_HAND"},
	{GScript::CreatureSetDesireValue, 3, 0, 0, "CREATURE_SET_DESIRE_VALUE"},
	{GScript::CreatureSetDesireActivated, 3, 0, 0, "CREATURE_SET_DESIRE_ACTIVATED"},
	{GScript::CreatureSetAllDesireActivated, 2, 0, 0, "CREATURE_SET_DESIRE_ACTIVATED"},
	{GScript::CreatureSetDesireMaximum, 3, 0, 0, "CREATURE_SET_DESIRE_MAXIMUM"},
	{GScript::ConvertCameraEditorPosition, 1, 3, 0, "CONVERT_CAMERA_POSITION"},
	{GScript::ConvertCameraEditorFocus, 1, 3, 0, "CONVERT_CAMERA_FOCUS"},
	{GScript::CreatureSetPlayer, 1, 0, 0, "CREATURE_SET_PLAYER"},
	{GScript::StartCountDownTimer, 1, 0, 0, "START_COUNTDOWN_TIMER"},
	{GScript::CreatureInitialiseNumTimesPerformedAction, 2, 0, 0, "CREATURE_INITIALISE_NUM_TIMES_PERFORMED_ACTION"},
	{GScript::CreatureGetNumTimesPerformedAction, 2, 1, 0, "CREATURE_GET_NUM_TIMES_ACTION_PERFORMED"},
	{GScript::RemoveCountDownTimer, 0, 0, 0, "REMOVE_COUNTDOWN_TIMER"},
	{GScript::GetObjectDropped, 1, 1, 0, "GET_OBJECT_DROPPED"},
	{GScript::ClearDroppedByObject, 1, 0, 0, "CLEAR_DROPPED_BY_OBJECT"},
	{GScript::CreateReaction, 2, 0, 0, "CREATE_REACTION"},
	{GScript::RemoveReaction, 1, 0, 0, "REMOVE_REACTION"},
	{GScript::GetCountDownTimer, 0, 1, 0, "GET_COUNTDOWN_TIMER"},
	{GScript::CreateDualCamera, 2, 0, 0, "START_DUAL_CAMERA"},
	{GScript::UpdateDualCamera, 2, 0, 0, "UPDATE_DUAL_CAMERA"},
	{GScript::ReleaseDualCamera, 0, 0, 0, "RELEASE_DUAL_CAMERA"},
	{GScript::SetCreatureHelp, 1, 0, 0, "SET_CREATURE_HELP"},
	{GScript::GetTargetObject, 1, 1, 0, "GET_TARGET_OBJECT"},
	{GScript::DesireIs, 2, 1, 0, "CREATURE_DESIRE_IS"},
	{GScript::CountDownTimerExists, 0, 1, 0, "COUNTDOWN_TIMER_EXISTS"},
	{GScript::SpiritLookAtGameThing, 2, 0, 0, "LOOK_GAME_THING"},
	{GScript::GetObjectDestination, 1, 3, 0, "GET_OBJECT_DESTINATION"},
	{GScript::CreatureForceFinish, 1, 0, 0, "CREATURE_FORCE_FINISH"},
	{GScript::HideCountDownTimer, 0, 0, 0, "HIDE_COUNTDOWN_TIMER"},
	{GScript::GetActionTextForObject, 1, 1, 0, "GET_ACTION_TEXT_FOR_OBJECT"},
	{GScript::CreateCameraBetweenObjectAndPoint, 4, 0, 0, "CREATE_DUAL_CAMERA_WITH_POINT"},
	{GScript::SetCameraToFaceObject, 2, 0, 0, "SET_CAMERA_TO_FACE_OBJECT"},
	{GScript::MoveCameraToFaceObject, 3, 0, 0, "MOVE_CAMERA_TO_FACE_OBJECT"},
	{GScript::GetMoonPercentage, 0, 1, 0, "GET_MOON_PERCENTAGE"},
	{GScript::PopulateContainer, 4, 0, 1, "POPULATE_CONTAINER"},
	{GScript::AddReference, 1, 1, 0, "ADD_REFERENCE"},
	{GScript::RemoveReference, 1, 1, 0, "REMOVE_REFERENCE"},
	{GScript::SetGameTime, 1, 0, 0, "SET_GAME_TIME"},
	{GScript::GetGameTime, 0, 1, 0, "GET_GAME_TIME"},
	{GScript::GetRealTime, 0, 1, 0, "GET_REAL_TIME"},
	{GScript::GetRealDay, 0, 1, 0, "GET_REAL_DAY"},
	{GScript::GetRealWeekDay, 0, 1, 0, "GET_REAL_DAY"},
	{GScript::GetRealMonth, 0, 1, 0, "GET_REAL_MONTH"},
	{GScript::GetRealYear, 0, 1, 0, "GET_REAL_YEAR"},
	{GScript::SetCameraPath, 1, 0, 0, "RUN_CAMERA_PATH"},
	{GScript::StartSpiritControl, 0, 1, 0, "START_DIALOGUE"},
	{GScript::EndSpiritControl, 0, 0, 0, "END_DIALOGUE"},
	{GScript::IsSpiritFree, 0, 1, 0, "IS_SPIRIT_READY"},
	{GScript::SetWeatherProperties, 6, 0, 0, "CHANGE_WEATHER_PROPERTIES"},
	{GScript::SetLightningProperties, 5, 0, 0, "CHANGE_LIGHTNING_PROPERTIES"},
	{GScript::SetTimeFadeProperties, 3, 0, 0, "CHANGE_TIME_FADE_PROPERTIES"},
	{GScript::SetCloudProperties, 4, 0, 0, "CHANGE_CLOUD_PROPERTIES"},
	{GScript::SetVelocityHeadingSpeed, 5, 0, 0, "SET_HEADING_AND_SPEED"},
	{GScript::StartGameSpeed, 0, 0, 0, "START_GAME_SPEED"},
	{GScript::EndGameSpeed, 0, 0, 0, "END_GAME_SPEED"},
	{GScript::BuildBuilding, 4, 0, 0, "BUILD_BUILDING"},
	{GScript::SetAffectedByWind, 2, 0, 0, "SET_AFFECTED_BY_WIND"},
	{GScript::IsWideScreenTransitionFinished, 0, 1, 0, "WIDESCREEN_TRANSISTION_FINISHED"},
	{GScript::GetResource, 2, 1, 0, "GET_RESOURCE"},
	{GScript::AddResource, 3, 1, 0, "ADD_RESOURCE"},
	{GScript::RemoveResource, 3, 1, 0, "REMOVE_RESOURCE"},
	{GScript::GetTargetRelativePos, 8, 3, 0, "GET_TARGET_RELATIVE_POS"},
	{GScript::StopSpiritPointing, 1, 0, 0, "STOP_POINTING"},
	{GScript::StopSpiritLooking, 1, 0, 0, "STOP_LOOKING"},
	{GScript::SpiritLookAtPosition, 4, 0, 0, "LOOK_AT_POSITION"},
	{GScript::SpiritPlayAnim, 5, 0, 0, "PLAY_SPIRIT_ANIM"},
	{GScript::CallInNotNear, 8, 1, 0, "CALL_IN_NOT_NEAR"},
	{GScript::SetCameraZone, 1, 0, 0, "SET_CAMERA_ZONE"},
	{GScript::GetScriptState, 1, 1, 0, "GET_OBJECT_STATE"},
	{GScript::RevealCountDownTimer, 0, 0, 0, "REVEAL_COUNTDOWN_TIMER"},
	{GScript::SetTimerTime, 2, 0, 0, "SET_TIMER_TIME"},
	{GScript::CreateTimer, 1, 1, 0, "CREATE_TIMER"},
	{GScript::GetTimeRemaining, 1, 1, 0, "GET_TIMER_TIME_REMAINING"},
	{GScript::GetTimeSinceSet, 1, 1, 0, "GET_TIMER_TIME_SINCE_SET"},
	{GScript::MoveMusicThing, 2, 0, 0, "MOVE_MUSIC"},
	{GScript::GetCameraInclusionDistance, 0, 1, 0, "GET_INCLUSION_DISTANCE"},
	{GScript::GetLandHeight, 3, 1, 0, "GET_LAND_HEIGHT"},
	{GScript::LoadMap, 1, 0, 0, "LOAD_MAP"},
	{GScript::StopScriptsExcluding, 1, 0, 0, "STOP_ALL_SCRIPTS_EXCLUDING"},
	{GScript::StopScriptsExcludingFiles, 1, 0, 0, "STOP_ALL_SCRIPTS_IN_FILES_EXCLUDING"},
	{GScript::StopScript, 1, 0, 0, "STOP_SCRIPT"},
	{GScript::ClearClickedObject, 0, 0, 0, "CLEAR_CLICKED_OBJECT"},
	{GScript::ClearClickedPosition, 0, 0, 0, "CLEAR_CLICKED_POSITION"},
	{GScript::PositionClickedNear, 4, 1, 0, "POSITION_CLICKED"},
	{GScript::ReleaseActorFromScript, 1, 0, 0, "RELEASE_FROM_SCRIPT"},
	{GScript::GetObjectHandOver, 0, 1, 0, "GET_OBJECT_HAND_IS_OVER"},
	{GScript::GetPoisonedSize, 1, 1, 0, "ID_POISONED_SIZE"},
	{GScript::IsPoisoned, 1, 1, 0, "IS_POISONED"},
	{GScript::CallPoisonedFromId, 4, 1, 0, "CALL_POISONED_IN"},
	{GScript::CallNotPoisonedFromId, 4, 1, 0, "CALL_NOT_POISONED_IN"},
	{GScript::SpiritPlayed, 1, 1, 0, "SPIRIT_PLAYED"},
	{GScript::ClingSpirit, 3, 0, 0, "CLING_SPIRIT"},
	{GScript::FlySpirit, 3, 0, 0, "FLY_SPIRIT"},
	{GScript::SetMoveable, 2, 0, 0, "SET_ID_MOVEABLE"},
	{GScript::SetPickupable, 2, 0, 0, "SET_ID_PICKUPABLE"},
	{GScript::IsOnFire, 1, 1, 0, "IS_ON_FIRE"},
	{GScript::IsFireNear, 4, 1, 0, "IS_FIRE_NEAR"},
	{GScript::StopScriptsInFiles, 1, 0, 0, "STOP_SCRIPTS_IN_FILES"},
	{GScript::SetPoisoned, 2, 0, 0, "SET_POISONED"},
	{GScript::SetTemperature, 2, 0, 0, "SET_TEMPERATURE"},
	{GScript::SetOnFire, 3, 0, 0, "SET_ON_FIRE"},
	{GScript::SetIdTarget, 5, 0, 0, "SET_TARGET"},
	{GScript::SetWalkPath, 5, 0, 1, "WALK_PATH"},
	{GScript::MoveCameraPosFocFollow, 2, 0, 0, "FOCUS_AND_POSITION_FOLLOW"},
	{GScript::GetWalkPathPercentage, 1, 1, 0, "GET_WALK_PATH_PERCENTAGE"},
	{GScript::SetFollowCameraProperties, 4, 0, 0, "CAMERA_PROPERTIES"},
	{GScript::SetMusicEnable, 2, 0, 0, "ENABLE_DISABLE_MUSIC"},
	{GScript::GetMusicObjectDistance, 1, 1, 0, "GET_MUSIC_OBJ_DISTANCE"},
	{GScript::GetMusicEnumDistance, 1, 1, 0, "GET_MUSIC_ENUM_DISTANCE"},
	{GScript::SetMusicPlayPosition, 4, 0, 0, "SET_MUSIC_PLAY_POSITION"},
	{GScript::AttachObjectLeachToObject, 2, 0, 0, "ATTACH_OBJECT_LEASH_TO_OBJECT"},
	{GScript::AttachLeashToHand, 1, 0, 0, "ATTACH_OBJECT_LEASH_TO_HAND"},
	{GScript::DetachObjectLeash, 1, 0, 0, "DETACH_OBJECT_LEASH"},
	{GScript::SetCreatureOnlyDesire, 3, 0, 0, "SET_CREATURE_ONLY_DESIRE"},
	{GScript::SetCreatureOnlyDesireOff, 1, 0, 0, "SET_CREATURE_ONLY_DESIRE_OFF"},
	{GScript::RestartMusic, 1, 0, 0, "RESTART_MUSIC"},
	{GScript::MusicPlayed, 1, 1, 0, "MUSIC_PLAYED"},
	{GScript::IsOfType, 3, 1, 0, "IS_OF_TYPE"},
	{GScript::ClearHitObject, 0, 0, 0, "CLEAR_HIT_OBJECT"},
	{GScript::IsHitObject, 1, 1, 0, "GAME_THING_HIT"},
	{GScript::SpellOnThing, 8, 1, 0, "SPELL_AT_THING"},
	{GScript::SpellAtPos, 10, 1, 0, "SPELL_AT_POS"},
	{GScript::CallPlayerCreature, 1, 1, 0, "CALL_PLAYER_CREATURE"},
	{GScript::GetSlowestInId, 1, 1, 0, "GET_SLOWEST_SPEED"},
	{GScript::GetHeldObject, 0, 1, 0, "GET_OBJECT_HELD"},
	{GScript::IsHelpSystemOn, 0, 1, 0, "HELP_SYSTEM_ON"},
	{GScript::ShakeCamera, 6, 0, 0, "SHAKE_CAMERA"},
	{GScript::SetAnimationModify, 2, 0, 0, "SET_ANIMATION_MODIFY"},
	{GScript::SetAviSequence, 2, 0, 0, "SET_AVI_SEQUENCE"},
	{GScript::PlayGesture, 5, 0, 0, "PLAY GESTURE"},
	{GScript::DevFunction, 1, 0, 0, "DEV_FUNCTION"},
	{GScript::HasMouseWheel, 0, 1, 0, "HAS_MOUSE_WHEEL"},
	{GScript::GetNumberMouseButtons, 0, 1, 0, "NUM_MOUSE_BUTTONS"},
	{GScript::SetCreatureDevelopmentPhase, 2, 0, 0, "SET_CREATURE_DEV_STAGE"},
	{GScript::SetFixedCamRotation, 4, 0, 0, "SET_FIXED_CAM_ROTATION"},
	{GScript::SwapCreature, 2, 0, 1, "SWAP_CREATURE"},
	{GScript::GetArena, 5, 1, 0, "GET_ARENA"},
	{GScript::GetFootballPitch, 1, 1, 0, "GET_FOOTBALL_PITCH"},
	{GScript::StopAllGames, 1, 0, 0, "STOP_ALL_GAMES"},
	{GScript::AttachToGame, 3, 0, 1, "ATTACH_TO_GAME"},
	{GScript::DetachFromGame, 3, 0, 1, "DETACH_FROM_GAME"},
	{GScript::DetachFirstFromGame, 2, 0, 1, "DETACH_UNDEFINED_FROM_GAME"},
	{GScript::SetOnlyForScripts, 2, 0, 1, "SET_ONLY_FOR_SCRIPTS"},
	{GScript::StartWithReferee, 2, 0, 1, "START_MATCH_WITH_REFEREE"},
	{GScript::GetTeamSize, 2, 0, 0, "GAME_TEAM_SIZE"},
	{GScript::GetType, 1, 1, 0, "GAME_TYPE"},
	{GScript::GetSubType, 1, 1, 0, "GAME_SUB_TYPE"},
	{GScript::IsLeashed, 1, 1, 0, "IS_LEASHED"},
	{GScript::SetCreatureHome, 4, 0, 0, "SET_CREATURE_HOME"},
	{GScript::GetLastHitObject, 0, 1, 0, "GET_HIT_OBJECT"},
	{GScript::GetObjectWhichHit, 0, 1, 0, "GET_OBJECT_WHICH_HIT"},
	{GScript::GetNearestTownOfPlayer, 5, 1, 0, "GET_NEAREST_TOWN_OF_PLAYER"},
	{GScript::GetSpellAtPoint, 5, 1, 0, "SPELL_AT_POINT"},
	{GScript::SetCreatureCanAttackOwnTown, 2, 0, 0, "SET_ATTACK_OWN_TOWN"},
	{GScript::IsFighting, 1, 1, 0, "IS_FIGHTING"},
	{GScript::SetRadius, 2, 0, 0, "SET_MAGIC_RADIUS"},
	{GScript::TempTextWithNumber, 4, 0, 0, "TEMP_TEXT_WITH_NUMBER"},
	{GScript::RunTextWithNumber, 4, 0, 0, "RUN_TEXT_WITH_NUMBER"},
	{GScript::SetCreatureSpellReversion, 2, 0, 0, "CREATURE_SPELL_REVERSION"},
	{GScript::GetDesire, 2, 1, 0, "GET_DESIRE"},
	{GScript::GetEventsPerSecond, 1, 1, 0, "GET_EVENTS_PER_SECOND"},
	{GScript::GetEventTimeSince, 1, 1, 0, "GET_TIME_SINCE"},
	{GScript::GetTotalEvents, 1, 1, 0, "GET_TOTAL_EVENTS"},
	{GScript::UpdateSnapShot, 0xFFFFFFFF, 0, 0, "UPDATE SNAPSHOT"},
	{GScript::CreateReward, 5, 1, 0, "CREATE_REWARD"},
	{GScript::CreateRewardInTown, 6, 1, 0, "CREATE_REWARD_IN_TOWN"},
	{GScript::SetFade, 4, 0, 0, "SET_FADE"},
	{GScript::SetFadeIn, 1, 0, 0, "SET_FADE_IN"},
	{GScript::IsFadeFinished, 0, 1, 0, "FADE_FINISHED"},
	{GScript::SetPlayerMagic, 3, 0, 0, "SET_PLAYER_MAGIC"},
	{GScript::HasPlayerMagic, 2, 1, 0, "HAS_PLAYER_MAGIC"},
	{GScript::SpiritSpeaks, 2, 1, 0, "SPIRIT_SPEAKS"},
	{GScript::GetThingBeliefForPlayer, 2, 1, 0, "BELIEF_FOR_PLAYER"},
	{GScript::GetThingHelp, 1, 1, 0, "GET_HELP"},
	{GScript::SetLeashWorks, 2, 0, 0, "SET_LEASH_WORKS"},
	{GScript::LoadMyCreature, 3, 0, 0, "LOAD_MY_CREATURE"},
	{GScript::SetObjectRelativeBelief, 3, 0, 0, "OBJECT_RELATIVE_BELIEF"},
	{GScript::CreateWithAngleAndScale, 7, 1, 0, "CREATE_WITH_ANGLE_AND_SCALE"},
	{GScript::SetHelpSystem, 1, 0, 0, "SET_HELP_SYSTEM"},
	{GScript::SetVirtualInfluence, 2, 0, 0, "SET_VIRTUAL_INFLUENCE"},
	{GScript::SetActive, 2, 0, 0, "SET_ACTIVE"},
	{GScript::IsThingValid, 1, 1, 0, "THING_VALID"},
	{GScript::VortexFadeOut, 1, 0, 0, "VORTEX_FADE_OUT"},
	{GScript::RemoveReactionsOfType, 2, 0, 0, "REMOVE_REACTION_OF_TYPE"},
	{GScript::CreatureLearnAllExcluding, 2, 0, 0, "CREATURE_LEARN_EVERYTHING_EXCLUDING"},
	{GScript::GetPlayedPercentage, 1, 1, 0, "PLAYED_PERCENTAGE"},
	{GScript::ObjectCastByObject, 2, 1, 0, "OBJECT_CAST_BY_OBJECT"},
	{GScript::IsWindMagicAtPos, 1, 1, 0, "IS_WIND_MAGIC_AT_POS"},
	{GScript::CreateMist, 9, 1, 0, "CREATE_MIST"},
	{GScript::SetMistFade, 6, 0, 0, "SET_MIST_FADE"},
	{GScript::GetMistFade, 1, 1, 0, "GET_OBJECT_FADE"},
	{GScript::PlayHandDemo, 3, 0, 0, "PLAY HAND DEMO"},
	{GScript::IsHandDemoPlayed, 0, 1, 0, "IS_PLAYING_HAND_DEMO"},
	{GScript::GetArsePosition, 1, 3, 0, "GET_ARSE_POSITION"},
	{GScript::ObjectLeashedToObject, 2, 1, 0, "IS_LEASHED_TO_OBJECT"},
	{GScript::InteractionMagnitude, 1, 1, 0, "GET_INTERACTION_MAGNITUDE"},
	{GScript::CreatureAvailable, 1, 1, 0, "IS_CREATURE_AVAILABLE"},
	{GScript::CreateHighlight, 5, 1, 0, "CREATE_HIGHLIGHT"},
	{GScript::GetObjectHeldByObject, 1, 1, 0, "GET_OBJECT_HELD"},
	{GScript::GetActionCount, 2, 1, 0, "GET_ACTION_COUNT"},
	{GScript::GetObjectLeashType, 1, 1, 0, "GET_OBJECT_LEASH_TYPE"},
	{GScript::SetCameraFocusFollow, 1, 0, 0, "SET_FOCUS_FOLLOW"},
	{GScript::SetCameraThingFollow, 1, 0, 0, "SET_POSITION_FOLLOW"},
	{GScript::SetCameraPosFocFollow, 2, 0, 0, "SET_FOCUS_AND_POSITION_FOLLOW"},
	{GScript::ResetCameraLens, 1, 0, 0, "SET_CAMERA_LENS"},
	{GScript::SetCameraLens, 2, 0, 0, "MOVE_CAMERA_LENS"},
	{GScript::SetCreatureReaction, 2, 0, 0, "CREATURE_REACTION"},
	{GScript::SetCreatureInDevScript, 2, 0, 0, "CREATURE_IN_DEV_SCRIPT"},
	{GScript::StoreCameraDetails, 0, 0, 0, "STORE_CAMERA_DETAILS"},
	{GScript::RestoreCameraDetails, 0, 0, 0, "RESTORE_CAMERA_DETAILS"},
	{GScript::StartAngleSound, 1, 0, 0, "START_ANGLE_SOUND"},
	{GScript::SetCameraPosFocLens, 7, 0, 0, "SET_CAMERA_POS_FOC_LENS"},
	{GScript::MoveCameraPosFocLens, 8, 0, 0, "MOVE_CAMERA_POS_FOC_LENS"},
	{GScript::GameTimeOnOff, 1, 0, 0, "GAME_TIME_ON_OFF"},
	{GScript::MoveGameTime, 2, 0, 0, "MOVE_GAME_TIME"},
	{GScript::SetHighGFXDetail, 2, 0, 0, "SET_HIGH_GRAPHICS_DETAIL"},
	{GScript::SetSkeleton, 2, 0, 0, "SET_SKELETON"},
	{GScript::IsSkeleton, 1, 1, 0, "IS_SKELETON"},
	{GScript::GetSpellLastCastTime, 1, 1, 0, "PLAYER_SPELL_CAST_TIME"},
	{GScript::GetSpellLastCast, 1, 1, 0, "PLAYER_SPELL_LAST_CAST"},
	{GScript::GetSpellLastCastPos, 1, 3, 0, "GET_LAST_SPELL_CAST_POS"},
	{GScript::AddTargetPos, 4, 0, 0, "ADD_SPOT_VISUAL_TARGET_POS"},
	{GScript::AddTargetObject, 2, 0, 0, "ADD_SPOT_VISUAL_TARGET_OBJECT"},
	{GScript::SetIndestructable, 2, 0, 0, "SET_INDESTRUCTABLE"},
	{GScript::SetClippingDistance, 2, 0, 0, "SET_GRAPHICS_CLIPPING"},
	{GScript::ScriptSpiritAppear, 1, 0, 0, "SPIRIT_APPEAR"},
	{GScript::ScriptSpiritDisappear, 1, 0, 0, "SPIRIT_DISAPPEAR"},
	{GScript::SetFocusOnObject, 2, 0, 0, "SET_FOCUS_ON_OBJECT"},
	{GScript::ReleaseObjectFocus, 1, 0, 0, "RELEASE_OBJECT_FOCUS"},
	{GScript::ImmersionExists, 0, 1, 0, "IMMERSION_EXISTS"},
	{GScript::SetDrawLeash, 1, 0, 0, "SET_DRAW_LEASH"},
	{GScript::SetDrawHighlight, 1, 0, 0, "SET_DRAW_HIGHLIGHT"},
	{GScript::SetOpenCloseState, 2, 0, 0, "SET_OPEN_CLOSE"},
	{GScript::SetIntroBuilding, 1, 0, 0, "SET_INTRO_BUILDING"},
	{GScript::SetCreatureFriends, 3, 0, 0, "CREATURE_FORCE_FRIENDS"},
	{GScript::MoveComputerPlayer, 6, 0, 0, "MOVE_COMPUTER_PLAYER_POSITION"},
	{GScript::SetComputerPlayerOnOff, 2, 0, 0, "ENABLE_DISABLE_COMPUTER_PLAYER"},
	{GScript::GetComputerPlayerPos, 1, 3, 0, "GET_COMPUTER_PLAYER_POSITION"},
	{GScript::SetComputerPlayerPos, 5, 0, 0, "SET_COMPUTER_PLAYER_POSITION"},
	{GScript::GetStoredCameraPosition, 0, 3, 0, "GET_STORED_CAMERA_POSITION"},
	{GScript::GetStoredCameraFocus, 0, 3, 0, "GET_STORED_CAMERA_FOCUS"},
	{GScript::CallNearInState, 8, 1, 0, "CALL_NEAR_IN_STATE"},
	{GScript::SetPlayCreatureSounds, 1, 0, 0, "SET_CREATURE_SOUND"},
	{GScript::ObjectInteractingWithObject, 2, 1, 0, "CREATURE_INTERACTING_WITH"},
	{GScript::SetSunDraw, 1, 0, 0, "SET_SUN_DRAW"},
	{GScript::ObjectInfoBits, 1, 1, 0, "OBJECT_INFO_BITS"},
	{GScript::SetHurtByFire, 2, 0, 0, "SET_HURT_BY_FIRE"},
	{GScript::ConfineObject, 5, 0, 0, "CONFINED_OBJECT"},
	{GScript::ClearConfineOnObject, 1, 0, 0, "CLEAR_CONFINED_OBJECT"},
	{GScript::GetObjectFlock, 1, 1, 0, "GET_OBJECT_FLOCK"},
	{GScript::SetBelief, 3, 0, 0, "SET_PLAYER_BELIEF"},
	{GScript::PlayJCSpecial, 1, 0, 0, "PLAY_JC_SPECIAL"},
	{GScript::IsPlayingJCSpecial, 1, 1, 0, "IS_PLAYING_JC_SPECIAL"},
	{GScript::SetVortexParameters, 8, 0, 0, "VORTEX_PARAMETERS"},
	{GScript::LoadComputerCreature, 6, 0, 0, "LOAD_CREATURE"},
	{GScript::IsSpellCharging, 1, 1, 0, "IS_SPELL_CHARGING"},
	{GScript::IsThatSpellCharging, 2, 1, 0, "IS_THAT_SPELL_CHARGING"},
	{GScript::GetOpposingCreatureType, 1, 1, 0, "OPPOSING_CREATURE"},
	{GScript::FlockWithinLimits, 1, 1, 0, "FLOCK_WITHIN_LIMITS"},
	{GScript::SetHighlightProperties, 3, 0, 0, "HIGHLIGHT_PROPERTIES"},
	{GScript::IsLastMusicLine, 1, 1, 0, "LAST_MUSIC_LINE"},
	{GScript::ScriptIsHandDemoTrigger, 0, 1, 0, "HAND_DEMO_TRIGGER"},
	{GScript::GetBellyPosition, 1, 3, 0, "GET_BELLY_POSITION"},
	{GScript::SetCreedProperties, 5, 0, 0, "SET_CREATURE_CREED_PROPERTIES"},
	{GScript::GameThingCanViewCamera, 2, 1, 0, "GAME_THING_CAN_VIEW_CAMERA"},
	{GScript::SaySoundEffect, 6, 0, 0, "GAME_PLAY_SAY_SOUND_EFFECT"},
	{GScript::SetTownDesireBoost, 3, 0, 0, "SET_TOWN_DESIRE_BOOST"},
	{GScript::IsLockedInteraction, 1, 1, 0, "IS_LOCKED_INTERACTION"},
	{GScript::SetCreatureName, 2, 0, 0, "SET_CREATURE_NAME"},
	{GScript::ComputerPlayerReady, 1, 1, 0, "COMPUTER_PLAYER_READY"},
	{GScript::SetComputerPaused, 2, 0, 0, "ENABLE_DISABLE_COMPUTER_PLAYER"},
	{GScript::ClearActorMind, 1, 0, 0, "CLEAR_ACTOR_MIND"},
	{GScript::EnterExitCitadel, 1, 0, 0, "ENTER_EXIT_CITADEL"},
	{GScript::StartPitchSound, 1, 0, 0, "START_ANGLE_SOUND"},
	{GScript::ThingJCSpecial, 3, 0, 0, "THING_JC_SPECIAL"},
	{GScript::IsMusicPlayed, 1, 1, 0, "MUSIC_PLAYED"},
	{GScript::UpdateSnapShotDetails, 11, 0, 0, "UPDATE SNAPSHOT_PICTURE"},
	{GScript::StopScriptsInFilesExcluding, 2, 0, 0, "STOP_SCRIPTS_IN_FILES_EXCLUDING"},
	{GScript::CreateRandomVillagerOfTribe, 4, 1, 0, "CREATE_RANDOM_VILLAGER_OF_TRIBE"},
	{GScript::TogglePlayerLeash, 1, 0, 0, "TOGGLE_LEASH"},
	{GScript::SetObjectMana, 2, 0, 0, "GAME_SET_MANA"},
	{GScript::SetMagicProperties, 3, 0, 0, "SET_MAGIC_PROPERTIES"},
	{GScript::SetGameSound, 1, 0, 0, "SET_GAME_SOUND"},
	{GScript::SexIsMale, 1, 1, 0, "SEX_IS_MALE"},
	{GScript::GetFirstHelp, 1, 1, 0, "GET_FIRST_HELP"},
	{GScript::GetLastHelp, 1, 1, 0, "GET_LAST_HELP"},
	{GScript::IsActive, 1, 1, 0, "IS_ACTIVE"},
	{GScript::SetBookmarkPosition, 4, 0, 0, "SET_BOOKMARK_POSITION"},
	{GScript::SetScaffoldProperties, 4, 0, 0, "SET_SCAFFOLD_PROPERTIES"},
	{GScript::SetComputerPlayerPersonality, 3, 0, 0, "SET_COMPUTER_PLAYER_PERSONALITY"},
	{GScript::SetComputerPlayerSuppression, 3, 0, 0, "SET_COMPUTER_PLAYER_SUPPRESSION"},
	{GScript::ForceComputerPlayerAction, 4, 0, 0, "FORCE_COMPUTER_PLAYER_ACTION"},
	{GScript::QueueComputerPlayerAction, 4, 0, 0, "QUEUE_COMPUTER_PLAYER_ACTION"},
	{GScript::GetTownWithId, 1, 1, 0, "GET_TOWN_WITH_ID"},
	{GScript::SetDisciple, 3, 0, 0, "SET_DISCIPLE"},
	{GScript::ReleaseComputerPlayer, 1, 0, 0, "RELEASE_COMPUTER_PLAYER"},
	{GScript::SetComputerPlayerSpeed, 2, 0, 0, "SET_COMPUTER_PLAYER_SPEED"},
	{GScript::FocusFollowComputerPlayer, 1, 0, 0, "SET_FOCUS_FOLLOW_COMPUTER_PLAYER"},
	{GScript::PositionFollowComputerPlayer, 1, 0, 0, "SET_POSITION_FOLLOW_COMPUTER_PLAYER"},
	{GScript::GetComputerPlayer, 1, 1, 0, "CALL_COMPUTER_PLAYER"},
	{GScript::GetBuildingInTown, 4, 1, 0, "CALL_BUILDING_IN_TOWN"},
	{GScript::SetBuildWorshipSite, 2, 0, 0, "SET_CAN_BUILD_WORSHIPSITE"},
	{GScript::GetFacingCameraPosition, 1, 3, 0, "GET_FACING_CAMERA_POSITION"},
	{GScript::SetComputerPlayerPersonalltyAttitude, 3, 0, 0, "SET_COMPUTER_PLAYER_ATTITUDE"},
	{GScript::GetComputerPlayerPersonalltyAttitude, 2, 1, 0, "GET_COMPUTER_PLAYER_ATTITUDE"},
	{GScript::LoadComputerPlayerPersonalltyFile, 2, 0, 0, "LOAD_COMPUTER_PLAYER_PERSONALITY"},
	{GScript::SaveComputerPlayerPersonalltyFile, 2, 0, 0, "SAVE_COMPUTER_PLAYER_PERSONALITY"},
	{GScript::SetPlayerAlly, 3, 0, 0, "SET_PLAYER_ALLY"},
	{GScript::CallFlying, 6, 1, 0, "CALL_FLYING"},
	{GScript::SetObjectFadeIn, 2, 0, 0, "SET_OBJECT_FADE_IN"},
	{GScript::AffectedBySpell, 2, 1, 0, "IS_AFFECTED_BY_SPELL"},
	{GScript::SetMagicInObject, 3, 0, 0, "SET_MAGIC_IN_OBJECT"},
	{GScript::GetObjectAdultSize, 1, 1, 0, "ID_ADULT_SIZE"},
	{GScript::GetObjectCapacity, 1, 1, 0, "OBJECT_CAPACITY"},
	{GScript::GetObjectAdultCapacity, 1, 1, 0, "OBJECT_ADULT_CAPACITY"},
	{GScript::SetCreatureAutoFighting, 2, 0, 0, "SET_CREATURE_AUTO_FIGHTING"},
	{GScript::IsCreatureAutoFighting, 1, 1, 0, "IS_AUTO_FIGHTING"},
	{GScript::QueueCreatureFightMove, 2, 0, 0, "SET_CREATURE_QUEUE_FIGHT_MOVE"},
	{GScript::QueueCreatureFightSpell, 2, 0, 0, "SET_CREATURE_QUEUE_FIGHT_SPELL"},
	{GScript::QueueCreatureFightStep, 2, 0, 0, "SET_CREATURE_QUEUE_FIGHT_STEP"},
	{GScript::GetCreatureFightAction, 1, 1, 0, "GET_CREATURE_FIGHT_ACTION"},
	{GScript::GetCreatureFightQueuedHits, 1, 1, 0, "CREATURE_FIGHT_QUEUE_HITS"},
	{GScript::SquareRoot, 1, 1, 0, "SQUARE_ROOT"},
	{GScript::GetPlayerAlly, 2, 1, 0, "GET_PLAYER_ALLY"},
	{GScript::SetNoWindResistanceFlag, 2, 1, 0, "SET_PLAYER_WIND_RESISTANCE"},
	{GScript::GetNoWindResistanceFlag, 2, 1, 0, "GET_PLAYER_WIND_RESISTANCE"},
	{GScript::SetPauseWeather, 1, 0, 0, "PAUSE_UNPAUSE_CLIMATE_SYSTEM"},
	{GScript::SetStormCreation, 1, 0, 0, "PAUSE_UNPAUSE_STORM_CREATION_IN_CLIMATE_SYSTEM"},
	{GScript::GetManaForSpell, 1, 1, 0, "GET_MANA_FOR_SPELL"},
	{GScript::KillStormsInArea, 4, 0, 0, "KILL_STORMS_IN_AREA"},
	{GScript::InsideTemple, 0, 1, 0, "INSIDE_TEMPLE"},
	{GScript::RestartThing, 1, 0, 0, "RESTART_OBJECT"},
	{GScript::SetGameTimeProperties, 3, 0, 0, "SET_GAME_TIME_PROPERTIES"},
	{GScript::ResetGameTimeProperties, 0, 0, 0, "RESET_GAME_TIME_PROPERTIES"},
	{GScript::SoundExists, 0, 1, 0, "SOUND_EXISTS"},
	{GScript::GetTownWorshipDeaths, 1, 1, 0, "GET_TOWN_WORSHIP_DEATHS"},
	{GScript::ClearDialogue, 0, 0, 0, "GAME_CLEAR_DIALOGUE"},
	{GScript::CloseDialogue, 0, 0, 0, "GAME_CLOSE_DIALOGUE"},
	{GScript::GetHandState, 0, 1, 0, "GET_HAND_STATE"},
	{GScript::SetCitadelInteract, 1, 0, 0, "SET_INTERFACE_CITADEL"},
	{GScript::MapScriptFunction, 1, 0, 0, "MAP_SCRIPT_FUNCTION"},
	{GScript::GameWithinRotation, 0, 1, 0, "WITHIN_ROTATION"},
	{GScript::GetPlayerTownTotal, 1, 1, 0, "GET_PLAYER_TOWN_TOTAL"},
	{GScript::ScriptSpiritScreenPoint, 3, 0, 0, "SPIRIT_SCREEN_POINT"},
	{GScript::ScriptKeyDown, 1, 1, 0, "KEY_DOWN"},
	{GScript::SetFightExit, 1, 0, 0, "SET_FIGHT_EXIT"},
	{GScript::GetObjectClicked, 0, 1, 0, "GET_OBJECT_CLICKED"},
	{GScript::GetObjectMana, 1, 1, 0, "GET_MANA"},
	{GScript::ClearPlayerSpellCharging, 1, 0, 0, "CLEAR_PLAYER_SPELL_CHARGING"},
	{GScript::StopSoundEffect, 3, 0, 0, "STOP_SOUND_EFFECT"},
	{GScript::GetTotemStatue, 1, 1, 0, "GET_TOTEM_STATUE"},
	{GScript::SetSetOnFire, 2, 0, 0, "SET_SET_ON_FIRE"},
	{GScript::SetLandBalance, 2, 0, 0, "SET_LAND_BALANCE"},
	{GScript::TownBalanceBeliefScale, 2, 0, 0, "SET_OBJECT_BELIEF_SCALE"},
	{GScript::StartImmersion, 1, 0, 0, "START_IMMERSION"},
	{GScript::StopImmersion, 1, 0, 0, "STOP_IMMERSION"},
	{GScript::StopAllImmersion, 0, 0, 0, "STOP_ALL_IMMERSION"},
	{GScript::SetCreatureInTemple, 1, 0, 0, "SET_CREATURE_IN_TEMPLE"},
	{GScript::DrawTextA, 7, 0, 0, "GAME_DRAW_TEXT"},
	{GScript::DrawTempText, 7, 0, 0, "GAME_DRAW_TEMP_TEXT"},
	{GScript::FadeAllDrawText, 1, 0, 0, "FADE_ALL_DRAW_TEXT"},
	{GScript::SetDrawTextColour, 3, 0, 0, "SET_DRAW_TEXT_COLOUR"},
	{GScript::SetClippingWindow, 5, 0, 0, "SET_CLIPPING_WINDOW"},
	{GScript::ClearClippingWindow, 1, 0, 0, "CLEAR_CLIPPING_WINDOW"},
	{GScript::InstantSaveForScript, 1, 0, 0, "SAVE_GAME_IN_SLOT"},
	{GScript::SetObjectCarrying, 2, 0, 0, "SET_OBJECT_CARRYING"},
	{GScript::PositionValidForCreature, 3, 1, 0, "POS_VALID_FOR_CREATURE"},
	{GScript::TimeSinceObjectAttacked, 2, 1, 0, "GET_TIME_SINCE_OBJECT_ATTACKED"},
	{GScript::GetTownAndVillagerHealthTotal, 1, 1, 0, "GET_TOWN_AND_VILLAGER_HEALTH_TOTAL"},
	{GScript::AddForBuildingForTown, 2, 0, 0, "GAME_ADD_FOR_BUILDING"},
	{GScript::SetAlignmentMusic, 1, 0, 0, "ENABLE_DISABLE_ALIGNMENT_MUSIC"},
	{GScript::GetDeadLiving, 4, 1, 0, "GET_DEAD_LIVING"},
	{GScript::AttachSoundTag, 4, 0, 0, "ATTACH_SOUND_TAG"},
	{GScript::DetachSoundTag, 3, 0, 0, "DETACH_SOUND_TAG"},
	{GScript::GetSacrificeTotal, 1, 1, 0, "GET_SACRIFICE_TOTAL"},
	{GScript::IsSoundPlaying, 2, 1, 0, "GAME_SOUND_PLAYING"},
	{GScript::GetTemplePosition, 1, 3, 0, "GET_TEMPLE_POSITION"},
	{GScript::SetCreatureAutoScale, 3, 0, 0, "CREATURE_AUTOSCALE"},
	{GScript::GetSpellIconFromTemple, 2, 1, 0, "GET_SPELL_ICON_IN_TEMPLE"},
	{GScript::ClearComputerPlayerActions, 1, 0, 0, "GAME_CLEAR_COMPUTER_PLAYER_ACTIONS"},
	{GScript::GetFirstInContainer, 1, 1, 0, "GET_FIRST_IN_CONTAINER"},
	{GScript::GetNextInContainer, 2, 1, 0, "GET_NEXT_IN_CONTAINER"},
	{GScript::GetTempleEntrancePosition, 3, 3, 0, "GET_TEMPLE_ENTRANCE_POSITION"},
	{GScript::SaySoundEffectPlaying, 2, 1, 0, "SAY_SOUND_EFFECT_PLAYING"},
	{GScript::SetHandDemoKeys, 1, 0, 0, "SET_HAND_DEMO_KEYS"},
	{GScript::CanSkipTutorial, 0, 1, 0, "CAN_SKIP_TUTORIAL"},
	{GScript::CanSkipTraining, 0, 1, 0, "CAN_SKIP_CREATURE_TRAINING"},
	{GScript::IsKeepingOldCreature, 0, 1, 0, "IS_KEEPING_OLD_CREATURE"},
	{GScript::CurrentProfileHasCreature, 0, 1, 0, "CURRENT_PROFILE_HAS_CREATURE"},
};

// BW1W120 006f9090 BW1M100 104fe414 GScript::SetFocusLoopFn(GameThingWithPos *, SCRIPT_OBJECT_TYPE, ulong)
int GScript::SetFocusLoopFn(GameThingWithPos* thing, SCRIPT_OBJECT_TYPE type, uint32_t param_3)
{
	((Object*)thing)->SetFocus(&GGame::g_game->script->FocusPos);
	return 0;
}

// BW1W120 006f90b0 BW1M100 1002e4a0 GScript::SetFocus(void)
void GScript::SetFocus()
{
	ScriptDLL*         dll = g_scriptDLL;
	LHPoint            pos;
	GameThingWithPos*  thing;
	Object*            object;
	SCRIPT_OBJECT_TYPE objectType;

	pos.z = dll->COORD_POP();
	pos.y = dll->COORD_POP();
	pos.x = dll->COORD_POP();
	thing = GetScriptGameThing(g_scriptDLL->THING_OR_NULL_POP());
	if (thing == NULL)
	{
		ScriptWarningMessage("Thing no longer valid");
		return;
	}
	if (thing->IsScriptContainer())
	{
		objectType = thing->GetScriptObjectType();
		GGame::g_game->script->FocusPos = pos;
		if (g_scriptObjectDispatch[objectType - 1].Loop == NULL)
		{
			return;
		}
		g_scriptObjectDispatch[objectType - 1].Loop(thing, SetFocusLoopFn, SCRIPT_OBJECT_TYPE_NONE, 0);
		return;
	}
	object = dynamic_cast<Object*>(thing);
	if (object != NULL)
	{
		if (object->IsCreature())
		{
			object->SetControlledByScript(1);
		}
		object->SetFocus(&pos);
		return;
	}
	ScriptErrorMessage("Jonty - Thing must be living to face position!");
}
