#include "Setup.h"

LHScriptCommandX<char> GSetup::MapCommands[] = {{(char*)"SET_NO_PLAYERS", "N         "},
                                                {(char*)"LOAD_TRIBE_DANCE", "AN        "},
                                                {(char*)"SET_DATE", "NNN       "},
                                                {(char*)"SET_TIME", "NNN       "},
                                                {(char*)"SET_TURNS_PER_YEAR", "N         "},
                                                {(char*)"SET_GAME_TICK_TIME", "N         "},
                                                {(char*)"LOAD_FEATURE_SCRIPT", "A         "},
                                                {(char*)"PAUSE_GAME", "          "},
                                                {(char*)"CREATE_CREATURE", "NNNN      "},
                                                {(char*)"OUTPUT_VILLAGERS", "          "},
                                                {(char*)"OUTPUT_TOWN", "          "},
                                                {(char*)"OUTPUT_CREATURES", "          "},
                                                {(char*)"OUTPUT_COLLIDE", "          "},
                                                {(char*)"OUTPUT_ALLOC", "          "},
                                                {(char*)"SAVE_FOR_NET_DEBUG", "NN        "},
                                                {(char*)"LOAD_FOR_NET_DEBUG", "N         "},
                                                {(char*)"LOAD_LANDSCAPE", "A         "},
                                                {(char*)"LOAD_GAME_SCRIPT", "A         "},
                                                {(char*)"LOAD_RAW_GAME_SCRIPT", "A         "},
                                                {(char*)"LOAD_LANGUAGE", "          "},
                                                {(char*)"LOAD_CHALLENGES", "A         "},
                                                {(char*)"OUTPUT_RAND", "          "},
                                                {(char*)"LOAD_OLD_CREATURE", "          "},
                                                {(char*)"CONFIG", "          "},
                                                {(char*)"KEYCONFIG", "A         "},
                                                {NULL, ""}};
