#ifndef __AUDIOMUSIC_H__
#define __AUDIOMUSIC_H__

//------------------------------------------------------------------------------------------------------------------------
enum	MUSIC_TYPE
{
	MUSIC_TYPE_NONE,
	MUSIC_TYPE_GENERIC_EVIL,
	MUSIC_TYPE_GENERIC_NEUTRAL,	 	
	MUSIC_TYPE_GENERIC_GOOD,		 	
	MUSIC_TYPE_CELTIC_TOWN_EVIL,		
	MUSIC_TYPE_CELTIC_TOWN_NEUTRAL,	
	MUSIC_TYPE_CELTIC_TOWN_GOOD,		
	MUSIC_TYPE_AZTEC_TOWN_EVIL,		
	MUSIC_TYPE_AZTEC_TOWN_NEUTRAL,	
	MUSIC_TYPE_AZTEC_TOWN_GOOD,		
	MUSIC_TYPE_JAPANESE_TOWN_EVIL,	
	MUSIC_TYPE_JAPANESE_TOWN_NEUTRAL,	
	MUSIC_TYPE_JAPANESE_TOWN_GOOD,	
	MUSIC_TYPE_INDIAN_TOWN_EVIL,		
	MUSIC_TYPE_INDIAN_TOWN_NEUTRAL,	
	MUSIC_TYPE_INDIAN_TOWN_GOOD,		
	MUSIC_TYPE_EGYPTIAN_TOWN_EVIL,	
	MUSIC_TYPE_EGYPTIAN_TOWN_NEUTRAL,	
	MUSIC_TYPE_EGYPTIAN_TOWN_GOOD,	
	MUSIC_TYPE_GREEK_TOWN_EVIL,		
	MUSIC_TYPE_GREEK_TOWN_NEUTRAL,	
	MUSIC_TYPE_GREEK_TOWN_GOOD,		
	MUSIC_TYPE_NORSE_TOWN_EVIL,		
	MUSIC_TYPE_NORSE_TOWN_NEUTRAL,	
	MUSIC_TYPE_NORSE_TOWN_GOOD,		
	MUSIC_TYPE_TIBETAN_TOWN_EVIL,		
	MUSIC_TYPE_TIBETAN_TOWN_NEUTRAL,	
	MUSIC_TYPE_TIBETAN_TOWN_GOOD,
	MUSIC_TYPE_CELTIC_CHANT,		
	MUSIC_TYPE_CELTIC_CHANT_VOX,	
	MUSIC_TYPE_AZTEC_CHANT,		
	MUSIC_TYPE_AZTEC_CHANT_VOX,	
	MUSIC_TYPE_JAPANESE_CHANT,	
	MUSIC_TYPE_JAPANESE_CHANT_VOX,	
	MUSIC_TYPE_INDIAN_CHANT,		
	MUSIC_TYPE_INDIAN_CHANT_VOX,	
	MUSIC_TYPE_EGYPTIAN_CHANT,	
	MUSIC_TYPE_EGYPTIAN_CHANT_VOX,	
	MUSIC_TYPE_GREEK_CHANT,		
	MUSIC_TYPE_GREEK_CHANT_VOX,	
	MUSIC_TYPE_NORSE_CHANT,		
	MUSIC_TYPE_NORSE_CHANT_VOX,	
	MUSIC_TYPE_TIBETAN_CHANT,		
	MUSIC_TYPE_TIBETAN_CHANT_VOX,	
	MUSIC_TYPE_CITADEL_EVIL,		  
	MUSIC_TYPE_CITADEL_NEUTRAL,		
	MUSIC_TYPE_CITADEL_GOOD,		  	
	MUSIC_TYPE_SCRIPT_PIPER_TUNE,
	MUSIC_TYPE_SCRIPT_PIPER_CAVE_TUNE,
	MUSIC_TYPE_SCRIPT_HERMIT,	
	MUSIC_TYPE_SCRIPT_MISSIONARIES_BACKGROUND,
	MUSIC_TYPE_SCRIPT_MISSIONARIES_VERSE_1,
	MUSIC_TYPE_SCRIPT_MISSIONARIES_VERSE_2,
	MUSIC_TYPE_SCRIPT_MISSIONARIES_VERSE_3,
	MUSIC_TYPE_SCRIPT_INTRO,
	MUSIC_TYPE_SCRIPT_SINGING_STONE_CIRCLE,
	MUSIC_TYPE_SCRIPT_WELCOME_DANCE,
	MUSIC_TYPE_SCRIPT_GENERIC_01,	//Happy
	MUSIC_TYPE_SCRIPT_GENERIC_02,	//Sinister
	MUSIC_TYPE_SCRIPT_GENERIC_03,	//Sad
	MUSIC_TYPE_SCRIPT_GENERIC_04,	//Spooky
	MUSIC_TYPE_SCRIPT_EPIC_01,		//Biblical
	MUSIC_TYPE_SCRIPT_EPIC_02,		//Glorious
	MUSIC_TYPE_SCRIPT_EPIC_03,		//Sad
	MUSIC_TYPE_SCRIPT_EPIC_04,		//Short sting
	MUSIC_TYPE_SCRIPT_CREATURE_CHOSEN,
	MUSIC_TYPE_SCRIPT_FUNERAL,
	MUSIC_TYPE_SCRIPT_CREATURE_GUIDE,
	MUSIC_TYPE_SCRIPT_KHAZAR,
	MUSIC_TYPE_SCRIPT_NEMESIS,
	MUSIC_TYPE_SCRIPT_TWINKLE,
	MUSIC_TYPE_SCRIPT_WHISTLE_FUNERAL,
	MUSIC_TYPE_SCRIPT_WHISTLE_TWINKLE,
	MUSIC_TYPE_SCRIPT_SLEG,
	MUSIC_TYPE_CREATURE_FIGHT,
	MUSIC_TYPE_CREATURE_BIG_FIGHT,
	MUSIC_TYPE_SCRIPT_GUARDIAN_STONES,
	MUSIC_TYPE_OUTRO,
	MUSIC_TYPE_SCRIPT_FAILURE,
	MUSIC_TYPE_SCRIPT_GREGORIAN,
	MUSIC_TYPE_SCRIPT_CHRISTMAS,
	MUSIC_TYPE_SCRIPT_GREGORIAN_3D,
	MUSIC_TYPE_SCRIPT_CIRCUS,
	MUSIC_TYPE_SCRIPT_CIRCUS_3D,
	MUSIC_TYPE_SCRIPT_CREATURE_END_SEQUENCE,
	MUSIC_TYPE_SCRIPT_MISSIONARIES_INTRO,
	MUSIC_TYPE_SCRIPT_MISSIONARIES_CAMP_FIRE,
	MUSIC_TYPE_SCRIPT_BROTHERHOOD_INTRO,
	MUSIC_TYPE_SCRIPT_RACE_MUSIC,
	MUSIC_TYPE_SCRIPT_SKELETON_GRAB,
	MUSIC_TYPE_SCRIPT_MARAUDER_CHANT,
	MUSIC_TYPE_SCRIPT_MISSIONARIES_BLOW_SCRIPT,
	MUSIC_TYPE_LAST,
};

//------------------------------------------------------------------------------------------------------------------------
enum	MUSIC_ALIGNMENT
{
	MUSIC_ALIGNMENT_EVIL=0,
	MUSIC_ALIGNMENT_NEUTRAL,
	MUSIC_ALIGNMENT_GOOD,
	MUSIC_ALIGNMENT_LAST
};

//------------------------------------------------------------------------------------------------------------------------
enum	MUSIC_STYLE
{
	MUSIC_STYLE_NONE=-1,
	MUSIC_STYLE_ALIGNMENT=0,
	MUSIC_STYLE_CHANT,
	MUSIC_STYLE_CITADEL_INTERIOR,
	MUSIC_STYLE_SCRIPT,
	MUSIC_STYLE_LAST,
};
  


#endif //__AUDIOMUSIC_H__