.intel_syntax noprefix
.align 16

.globl _jmp_addr_0x007aebb6
.globl _jmp_addr_0x007aecb2
.globl _jmp_addr_0x007aed24
.globl _jmp_addr_0x007aed2a

                         jmp                  dword ptr [__imp__gethostname@4]                                                                 // 0x007aebb0    ff25f4988a00
_jmp_addr_0x007aebb6:    jmp                  dword ptr [__imp__inet_ntoa]                                                                     // 0x007aebb6    ff252c998a00
                         jmp                  dword ptr [__imp__GetTickCount@4]                                                                // 0x007aebbc    ff25c4918a00
                         jmp                  dword ptr [__imp__GetFileAttributesA@4]                                                          // 0x007aebc2    ff25c0918a00
                         jmp                  dword ptr [__imp__GetVersionExA@4]                                                               // 0x007aebc8    ff25bc918a00
                         jmp                  dword ptr [__imp__GlobalMemoryStatus@4]                                                          // 0x007aebce    ff25b8918a00
                         jmp                  dword ptr [__imp__GlobalFree@4]                                                                  // 0x007aebd4    ff2544928a00
                         jmp                  dword ptr [__imp__GlobalUnlock@4]                                                                // 0x007aebda    ff2540928a00
                         jmp                  dword ptr [__imp__GlobalLock@4]                                                                  // 0x007aebe0    ff253c928a00
                         jmp                  dword ptr [__imp__GlobalAlloc@4]                                                                 // 0x007aebe6    ff2538928a00
                         jmp                  dword ptr [__imp__GetSystemInfo@4]                                                               // 0x007aebec    ff2534928a00
                         jmp                  dword ptr [__imp__Sleep@4]                                                                       // 0x007aebf2    ff2530928a00
                         jmp                  dword ptr [__imp__WideCharToMultiByte@32]                                                        // 0x007aebf8    ff252c928a00
                         jmp                  dword ptr [__imp__DeleteFileA@4]                                                                 // 0x007aebfe    ff2528928a00
                         jmp                  dword ptr [__imp__FindClose@4]                                                                   // 0x007aec04    ff2524928a00
                         jmp                  dword ptr [__imp__FindNextFileA@4]                                                               // 0x007aec0a    ff2598918a00
                         jmp                  dword ptr [__imp__FindFirstFileA@4]                                                              // 0x007aec10    ff2594918a00
                         jmp                  dword ptr [__imp__RemoveDirectoryA@4]                                                            // 0x007aec16    ff2590918a00
                         jmp                  dword ptr [__imp__GetCurrentDirectoryA@8]                                                        // 0x007aec1c    ff258c918a00
                         jmp                  dword ptr [__imp__SetCurrentDirectoryA@4]                                                        // 0x007aec22    ff2588918a00
                         jmp                  dword ptr [__imp__LeaveCriticalSection@4]                                                        // 0x007aec28    ff2584918a00
                         jmp                  dword ptr [__imp__EnterCriticalSection@4]                                                        // 0x007aec2e    ff2580918a00
                         jmp                  dword ptr [__imp__InitializeCriticalSection@4]                                                   // 0x007aec34    ff257c918a00
                         jmp                  dword ptr [__imp__DeleteCriticalSection@4]                                                       // 0x007aec3a    ff2578918a00
                         jmp                  dword ptr [__imp__FreeLibrary@4]                                                                 // 0x007aec40    ff2574918a00
                         jmp                  dword ptr [__imp__GetProcAddress@8]                                                              // 0x007aec46    ff2570918a00
                         jmp                  dword ptr [__imp__LoadLibraryA@4]                                                                // 0x007aec4c    ff256c918a00
                         jmp                  dword ptr [__imp__CreateDirectoryA@8]                                                            // 0x007aec52    ff2568918a00
                         jmp                  dword ptr [__imp__GetTempFileNameA@4]                                                            // 0x007aec58    ff2564918a00
                         jmp                  dword ptr [__imp__GetTempPathA@4]                                                                // 0x007aec5e    ff259c918a00
                         jmp                  dword ptr [__imp__GetDateFormatA@4]                                                              // 0x007aec64    ff2560918a00
                         jmp                  dword ptr [__imp__MoveFileA@8]                                                                   // 0x007aec6a    ff255c918a00
                         jmp                  dword ptr [__imp__CopyFileA@4]                                                                   // 0x007aec70    ff2558918a00
                         jmp                  dword ptr [__imp__GetVolumeInformationA@4]                                                       // 0x007aec76    ff25a4918a00
                         jmp                  dword ptr [__imp__SetErrorMode@4]                                                                // 0x007aec7c    ff25a0918a00
                         jmp                  dword ptr [__imp__GetCommandLineA@0]                                                             // 0x007aec82    ff2548918a00
                         jmp                  dword ptr [__imp__QueryPerformanceCounter@4]                                                     // 0x007aec88    ff2544918a00
                         jmp                  dword ptr [__imp__QueryPerformanceFrequency@4]                                                   // 0x007aec8e    ff2554918a00
                         jmp                  dword ptr [__imp__MultiByteToWideChar@24]                                                        // 0x007aec94    ff253c918a00
                         jmp                  dword ptr [__imp__OutputDebugStringA@4]                                                          // 0x007aec9a    ff2550918a00
                         jmp                  dword ptr [__imp__GetTimeFormatA@4]                                                              // 0x007aeca0    ff2534918a00
                         jmp                  dword ptr [__imp__GetTimeFormatW@4]                                                              // 0x007aeca6    ff2540918a00
                         jmp                  dword ptr [__imp__GetDateFormatW@4]                                                              // 0x007aecac    ff254c918a00
_jmp_addr_0x007aecb2:    jmp                  dword ptr [__imp__DebugBreak@4]                                                                  // 0x007aecb2    ff2538918a00
                         jmp                  dword ptr [__imp__SendMessageA@4]                                                                // 0x007aecb8    ff25dc978a00
                         jmp                  dword ptr [__imp__GetFocus@4]                                                                    // 0x007aecbe    ff25f8978a00
                         jmp                  dword ptr [__imp__GetKeyNameTextA@4]                                                             // 0x007aecc4    ff25d8978a00
                         jmp                  dword ptr [__imp__GetKeyNameTextW@4]                                                             // 0x007aecca    ff25d4978a00
                         jmp                  dword ptr [__imp__ShowWindow@4]                                                                  // 0x007aecd0    ff25d0978a00
                         jmp                  dword ptr [__imp__MessageBeep@4]                                                                 // 0x007aecd6    ff25cc978a00
                         jmp                  dword ptr [__imp__ReleaseDC@4]                                                                   // 0x007aecdc    ff25c8978a00
                         jmp                  dword ptr [__imp__GetWindowDC@4]                                                                 // 0x007aece2    ff25b4978a00
                         jmp                  dword ptr [__imp__LoadImageA@4]                                                                  // 0x007aece8    ff25c4978a00
                         jmp                  dword ptr [__imp__SetWindowTextA@4]                                                              // 0x007aecee    ff25c0978a00
                         jmp                  dword ptr [__imp__PostQuitMessage@4]                                                             // 0x007aecf4    ff25bc978a00
                         jmp                  dword ptr [__imp__MessageBoxA@16]                                                                // 0x007aecfa    ff25b8978a00
                         jmp                  dword ptr [__imp__DeleteObject@4]                                                                // 0x007aed00    ff256c908a00
                         jmp                  dword ptr [__imp__DeleteDC@4]                                                                    // 0x007aed06    ff2574908a00
                         jmp                  dword ptr [__imp__BitBlt@4]                                                                      // 0x007aed0c    ff2560908a00
                         jmp                  dword ptr [__imp__SelectObject@4]                                                                // 0x007aed12    ff2570908a00
                         jmp                  dword ptr [__imp__CreateCompatibleDC@4]                                                          // 0x007aed18    ff2564908a00
                         jmp                  dword ptr [__imp__CreateDIBSection@4]                                                            // 0x007aed1e    ff2568908a00
_jmp_addr_0x007aed24:    jmp                  dword ptr [__imp__GetSaveFileNameA@4]                                                            // 0x007aed24    ff256c998a00
_jmp_addr_0x007aed2a:    jmp                  dword ptr [__imp__GetOpenFileNameA@4]                                                            // 0x007aed2a    ff2570998a00
                         jmp                  dword ptr [__imp__GetUserNameA@4]                                                                // 0x007aed30    ff250c908a00
                         jmp                  dword ptr [__imp__ShellExecuteA@4]                                                               // 0x007aed36    ff25ac978a00
                         jmp                  dword ptr [__imp___GetContainedEffect_CImmCompoundEffect__QAEPAVCImmEffect__J_Z@4]               // 0x007aed3c    ff25c8908a00
                         jmp                  dword ptr [__imp___GetStatus_CImmEffect__QAEHPAK_Z@4]                                            // 0x007aed42    ff25b4908a00
                         jmp                  dword ptr [__imp___reset_CImmMouse__MAEXXZ@4]                                                    // 0x007aed48    ff25b0908a00
                         jmp                  dword ptr [__imp___prepare_device_CImmMouse__MAEHXZ@4]                                           // 0x007aed4e    ff25ac908a00
                         jmp                  dword ptr [__imp___SwitchToAbsoluteMode_CImmMouse__UAEHH_Z@4]                                    // 0x007aed54    ff25e8908a00
                         jmp                  dword ptr [__imp___ChangeScreenResolution_CImmMouse__UAEHHKK_Z@4]                                // 0x007aed5a    ff25e0908a00
                         jmp                  dword ptr [__imp___GetCurrentPosition_CImmMouse__UAEHAAJ0_Z@4]                                   // 0x007aed60    ff25a0908a00
                         jmp                  dword ptr [__imp___GetProductGUID_CImmMouse__UAE_AU_GUID__XZ@4]                                  // 0x007aed66    ff259c908a00
                         jmp                  dword ptr [__imp___GetProductGUIDString_CImmMouse__UAEHPADH_Z@4]                                 // 0x007aed6c    ff2598908a00
                         jmp                  dword ptr [__imp___GetProductName_CImmMouse__UAEHPADH_Z@4]                                       // 0x007aed72    ff2594908a00
                         jmp                  dword ptr [__imp___GetDriverVersion_CImmMouse__UAEHAAK00_Z@4]                                    // 0x007aed78    ff2590908a00
                         jmp                  dword ptr [__imp___GetProductType_CImmMouse__UAEKXZ@4]                                           // 0x007aed7e    ff258c908a00
                         jmp                  dword ptr [__imp___GetDevice_CImmMouse__UAEPAUIFeelitDevice__XZ@4]                               // 0x007aed84    ff2584908a00
                         jmp                  dword ptr [__imp___GetAPI_CImmMouse__UAEPAUIFeelit__XZ@4]                                        // 0x007aed8a    ff2580908a00
                         jmp                  dword ptr [__imp____1CImmProject__QAE_XZ@4]                                                      // 0x007aed90    ff257c908a00
                         jmp                  dword ptr [__imp___CreateEffect_CImmProject__QAEPAVCImmCompoundEffect__PBDPAVCImmDevice__K_Z@4]  // 0x007aed96    ff25f0908a00
                         jmp                  dword ptr [__imp___GetParameters_CImmEffect__QAEXAAUFEELIT_EFFECT___Z@4]                         // 0x007aed9c    ff25ec908a00
                         jmp                  dword ptr [__imp___GetNumEffectsFromIFR_CImmProject__QAEHXZ@4]                                   // 0x007aeda2    ff2588908a00
                         jmp                  dword ptr [__imp___OpenFile_CImmProject__QAEHPBDPAVCImmDevice___Z@4]                             // 0x007aeda8    ff25a8908a00
                         jmp                  dword ptr [__imp____0CImmProject__QAE_XZ@4]                                                      // 0x007aedae    ff25dc908a00
                         jmp                  dword ptr [__imp___Initialize_CImmMouse__QAEHPAX0KH_Z@4]                                         // 0x007aedb4    ff25a4908a00
                         jmp                  dword ptr [__imp____0CImmMouse__QAE_XZ@4]                                                        // 0x007aedba    ff25e4908a00
                         jmp                  dword ptr [__imp____1CImmMouse__UAE_XZ@4]                                                        // 0x007aedc0    ff25bc908a00
                         jmp                  dword ptr [__imp___Close_CImmProject__QAEXXZ@4]                                                  // 0x007aedc6    ff25c0908a00
                         jmp                  dword ptr [__imp___DestroyEffect_CImmProject__QAEXPAVCImmCompoundEffect___Z@4]                   // 0x007aedcc    ff25c4908a00
                         jmp                  dword ptr [__imp___Start_CImmCompoundEffect__QAEHKK_Z@4]                                         // 0x007aedd2    ff25cc908a00
                         jmp                  dword ptr [__imp___Stop_CImmCompoundEffect__QAEHXZ@4]                                            // 0x007aedd8    ff25d0908a00
                         jmp                  dword ptr [__imp___ChangeBaseParamsPolar_CImmEffect__QAEHJKPAUFEELIT_ENVELOPE__KKKKK_Z@4]        // 0x007aedde    ff25d4908a00
                         jmp                  dword ptr [__imp___ChangeParameters_CImmPeriodic__QAEHKKKJJJKPAUFEELIT_ENVELOPE___Z@4]           // 0x007aede4    ff25d8908a00
                         jmp                  dword ptr [__imp__RegistryRetrieveULong__YA_AW4LH_RETURN__PAD0PAK_Z]                             // 0x007aedea    ff2544938a00
                         jmp                  dword ptr [__imp__RegistrySetULong__YA_AW4LH_RETURN__PAD0K_Z@4]                                  // 0x007aedf0    ff2550938a00
                         jmp                  dword ptr [__imp__GetCurrentStackString__YAPADXZ@4]                                              // 0x007aedf6    ff2554938a00
                         jmp                  dword ptr [__imp___0LHSPrintf__QAA_PADZZ@4]                                                      // 0x007aedfc    ff255c938a00
                         jmp                  dword ptr [__imp___0LHSPrintfW__QAA_PAGZZ@4]                                                     // 0x007aee02    ff25d8938a00
                         jmp                  dword ptr [__imp__UNICODE_sprintf__YAHPAG0ZZ@4]                                                  // 0x007aee08    ff2560938a00
                         jmp                  dword ptr [__imp__EncryptBlock_LHVersion__SAXPAEG_Z@4]                                           // 0x007aee0e    ff25c8938a00
                         jmp                  dword ptr [__imp__GetFileName_LHLogger__SAPADPAD_Z@4]                                            // 0x007aee14    ff25c4938a00
                         jmp                  dword ptr [__imp__DecryptBlock_LHVersion__SAXPAEG_Z@4]                                           // 0x007aee1a    ff25c0938a00
                         jmp                  dword ptr [__imp__RegistryRetrieveVal__YA_AW4LH_RETURN__PAD0PAEPAKK_Z@4]                         // 0x007aee20    ff25bc938a00
                         jmp                  dword ptr [__imp__RegistryRetrieveString__YA_AW4LH_RETURN__PAD00PAK_Z@4]                         // 0x007aee26    ff25b8938a00
                         jmp                  dword ptr [__imp__LHRegistrySetCurrentKey__YAXW4LH_REG_KEY_TYPE___Z@4]                           // 0x007aee2c    ff25b4938a00
                         jmp                  dword ptr [__imp__LHRegistryGetCurrentKey__YA_AW4LH_REG_KEY_TYPE__XZ@4]                          // 0x007aee32    ff25b0938a00
                         jmp                  dword ptr [__imp__RegistrySetString__YA_AW4LH_RETURN__PAD00_Z@4]                                 // 0x007aee38    ff25ac938a00
                         jmp                  dword ptr [__imp__GetText_LHLogger__SAPADXZ@4]                                                   // 0x007aee3e    ff25a8938a00
                         jmp                  dword ptr [__imp__GetCode_LHLogger__SAKXZ@4]                                                     // 0x007aee44    ff25a4938a00
                         jmp                  dword ptr [__imp__AppendString_LHSPrintfW__QAAXPAGZZ@4]                                          // 0x007aee4a    ff25a0938a00
                         jmp                  dword ptr [__imp__GetModuleChecksum_LHVersion__SAKXZ@4]                                          // 0x007aee50    ff259c938a00
                         jmp                  dword ptr [__imp__GetMajorMinor_LHVersion__SA_AW4LH_RETURN__PADPAK1_Z@4]                         // 0x007aee56    ff2598938a00
                         jmp                  dword ptr [__imp___BLHSPrintf__QAEPADXZ@4]                                                       // 0x007aee5c    ff2594938a00
                         jmp                  dword ptr [__imp__SetString_LHSPrintf__QAAXPADZZ@4]                                              // 0x007aee62    ff2590938a00
                         jmp                  dword ptr [__imp__RegistryRetrieveGUID__YA_AW4LH_RETURN__PAD0PAU_GUID___Z@4]                     // 0x007aee68    ff2584938a00
                         jmp                  dword ptr [__imp__RegistryRetrieveINT64__YA_AW4LH_RETURN__PAD0PA_J_Z@4]                          // 0x007aee6e    ff2580938a00
                         jmp                  dword ptr [__imp___0LHVersion__QAE_PAULHVersionBlock___Z@4]                                      // 0x007aee74    ff25cc938a00
                         jmp                  dword ptr [__imp___1LHVersion__QAE_XZ@4]                                                         // 0x007aee7a    ff2578938a00
                         jmp                  dword ptr [__imp__LHAssertStatement__YA_AW4LH_ASSERT_RETURN__PADK00G0H_Z@4]                      // 0x007aee80    ff2570938a00
                         jmp                  dword ptr [__imp__RawLogT_LHLogger__QAEXPAD_Z@4]                                                 // 0x007aee86    ff256c938a00
                         jmp                  dword ptr [__imp__CreateLogTextS_LHLogger__SAHPAVLHSPrintf__PAD1K1ZZ@4]                          // 0x007aee8c    ff2568938a00
                         jmp                  dword ptr [__imp__FindLHLogger_LHLogger__SAPAV1_PADK_Z@4]                                        // 0x007aee92    ff2564938a00
