#ifndef __AUDIOSFX_H__
#define __AUDIOSFX_H__

//------------------------------------------------------------------------------------------------------------------------
enum	AUDIO_SFX_BANK_TYPE
{
	AUDIO_SFX_BANK_TYPE_NONE,
	AUDIO_SFX_BANK_TYPE_IN_GAME,
	AUDIO_SFX_BANK_TYPE_EDITOR,
	AUDIO_SFX_BANK_TYPE_SPELL,
	AUDIO_SFX_BANK_TYPE_CREATURE_GENERIC,
	AUDIO_SFX_BANK_TYPE_SCRIPT_SFX,
	AUDIO_SFX_BANK_TYPE_HELP_SPRITES,
	AUDIO_SFX_BANK_TYPE_VILLAGERS,
	AUDIO_SFX_BANK_TYPE_VILLAGERS_BANTER,
	AUDIO_SFX_BANK_TYPE_SPELL_DIALOG,
	AUDIO_SFX_BANK_TYPE_GUIDANCE,
	AUDIO_SFX_BANK_TYPE_CI_VILLAGERS,
	AUDIO_SFX_BANK_TYPE_CI_HELP_SPRITES,
	AUDIO_SFX_BANK_TYPE_CI_SPELL_DIALOGUE,
	AUDIO_SFX_BANK_TYPE_LAST,
};

#endif //__AUDIOSFX_H__