name: lint

on:
  pull_request:
    paths:
      - '**.hpp'
      - '**.cpp'
      - '**.h'
      - '**.c'
      - '**.clang-format'
  push:
    branches:
      - main
    paths:
      - '**.hpp'
      - '**.cpp'
      - '**.h'
      - '**.c'
      - '**.clang-format'

permissions:
  contents: read

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: jidicula/clang-format-action@v4.16.0
      with:
        clang-format-version: '21'
        fallback-style: 'none'
