name: Reassemble

on: [push, pull_request]

jobs:
  reassemble:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, windows]

    runs-on: ${{ matrix.os }}-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: ./.github/actions/python_prep

    - uses: ./.github/actions/clang_prep

    - name: Build bw1-decomp project
      uses: ./.github/actions/clang_build
      with:
        configuration: Release
        build_dir: build

    - name: Upload binary build path if it fails
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: failed-build-${{ matrix.os }}
        path: build/

    - name: Upload binary if MD5 sum mismatch
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: failed-binary-${{ matrix.os }}
        path: build/runblack-reassembled.exe

    - name: Build bw1-decomp project (Debug)
      uses: ./.github/actions/clang_build
      with:
        configuration: RelWithDebInfo
        build_dir: build_debug

    - name: Upload debug version
      uses: actions/upload-artifact@v4
      with:
        name: debug-binary-${{ matrix.os }}
        path: |
          build_debug/runblack-reassembled.exe
          build_debug/runblack-reassembled.exe.pdb
